---
title: "Chapter 11"
output: html_notebook
---

# 11 Functionals

## 11.1 My first functional: lapply()

```{r}
randomise <- function(f) f(runif(1e3))
randomise(mean)
randomise(mean)
randomise(sum)
```

```{r}
lapply2 <- function(x, f, ...) {
  out <- vector("list", length(x))
  for (i in seq_along(x)) {
    out[[i]] <- f(x[[i]], ...)
  }
  out
}
```

```{r}
l <- replicate(20, runif(sample(1:10, 1)), simplify = FALSE)
l
```

```{r}
out <- vector("list", length(l))
for (i in seq_along(l)) {
  out[[i]] <- length(l[[i]])
}
unlist(out)
```

```{r}
unlist(lapply(l, length))
```

```{r}
unlist(lapply(mtcars, class))
```

```{r}
mtcars[] <- lapply(mtcars, function(x) x / mean(x))
mtcars
```

```{r}
trims <- c(0, 0.1, 0.2, 0.5)
x <- rcauchy(1000)
unlist(lapply(trims, function(trim) mean(x, trim = trim)))
```

```{r}
xs <- runif(1e3)
res <- c()
for (x in xs) {
  res <- c(res, sqrt(x))
}
```

```{r}
res <- numeric(length(xs))
for (i in seq_along(xs)) {
  res[i] <- sqrt(xs[i])
}
```

```{r}
# lapply(xs, function(x) {})
# lapply(seq_along(xs), function(i) {})
# lapply(names(xs), function(nm) {})
```

```{r}
trims <- c(0, 0.1, 0.2, 0.5)
x <- rcauchy(100)

unlist(lapply(trims, function(trim) mean(x, trim = trim)))
unlist(lapply(trims, mean, x = x))
```

## 11.2 For loop functionals: friends of lapply()

```{r}
sapply(mtcars, is.numeric)
```

```{r}
vapply(mtcars, is.numeric, logical(1))
```

```{r}
sapply(list(), is.numeric)
```

```{r}
vapply(list(), is.numeric, logical(1))
```

```{r}
df <- data.frame(x = 1:10, y = letters[1:10])
df
```

```{r}
sapply(df, class)
vapply(df, class, character(1))
```

```{r}
df2 <- data.frame(x = 1:10, y = Sys.time() + 1:10)
df2
```

```{r}
sapply(df2, class)
```

```{r}
try(vapply(df2, class, character(1)))
```

```{r}
sapply2 <- function(x, f, ...) {
  res <- lapply2(x, f, ...)
  simplify2array(res)
}

vapply2 <- function(x, f, f.value, ...) {
  out <- matrix(rep(f.value, length(x)), nrow = length(f.value))
  for (i in seq_along(x)) {
    res <- f(x[[i]], ...)
    stopifnot(
      length(res) == length(f.value),
      typeof(res) == typeof(f.value)
    )
    out[ ,i] <- res
  }
  out
}
```

```{r}
xs <- replicate(5, runif(10), simplify = FALSE)
xs
```

```{r}
ws <- replicate(5, rpois(10, 5) + 1, simplify = FALSE)
ws
```

```{r}
unlist(lapply(xs, mean))
```

```{r}
unlist(lapply(seq_along(xs), function(i) {
  weighted.mean(xs[[i]], ws[[i]])
}))
```

```{r}
unlist(Map(weighted.mean, xs, ws))
```

```{r}
mtmeans <- lapply(mtcars, mean)
mtcars[] <- Map('/', mtcars, mtmeans)
mtcars
```

```{r}
mtcars[] <- lapply(mtcars, function(x) x / mean(x))
mtcars
```

```{r}
Map(function(x, w) weighted.mean(x, w, na.rm = TRUE), xs, ws)
```

```{r}
rollmean <- function(x, n) {
  out <- rep(NA, length(x))
  
  offset <- trunc(n / 2)
  for (i in (offset + 1):(length(x) - n + offset + 1)) {
    out[i] <- mean(x[(i - offset):(i + offset - 1)])
  }
  out
}
x <- seq(1, 3, length = 1e2) + runif(1e2)
plot(x)
lines(rollmean(x, 5), col = "blue", lwd = 2)
lines(rollmean(x, 10), col = "red", lwd = 2)
```

```{r}
rollmean(x, 10)
```

```{r}
x <- seq(1, 3, length = 1e2) + rt(1e2, df = 2) / 3
plot(x)
lines(rollmean(x, 5), col = "red", lwd = 2)
```

```{r}
rollapply <- function(x, n, f, ...) {
  out <- rep(NA, length(x))

  offset <- trunc(n / 2)
  for (i in (offset + 1):(length(x) - n + offset + 1)) {
    out[i] <- f(x[(i - offset):(i + offset - 1)], ...)
  }
  out
}
plot(x)
lines(rollapply(x, 5, median), col = "red", lwd = 2)
```

```{r}
rollapply <- function(x, n, f, ...) {
  offset <- trunc(n / 2)
  locs <- (offset + 1):(length(x) - n + offset + 1)
  num <- vapply(
    locs, 
    function(i) f(x[(i - offset):(i + offset)], ...),
    numeric(1)
  )

  c(rep(NA, offset), num)
}
```

```{r}
lapply3 <- function(x, f, ...) {
  out <- vector("list", length(x))
  for (i in sample(seq_along(x))) {
    out[[i]] <- f(x[[i]], ...)
  }
  out
}
unlist(lapply(1:10, sqrt))
#>  [1] 1.000000 1.414214 1.732051 2.000000 2.236068 2.449490 2.645751
#>  [8] 2.828427 3.000000 3.162278
unlist(lapply3(1:10, sqrt))
```

```{r}
unlist(parallel::mclapply(1:100, sqrt, mc.cores = 4))
```

```{r}
boot_df <- function(x) x[sample(nrow(x), rep = T), ]
rsquared <- function(mod) summary(mod)$r.square
boot_lm <- function(i) {
  rsquared(lm(mpg ~ wt + disp, data = boot_df(mtcars)))
}


```

```{r}
system.time(lapply(1:5000, boot_lm))
```

```{r}
system.time(parallel::mclapply(1:5000, boot_lm, mc.cores = 4))
```

## 11.3 Manipulating matrices and data frames

```{r}
a <- matrix(1:20, nrow = 5)
a
```

```{r}
apply(a, 1, mean)
```

```{r}
apply(a, 2, mean)
```

```{r}
a1 <- apply(a, 1, identity)
a1
```

```{r}
identical(a, a1)
```

```{r}
identical(a, t(a1))
```

```{r}
a2 <- apply(a, 2, identity)
identical(a, a2)
```

```{r}
x <- matrix(rnorm(20, 0, 10), nrow = 4)
x
```

```{r}
x1 <- sweep(x, 1, apply(x, 1, min), `-`)
x1
```

```{r}
x2 <- sweep(x1, 1, apply(x1, 1, max), `/`)
x2
```

```{r}
outer(1:3, 1:10, "*")
```

```{r}
pulse <- round(rnorm(22, 70, 10 / 3)) + rep(c(0, 5), c(10, 12))
group <- rep(c("A", "B"), c(10, 12))
```

```{r}
tapply(pulse, group, length)
```

```{r}
tapply(pulse, group, mean)
```

```{r}
split(pulse, group)
```

```{r}
tapply2 <- function(x, group, f, ..., simplify = TRUE) {
  pices <- split(x, group)
  sapply(pices, f, simplify = simplify)
}
tapply2(pulse, group, length)
tapply2(pulse, group, mean)
```

## 11.4 Manipulating lists

```{r}
Reduce(`+`, 1:3)
Reduce(sum, 1:3)
```

```{r}
Reduce2 <- function(f, x) {
  out <- x[[1]]
  for (i in seq(2, length(x))) {
    out <- f(out, x[[i]])
  }
  out
}
```

```{r}
l <- replicate(5, sample(1:10, 15, replace = TRUE), simplify = FALSE)
str(l)
```

```{r}
Reduce(intersect, l)
```

```{r}
where <- function(f, x) {
  vapply(x, f, logical(1))
}

df <- data.frame(x = 1:3, y = factor(c("a", "b", "c")))
where(is.factor, df)
str(Filter(is.factor, df))
str(Find(is.factor, df))
Position(is.factor, df)
```

## 11.5 Mathematical functionals

```{r}
integrate(sin, 0, pi)
```

```{r}
str(uniroot(sin, pi * c(1/2, 3/2)))
```

```{r}
str(optimise(sin, c(0, 2 * pi)))
```

```{r}
str(optimize(sin, c(0, pi), maximum = TRUE))
```

```{r}
poisson_nll <- function(x) {
  n <- length(x)
  sum_x <- sum(x)
  function(lambda) {
    n * lambda - sum_x * log(lambda)
  }
}
```

```{r}
x1 <- c(41, 30, 31, 38, 29, 24, 30, 29, 31, 38)
x2 <- c(6, 4, 7, 3, 3, 7, 5, 2, 2, 7, 5, 4, 12, 6, 9)
nll1 <- poisson_nll(x1)
nll2 <- poisson_nll(x2)
```

```{r}
optimize(nll1, c(0, 100))
```

```{r}
optimize(nll2, c(0, 100))
```

## 11.6 Loops that should be left as is

```{r}
trans <- list(
  disp = function(x) x * 0.0163871,
  am = function(x) factor(x, labels = c("auto", "manual"))
)
for(var in names(trans)) {
  mtcars[[var]] <- trans[[var]](mtcars[[var]])
}
```

```{r}
lapply(names(trans), function(var) {
  mtcars[[var]] <<- trans[[var]](mtcars[[var]])
})
```

```{r}
exps <- function(x, alpha) {
  s <- numeric(length(x) + 1)
  for (i in seq_along(s)) {
    if(i == 1) {
      s[i] <- x[i]
    } else {
      s[i] <- alpha * x[i] + (1 - alpha) * s[i-1] 
    }
  }
  s
}
x <- runif(6)
exps(x, 0.5)
```

```{r}
for (i in 1:10) print(i)
```

```{r}
i <- 1
while (i <= 10) {
  print(i)
  i <- i + 1
}
```

```{r}
i <- 0
while(TRUE) {
  if (runif(1) > 0.9) break
  i <- i + 1
  print(i)
}
```

```{r}
i <- rgeom(1, 0.1)
i
```

## 11.7 A family of functions

```{r}
add <- function(x, y) {
  stopifnot(length(x) == 1, length(y) == 1,
  is.numeric(x), is.numeric(y))
  x + y
}
```

```{r}
rm_na <- function(x, y, identity) {
  if (is.na(x) && is.na(y)) {
    identity
  } else if (is.na(x)) {
    y
  } else {
    x
  }
}

rm_na(NA, 10, 0)
rm_na(20, NA, 0)
rm_na(NA, NA, 0)
```

```{r}
add <- function(x, y, na.rm = FALSE) {
  if (na.rm && (is.na(x) || is.na(y))) rm_na(x, y, 0) else x + y
}
add(10, NA)
add(10, NA, na.rm = TRUE)
add(NA, NA)
add(NA, NA, na.rm = TRUE)
```

```{r}
add(add(3, NA, na.rm = TRUE), NA, na.rm = TRUE)
add(3, add(NA, NA, na.rm = TRUE), na.rm = TRUE)
```

```{r}
r_add <- function(xs, na.rm = TRUE) {
  Reduce(function(x, y) add(x, y, na.rm = na.rm), xs)
}
r_add(c(1, 4, 10))
```

```{r}
r_add(NA, na.rm = TRUE)
r_add(numeric())
```

```{r}
r_add <- function(xs, na.rm = TRUE) {
  Reduce(function(x, y) add(x, y, na.rm = na.rm), xs, init = 0)
}
r_add(c(1, 4, 10))
r_add(NA, na.rm = TRUE)
r_add(numeric())
```

```{r}
v_add1 <- function(x, y, na.rm = FALSE) {
  stopifnot(length(x) == length(y), is.numeric(x), is.numeric(y))
  if (length(x) == 0) return(numeric())
  simplify2array(
    Map(function(x, y) add(x, y, na.rm = na.rm), x, y)
  )
}

v_add2 <- function(x, y, na.rm = FALSE) {
  stopifnot(length(x) == length(y), is.numeric(x), is.numeric(y))
  vapply(seq_along(x), function(i) add(x[i], y[i], na.rm = na.rm),
    numeric(1))
}
```

```{r}
# Both versions give the same results
v_add1(1:10, 1:10)
v_add1(numeric(), numeric())
v_add1(c(1, NA), c(1, NA))
v_add1(c(1, NA), c(1, NA), na.rm = TRUE)
```

```{r}
c_add <- function(xs, na.rm = FALSE) {
  Reduce(function(x, y) add(x, y, na.rm = na.rm), xs,
    accumulate = TRUE)
}
c_add(1:10)
c_add(10:1)
```

```{r}
row_sum <- function(x, na.rm = FALSE) {
  apply(x, 1, r_add, na.rm = na.rm)
}
col_sum <- function(x, na.rm = FALSE) {
  apply(x, 2, r_add, na.rm = na.rm)
}
arr_sum <- function(x, dim, na.rm = FALSE) {
  apply(x, dim, r_add, na.rm = na.rm)
}
```
