---
title: "Chapter 12"
output: html_notebook
---

# 12 Function operators

```{r}
chatty <- function(f) {
  function(x, ...) {
    res <- f(x, ...)
    cat("Processing ", x, "\n", sep = "")
    res
  }
}
f <- function(x) x^2
s <- c(3, 2, 1)
```

```{r}
chatty(f)(1)
```

```{r}
vapply(s, chatty(f), numeric(1))
```

## 12.1 Behavioural FOs

```{r}
urls <- c()
download_file <- function(url, ...) {
  down.file(url, basename(url), ...)
}
lapply(urls, download_file)
```

```{r}
urls <- c()
i <- 1
for (url in urls) {
  i <- i + 1
  if (i %% 10 == 0) cat(".")
  Sys.delay(1)
  download_file(url)
}
```

```{r}
delay_by <- function(delay, f) {
  function(...) {
    Sys.sleep(delay)
    f(...)
  }
}

system.time(runif(100))
system.time(delay_by(1, runif)(100))
```

```{r}
dot_every <- function(n, f) {
  i <- 1
  function(...) {
    if (i %% n == 0) cat(".")
    i <<- i + 1
    f(...)
  }
}

x <- lapply(1:100, runif)
x <- lapply(1:100, dot_every(10, runif))
```

```{r}
download <- dot_every(10, delay_by(1, download_file))
```

```{r}
library(memoise)
```

```{r}
slow_function <- function() {
  Sys.sleep(1)
  10
}

system.time(slow_function())
system.time(slow_function())
```

```{r}
fast_function <- memoise(slow_function)
system.time(fast_function())
system.time(fast_function())
```

```{r}
fib <- function(n) {
  if (n < 1) {
    return(1)
  }
  fib(n - 2) + fib(n - 1)
}
system.time(fib(25))
system.time(fib(26))
```

```{r}
fib2 <- memoise(function(n) {
  if (n < 2) {
    return(1)
  }
  fib2(n - 2) + fib2(n - 1)
})
system.time(fib2(25))
system.time(fib2(26))
```

```{r}
runifm <- memoise(runif)
runifm(5)
runifm(5)
```

```{r}
download <- dot_every(10, memoise(delay_by(1, download_file)))
```

```{r}
ignore <- function(...) NULL
tee <- function(f, on_input = ignore, on_output = ignore) {
  function(...) {
    on_input(...)
    output <- f(...)
    on_output(output)
    output
  }
}
```

```{r}
g <- function(x) cos(x) - x
zero <- uniroot(g, c(-5, 5))
show_x <- function(x, ...) cat(sprintf("%+.08f", x), "\n")
```

```{r}
zero <- uniroot(tee(g, on_input = show_x), c(-5, 5))
```

```{r}
zero <- uniroot(tee(g, on_output = show_x), c(-5, 5))
```

```{r}
zero
```

```{r}
remember <- function() {
  memory <- list()
  f <- function(...) {
    # This is inefficient!
    memory <<- append(memory, list(...))
    invisible()
  }

  structure(f, class = "remember")
}
as.list.remember <- function(x, ...) {
  environment(x)$memory
}
print.remember <- function(x, ...) {
  cat("Remembering...\n")
  str(as.list(x))
}
```

```{r}
locs <- remember()
vals <- remember()
zero <- uniroot(tee(g, locs, vals), c(-5, 5))
x <- unlist(as.list(locs))
error <- unlist(as.list(vals))
plot(x, type = "b")
abline(h = 0.739, col = "grey50")
```

```{r}
plot(error, type = "b")
abline(h = 0, col = "grey50")
```

```{r}
funs <- list(mean = mean, sum = sum)

funs_m <- vector("list", length(funs))
for (fun in names(funs)) {
  funs_m[[fun]] <- delay_by(funs[[fun]], delay = 0.1)
}
funs_m$mean(1:10)
```

```{r}
delay_by <- function(delay, f) {
  force(f)
  function(...) {
    Sys.sleep(delay)
    f(...)
  }
}

funs_m <- vector("list", length(funs))
for (fun in names(funs)) {
  funs_m[[fun]] <- delay_by(funs[[fun]], delay = 0.1)
}
funs_m$mean(1:10)
```

```{r}
delay_by <- function(delay, f) {
  function(...) {
    Sys.sleep(delay)
    f(...)
  }
}

funs_m <- lapply(funs, delay_by, delay = 0.1)
funs_m$mean(1:10)
```

## 12.2 Output FOs

```{r}
Negate <- function(f) {
  force(f)
  function(...) !f(...)
}

Negate(is.null)(NULL)
```

```{r}
compact <- function(x) Filter(Negate(is.null), x)
```

```{r}
failwith <- function(default = NULL, f, quiet = FALSE) {
  force(f)
  function(...) {
    out <- default
    try(out <- f(...), silent = quiet)
    out
  }
}
# log("a")
```

```{r}
failwith(NA, log)("a")
failwith(NA, log, quiet = TRUE)("a")
failwith("Yes", log)("a")
```

```{r}

d1 <- data.frame(matrix(runif(40), ncol = 4))
names(d1) <- c("y", "x1", "x2", "x3")

d2 <- data.frame(matrix(runif(40), ncol = 4))
names(d2) <- c("y", "x1", "x2", "x3")

d3 <- data.frame(matrix(runif(40), ncol = 4))
names(d3) <- c("y", "x1", "x2", "x3")

datasets <- list(d1 = d1, d2 = d2, d3 = d3)



# If any model fails, all models fail to fit:
models <- lapply(datasets, glm,
  formula = y ~ x1 + x2 * x3,
  family = "gaussian"
)
# If a model fails, it will get a NULL value
models <- lapply(datasets, failwith(NULL, glm),
  formula = y ~ x1 + x2 * x3,
  family = "gaussian"
)

# remove failed models (NULLs) with compact
ok_models <- compact(models)
# extract the datasets corresponding to failed models
failed_data <- datasets[vapply(models, is.null, logical(1))]
```

```{r}
capture_it <- function(f) {
  force(f)
  function(...) {
    capture.output(f(...))
  }
}
str_out <- capture_it(str)
str(1:10)
str_out(1:10)
```

```{r}
time_it <- function(f) {
  force(f)
  function(...) {
    system.time(f(...))
  }
}
time_it(str)(1:10)
```

```{r}
compute_mean <- list(
  base = function(x) mean(x),
  sum = function(x) sum(x) / length(x)
)
x <- runif(1e6)
call_fun <- function(f, ...) f(...)
lapply(compute_mean, time_it(call_fun), x)
```

## 12.3 Input FOs

```{r}
# f <- function(a) g(a, b = 1)
# compact <- function(x) Filter(Negate(is.null), x)
# Map(function(x, y) f(x, y, zs), xs, ys)
```

```{r}
# f <- partial(g, b = 1)
# compact <- partial(Filter, Negate(is.null))
# Map(partial(f, zs = zs), xs, ys)
```

```{r}
pryr::partial
```

```{r}
funs2 <- list(
  sum = function(...) sum(..., na.rm = TRUE),
  mean = function(...) mean(..., na.rm = TRUE),
  median = function(...) median(..., na.rm = TRUE)
)
```

```{r}
library(pryr)
funs2 <- list(
  sum = partial(sum, na.rm = TRUE),
  mean = partial(mean, na.rm = TRUE),
  median = partial(median, na.rm = TRUE)
)
```

```{r}
sample2 <- Vectorize(sample, "size", SIMPLIFY = FALSE)
str(sample2(1:5, c(1, 1, 3)))
```

```{r}
(sample2(1:5, 5:3))
```

```{r}
splat <- function(f) {
  force(f)
  function(args) {
    do.call(f, args)
  }
}

x <- c(NA, runif(100), 1000)
args <- list(
  list(x),
  list(x, na.rm = TRUE),
  list(x, na.rm = TRUE, trim = 0.1)
)
lapply(args, splat(mean))
```

```{r}
# median(mtcars)
median(mtcars$mpg)
```

```{r}
plyr::colwise(median)(mtcars)
```

```{r}
?plyr::colwise
```

## 12.4 Combining FOs

```{r}
summaries <- plyr::each(mean, sd, median)
summaries(1:10)
```

```{r}
sapply(mtcars, function(x) length(unique(x)))
```

```{r}
compose <- function(f, g) {
  function(...) f(g(...))
}
```

```{r}
sapply(mtcars, compose(length, unique))
```

```{r}
"%o%" <- compose
sapply(mtcars, length %o% unique)
```

```{r}
sqrt(1 + 8)
compose(sqrt, `+`)(1, 8)
(sqrt %o% `+`)(1, 8)
```

```{r}
Negate <- partial(compose, `!`)
```

```{r}
square <- function(x) x^2
deviation <- function(x) x - mean(x)

sd2 <- sqrt %o% mean %o% square %o% deviation
sd2(1:10)
```

```{r}
download <- dot_every(10, memoise(delay_by(1, download_file)))

download <- pryr::compose(
  partial(dot_every, 10),
  memoise,
  partial(delay_by, 1)
)(download_file)

download <- (partial(dot_every, 10) %o%
  memoise %o%
  partial(delay_by, 1))(download_file)
```

```{r}
Filter(function(x) is.character(x) || is.factor(x), iris)
```

```{r}
and <- function(f1, f2) {
  force(f1)
  force(f2)
  function(...) {
    f1(...) && f2(...)
  }
}

or <- function(f1, f2) {
  force(f1)
  force(f2)
  function(...) {
    f1(...) || f2(...)
  }
}

not <- function(f) {
  force(f)
  function(...) {
    !f(...)
  }
}
```

```{r}
Filter(or(is.character, is.factor), iris)
Filter(not(is.numeric), iris)
```
