---
title: "Chapter 14"
output: html_notebook
---

# 14 Expressions

## 14.1 Structure of expressions

```{r}
x <- 4
y <- x * 10
y
```

```{r}
z <- quote(y <- x * 10)
str(z)
```

```{r}
library(pryr)
ast(y <- x * 10)
```

```{r}
ast("a")
ast(1)
ast(1L)
ast(TRUE)
```

```{r}
identical(1, quote(1))
#> [1] TRUE
identical("test", quote("test"))
#> [1] TRUE
```

```{r}
ast(x)
ast(mean)
ast(`an unusual name`)
```

```{r}
ast(f())
```

```{r}
ast(f(1, 2))
```

```{r}
ast(f(a, b))
```

```{r}
ast(f(g(), h(1, a)))
```

```{r}
ast(a + b)
```

```{r}
ast(if (x > 1) x else 1 / x)
```

```{r}
ast(function(x = 1, y) x)
```

```{r}
ast(function(x = 1, y = x * 2) {
  x / y
})
```

```{r}
str(quote(a))
```

```{r}
str(quote(a + b))
```

## 14.2 Names

```{r}
as.name("name")
identical(quote(name), as.name("name"))
is.name("name")
is.name(quote(name))
is.name(quote(f(name)))
```

```{r}
as.name("a b")
as.name("if")
```

```{r}
f <- function(x) 10
formals(f)$x
is.name(formals(f)$x)
as.character(formals(f)$x)
missing_arg <- formals(f)$x
try(is.name(missing_arg))
```

```{r}
quote(expr = 1 + 1)
```

## 14.3 Calls

```{r}
x <- quote(read.csv("important.csv", row.names = FALSE))
x[[1]]
is.name(x[[1]])
```

```{r}
y <- quote(add(10)(20))
y[[1]]
is.call(y[[1]])
```

```{r}
x <- quote(read.csv("important.csv", row.names = FALSE))
x[[2]]
x$row.names
names(x)
```

```{r}
length(x) - 1
```

```{r}
y <- quote(read.csv("important.csv", row.names = FALSE))
y$row.names <- TRUE
y$col.names <- FALSE
y
```

```{r}
x[-3]
```

```{r}
x[-1]
```

```{r}
x
```

```{r}
as.list(x[-1])
```

```{r}
m1 <- quote(read.delim("data.txt", sep = "|"))
m2 <- quote(read.delim(s = "|", "data.txt"))
m3 <- quote(read.delim(file = "data.txt", , "|"))
```

```{r}
standardise_call(m1)
standardise_call(m2)
standardise_call(m3)
```

```{r}
call(":", 1, 10)
```

```{r}
call("mean", 1:10, na.rm = TRUE)
```

```{r}
as.call(list(quote(mean), quote(1:10)))
```

```{r}
as.call(list(quote(mean), quote(1:10)))
```

```{r}
as.call(list(quote(adder(10)), 20))
```

```{r}
(a <- call("mean", 1:10))
(b <- call("mean", quote(1:10)))
identical(a, b)
```

## 14.4 Capturing the current call

```{r}
f <- function(abc = 1, def = 2, ghi = 3) {
  list(sys = sys.call(), match = match.call())
}
f(d = 2, 2)
```

```{r}
mod <- lm(mpg ~ wt, data = mtcars)
update(mod, formula = . ~ . + cyl)
```

```{r}
update_call <- function(object, formula., ...) {
  call <- object$call

  if (!missing(formula.)) {
    call$formula <- update.formula(formula(object), formula.)
  }

  modify_call(call, dots(...))
}
update_model <- function(object, formula., ...) {
  call <- update_call(object, formula., ...)
  eval(call, parent.frame())
}
update_model(mod, formula = . ~ . + cyl)
```

```{r}
f <- function() {
  n <- 3
  lm(mpg ~ poly(wt, n), data = mtcars)
}
mod <- f()
try(update(mod, data = mtcars))
#> Error in poly(wt, n): object 'n' not found

update_model <- function(object, formula., ...) {
  call <- update_call(object, formula., ...)
  eval(call, environment(formula(object)))
}
update_model(mod, data = mtcars)
```

## 14.5 Pairlists

```{r}
make_function <- function(args, body, env = parent.frame()) {
  args <- as.pairlist(args)

  eval(call("function", args, body), env)
}
```

```{r}
add <- make_function(alist(a = 1, b = 2), quote(a + b))
add(1)
add(1, 2)
```

```{r}
add2 <- make_function(alist(a = , b = a), quote(a + b))
add2(1)
```

```{r}
add3 <- make_function(alist(a = , b = , ... = ), quote(a + b))
add3
add3(1, 2, 4)
```

```{r}
adder <- function(x) {
  make_function(alist(y = ), substitute({
    x + y
  }), parent.frame())
}
adder(10)
```

```{r}
curve(sin(exp(4 * x)), n = 1000)
```

```{r}
curve2 <- function(expr, xlim = c(0, 1), n = 100,
                   env = parent.frame()) {
  f <- make_function(alist(x = ), substitute(expr), env)

  x <- seq(xlim[1], xlim[2], length = n)
  y <- f(x)

  plot(x, y, type = "l", ylab = deparse(substitute(expr)))
}
curve2(sin(exp(4 * x)), n = 1000)
```

## 14.6 Parsing and deparsing

```{r}
z <- quote(y <- x * 10)
deparse(z)
```

```{r}
x <- 1
eval(parse(text = deparse(z)))
y
```

```{r}
exp <- parse(text = c("x <- 4
                      x
                      5
                      "))
length(exp)
typeof(exp)
exp[[1]]
exp[[2]]
```

## 14.7 Walking the AST with recursive functions

```{r}
recurse_call <- function(x) {
  if (is.atomic(x)) {
    # Return a value
  } else if (is.name(x)) {
    # Return a value
  } else if (is.call(x)) {
    # Call recurse_call recursively
  } else if (is.pairlist(x)) {
    # Call recurse_call recursively
  } else {
    # User supplied incorrect input
    stop("Don't know how to handle type ", typeof(x),
      call. = FALSE
    )
  }
}
```

```{r}
ast(TRUE)
ast(T)
```

```{r}
logical_abbr <- function(x) {
  if (is.atomic(x)) {
    FALSE
  } else if (is.name(x)) {
    identical(x, quote(T)) || identical(x, quote(F))
  } else if (is.call(x) || is.pairlist(x)) {
    for (i in seq_along(x)) {
      if (logical_abbr(x[[i]])) {
        return(TRUE)
      }
    }
    FALSE
  } else {
    stop("Don't know how to handle type ", typeof(x),
      call. = FALSE
    )
  }
}

logical_abbr(quote(TRUE))
#> [1] FALSE
logical_abbr(quote(T))
#> [1] TRUE
logical_abbr(quote(mean(x, na.rm = T)))
#> [1] TRUE
logical_abbr(quote(function(x, na.rm = T) FALSE))
#> [1] TRUE
```

```{r}
ast(x <- 10)
```

```{r}
find_assign <- function(x) {
  if (is.atomic(x) || is.name(x)) {
    NULL
  } else if (is.call(x)) {
    if (identical(x[[1]], quote(`<-`))) {
      x[[2]]
    } else {
      lapply(x, find_assign)
    }
  } else if (is.pairlist(x)) {
    lapply(x, find_assign)
  } else {
    stop("Don't know how to handle type ", typeof(x),
      call. = FALSE
    )
  }
}
find_assign(quote(a <- 1))
#> a
find_assign(quote({
  a <- 1
  b <- 2
}))
```

```{r}
find_assign2 <- function(x) {
  if (is.atomic(x) || is.name(x)) {
    character()
  } else if (is.call(x)) {
    if (identical(x[[1]], quote(`<-`))) {
      as.character(x[[2]])
    } else {
      unlist(lapply(x, find_assign2))
    }
  } else if (is.pairlist(x)) {
    unlist(lapply(x, find_assign2))
  } else {
    stop("Don't know how to handle type ", typeof(x),
      call. = FALSE
    )
  }
}

find_assign2(quote({
  a <- 1
  b <- 2
  a <- 3
}))
#> [1] "a" "b" "a"

find_assign2(quote({
  system.time(x <- print(y <- 5))
}))
#> [1] "x"
```

```{r}
find_assign3 <- function(x) {
  if (is.atomic(x) || is.name(x)) {
    character()
  } else if (is.call(x)) {
    if (identical(x[[1]], quote(`<-`))) {
      lhs <- as.character(x[[2]])
    } else {
      lhs <- character()
    }

    unique(c(lhs, unlist(lapply(x, find_assign3))))
  } else if (is.pairlist(x)) {
    unique(unlist(lapply(x, find_assign3)))
  } else {
    stop("Don't know how to handle type ", typeof(x),
      call. = FALSE
    )
  }
}

find_assign3(quote({
  a <- 1
  b <- 2
  a <- 3
}))
#> [1] "a" "b"

find_assign3(quote({
  system.time(x <- print(y <- 5))
}))
#> [1] "x" "y"
```

```{r}
find_assign3(quote({
  l <- list()
  l$a <- 5
  names(l) <- "b"
}))
#> [1] "l"     "$"     "a"     "names"
```

```{r}
ast(l$a <- 5)
#> \- ()
#>   \- `<-
#>   \- ()
#>     \- `$
#>     \- `l
#>     \- `a
#>   \-  5
ast(names(l) <- "b")
#> \- ()
#>   \- `<-
#>   \- ()
#>     \- `names
#>     \- `l
#>   \-  "b"
```

```{r}
find_assign4 <- function(x) {
  if (is.atomic(x) || is.name(x)) {
    character()
  } else if (is.call(x)) {
    if (identical(x[[1]], quote(`<-`)) && is.name(x[[2]])) {
      lhs <- as.character(x[[2]])
    } else {
      lhs <- character()
    }

    unique(c(lhs, unlist(lapply(x, find_assign4))))
  } else if (is.pairlist(x)) {
    unique(unlist(lapply(x, find_assign4)))
  } else {
    stop("Don't know how to handle type ", typeof(x),
      call. = FALSE
    )
  }
}

find_assign4(quote({
  l <- list()
  l$a <- 5
  names(l) <- "b"
}))
#> [1] "l"
```

```{r}
a <- 1
b <- 3
bquote(a + b)
```

```{r}
bquote(a + .(b))
```

```{r}
bquote(.(a) + .(b))
```

```{r}
bquote(.(a + b))
```

```{r}
bquote2 <- function(x, where = parent.frame()) {
  if (is.atomic(x) || is.name(x)) {
    # Leave unchanged
    x
  } else if (is.call(x)) {
    if (identical(x[[1]], quote(.))) {
      # Call to .(), so evaluate
      eval(x[[2]], where)
    } else {
      # Otherwise apply recursively, turning result back into call
      as.call(lapply(x, bquote2, where = where))
    }
  } else if (is.pairlist(x)) {
    as.pairlist(lapply(x, bquote2, where = where))
  } else {
    # User supplied incorrect input
    stop("Don't know how to handle type ", typeof(x),
      call. = FALSE
    )
  }
}

x <- 1
y <- 2
bquote2(quote(x == .(x)))
bquote2(quote(function(x = .(x)) {
  x + .(y)
}))
```

```{r}
bquote2(quote(function(x = .(x)) {
  # This is a comment
  x + # funky spacing
    .(y)
}))
```
