---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(brms)
```


```{r}
d <- read.csv("RStanBook-master/chap04/input/data-salary.txt")
d
```

```{r}
d |> 
  ggplot(aes(x=X, y=Y)) +
  geom_point() +
  # geom_point(shape=1, size=3) +
  theme_bw(base_size=18)
```

```{r}
res_lm <- lm(Y ~ X, data = d)
summary(res_lm)
```
```{r}
X_new <- data.frame(X = 23:60)
X_new <-
  X_new |> 
  bind_cols(
    predict(res_lm, newdata = X_new, interval = "confidence", level = 0.95),
    predict(res_lm, newdata = X_new, interval = "confidence", level = 0.50),
    predict(res_lm, newdata = X_new, interval = "prediction", level = 0.95),
    predict(res_lm, newdata = X_new, interval = "prediction", level = 0.50)
  )
names(X_new) <- c("X", 
       "conf_95_fit", "conf_95_lwr", "conf_95_upr",
       "conf_50_fit", "conf_50_lwr", "conf_50_upr",
       "pred_95_fit", "pred_95_lwr", "pred_95_upr",
       "pred_50_fit", "pred_50_lwr", "pred_50_upr"
  )
X_new
```


```{r}
X_new |> 
  ggplot(aes(X)) +
  geom_ribbon(aes(ymin = conf_95_lwr, ymax = conf_95_upr), alpha = 1/6) +
  geom_ribbon(aes(ymin = conf_50_lwr, ymax = conf_50_upr), alpha = 2/6) +
  geom_line(aes(y = conf_50_fit)) +
  geom_point(aes(y = Y), data = d) +
  labs(x='X', y='Y') + 
  coord_cartesian(xlim=c(22, 61), ylim=c(200, 1400)) +
  scale_y_continuous(breaks=seq(from=200, to=1400, by=400)) + 
  theme_bw(base_size = 18)

X_new |>
  ggplot(aes(X)) +
  geom_ribbon(aes(ymin = pred_95_lwr, ymax = pred_95_upr), alpha = 1/6) +
  geom_ribbon(aes(ymin = pred_50_lwr, ymax = pred_50_upr), alpha = 2/6) +
  geom_line(aes(y = pred_50_fit)) +
  geom_point(aes(y = Y), data = d) +
  labs(x='X', y='Y') + 
  coord_cartesian(xlim=c(22, 61), ylim=c(200, 1400)) +
  scale_y_continuous(breaks=seq(from=200, to=1400, by=400)) + 
  theme_bw(base_size = 18)
```

```{r}
res_brm <- brm(Y ~ X, data = d, refresh = 0)
res_brm
```

```{r}
stancode(res_brm)
```

```{r}
res_brm
```

```{r}
res_brm$fit
```

```{r}
plot(res_brm)
```






