---
title: "note02"
output: html_notebook
---

```{r}
library(tidyverse)
```

# Case Studies

## 2.2 Age-Related Macular Degeneration Trial

```{r}
armd240.data <- read.csv("https://raw.githubusercontent.com/cran/nlmeU/master/inst/csvData/armd240.data.csv")
armd240.data
```

```{r}
dim(armd240.data)
```

```{r}
nms <- names(armd240.data)
nms
```

```{r}
unique(sapply(armd240.data, class))
```

```{r}
str(armd240.data)
```

```{r}
abbreviate(nms)
```

```{r}
data(armd.wide, package = "nlmeU")
armd.wide
```

```{r}
str(armd.wide)
```

```{r}
facs <- sapply(armd.wide, is.factor)
facs
```

```{r}
names(facs[facs == TRUE])
```

```{r}
attach(armd240.data)
treat.f <-
  factor(treat, labels = c("Placebo", "Active"))
levels(treat.f)
str(treat.f)
```

```{r}
miss.pat <- nlmeU:::missPat(visual4, visual12, visual24, visual52)
miss.pat
length(miss.pat)
mode(miss.pat)
detach(armd240.data)
```

```{r}
data(armd0, package = "nlmeU")
armd0
```

```{r}
dim(armd0)
names(armd0)
str(armd0)
```

```{r}
armd0 %>%
  ggplot(aes(time, visual)) +
  geom_line(aes(group = subject), alpha = 0.3) +
  facet_wrap(~treat.f)
```

```{r}
auxDt <- subset(armd0, time > 0)
auxDt
```

```{r}
levels(auxDt$time.f)
```

```{r}
armd <- droplevels(auxDt)
armd
```

```{r}
levels(armd$time.f)
```

```{r}
armd <- within(armd, {
  contrasts(time.f) <- contr.poly(4, scores = c(4, 12, 24, 52))
})
armd
```

## 2.3 Progressive Resistance Training Study

```{r}
prt.subjects.data <- read.csv("https://raw.githubusercontent.com/cran/nlmeU/master/inst/csvData/prt.subjects.data.csv", as.is = TRUE)
prt.subjects.data
```

```{r}
glimpse(prt.subjects.data)
```

```{r}
prt.fiber.data <- read.csv("https://raw.githubusercontent.com/cran/nlmeU/master/inst/csvData/prt.fiber.data.csv")
prt.fiber.data
```

```{r}
glimpse(prt.fiber.data)
```

```{r}
prt.subjects <-
  within(prt.subjects.data, {
    id <- factor(id)
    bmi <- weight / (height^2)
    sex.f <- factor(gender, labels = c("Female", "Male"))
    age.f <- factor(ageGrp, labels = c("Young", "Old"))
    prt.f <- factor(trainGrp, levels = c("1", "0"), labels = c("High", "Low"))
    gender <- ageGrp <- trainGrp <- height <- weight <- NULL
  })
prt.subjects
```

```{r}
prt.fiber <-
  within(prt.fiber.data, {
    id <- factor(id)
    fiber.f <- factor(fiber.type, labels = c("Type 1", "Type 2"))
    occ.f <- factor(train.pre.pos, labels = c("Pre", "Pos"))
    fiber.type <- train.pre.pos <- NULL
  })
prt.fiber
```

```{r}
prt <- merge(prt.subjects, prt.fiber, sort = FALSE)
prt
```

```{r}
names(prt)
```

## 2.4 The Study of Instructional Improvement Project

```{r}
data(classroom, package = "WWGbook")
classroom
```

```{r}
glimpse(classroom)
```

```{r}
SIIdata <-
  within(classroom, {
    sex <- factor(sex, levels = c(0, 1), labels = c("M", "F"))
    minority <- factor(minority, labels = c("Mnrt:No", "Mnrt:Yes"))
    schoolid <- factor(schoolid)
    classid <- factor(classid)
    childid <- factor(childid)
  })
SIIdata
```

```{r}
fp <- "temp/SIIdata.Rdata"
save(SIIdata, file = "temp/SIIdata.Rdata")
file.exists(fp)
(load(fp))
```

```{r}
data(SIIdata, package = "nlmeU")
dtId <- subset(SIIdata, select = c(schoolid, classid, childid))
dtId
```

```{r}
any(duplicated(dtId))
```

```{r}
library(nlme)
```

```{r}
names(gsummary(dtId, form = ~childid, inv = TRUE))
```

```{r}
names(gsummary(dtId, form = ~classid, inv = TRUE))
```

```{r}
names(gsummary(dtId, form = ~schoolid, inv = TRUE))
```

```{r}
nms1 <- names(gsummary(SIIdata, form = ~schoolid, inv = TRUE))
nms1
```

```{r}
nms2a <- names(gsummary(SIIdata, form = ~classid, inv = TRUE))
nms2a
```

```{r}
idx1 <- match(nms1, nms2a)
nms2 <- nms2a[-idx1]
nms2
```

```{r}
nms3a <- names(gsummary(SIIdata, form = ~childid, inv = TRUE))
nms3a
```

```{r}
idx12 <- match(c(nms1, nms2), nms3a)
nms3a[-idx12]
```

## 2.5 The Flemish Community Attainment-Targets Study

```{r}
crossreg.data <- read.csv("https://raw.githubusercontent.com/cran/nlmeU/master/inst/csvData/crossreg.data.csv")
crossreg.data
```

```{r}
unique(crossreg.data$target)
```

```{r}
unique(crossreg.data$id)
```

```{r}
unique(crossreg.data$scorec)
```

```{r}
summary(crossreg.data$scorec)
```

```{r}
nItms <- c(4, 6, 8, 5, 9, 6, 8, 6, 5)
lbls <- paste("T", 1:9, "(", nItms, ")", sep = "")
lbls
```

```{r}
fcat <- within(crossreg.data, {
  id <- factor(id)
  target <- factor(target, labels = lbls)
})
fcat
```

```{r}
tab1 <- xtabs(~ id + target, data = fcat)
tab1
```

```{r}
all(tab1 > 0)
range(tab1)
```

# ---
