---
title: "note06"
output: html_notebook
---

# 6 ARMD Trial: Linear Model with Homogeneous Variance

```{r}
data(armd, package = "nlmeU")
```


## 6.3 Fitting a Linear Model Using the lm() Function

```{r}
lm1.form <-
  formula(visual ~ -1 + visual0 + time.f + treat.f:time.f)
```

```{r}
vis.lm1.mf <- model.frame(lm1.form, armd)
vis.lm1.mf
```

```{r}
vis.lm1.dm <- model.matrix(lm1.form, vis.lm1.mf)
dim(vis.lm1.dm)
```

```{r}
(nms <- colnames(vis.lm1.dm))
```

```{r}
nms <- (abbreviate(nms))
nms
```

```{r}
colnames(vis.lm1.dm) <- nms
head(vis.lm1.dm, n = 6)
```

```{r}
attr(vis.lm1.dm, "contrasts")
```

```{r}
str(armd$time.f)
```

```{r}
contrasts(armd$treat.f)
```

```{r}
contrasts(armd$time.f)
```

```{r}
data(armd, package = "nlmeU")
summary(lm(visual ~ 0 + visual0 + time.f + treat.f:time.f, data = armd))
```

```{r}
str(armd$time.f)
```

```{r}
lm6.1 <- lm(lm1.form, data = armd)
summ <- summary(lm6.1)
summ
```

```{r}
tT <- coef(summ)
rownames(tT)
```

```{r}
printCoefmat(tT, P.values = TRUE)
```

```{r}
summ$sigma
```

```{r}
anova(lm6.1)
```

```{r}
plot(fitted(lm6.1), resid(lm6.1))
abline(h = seq(-40, 40, by = 20), col = "grey")
abline(v = seq(10, 80, by = 10), col = "grey")
```

```{r}
qqnorm(resid(lm6.1))
qqline(resid(lm6.1))
```

```{r}
par(mfrow = c(2, 2))
plot(lm6.1)
```

## 6.4 Fitting a Linear Model Using the gls() Function

```{r}
library(nlme)
```

```{r, paged.print = FALSE}
fm6.1 <- gls(lm1.form, data = armd)
summary(fm6.1)
```

```{r, paged.print = FALSE}
fm6.1ML <- gls(lm1.form, data = armd, method = "ML")
summary(fm6.1ML)
```

```{r}
intervals(fm6.1)
```

```{r}
plot(predict(fm6.1), residuals(fm6.1))
```

```{r}
qqnorm(residuals(fm6.1))
qqline(residuals(fm6.1))
```

```{r}
plot(fm6.1)
```

```{r}
all.equal(coef(lm6.1), coef(fm6.1))
all.equal(coef(lm6.1), coef(fm6.1ML))
```
