---
title: "note05"
output: html_notebook
---

# 5 Fitting Linear Models with Homogeneous Variance: The lm() and gls() Functions

## 5.2 Specifying the Mean Structure Using a Model Formula

```{r}
y ~ x1
```

```{r}
formula(y ~ x1)
```

```{r}
formA <- y ~ f1 * f2
```

```{r}
termsA <- terms(formA)
termsA
```

```{r}
attributes(termsA)
```

```{r}
names(attributes(termsA))
```

```{r}
labels(termsA)
```

```{r}
attr(termsA, "order")
attr(termsA, "intercept")
attr(termsA, "variables")
```

```{r}
formB <- update(formA, . ~ . - f1:f2 - 1)
termsB <- terms(formB)
attributes(termsB)
```

## 5.3 From a Formula to the Design Matrix 99

```{r}
form1 <- formula(
  visual52 ~
    sqrt(line0) +
    factor(lesion) +
    treat.f * log(visual24) +
    poly(visual0, 2)
)
```

```{r}
data(armd.wide, package = "nlmeU")
str(armd.wide)
```

```{r}
armd.mf1 <-
  model.frame(
    form1,
    data = armd.wide,
    subset = !(subject %in% c("1", "2")),
    na.action = na.exclude,
    SubjectId = subject
  )
armd.mf1
```

```{r}
class(armd.mf1)
```

```{r}
dim(armd.mf1)
```

```{r}
names(armd.mf1)
```

```{r}
head(armd.mf1, n = 4)
```

```{r}
terms.mf1 <- attr(armd.mf1, "terms")
class(terms.mf1)
```

```{r}
names(attributes(terms.mf1))
```

```{r}
attr(terms.mf1, "dataClasses")
```

```{r}
attr(terms.mf1, "predvars")
```

```{r}
labels(terms.mf1)
```

```{r}
Xmtx <- model.matrix(form1, armd.mf1)
head(Xmtx)
```

```{r}
dim(Xmtx)
```

```{r}
(nms <- colnames(Xmtx))
```

```{r}
colnames(Xmtx) <- abbreviate(nms)
print(head(Xmtx, n = 6), digits = 4)
```

```{r}
names(attributes(Xmtx))
```

```{r}
attr(Xmtx, "assign")
```

```{r}
attr(Xmtx, "contrasts")
```

```{r}
contr.treatment((3))
```

```{r}
contr.treatment(3, base = 3)
```

```{r}
contr.sum(3)
```

```{r}
contr.helmert(3)
```

```{r}
contr.poly(3, scores = c(1, 5, 7))
```

```{r}
options()$contrasts
```

```{r}
lesion.f <- factor(armd.wide$lesion)
str(lesion.f)
```

```{r}
names(attributes(lesion.f))
```

```{r}
levels(lesion.f)
```

```{r}
contrasts(lesion.f)
```

```{r}
lesion2.f <- C(lesion.f, contr.sum(4))
lesion2.f
```

```{r}
names(attributes(lesion2.f))
```

```{r}
contrasts(lesion2.f)
```

```{r}
lesion2a.f <- factor(lesion.f)
contrasts(lesion2a.f) <- contr.sum(4)
contrasts(lesion2a.f)
```
