---
title: "note09"
output: html_notebook
---

# 9 ARMD Trial: Linear Model with Heterogeneous Variance

```{r}
library(nlme)
library(lattice)
```

```{r}
data(armd, package = "nlmeU")
armd
```

## 9.2 A Linear Model with Independent Residual Errors and Heterogeneous Variance

```{r}
lm1.form <-
  formula(visual ~ -1 + visual0 + time.f + treat.f:time.f)
lm1.form
```

```{r, paged.print = FALSE}
fm9.1 <-
  gls(lm1.form,
    weights = varIdent(form = ~ 1 | time.f),
    data = armd
  )
summary(fm9.1)
```

```{r}
fm9.1$modelStruct$varStruct
```

```{r}
intervals(fm9.1, which = "var-cov")
```

```{r, paged.print = FALSE}
fm6.1 <- gls(lm1.form, data = armd)
summary(fm6.1)
```

```{r}
anova(fm6.1, fm9.1)
```

## 9.3 Linear Models with the varPower(·) Variance-Function

```{r, paged.print=FALSE}
fm9.2 <-
  update(fm9.1,
    weights = varPower(form = ~time)
  )
summary(fm9.2)
```

```{r, paged.print=FALSE}
fm9.3 <-
  update(fm9.1,
    weights = varPower(form = ~ time | treat.f)
  )
summary(fm9.3)
```

```{r, paged.print=FALSE}
fm9.4 <-
  update(fm9.1, weights = varPower())
summary(fm9.4)
```

```{r, paged.print=FALSE}
fm9.5 <-
  update(fm9.1, weights = varPower(fixed = 1))
summary(fm9.5)
```

```{r}
anova(fm9.1, fm9.2, fm9.3, fm9.4, fm9.5)
```

```{r}
mSt2 <- fm9.2$modelStruct
vF2 <- mSt2$varStruct
summary(vF2)
```

```{r}
summary(fm9.2)$sigma
```

```{r}
mSt3 <- fm9.3$modelStruct
vF3 <- mSt3$varStruct
summary(vF3)
```

```{r}
coef(vF3)
```

```{r}
formula(vF3)
```

```{r}
varWeights(vF3)[3:10]
```

```{r}
plot(
  fm9.2,
  resid(., type = "response") ~ fitted(.)
)
plot(
  fm9.2,
  resid(., type = "response") ~ time
)
bwplot(resid(fm9.2) ~ time.f, pch = "|", data = armd)
```

```{r}
plot(
  fm9.2,
  resid(., type = "pearson") ~ fitted(.)
)
plot(
  fm9.2,
  resid(., type = "pearson") ~ time
)
bwplot(resid(fm9.2, type = "pearson") ~ time.f, pch = "|", data = armd)
```

```{r}
plot(fm9.2,
  sqrt(abs(resid(., type = "response"))) ~ fitted(.),
  type = c("p", "smooth")
)
plot(fm9.2,
  sqrt(abs(resid(., type = "pearson"))) ~ fitted(.),
  type = c("p", "smooth")
)
```

```{r, fig.asp = 1}
#library(tidyverse)
res <- cbind(resid = residuals(fm9.2, type = "pearson"), armd)
res %>%
  dplyr::filter(miss.pat == "----") %>%
  dplyr::select(subject, resid, time.f) %>%
  tidyr::pivot_wider(names_from = time.f, values_from = resid) %>%
  dplyr::select(-subject) %>%
  splom()
```
