---
title: "Chapter 4"
output: html_notebook
---

# 4 One-parameter root-finding problems

## 4.3 Some examples

### 4.3.1 Exponentially speaking

```{r}
## ----label=C04chunk13,echo=TRUE,cache=TRUE-------------------------------
# cat("exponential example\n")
# require("rootoned")
alpha <- 1.0
efn <- function(x, alpha) {
  exp(-alpha * x) - 0.2
}
zfn <- function(x) {
  x * 0
}
tint <- c(0, 100)
curve(efn(x, alpha = 1.0), from = tint[1], to = tint[2], lty = 2, ylab = "efn(x, alpha)")
title(sub = "dashed for alpha=1, dotted for alpha=0.2")
curve(zfn, add = TRUE)
curve(efn(x, alpha = 0.02), add = TRUE, lty = 3)
```

```{r}
rform1 <- -log(0.2) / 1.0
rform2 <- -log(0.2) / 0.02
rform1
rform2
```

```{r}
resr1 <- uniroot(efn, tint, tol = 1e-10, alpha = 1)
cat("alpha = ", 1.0, "\n")
cat(
  "root(formula):", rform1,
  " root1d:", resr1$root,
  " tol:", resr1$estim.prec,
  " fval:", resr1$f.root, "in", resr1$iter, "\n\n"
)
```

```{r}
resr2 <- uniroot(efn, tint, tol = 1e-10, alpha = 0.02)
cat("alpha = ", 0.02, "\n")
cat(
  "root(formula):", rform2,
  " root1d:", resr2$root,
  " tol:", resr2$estim.prec,
  " fval:", resr2$f.root, "in", resr2$iter, "\n\n"
)
```

```{r}
cat("Now look for the root in [0,1]\n")
tint2a <- c(0, 1)
resr2a <- try(uniroot(efn, tint2a, tol = 1e-10, alpha = 0.02)) # raise error
```

### 4.3.2 A normal concern

```{r}
## ----label=C04chunk9, echo=TRUE, size="scriptsize", cache=TRUE-----------
cat("Gaussian derivative\n")
der <- function(x, mu, sigma) {
  dd <- (-1) * (1 / sqrt(2 * pi * sigma^2)) * (exp(-(x - mu)^2 / (2 * sigma^2)) *
    ((x - mu) / (sigma^2)))
}
x <- seq(0, 8, length.out = 10001)
plot(x, der(x, mu = 4, sigma = 1), type = "l")
lines(x, der(x, mu = 4, sigma = 0.1), type = "l", col = "blue")
lines(x, der(x, mu = 4, sigma = 0.01), type = "l", col = "red")
lines(x, der(x, mu = 4, sigma = 0.001), type = "l", col = "orange")
```

```{r}
r1 <- uniroot(der, lower = 1, upper = 6, mu = 4, sigma = 1)
r.1 <- uniroot(der, lower = 1, upper = 6, mu = 4, sigma = .1)
r.01 <- uniroot(der, lower = 1, upper = 6, mu = 4, sigma = .01) # 근을 못구함
r.001 <- uniroot(der, lower = 1, upper = 6, mu = 4, sigma = .001) # 근을 못구함
sig <- c(1, .1, .01, .001)
roo <- c(r1$root, r.1$root, r.01$root, r.001$root)
tabl <- data.frame(sig, roo)
print(tabl)
```

```{r}
library(Rmpfr)
```

```{r}
der <- function(x, mu, sigma) {
  dd <- (-1) * (1 / sqrt(2 * pi * sigma^2)) * (exp(-(x - mu)^2 / (2 * sigma^2)) * ((x - mu) / (sigma^2)))
}
```

```{r}
rootint1 <- mpfr(c(1.9, 2.1), 200)
rootint1
r140 <- try(unirootR(der, rootint1, tol = 1e-40, mu = 4, sigma = 1))
```

```{r}
rootint2 <- mpfr(c(1, 6), 200)
rootint2
```

```{r}
r140a <- try(unirootR(der, rootint2, tol = 1e-40, mu = 4, sigma = 1))
r140a
```

### 4.3.3 Little Polly Nomial

```{r}
## ----label=C04chunk10, echo=TRUE, size="scriptsize", cache=TRUE----------
z <- c(10, -3, 0, 1)
simpol <- function(x) { # calculate polynomial z at x
  zz <- c(10, -3, 0, 1)
  ndeg <- length(zz) - 1 # degree of polynomial
  val <- zz[ndeg + 1]
  for (i in 1:ndeg) {
    val <- val * x + zz[ndeg + 1 - i]
  }
  val
}

simpol2 <- function(x) {
  10 - 3 * x + x^3
}
```

```{r}
tint <- c(-5, 5)
cat("roots of polynomial specified by ")
print(z)
cat("\n")
```

```{r}
curve(simpol, from = tint[1], to = tint[2])
curve(simpol2, from = tint[1], to = tint[2])
```

```{r}
require(polynom)
allroots <- polyroot(z)
print(allroots)
```

```{r}
cat("single root from uniroot on interval ", tint[1], ",", tint[2], "\n")
rt1 <- uniroot(simpol, tint)
print(rt1)
```

```{r}
rt2 <- uniroot(simpol2, tint)
print(rt2)
```

```{r}
## ----label=C04chunk11, echo=TRUE, size="scriptsize", cache=TRUE----------
z <- c(16, -8, 1)
simpol2 <- function(x) { # calculate polynomial z at x
  val <- (x - 4)^2
}
tint <- c(-5, 5)
cat("roots of polynomial specified by ")
print(z)
require(polynom)
allroots <- polyroot(z)
print(allroots)
```

```{r}
cat("single root from uniroot on interval ", tint[1], ",", tint[2], "\n")
rt1 <- try(uniroot(simpol2, tint), silent = TRUE)
print(strwrap(rt1))
```

```{r}
cat("\n Try a cubic\n")
cub <- function(z) {
  val <- (z - 4)^3
}
cc <- c(-64, 48, -12, 1)
croot <- polyroot(cc)
croot
```

```{r}
ans <- uniroot(cub, lower = 2, upper = 6)
ans
```

### 4.3.4 A hypothequial question

```{r}
## ----label=C04chunk12, echo=TRUE, size="scriptsize", cache=TRUE----------
mrate <- function(R) {
  val <- 0
  den <- 1
  fact <- 1 / 6
  term <- 1
  rr <- R / 200
  repeat { # main loop
    term <- term * fact * rr / den
    vallast <- val
    val <- val + term
    #      cat("term =",term,"  val now ",val,"\n")
    if (val == vallast) break
    fact <- (fact - 1)
    den <- den + 1
    if (den > 1000) stop("Too many terms in mrate")
  }
  val * 100
}
A <- function(I, Rval) {
  A <- (1 + I / 100)^6 - (1 + R / 200)
}
```

```{r}
Rvec <- c()
i.formula <- c()
i.root <- c()
i.mrate <- c()

eps <- .Machine$double.eps
for (r2 in 0:18) {
  R <- r2 / 2 # rate per year
  Rvec <- c(Rvec, R)
  i.formula <- c(i.formula, 100 * ((1 + R / 200)^(1 / 6) - 1))
  i.root <- c(i.root, uniroot(A, c(0, 20), Rval = R)$root) # default or
  # i.root<-c(i.root, uniroot(A,c(0,20),tol=eps,Rval=R)$root) # with tol
  i.mrate <- c(i.mrate, mrate(R))
}
tabR <- data.frame(Rvec, i.mrate, (i.formula - i.mrate), (i.root - i.mrate))
colnames(tabR) <- c("rate", "i.mrate", "form - mrate", "root - mrate")
print(tabR)
```

## 4.4 Approaches to solving 1D root-finding problems

```{r}
## ----label=C04mytanchunk1, echo=TRUE, size="scriptsize", cache=TRUE------
mytan <- function(xdeg) { # tangent in degrees
  xrad <- xdeg * pi / 180.0 # conversion to radians
  tt <- tan(xrad)
}
gmytan <- function(xdeg) { # tangent in degrees
  xrad <- xdeg * pi / 180.0 # conversion to radians
  gg <- pi / (180 * cos(xrad)^2)
}
```

```{r}
curve(mytan, from = -360, to = 360, n = 501)
curve(gmytan, from = -360, to = 360, n = 501)
```

```{r}
## ----label=C04mytanroot1
# install.packages("rootoned", repos = "http://R-Forge.R-project.org")
library(rootoned)
```

```{r}
tint <- c(80, 100)
ru <- uniroot(mytan, tint)
ru
```

```{r}
rz <- zeroin(mytan, tint)
rz
```

```{r}
rr <- root1d(mytan, tint)
rr
```

```{r}
rn80 <- newt1d(mytan, gmytan, 80)
rn80
```

```{r}
rn100 <- newt1d(mytan, gmytan, 100)
rn100
```
