---
title: "Chapter 21"
output: html_notebook
---

# 21 Miscellaneous nonlinear estimation tools for R

## 21.1 Maximum likelihood

```{r}
## ----label=C21mle, echo=TRUE---------------------------------------------
require(stats4, quietly = TRUE)
lhobbs.res <- function(xl, y) { # log scaled Hobbs weeds problem -- residual
  # base parameters on log(x)
  x <- exp(xl)
  if (abs(12 * x[3]) > 50) { # check computability
    rbad <- rep(.Machine$double.xmax, length(x))
    return(rbad)
  }
  if (length(x) != 3) stop("hobbs.res -- parameter vector n!=3")
  t <- 1:length(y)
  res <- x[1] / (1 + x[2] * exp(-x[3] * t)) - y
}
lhobbs.lik <- function(Asym, b2, b3, lsig) { # likelihood function including sigma
  y <- c(5.308, 7.24, 9.638, 12.866, 17.069, 23.192, 31.443)
  y <- c(y, 38.558, 50.156, 62.948, 75.995, 91.972)
  xl <- c(Asym, b2, b3)
  logSigma <- lsig
  sigma2 <- exp(2.0 * logSigma)
  res <- lhobbs.res(xl, y)
  nll <- 0.5 * (length(res) * log(2 * pi * sigma2) + sum(res * res) / sigma2)
}
mystart <- list(Asym = 1, b2 = 1, b3 = 1, lsig = 1) # must be a list
amlef <- mle(lhobbs.lik, start = mystart, fixed = list(lsig = log(0.4)))
amlef
amlef@min # minimal neg log likelihood
```

```{r}
amle <- mle(lhobbs.lik, start = as.list(coef(amlef)))
amle
```

```{r}
val <- do.call(lhobbs.lik, args = as.list(coef(amle)))
val
```

```{r}
# Note: This does not work
testval <- try(print(lhobbs.lik(as.list(coef(amle)))))
# But this displays the minimum of the negative log likelihood
amle@min
```

```{r}
require(bbmle, quietly = TRUE)
lhobbs2.lik <- function(Asym, b2, b3, lsig, y) { # likelihood function including sigma
  xl <- c(Asym, b2, b3)
  logSigma <- lsig
  sigma2 <- exp(2.0 * logSigma)
  res <- lhobbs.res(xl, y)
  nll <- 0.5 * (length(res) * log(2 * pi * sigma2) + sum(res * res) / sigma2)
}
y0 <- c(5.308, 7.24, 9.638, 12.866, 17.069, 23.192, 31.443)
y0 <- c(y0, 38.558, 50.156, 62.948, 75.995, 91.972)
mystart <- list(Asym = 1, b2 = 1, b3 = 1, lsig = 1) # must be a list
flist <- list(lsig = log(0.4))
amle2f <- mle2(lhobbs2.lik, start = mystart, data = list(y = y0), fixed = flist)
amle2f
```

```{r}
amle2 <- mle2(lhobbs2.lik, start = as.list(coef(amlef)), data = list(y = y0))
amle2
```

```{r}
amle@details$value
```

```{r}
suppressMessages(require(maxLik))
llh <- function(xaug, y) {
  Asym <- xaug[1]
  b2 <- xaug[2]
  b3 <- xaug[3]
  lsig <- xaug[4]
  val <- (-1) * lhobbs2.lik(Asym, b2, b3, lsig, y)
}
aml <- maxLik(llh, start = c(1, 1, 1, 1), y = y0)
aml
```

## 21.2 Generalized nonlinear models

```{r}
## ----C21gnmhobbsb, echo=TRUE---------------------------------------------
require(gnm, quietly = TRUE)
y0 <- c(5.308, 7.24, 9.638, 12.866, 17.069, 23.192, 31.443)
y0 <- c(y0, 38.558, 50.156, 62.948, 75.995, 91.972)
t0 <- 1:12
Hdta <- data.frame(y = y0, x = t0)
formula <- y ~ -1 + Mult(1, Inv(Const(1) + Exp(Mult(1 + offset(-x), Inv(1)))))
st <- c(Asym = 200, xmid = 10, scal = 3)
ans <- gnm(formula, start = st, data = Hdta)
ans
```

```{r}
require(nlmrt, quietly = TRUE)
anls <- nlxb(y ~ Asym / (1 + exp((xmid - x) / scal)), start = st, data = Hdta)
anls
```

## 21.4 Additional nonlinear least squares tools

```{r}
## ----C21tgrofit, echo=TRUE-----------------------------------------------
## tgrofit.R -- Use Hobbs problem to test grofit
#     y<-c(5.308, 7.24, 9.638, 12.866, 17.069, 23.192, 31.443)
#     y<-c(y, 38.558, 50.156, 62.948, 75.995, 91.972)
#     tt<-1:12
# require(grofit, quietly=TRUE)
# ah <- gcFitModel(time=tt, data=y)
# print(summary(ah))
# ah$model
# summary(ah$nls)
# ah$nls
```

## 21.5 Nonnegative least squares

```{r}
## ----C21nnlsa, echo=TRUE-------------------------------------------------
Sig1 <- c(0, 0, 1, 2, 3, 4, 3, 2, 1, 0, 0, 2, 4, 8, 16, 8, 5, 1, 0)
Sig2 <- c(2, 3, 4, 2, 1, 1, 3, 5, 7, 1, 0, 0, 0, 0, 0, 0, 5, 0, 0)
Sig3 <- c(0, 0, 0, 0, 0, 4, 4, 4, 1, 0, 0, 1, 14, 18, 16, 18, 15, 1, 10)

C <- cbind(Sig1, Sig2, Sig3)

bb <- C %*% as.matrix(c(0.23, 0.4, 0.1))

scale <- 0.15
require(setRNG)
setRNG(kind = "Wichmann-Hill", seed = c(979, 1479, 1542), normal.kind = "Box-Muller")
d <- bb + scale * rnorm(19)
```

```{r}
## ----C21nnlsb, echo=TRUE-------------------------------------------------
require(nnls, quietly = TRUE)
aCd <- nnls(C, d)
aCd
```

```{r}
## ----C21nnlsc, echo=TRUE-------------------------------------------------
############# another example ############
resfn <- function(x, matvec, A) {
  x <- as.matrix(x)
  res <- (A %*% x) - matvec
}

jacfn <- function(x, matvec = NULL, A) {
  A
}

ssfun <- function(x, matvec, A) {
  rr <- resfn(x, matvec, A)
  val <- sum(rr^2)
}
ggfun <- function(x, matvec, A) {
  rr <- resfn(x, matvec, A)
  JJ <- jacfn(x, matvec, A)
  gg <- 2 * as.numeric(t(JJ) %*% rr)
}


## ----label=C21nnlsc2, echo=TRUE, eval=FALSE------------------------------
## # Check functions:
xx <- rep(1, 3)
# resfn
print(resfn(xx, d, C))
# jacfn
print(jacfn(xx, d, C))
# ssfun
print(ssfun(xx, d, C))
# ggfun:
print(ggfun(xx, d, C))
```

```{r}
## ----C21nnlsd, echo=TRUE-------------------------------------------------
require(nlmrt, quietly = TRUE)
strt <- c(p1 = 0, p2 = 0, p3 = 0)
aCdnlfb <- nlfb(strt, resfn, jacfn, lower = 0, matvec = d, A = C)
aCdnlfb
```

```{r}
## ----C21nnlse, echo=TRUE-------------------------------------------------
require(optimx, quietly = TRUE)
strt <- c(p1 = 0, p2 = 0, p3 = 0)
strt2 <- c(p1 = 0.1, p2 = 0.1, p3 = 0.1)
lo <- c(0, 0, 0)
aop <- optimx(strt, ssfun, ggfun, method = "all", lower = lo, matvec = d, A = C)
summary(aop, order = value)
aop2 <- optimx(strt2, ssfun, ggfun, method = "all", lower = lo, matvec = d, A = C)
summary(aop2, order = value)
```

```{r}
## ----C21nnlse2, echo=TRUE, eval=FALSE------------------------------------
## ## No gradient function is needed -- example not run
## ## aopn<-optimx(strt, ssfun, method="all", control=list(trace=0),
## ##       lower=c(0,0,0), matvec=d, A=C)
## ## summary(aopn, order=value)
## ## aop2n<-optimx(strt1, ssfun, method="all", lower=lo, matvec=d, A=C)
## ## summary(aop2n, order=value)
```
