---
title: "Chapter 2"
output: html_notebook
---

# 2 Optimization algorithms -- an overview

## 2.1 Methods that use the gradient

```{r}
sq.f <- function(x) {
  nn <- length(x)
  yy <- 1:nn
  f <- sum((yy - x)^2)
  cat("Fv=", f, " at ")
  print(x)
  f
}

sq.g <- function(x) {
  nn <- length(x)
  yy <- 1:nn
  gg <- 2 * (x - yy)
}
```

```{r}
x <- c(0.1, 0.8)
sq.f(x)
```

```{r}
print(sq.g(x))  # print를 하지 않으면 gg 값이 출력되지 않음
```

```{r}
source("resources/C02steepdesc.r")
x <- c(0.1, 0.8)
asqsd <- stdesc(x, sq.f, sq.g, control = list(trace = 1))
```

```{r}
print(asqsd)
```

```{r}
# ls() 1 to (n-1) variant of generalized rosenbrock function
grose.f <- function(x, gs = 100) {
  n <- length(x)
  1 + sum(gs * (x[1:(n - 1)] - x[2:n]^2)^2 + (x[1:(n - 1)] - 1)^2)
}
grose.g <- function(x, gs = 100) {
  # gradient of 1 to (n-1) variant of generalized rosenbrock function # vectorized by JN 090409
  n <- length(x)
  gg <- as.vector(rep(0, n))
  tn <- 2:n
  tn1 <- tn - 1
  z1 <- x[tn1] - x[tn]^2
  z2 <- x[tn1] - 1
  gg[tn1] <- 2 * (z2 + gs * z1)
  gg[tn] <- gg[tn] - 4 * gs * z1 * x[tn]
  gg
}
```

```{r}
x <- c(0.1, 0.8)
arksd <- stdesc(x, grose.f, grose.g, control = list(trace = 0))
print(arksd)
```

## 2.2 Newton-like methods

```{r}
## Figure 2.1
F <- function(x) exp(-.05 * x) * (x - 4)^2
curve(F, from = 0, to = 5)
```

```{r}
newt <- function(x) {
  x1 <- exp(-0.05 * x) * (2 * (x - 4)) - exp(-0.05 * x) * 0.05 * (x - 4)^2
  x2 <- (exp(-0.05 * x) * 2 - exp(-0.05 * x) * 0.05 * (2 * (x - 4)) -
    (exp(-0.05 * x) * 0.05 * (2 * (x - 4)) - exp(-0.05 * x) *
      0.05 * 0.05 * (x - 4)^2))
  xnew <- x - x1 / x2
}

x <- -9
xold <- -10
while (xold != x) {
  xold <- x
  cat("f(", x, ")=", F(x), "\n")
  x <- newt(xold)
}
```

```{r}
newt2 <- function(x) {
  x1 <- exp(-0.05 * x) * (-8.8 + 2.4 * x - 0.05 * x^2) # f'(x) from mathematica
  x2 <- exp(-0.05 * x) * (2.84 - 0.22 * x + 0.0025 * x^2) # f''(x) from mathematica
  xnew <- x - x1 / x2
}

x <- -9
xold <- -10
while (xold != x) {
  xold <- x
  cat("f(", x, ")=", F(x), "\n")
  x <- newt2(xold)
}
```
