---
title: "Chapter 5"
output: html_notebook
---

# 5 One-parameter minimization problems

## 5.1 The optimize() function

```{r}
ljfn <- function(r, ep = 0.6501696, sig = 0.3165555) {
  fn <- 4 * ep * ((sig / r)^12 - (sig / r)^6)
}
min <- optimize(ljfn, interval = c(0.001, 5))
print(min)
```

```{r}
curve(ljfn, from = 0.3, to = 1)
points(min$minimum, min$objective, pch = 19)
title(main = "Lennard Jones minimum")
title(sub = "Minimum found is marked with a dot")
```

## 5.2 Using a root-finder

```{r}
## ----label=C05lj2, echo=TRUE, cache=TRUE---------------------------------
ljgr <- function(r, ep = 0.6501696, sig = 0.3165555) {
  expr1 <- 4 * ep
  expr2 <- sig / r
  expr8 <- sig / r^2
  value <- expr1 * (expr2^12 - expr2^6)
  grad <- -(expr1 * (12 * (expr8 * expr2^(11)) - 6 * (expr8 * expr2^5)))
}
root <- uniroot(ljgr, interval = c(0.001, 5))
cat("f(", root$root, ")=", root$f.root, " after ", root$iter, " Est. Prec'n=", root$estim.prec, "\n")
```

## 5.3 But where is the minimum?

```{r}
## ----label=C05findwobl1a, echo=TRUE, cache=FALSE, fig.height=5-----------
woblramp <- function(x) {
  (-3 + 0.1 * x) * cos(x * 2)
}
require(pracma, quietly=TRUE)
wmins <- pracma::findmins(woblramp, a = -10, b = 10)
curve(woblramp, from = -10, to = 10, n = 1001)
ymins <- woblramp(wmins) # compute the function at minima
points(wmins, ymins, col = "red") # and overprint on graph
title(main = "WOBLRAMP function with minima graphed")
```


```{r}
detach(package:pracma) 

require(numDeriv)
## Loading required package: numDeriv
require(pracma)
```

## 5.4 Ideas for 1D minimizers

```{r}
# Protected log function
mlp <- function(x) {
  if (x < 1e-9) {
    fval <- 0.1 * .Machine$double.xmax
  } else {
    fval <- (log(x) * (x * x - 3000))
  }
}
mlp <- Vectorize(mlp)
curve(mlp, from = 0, to = 100, n = 100001)
```

```{r}
ml <- function(x) {
  fval <- (log(x) * (x * x - 3000))
}
curve(ml, from = 0, to = 100, n = 100001)
```

```{r}
min <- optimize(mlp, interval = c(-5, 5))
print(min)
```


```{r}
minx <- optimize(ml, interval = c(-5, 5))
print(minx)
```

```{r}
## But we missed the solution!
min2 <- optimize(mlp, interval = c(-5, 55))
print(min2)
```

















