---
title: "Chapter 3"
output: html_notebook
---

# 3 Software structure and interfaces

## 3.5 Communicating exogenous data to problem definition functions

```{r}
xx <- 1:12
yy <- exp(-0.1 * sin(0.3 * xx))
plot(xx, yy)
```

```{r}
strt1 <- list(p1 = 0, p2 = 1)
require(minpack.lm, quietly = TRUE)
## here we do not specify any exogenous data
anls1 <- nlsLM(yy ~ exp(p1 * sin(p2 * xx)), start = strt1, trace = TRUE)
anls1
```

```{r}
rss <- function(par) {
  p1 <- par[1]
  p2 <- par[2]
  res <- exp(p1 * sin(p2 * xx)) - yy
  sum(res * res)
}
## check the initial sum of squares
print(rss(c(-0.1, 0.3)))
```

```{r}
print(rss(coef(anls1)))
```

```{r}
anm <- optim(strt1, rss)
anm
```

```{r}
## But (at time of writing) nlmrt requires explicit data
mydat <- data.frame(xx = xx, yy = yy)
library(nlmrt, quietly = TRUE)
anlxb1 <- nlxb(yy ~ exp(p1 * sin(p2 * xx)),
  start = strt1,
  trace = FALSE, data = mydat
)
print(anlxb1)
```

```{r}
## Insert following into call to get a more aggressive search
##   control=list(roffset=FALSE, smallsstest=FALSE)
anlxb2 <- nlxb(yy ~ exp(p1 * sin(p2 * xx)),
  start = strt1,
  trace = FALSE, data = mydat,
  control = list(roffset = FALSE, smallsstest = FALSE)
)
print(anlxb2)
```

### 3.5.1 Use of "global" data and variables

```{r}
## ----label=C03globenv1, echo=TRUE, eval=TRUE-----------------------------
mystart <- function() {
  # JN: Define globals here.
  gtn <- list(x = 0, y = 1, vec = rep(0, 9))
  envjn <<- list2env(gtn)
}

y <- 4

myrun <- function() {
  cat("y:", y, "  envjn$y: ")
  print(envjn$y)
  envjn$y <- 9876
  return(0)
}

mystart()
myrun()
cat("envjn$y:", envjn$y, "\n")
```

## 3.8 Providing derivatives for functions

```{r}
eps <- sqrt(.Machine$double.eps)
eps
```

```{r}
## ----label=C03gr1, echo=TRUE---------------------------------------------
gr <- function(par, ...) {
  fbase <- myfn(par, ...) # ensure we have right value, may not be necessary
  df <- rep(NA, length(par))
  teps <- eps * (abs(par) + eps)
  for (i in 1:length(par)) {
    dx <- par
    dx[i] <- dx[i] + teps[i] # Dangerous step if a constraint is in the way!
    tdf <- (myfn(dx, ...) - fbase) / teps[i]
    if (!is.finite(tdf) || is.nan(tdf)) tdf <- 0 # Is this a good choice?
    df[i] <- tdf
  }
  df
}
```
