---
title: "note05"
output: html_notebook
---

# 5 시계열 회귀 모델

## 5.1 선형 모델

```{r}
library(fpp2)
library(ggplot2)
theme_set(theme_grey(base_family = "NanumGothic"))
```

```{r}
autoplot(uschange[, c("Consumption", "Income")]) +
  ylab("% 변화") + xlab("연도") +
  guides(colour = guide_legend(title = " "))
```

```{r}
uschange |>
  as.data.frame() |>
  ggplot(aes(Income, Consumption)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  ylab("소비 (분기별 % 변화)") +
  xlab("소득 (분기별 % 변화)")
```

```{r}
tslm(Consumption ~ Income, data = uschange)
```

```{r}
uschange |>
  autoplot(facets = TRUE)
```

```{r}
uschange |>
  as.data.frame() |>
  GGally::ggpairs()
```

## 5.2 최소 제곱 추정

```{r}
fit.consMR <-
  uschange |>
  tslm(Consumption ~ Income + Production + Unemployment + Savings, data = _)
summary(fit.consMR)
```

```{r}
autoplot(uschange[, "Consumption"], series = "Data") +
  autolayer(fitted(fit.consMR), series = "Fitted") +
  xlab("연도") + ylab("") +
  ggtitle("미국 소비 지출의 백분율 변화") +
  guides(colour = guide_legend(title = " "))
```

```{r}
cbind(
  Data = uschange[, "Consumption"],
  Fitted = fitted(fit.consMR)
) |>
  as.data.frame() |>
  ggplot(aes(Data, Fitted)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1) +
  ylab("적합값 (예측된 값)") +
  xlab("데이터 (예측된 값)") +
  ggtitle("미국 소비 지출의 백분율 변화")
```

## 5.3 회귀 모델 평가

```{r}
checkresiduals(fit.consMR)
```

```{r}
df <- as.data.frame(uschange)
df[, "Residuals"] <- as.numeric(residuals(fit.consMR))
p1 <- ggplot(df, aes(Income, Residuals)) +
  geom_point()
p2 <- ggplot(df, aes(Production, Residuals)) +
  geom_point()
p3 <- ggplot(df, aes(Savings, Residuals)) +
  geom_point()
p4 <- ggplot(df, aes(Unemployment, Residuals)) +
  geom_point()
gridExtra::grid.arrange(p1, p2, p3, p4, nrow = 2)
```

```{r}
cbind(
  Fitted = fitted(fit.consMR),
  Residuals = residuals(fit.consMR)
) |>
  as.data.frame() |>
  ggplot(aes(Fitted, Residuals)) +
  geom_point()
```

```{r}
aussies <- ausair |> window(end = 2011)
fit <- tslm(aussies ~ guinearice)
summary(fit)
```

```{r}
checkresiduals(fit)
```

## 5.4 몇 가지 유용한 예측변수

```{r}
beer2 <- ausbeer |> window(start = 1992)
autoplot(beer2) +
  xlab("연도") + ylab("백만 리터")
```

```{r}
fit.beer <- tslm(beer2 ~ trend + season)
summary(fit.beer)
```

```{r}
autoplot(beer2, series = "데이터") +
  autolayer(fitted(fit.beer), series = "적합값") +
  xlab("연도") + ylab("백만 리터") +
  guides(colour = guide_legend(title = " ")) +
  ggtitle("분기별 맥주 생산량")
```

```{r}
cycle(beer2)
```

```{r}
beer2 |>
  cbind(Data = _, Fitted = fitted(fit.beer)) |>
  as.data.frame() |>
  ggplot(aes(Data, Fitted, color = as.factor(cycle(beer2)))) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1) +
  scale_color_brewer(palette = "Dark2", name = "분기") +
  xlab("측정값") +
  ylab("적합값") +
  ggtitle("분기별 맥주 생산량")
```

```{r}
fourier.beer <- tslm(beer2 ~ trend + fourier(beer2, K = 2))
summary(fourier.beer)
```

```{r}
fourier.beer <- tslm(beer2 ~ trend + season)
summary(fourier.beer)
```

## 5.5 예측변수 선택

```{r}
# uschange
rbind(
  CV(tslm(Consumption ~ Income + Production + Savings + Unemployment, data = uschange)),
  CV(tslm(Consumption ~ Income + Savings + Unemployment, data = uschange)),
  CV(tslm(Consumption ~ Income + Production + Savings, data = uschange)),
  CV(tslm(Consumption ~ Income + Savings, data = uschange))
) |>
  round(digits = 3)
```

## 5.6 회귀로 예측하기

```{r}
beer2 <- ausbeer |> window(start = 1992)
fit.beer <- tslm(beer2 ~ trend + season)
fcast <- forecast(fit.beer)
autoplot(fcast) +
  ggtitle("회귀를 이용한 맥주 생산량 예측값") +
  xlab("연도") + ylab("백만 리터")
```

```{r}
fit.consBest <- tslm(Consumption ~ Income + Savings + Unemployment,
  data = uschange
)
fit.consBest
```

```{r}
h <- 4
newdata <- data.frame(
  Income = c(1, 1, 1, 1),
  Savings = c(0.5, 0.5, 0.5, 0.5),
  Unemployment = c(0, 0, 0, 0)
)
fcast.up <- forecast(fit.consBest, newdata = newdata)
newdata <- data.frame(
  Income = rep(-1, h),
  Savings = rep(-0.5, h),
  Unemployment = rep(0, h)
)
fcast.down <- forecast(fit.consBest, newdata = newdata)
```

```{r}
autoplot(uschange[, 1]) +
  autolayer(fcast.up, PI = TRUE, series = "Up") +
  autolayer(fcast.down, PI = TRUE, series = "Down") +
  xlab("Year") +
  ylab("미국 소비 지출 % 변화")
```

```{r}
fit.cons <- tslm(Consumption ~ Income, data = uschange)
h <- 4
fcast.ave <- forecast(fit.cons,
  newdata = data.frame(
    Income = rep(mean(uschange[, "Income"]), h)
  )
)

fcast.up <- forecast(fit.cons,
  newdata = data.frame(
    Income = rep(5, h)
  )
)
autoplot(uschange[, "Consumption"]) +
  autolayer(fcast.ave, series = "평균적인 증가") +
  autolayer(fcast.up, series = "극단적인 증가") +
  guides(color = guide_legend(title = "시나리오")) +
  xlab("연도") +
  ylab("미국 소비 % 변화")
```

## 5.7 행렬 정식화

## 5.8 비선형 회귀

```{r}
h <- 10

fit.lin <- tslm(marathon ~ trend)
fcasts.lin <- forecast(fit.lin, h = h)
fcasts.lin
```

```{r}
fit.exp <- tslm(marathon ~ trend, lambda = 0)
fcasts.exp <- forecast(fit.exp, h = h)
```

```{r}
t <- time(marathon)
t.break1 <- 1940
t.break2 <- 1980

tb1 <- ts(pmax(0, t - t.break1), start = 1897)
tb2 <- ts(pmax(0, t - t.break2), start = 1897)

fit.pw <- tslm(marathon ~ t + tb1 + tb2)

t.new <- t[length(t)] + seq(h)
tb1.new <- tb1[length(tb1)] + seq(h)
tb2.new <- tb2[length(tb2)] + seq(h)

newdata <- data.frame(
  t = t.new,
  tb1 = tb1.new,
  tb2 = tb2.new
)
fcasts.pw <- forecast(fit.pw, newdata = newdata)
```

```{r}
fit.spline <- tslm(marathon ~ t + I(t^2) + I(t^3) + I(tb1^3) + I(tb2^3))
fcasts.spl <- forecast(fit.spline, newdata = newdata)
```

```{r}
autoplot(marathon) +
  autolayer(fitted(fit.lin), series = "Linear") +
  autolayer(fitted(fit.exp), series = "Exponential") +
  autolayer(fitted(fit.pw), series = "Piece-wise") +
  autolayer(fitted(fit.spline), series = "Spline") +
  autolayer(fcasts.pw, series = "Piece-wise") +
  autolayer(fcasts.lin, series = "Linear", PI = FALSE) +
  autolayer(fcasts.exp, series = "Exponential", PI = FALSE) +
  autolayer(fcasts.spl, series = "Spline", PI = FALSE) +
  xlab("Year") +
  ylab("우승 기록 (분)") +
  guides(color = guide_legend(title = " "))
```

```{r}
marathon |>
  splinef(lambda = 0) |>
  autoplot() +
  xlab("연도")
```

```{r}
marathon %>%
  splinef(lambda = 0) %>%
  checkresiduals()
```

## 5.9 상관관계, 인과관계, 그리고 예측

## 5.10 연습문제
