---
title: "note07"
output: html_notebook
---

```{r}
library(fpp2)
library(ggplot2)
theme_set(theme_gray(base_family = "NanumGothic"))
```

# 7 지수평활

## 7.1 단순 지수평활

```{r}
oildata <- oil |> window(start = 1996)
autoplot(oildata) +
  ylab("원유 (백만 톤)") + xlab("연도")
```

```{r}
fc <- ses(oildata, h = 5)
round(accuracy(fc), 2)
```

```{r}
autoplot(fc) +
  autolayer(fitted(fc), series = "Fitted") +
  ylab("원유 (백만 톤)") + xlab("연도") +
  ggtitle("단순 지수평활로 얻은 예측값")
```

```{r}
cbind(oildata, fitted(fc))
```

## 7.2 추세 기법

```{r}
air <- window(ausair, start = 1990)
fc <- holt(air, h = 5)
```

```{r}
autoplot(fc, series = "Data") +
  autolayer(fitted(fc), series = "Fitted")
```

```{r}
fc <- holt(air, h = 15)
fc2 <- holt(air, damped = TRUE, phi = 0.90, h = 15)
autoplot(air) +
  autolayer(fc, series = "홀트 기법", PI = FALSE) +
  autolayer(fc2, series = "감쇠 홀트 기법", PI = FALSE) +
  ggtitle("홀트 기법으로 얻은 예측값") + xlab("연도") +
  ylab("호주 항공객 (백만 명)") +
  guides(colour = guide_legend(title = "예측값"))
```

```{r}
livestock |>
  autoplot()
```

```{r}
e1 <- tsCV(livestock, ses, h = 1)
e2 <- tsCV(livestock, holt, h = 1)
e3 <- tsCV(livestock, holt, damped = TRUE, h = 1)
```

```{r}
mean(e1^2, na.rm = TRUE)
mean(e2^2, na.rm = TRUE)
mean(e3^2, na.rm = TRUE)
```

```{r}
mean(abs(e1), na.rm = TRUE)
mean(abs(e2), na.rm = TRUE)
mean(abs(e3), na.rm = TRUE)
```

```{r}
fc <- holt(livestock, damped = TRUE)
fc$model
```

```{r}
autoplot(fc) +
  xlab("연도") + ylab("아시아의 양 목축 (단위: 백만)") +
  ggtitle("감쇠 홀트 기법으로 얻은 예측값")
```

## 7.3 홀트-윈터스의 계절성 기법

```{r}
aust <- window(austourists, start = 2005)
fit1 <- hw(aust, seasonal = "additive")
fit2 <- hw(aust, seasonal = "multiplicative")
autoplot(aust) +
  autolayer(fit1, series = "HW 덧셈 예측", PI = FALSE) +
  autolayer(fit2, series = "HW 곱셈 예측", PI = FALSE) +
  xlab("연도") +
  ylab("호주 국제선 여행객 숙박일 (단일: 백만)") +
  guides(color = guide_legend(title = "예측"))
```

```{r}
data <- subset(hyndsight, end = length(hyndsight) - 35)
fc <- hw(data, damped = TRUE, seasonal = "multiplicative", h = 35)
autoplot(hyndsight) +
  autolayer(fc, series = "HW 곱셈 감쇠", PI = FALSE) +
  guides(color = guide_legend(title = "일별 예측값"))
```

## 7.4 지수 평활 기법 분류 체계

## 7.5 지수 평활에 대한 혁신 상태 공간 모델

## 7.6 추정과 모델 선택

```{r}
aust <- austourists |> window(start = 2005)
fit <- ets(aust)
summary(fit)
```

```{r}
autoplot(fit) +
  ggtitle("ETS(M,A,M) 기법의 성분")
```

```{r}
cbind(
  "잔차" = residuals(fit),
  "예측오차" = residuals(fit, type = "response")
) |>
  autoplot(facet = TRUE) +
  xlab("Year") +
  ylab("")
```

## 7.7 ETS 모델로 예측하기

```{r}
fit |>
  forecast(h = 8) |>
  autoplot() +
  ylab("호주 국제선 여행객 숙박일 수 (단위: 백만)") +
  ggtitle("ETS(M, A, M)으로 얻은 예측값")
```

## 7.8 연습문제
