---
title: "Chapter 1"
output: html_notebook
---

# 1 Introduction

```{r}
library("microbenchmark")
library("profvis")
library("ggplot2")
```

## 1.6 벤치마킹 및 프로파일링

### 1.6.2 벤치마킹 예시

```{r}
library("microbenchmark")
df <- data.frame(v = 1:4, name = letters[1:4])
microbenchmark(df[3, 2], df[3, "name"], df$name[3])
```

```{r}
library("profvis")
profvis(expr = {
  library("ggplot2")
  out <- readRDS("extdata/out-ice.Rds")
  df <- dplyr::bind_rows(out, .id = "Year")
  ggplot(df, aes(long, lat, group = paste(group, Year))) +
    geom_path(aes(color = Year))
  ggsave("figures/icesheet-test.png")
}, interval = 0.01, prof_out = "temp/ice-prof")
```

#### 1.6.3.1 연습

```{r}
cs_for <- function(x) {
  for (i in x) {
    if (i == 1) {
      xc = x[i]
    } else {
      xc = c(xc, sum(x[1:i]))
    }
  }
  xc
}

cs_apply = function(x) {
  sapply(x, function(x) sum(1:x))
}
x <- 1:50000
microbenchmark(cs_for(x), cs_apply(x), cumsum(x), times = 1, units = "s")
```

```{r}
n <- 500000
df = data.frame(v = 1:4, name = letters[1:4])
# Test how long it takes to subset the data frame 50,000 times:
system.time(
  for(i in 1:n){
    df[3, 2]
  }
)
system.time(
  for(i in 1:n){
    df[3, "name"]
  }
)

system.time(
  for(i in 1:n){
    df$name[3]
  }
)
```

```{r}
profvis({
  n <- 100000
  df = data.frame(v = 1:4, name = letters[1:4])
  # Test how long it takes to subset the data frame 50,000 times:
  system.time(
    for(i in 1:n){
      df[3, 2]
    }
  )
  system.time(
    for(i in 1:n){
      df[3, "name"]
    }
  )
  
  system.time(
    for(i in 1:n){
      df$name[3]
    }
  )
})
```
