---
title: "note14"
output: html_notebook
---

# 14 Fitting Linear Mixed-Effects Models: The lme() Function

## 14.2 Representation of a Positive-Definite Matrix: The pdMat Class

```{r}
library(nlme)
```

```{r}
pdCSO <- pdCompSymm(~agex)
isInitialized(pdCSO)
```

```{r}
mtxUN <- matrix(c(4, 1, 1, 9), nrow = 2)
mtxUN
```

```{r}
dt1 <- data.frame(agex = c(15, 45, 71, 82))
pdSm <- pdSymm(mtxUN, ~agex, data = dt1)
pdSm
```

```{r}
isInitialized(pdSm)
```

```{r}
mtxCS <- matrix(4 * diag(3) + 1, nrow = 3)
mtxCS
```

```{r}
dt2 <- data.frame(agef = c("Y", "M", "O", "O"))
pdCSf <- pdCompSymm(mtxCS, ~ -1 + agef, data = dt2)
pdCSf
```

```{r}
summary(pdSm)
```

```{r}
formula(pdSm)
```

```{r}
Names(pdSm)
```

```{r}
Dmtx <- as.matrix(pdSm)
Dmtx
```

```{r}
Dim(pdSm)
```

```{r}
logDet(pdSm)
```

```{r}
VarCorr(pdSm)
```

```{r}
corMatrix(pdSm)
```

```{r}
Names(pdCSf)
```

```{r}
as.matrix(pdCSf)
```

```{r}
coef(pdSm, unconstrained = FALSE)
```

```{r}
coef(pdSm)
```

```{r}
coef(pdCSf, unconstrained = FALSE)
```

```{r}
coef(pdCSf)
```

```{r}
log(5) / 2
```

```{r}
rho <- 0.2
nc <- 3
aux <- (rho + 1 / (nc - 1)) / (1 - rho)
log(aux)
```

```{r}
pdSm0 <- pdSymm(mtxUN)
coef(pdSm0)
```

```{r}
Dmtx <- pdMatrix(pdSm0)
CholD <- chol(Dmtx)
vd <- svd(CholD, nu = 0)
vd$v %*% (log(vd$d) * t(vd$v))
```

```{r}
pdLCh <- pdLogChol(mtxUN)
coef(pdLCh)
```

```{r}
LChD <- CholD
diag(LChD) <- log(diag(LChD))
LChD
```

```{r}
pdNat <- pdNatural(mtxUN)
coef(pdNat)
```

```{r}
log(sqrt(diag(Dmtx)))
```

```{r}
corD <- cov2cor(Dmtx)
rho <- corD[upper.tri(corD)]
log((1 + rho) / (1 - rho))
```

## 14.3 Random-Effects Structure Representation: The reStruct class

```{r}
reSt <- reStruct(list(g1 = pdSm, g2 = pdCSf))
reSt
```

```{r}
isInitialized(reSt)
```

```{r}
names(reSt)
```

```{r}
formula(reSt)
```

```{r}
getGroupsFormula(reSt)
```

```{r}
Names(reSt)
```

```{r}
as.matrix(reSt)
```

```{r}
coef(reSt)
```

```{r}
reSt[["g1"]]
```

```{r}
g2.pdMat <- reSt[["g2"]]
all.equal(pdCSf, g2.pdMat)
```

```{r}
Zmtx1 <- model.matrix(formula(pdSm), dt1)
Zmtx1
```

```{r}
Zmtx2 <- model.matrix(formula(pdCSf), dt2)
Zmtx2
```

```{r}
prmatrix(Zmtx2)
```

```{r}
dtz <- data.frame(dt1, dt2)
dtz
```

```{r}
Zmtx <- model.matrix(reSt, dtz)
Zmtx
```

```{r}
prmatrix(Zmtx)
```

## 14.4 The Random Part of the Model Representation: The lmeStruct Class

```{r}
reSt <- reStruct(list(g1 = pdSm, g2 = pdCSf))
corSt <- corExp(c(0.3, 0.1), form = ~tx, nugget = TRUE)
vF <- varExp(0.8, form = ~agex)
lmeSt <- lmeStruct(reStruct = reSt, corStruct = corSt, varStruct = vF)
lmeSt
```

```{r}
coefs <- coef(lmeSt, unconstrained = FALSE)
as.matrix(coefs)
```
