---
title: "note15"
output: html_notebook
---

# 15 Fitting Linear Mixed-Effects Models: The lmer() Function

## 15.6 Illustration of Computations

```{r}
n1 <- 2
n2 <- 3
i <- gl(n1, n2)
j <- gl(n2, 1, n1 * n2)
b1x <- rnorm(n1, 0, 1)
b2x <- rnorm(n2, 0, 2)
dt0 <- data.frame(i, j)
dtc <- within(dt0, {
  eps <- rnorm(nrow(dt0), 0, 0.2)
  b1 <- b1x[i]
  b2 <- b2x[j]
  y <- 10 + b1 + b2 + eps
  g2 <- factor(j, labels = letters[1:n2])
  g1 <- factor(LETTERS[i])
})
dtc
```

```{r}
Zg1 <- model.matrix(~ 0 + g1, data = dtc)
Zg2 <- model.matrix(~ 0 + g2, data = dtc)
Z0 <- cbind(Zg1, Zg2)
A0 <- t(Z0)
A0c <- tcrossprod(A0)
Dg <- diag(nrow(A0))
A0q <- A0c + Dg
A0q
```

```{r}
L0 <- t(chol(A0q))
sum(L0 != 00)
```

```{r}
max(abs(L0 %*% t(L0) - A0q))
```

```{r}
pvec <- c(3, 4, 5, 1, 2)
A1 <- A0[pvec, ]
A1c <- tcrossprod(A1)
A1q <- A1c + Dg
A1q
```

```{r}
A1q. <- A0q[pvec, pvec]
identical(A1q, A1q.)
```

```{r}
L1 <- t(chol(A1q.))
sum(L1 != 0.0)
```

```{r}
library(Matrix)
A0 <- as(A0, "dgCMatrix")
A0c <- tcrossprod(A0)
L0 <- Cholesky(A0c, perm = FALSE, Imult = 1, LDL = FALSE)
nnzero(L0. <- as(L0, "sparseMatrix"))
```

```{r}
Dg <- Diagonal(nrow(A0))
A0q <- A0c + Dg
A0q
```

```{r}
max(abs(L0. %*% t(L0.) - A0q))
```

```{r}
pvec <- c(3, 4, 5, 1, 2)
P1 <- as(pvec, "pMatrix")
A1c <- P1 %*% A0c %*% t(P1)
L1 <- Cholesky(A1c, perm = FALSE, Imult = 1, LDL = FALSE)
nnzero(as(L1, "sparseMatrix"))
```

```{r}
L2 <- Cholesky(A0c, perm = TRUE, Imult = 1, LDL = FALSE)
nnzero(as(L2, "sparseMatrix"))
```

```{r}
slot(L2, "perm") + 1L
detach(package:Matrix)
```

```{r}
library(lme4)
```

```{r}
fmc <- lmer(y ~ 1 + (1 | g1) + (1 | g2), data = dtc)
summary(fmc)
```

```{r}
gf <- getME(fmc, "flist")
xtabs(~ g1 + g2, gf)
```

```{r}
Zt <- getME(fmc, "flist")
Zt
```

```{r}
# STs <- expand(fmc)
# summary(STs)
# (P <- STs$P)
# S <- STs$S
# summary(S)
# T <- STs$T
# summary(T)
```

```{r}
# TS <- T %*% S
# sig <- STs$sigma
# sig
# sig * sig * tcrossprod(TS)
```

```{r}
# A <- getME(fmc, "A")
# ZTS <- t(Zt) %*% TS
# max(abs(t(A) - ZTS))
```

```{r}
# Ac <- tcrossprod(A)
# AcI <- Ac + diag(nrow(A))
# LS <- slot(fmc, "L")
# PP <- P %*% AcI %*% t(P)
# L <- as(Ls, "sparseMatrix")
# max(abs(tcrossprod(L) - PP))
```
