---
title: "Chapter 18"
output: html_notebook
---

# 18 Tuning and terminating methods

## 18.1 Timing and profiling

```{r}
nnum <- 100000L
cat("Time to generate ", nnum, "  is ")
tt <- system.time(xx <- runif(nnum))
cat(tt[[3]], "\n")
tt
```

### 18.1.1 rbenchmark

```{r}
nnum <- 100000L
require("rbenchmark")
cat("Time to generate ", nnum, "  is ")
trb <- rbenchmark::benchmark(runif(nnum))
# print(str(trb))
print(trb)
```

### 18.1.2 microbenchmark

```{r}
nnum <- 100000L
require("microbenchmark")
cat("Time to generate ", nnum, "  is ")
tmb <- microbenchmark(xx <- runif(nnum))
print(str(tmb))
print(tmb)
```

```{r}
plot(tmb)
```

### 18.1.3 Calibrating our timings

```{r}
## ### Compute benchmark for machine in R
## ###  J C Nash 2013
busyfnloop <- function(k) {
  for (j in 1:k) {
    x <- log(exp(sin(cos(j * 1.11))))
  }
  x
}
busyfnvec <- function(k) {
  vk <- 1:k
  x <- log(exp(sin(cos(1.1 * vk))))[k]
}
# if (!file.exists("./tmpdata/timbench.dput")) {
require(microbenchmark, quietly = TRUE)
nlist <- c(1e3, 1e4, 5e4, 1e5, 2e5)
mlistl <- rep(NA, length(nlist))
slistl <- mlistl
mlistv <- mlistl
slistv <- mlistl
for (kk in 1:length(nlist)) {
  k <- nlist[kk]
  cat("number of loops =", k, "\n")
  cat("loop\n")
  tt <- microbenchmark(busyfnloop(k))
  mlistl[kk] <- mean(tt$time) * 1e-6
  slistl[kk] <- sd(tt$time) * 1e-6
  cat("vec\n")
  tt <- microbenchmark(busyfnvec(k))
  mlistv[kk] <- mean(tt$time) * 1e-6
  slistv[kk] <- sd(tt$time) * 1e-6
}
##  build table
cvl <- slistl / mlistl
cvv <- slistv / mlistv
l2v <- mlistl / mlistv
restime <- data.frame(nlist, mlistl, slistl, cvl, mlistv, slistv, cvv, l2v)
names(restime) <- c(" n", "mean loop", "sd loop", "cv loop", "mean vec", "sd vec", "cv vec", "loop/vec")
## Times were converted to milliseconds
restime
# dput(restime, file = "filenameforyourmachine.dput")
# } else {
#   ## ----label=C18timbenchx, echo=FALSE--------------------------------------
#   restime <- dget("tmpdata/timbench.dput")
# }
options(width = 100) # to get all the columns on the display
print(restime)
```

## 18.2 Profiling

```{r}
path_current <- getwd()
path_new <- paste0(path_current, "/resources")
setwd(path_new)
system("Rscript --vanilla doprof.R")
myprof <- summaryRprof("testjohn1.txt")
myprof$by.self
setwd(path_current)
```

```{r}
# rnotebook에서 작동 불가
# tryit<-profr::profr("rpcode.R")
# tryit
```

### 18.2.1 Trying possible improvements

```{r}
## testc.txt, testt.txt, testB.txt 이 세 파일이 없어서 실행불가

# ## ----label=C18upnew1, echo=TRUE------------------------------------------
# require(microbenchmark)
# # Different ways to do the BFGS update
# bfgsout<-function(B, t, y, D1, D2){
#     Bouter <- B - (outer(t, y) + outer(y, t) - D2 * outer(t, t))/D1
# }
#
# bfgsloop<-function(B, t, y, D1, D2){
#    A<-B
#    n<-dim(A)[1]
#    for (i in 1:n) {
#        for (j in 1:n) {
#            A[i,j]<-A[i,j]-(t[i]*y[j]+y[i]*t[j]-D2*t[i]*t[j])/D1
#        }
#    }
#    A
# }
#
# bfgsmult<-function(B, t, y, D1, D2){
#    A<-B
#    A<-A - (t%*%t(y) + y%*%t(t) - D2 * t%*%t(t))/D1
# }
#
# bfgsx<-function(B, t, y, D1, D2){ # fastest
#    A<-outer(t,y)
#    A<- B - (A+t(A) - D2 * outer(t,t))/D1
# }
#
# # Recover saved data
# c<-dget(file="testc.txt")
# t<-dget(file="testt.txt")
# B<-dget(file="testB.txt")
# # ychk<-dget(file="testy.txt")
# tD1sum<- microbenchmark(D1a <- sum(t * c))$time # faster?
# tD1crossprod<-microbenchmark(D1c<-as.numeric(crossprod(t, c)))$time
# #summary(tD1sum)
# #summary(tD1crossprod)
# mean(tD1crossprod-tD1sum)
# cat("abs(D1a-D1c)=",abs(D1a-D1c),"\n")
# if (D1a <=0) stop("D1 <= 0")
# tymmult<-microbenchmark(y <- as.vector(B %*% c))$time
# tycrossprod<-microbenchmark(ya<- crossprod(B, c))$time # faster
# #summary(tymmult)
# #summary(tycrossprod)
# mean(tymmult-tycrossprod)
# cat("max(abs(y-ya)):", max(abs(y-ya)),"\n")
# td2vmult<-microbenchmark(D2a <- as.double(1 + (t(c) %*% y)/D1a))$time
# td2crossprod<-microbenchmark(D2b <- as.double(1+crossprod(c,y)/D1a))$time # faster
# cat("abs(D2a-D2b)=",abs(D2a-D2b),"\n")
# #summary(td2vmult)
# #summary(td2crossprod)
# mean(td2vmult-td2crossprod)
# touter<-microbenchmark(Bouter <- bfgsout(B, t, y, D1a, D2a))$time
# tbloop<-microbenchmark(Bloop<-bfgsloop(B, t, y, D1a, D2a))$time
# tbmult<-microbenchmark(Bmult<-bfgsloop(B, t, y, D1a, D2a))$time
# tboutsave<-microbenchmark(Boutsave<-bfgsx(B, t, y, D1a, D2a))$time # faster?
# ## summary(touter)
# ## summary(tbloop)
# ## summary(tbmult)
# ## summary(tboutsave)
# dfBup<-data.frame(touter, tbloop, tbmult, tboutsave)
# colnames(dfBup)<-c("outer", "loops", "matmult", "out+save")
# boxplot(dfBup)
# title("Comparing timings for BFGS update")
# ## check computations are equivalent
# max(abs(Bloop-Bouter))
# max(abs(Bmult-Bouter))
# max(abs(Boutsave-Bouter))
```

### 18.3.2 Avoiding loops

```{r}
## ----label=C18forwhiletime, echo=TRUE, eval=FALSE------------------------
## #  forwhiletime.R
require(microbenchmark)
require(compiler)
##
tfor <- function(n) {
  for (i in 1:n) {
    xx <- exp(sin(cos(as.double(i))))
  }
  xx
}
##
twhile <- function(n) {
  i <- 0
  while (i < n) {
    i <- i + 1
    xx <- exp(sin(cos(as.double(i))))
  }
  xx
}
n <- 10000

timfor <- microbenchmark(tfor(n))
timwhile <- microbenchmark(twhile(n))
tforc <- cmpfun(tfor)
twhilec <- cmpfun(twhile)
timforc <- microbenchmark(tforc(n))
timwhilec <- microbenchmark(twhilec(n))
looptimes <- data.frame(timfor$time, timforc$time, timwhile$time, timwhilec$time)
print(colMeans(looptimes))
```

### 18.3.3 Package upgrades - an example

```{r}
## ----label=C18expmtime0, echo=TRUE---------------------------------------
require(expm)
tt <- c(
  0.77, 1.69, 2.69, 3.67, 4.69, 5.71, 7.94, 9.67, 11.77, 17.77,
  23.77, 32.77, 40.73, 47.75, 54.90, 62.81, 72.88, 98.77, 125.92, 160.19,
  191.15, 223.78, 287.70, 340.01, 340.95, 342.01
)
y <- c(
  1.396, 3.784, 5.948, 7.717, 9.077, 10.100, 11.263, 11.856, 12.251, 12.699,
  12.869, 13.048, 13.222, 13.347, 13.507, 13.628, 13.804, 14.087, 14.185, 14.351,
  14.458, 14.756, 15.262, 15.703, 15.703, 15.703
)
ones <- rep(1, length(t))

Mpred <- function(theta) { # WARNING: assumes tt global
  kvec <- exp(theta[1:3])
  k1 <- kvec[1]
  k2 <- kvec[2]
  k3 <- kvec[3]
  #   MIN problem terbuthylazene disappearance
  z <- k1 + k2 + k3
  y <- z * z - 4 * k1 * k3
  l1 <- 0.5 * (-z + sqrt(y))
  l2 <- 0.5 * (-z - sqrt(y))
  val <- 100 * (1 - ((k1 + k2 + l2) * exp(l2 * tt) - (k1 + k2 + l1) * exp(l1 * tt)) / (l2 - l1))
} # val should be a vector if t is a vector

negll <- function(theta) {
  # non expm version JN 110731
  pred <- Mpred(theta)
  sigma <- exp(theta[4])
  -sum(dnorm(y, mean = pred, sd = sigma, log = TRUE))
}

nlogL <- function(theta) {
  k <- exp(theta[1:3])
  sigma <- exp(theta[4])
  A <- rbind(
    c(-k[1], k[2]),
    c(k[1], -(k[2] + k[3]))
  )
  x0 <- c(0, 100)
  sol <- function(tt) {
    100 - sum(expm(A * tt) %*% x0)
  }
  pred <- sapply(tt, sol)
  -sum(dnorm(y, mean = pred, sd = sigma, log = TRUE))
}
mytheta <- c(-2, -2, -2, -2)
vnlogL <- nlogL(mytheta)
cat("nlogL(-2,-2,-2,-2) = ", vnlogL, "\n")
vnegll <- negll(mytheta)
cat("negll(-2,-2,-2,-2) = ", vnegll, "\n")


## ----label=C18expmtime1, echo=FALSE--------------------------------------
## system("Rscript --vanilla supportdocs/tuning/timenegll.R >tempout.txt")
# mntim<-dget(file="/home/john/nlpor/supportdocs/tuning/mntim.dput")
# mntim
```

### 18.3.4 Specializing codes

```{r}
require(microbenchmark)
require(Rvmmin)
require(Rcgmin)
sqs <- function(x) {
  sum(seq_along(x) * (x - 0.5 * seq_along(x))^2)
}
sqsg <- function(x) {
  ii <- seq_along(x)
  g <- 2. * ii * (x - 0.5 * ii)
}

xstrt <- rep(pi, 20)
lb <- rep(-100, 20)
ub <- rep(100, 20) # very loose bounds
bdmsk <- rep(1, 20) # free parameters
tvmu <- microbenchmark(avmu <- Rvmminu(xstrt, sqs, sqsg))
tcgu <- microbenchmark(acgu <- Rcgminu(xstrt, sqs, sqsg))
tvmb <- microbenchmark(avmb <- Rvmminb(xstrt, sqs, sqsg, bdmsk = bdmsk, lower = lb, upper = ub))
tcgb <- microbenchmark(acgb <- Rcgminb(xstrt, sqs, sqsg, bdmsk = bdmsk, lower = lb, upper = ub))
svmu <- summary(tvmu$time)
cnames <- names(svmu)
svmu <- as.numeric(svmu)
svmb <- as.numeric(summary(tvmb$time))
scgu <- as.numeric(summary(tcgu$time))
scgb <- as.numeric(summary(tcgb$time))
names(svmu) <- cnames
names(svmb) <- cnames
names(scgu) <- cnames
names(scgb) <- cnames
mytab <- rbind(svmu, svmb, scgu, scgb)
rownames(mytab) <- c("Rvmminu", "Rvmminb", "Rcgminu", "Rcgminb")
print(mytab)
```

### 18.4 External language compiled functions

```{r}
molermat <- function(n) {
  A <- matrix(NA, nrow = n, ncol = n)
  for (i in 1:n) {
    for (j in 1:n) {
      if (i == j) {
        A[i, i] <- i
      } else {
        A[i, j] <- min(i, j) - 2
      }
    }
  }
  A
}

rayq <- function(x, A) {
  rayquo <- as.numeric(crossprod(x, crossprod(A, x)) / crossprod(x))
}

require(microbenchmark)
require(compiler)
molermatc <- cmpfun(molermat)
rayqc <- cmpfun(rayq)
n <- 200
x <- rep(1, n)
tbuild <- microbenchmark(A <- molermat(n))$time
tbuildc <- microbenchmark(A <- molermatc(n))$time
teigen <- microbenchmark(evs <- eigen(A))$time
tr <- microbenchmark(rayq(x, A))$time
trc <- microbenchmark(rayqc(x, A))$time
eigvec <- evs$vectors[, 1] # select first eigenvector
# normalize first eigenvector
eigvec <- sign(eigvec[[1]]) * eigvec / sqrt(as.numeric(crossprod(eigvec)))
```

```{r}
require(optimx)
tcg <- system.time(amax <- optimx(x,
  fn = rayq, method = "Rcgmin",
  control = list(usenumDeriv = TRUE, kkt = FALSE), A = -A
))[[3]]
# summary(amax)
cat("maximal eigensolution: Value=", -amax$value, "  timecg= ", tcg, "\n")
tvec <- coef(amax)[1, ]
rcgvec <- sign(tvec)[[1]] * (tvec) / sqrt(as.numeric(crossprod(tvec)))
cat("Compare with eigen()\n")
cat("Difference in eigenvalues = ", (-amax$value[1] - evs$values[[1]]), "\n")
cat("Max abs vector difference = ", max(abs(eigvec - rcgvec)), "\n")
```

```{r}
axmoler <- function(x) {
  # A memory-saving version of A%*%x
  # For Moler matrix.
  n <- length(x)
  j <- 1:n
  ax <- rep(0, n)
  for (i in 1:n) {
    term <- x * (pmin(i, j) - 2)
    ax[i] <- sum(term[-i])
  }
  ax <- ax + j * x
  ax
}
require(compiler)
require(microbenchmark)
n <- 200
x <- rep(1, n)
tax <- microbenchmark(ax <- axmoler(x))$time
axmolerc <- cmpfun(axmoler)
taxc <- microbenchmark(axc <- axmolerc(x))$time
cat("time.ax, time.axc:", mean(tax), mean(taxc), "\n")
## On J6 gives time.ax, time.axc: 5591866 4925221
```

```{r}

```
