---
title: "Chapter 12"
output: html_notebook
---

# 12 Using masks

## 12.2 Specifying the objective

```{r}
## ----label=C12lhobbs.res, echo=TRUE--------------------------------------
lhobbs.res<-function(xl,y){ # log scaled Hobbs weeds problem -- residual
# base parameters on log(x)
    x<-exp(xl)
    if (abs(12*x[3]) > 50) { # check computability
       rbad<-rep(.Machine$double.xmax, length(x))
       return(rbad)
    }
    if(length(x) != 3) stop("hobbs.res -- parameter vector n!=3")
    t<-1:length(y)
    res<-x[1]/(1+x[2]*exp(-x[3]*t)) - y
}


## ----label=C12lhobbs.lik, echo=TRUE--------------------------------------
lhobbs.lik<-function(xaug,y=y0){ # likelihood function including sigma
  xl<-xaug[1:3]
  logSigma<-xaug[4]
  sigma2=exp(2.0*logSigma);
  res<-lhobbs.res(xl,y)
  nll<-0.5*(length(res)*log(2*pi*sigma2)+sum(res*res)/sigma2)
}


## ----label=C12lhobbs.jac, echo=TRUE--------------------------------------
lhobbs.jac<-function(xl, y) { # scaled Hobbs weeds problem -- Jacobian
    x<-exp(xl)
    jj<-matrix(0.0, 12, 3)
    t<-1:12
    yy<-exp(-x[3]*t)
    zz<-1/(1+x[2]*yy)
    jj[t,1] <- zz*exp(xl[1])
    jj[t,2] <- -x[1]*zz*zz*yy*exp(xl[2])
    jj[t,3] <- x[1]*zz*zz*yy*x[2]*t*exp(xl[3])
    return(jj)
}


## ----label=C12lhobbs.g, echo=TRUE----------------------------------------
lhobbs.g <- function(xl,y) { # scaled Hobbs weeds problem -- gradient
   shj<-lhobbs.jac(xl,y)
   shres<-lhobbs.res(xl,y)
   shg<-as.vector(2.0* (shres %*% shj))
   return(shg)
}


## ----label=C12lhobbs.lg, echo=TRUE---------------------------------------
lhobbs.lg<-function(xaug,y=y0){ # gradient function including sigma
  xl<-xaug[1:3]
  logSigma<-xaug[4]
  sigma2=exp(2.0*logSigma);
  res3<-lhobbs.res(xl,y)
  n<-length(res3)
  f3<-crossprod(res3)
  g3<-0.5*lhobbs.g(xl,y)/sigma2
  gg<-c(g3,(n - f3/sigma2))
}
```

```{r}
## ----label=C12run3par, echo=TRUE-----------------------------------------
y0 <- c(5.308, 7.24, 9.638, 12.866, 17.069, 23.192, 31.443, 
        38.558, 50.156, 62.948, 75.995, 91.972)
```

```{r}
## Above is same as C11lhobbs.R -- here for self-standing chapter directory
require(Rvmmin)
start<-c(1,1,1,1)
bdmsk<-c(1,1,1,0) # Cat fix parameter 4 at first
```

```{r}
## afix4<-Rvmmintry(start, lhobbs.lik, lhobbs.lg, bdmsk=bdmsk, y=y0,
##        control=list(trace=2))
afix4<-Rvmmin(start, lhobbs.lik, lhobbs.lg, bdmsk=bdmsk, y=y0,
       control=list(trace=0))
print(afix4)
```

```{r}
## ----label=C12run4parafter3, echo=TRUE-----------------------------------
start2<-afix4$par
## new start
print(start2)
bdmsk<-rep(1,4) ## EXPLICITLY free all parameters
aall<-Rvmmin(start2,lhobbs.lik, lhobbs.lg, bdmsk=bdmsk, y=y0)
print(aall)
```

```{r}

## ----label=C12run4fromguess, echo=FALSE----------------------------------
print(start)
aall0<-Rvmmin(start,lhobbs.lik, lhobbs.lg, y=y0)
print(aall0)
maskcounts<-afix4$counts+aall$counts
freecounts<-aall0$counts
cat("\n\nComparison of work: Masked      vs.    Free \n")
cat("    Functions         ",maskcounts[1],"           ",freecounts[1],"\n")
cat("    Gradients          ",maskcounts[2],"            ",freecounts[2],"\n")
cat("\n Exponentiated parameters, last is sigma:")
print(exp(aall$par))
```

```{r}
## ----label=C12run4fromguess, echo=FALSE----------------------------------
print(start)
aall0<-Rvmmin(start,lhobbs.lik, lhobbs.lg, y=y0)
print(aall0)
maskcounts<-afix4$counts+aall$counts
freecounts<-aall0$counts
cat("\n\nComparison of work: Masked      vs.    Free \n")
cat("    Functions         ",maskcounts[1],"           ",freecounts[1],"\n")
cat("    Gradients          ",maskcounts[2],"            ",freecounts[2],"\n")
cat("\n Exponentiated parameters, last is sigma:")
print(exp(aall$par))
```

## 12.3 Masks for nonlinear least squares

```{r}
## ----label=C12bateshobbsmask1, echo=TRUE---------------------------------
weeddata<-data.frame(y=y0, t=1:12)
mystart<-c(Asym=250, xmid=6, scal=1) # This sets the Asym value
require(nlmrt) # Ensure tools available
maskrun<-nlxb(y~Asym/(1+exp((xmid-t)/scal)), start=mystart, data=weeddata, 
      mask=c("Asym"), trace=FALSE)
maskrun
```

```{r}

## ----label=C12bateshobbsmask2, echo=TRUE---------------------------------
mystart2<-c(xmid=6, scal=1) # This sets the Asym value
maskrun2<-nlxb(y~250/(1+exp((xmid-t)/scal)), start=mystart2, data=weeddata)
maskrun2
```
