---
title: "Chapter 14"
output: html_notebook
---

# 14 Applications of mathematical programming

## 14.3 Example problem: L1 regression

```{r}
# data generation so script is self-standing
x <- c(3, -2, -1)
a1 <- rep(1, 10)
a2 <- 1:10
a3 <- a2^2
A <- matrix(c(a1, a2, a3), nrow = 10, ncol = 3)
A
```

```{r}
## create model data
y0 <- A %*% x
y0
```

```{r}
## perturb the model data -- get working data
set.seed(1245)
y <- as.numeric(y0) + runif(10, -1, 1)
y
```

```{r}
## try a least squares model
l2fit <- lm(y ~ a2 + a3)
l2fit
```

```{r}
# other functions needed for self-standing script
sumabs <- function(x, A, y) { # loss function
  sum(abs(y - A %*% x))
}
sumsqr <- function(x, A, y) { # loss function
  sum((y - A %*% x)^2) # a poor way to do this
}
```

```{r}
require(optimx)
require(optextras)
st <- c(1, 1, 1)
method <- c(
  "Rvmmin",
  "nlm",
  "ucminf",
  "nlminb",
  "BFGS",
  "CG",
  "Nelder-Mead",
  "L-BFGS-B"
  # "Rcgmin",
  # "newuoa",
  # "bobyqa",
  # "hjkb",
  # "nmkb",
  # "spg"
)
```

```{r}
ansmm1 <- optimx(st, sumabs, gr = "grnd", method = method, A = A, y = y)
print(summary(ansmm1, order = value))
```

```{r}
ansmm2 <- optimx(st, sumsqr, gr = "grnd", method = method, A = A, y = y)
print(summary(ansmm2, order = value))
```

```{r}
## ----label=C14mplreg3, echo=TRUE, cache=TRUE-----------------------------
LADreg <- function(A, y) { # Least sum abs residuals regression
  require(linprog)
  m <- dim(A)[1]
  n <- dim(A)[2]
  if (length(y) != m) stop("Incompatible A and y sizes in LADreg")
  ones <- diag(rep(1, m))
  Abig <- rbind(cbind(-ones, -A, A), cbind(-ones, A, -A))
  bvec <- c(-y, y)
  cvec <- c(rep(1, m), rep(0, 2 * n)) # m z's, n pos x, n neg x
  ans <- solveLP(cvec, bvec, Abig, lpSolve = TRUE)
  sol <- ans$solution
  coeffs <- sol[(m + 1):(m + n)] - sol[(m + n + 1):(m + 2 * n)]
  names(coeffs) <- as.character(1:n)
  res <- as.numeric(sol[1:m])
  sad <- sum(abs(res))
  answer <- list(coeffs = coeffs, res = res, sad = sad)
}


## ----label=C14mplreg4, echo=TRUE, cache=TRUE-----------------------------
myans1 <- LADreg(A, y)
myans1$coeffs
myans1$sad
```

```{r}
## ----label=C14mplreg5, echo=TRUE, cache=TRUE-----------------------------
require(pracma)
ap1 <- L1linreg(A = A, b = y)
ap1
sumabs(ap1$x, A, y)
require(quantreg)
qreg <- rq(y ~ a2 + a3, tau = 0.5)
qreg
xq <- coef(qreg)
sumabs(xq, A, y)
```

## 14.4 Example problem: minimax regression

```{r}

minmaxw <- function(x, A, y) {
  res <- y - A %*% x
  val <- max(abs(res))
  attr(val, "where") <- which(abs(res) == val)
  val
}
minmax <- function(x, A, y) {
  res <- y - A %*% x
  val <- max(abs(res))
}
```

```{r}
ansmm3 <- optimx(st, minmax, gr = "grnd", method = method, A = A, y = y)
print(summary(ansmm3, order = value))
```

```{r}
## ----label=C14mmreg2, echo=TRUE, cache=TRUE------------------------------
mmreg <- function(A, y) { # max abs residuals regression
  require(linprog)
  m <- dim(A)[1]
  n <- dim(A)[2]
  if (length(y) != m) stop("Incompatible A and y sizes in LADreg")
  onem <- rep(1, m)
  Abig <- rbind(cbind(-A, A, -onem), cbind(A, -A, -onem))
  bvec <- c(-y, y)
  cvec <- c(rep(0, 2 * n), 1) # n pos x, n neg x, 1 t
  ans <- solveLP(cvec, bvec, Abig, lpSolve = TRUE)
  sol <- ans$solution
  coeffs <- sol[1:n] - sol[(n + 1):(2 * n)]
  names(coeffs) <- as.character(1:n)
  res <- as.numeric(A %*% coeffs - y)
  mad <- max(abs(res))
  answer <- list(coeffs = coeffs, res = res, mad = mad)
}
```

```{r}
## ----label=C14mmreg3, echo=TRUE, cache=TRUE------------------------------
amm <- mmreg(A, y)
amm
mmcoef <- amm$coeffs
## sum of squares of minimax solution
print(sumsqr(mmcoef, A, y))
## sum abs residuals of minimax solution
print(sumabs(mmcoef, A, y))
```

## 14.5 Nonlinear quantile regression

```{r}
## ----label=C14nlrq1, echo=TRUE, cache=TRUE-------------------------------
y <- c(
  5.308, 7.24, 9.638, 12.866, 17.069, 23.192, 31.443,
  38.558, 50.156, 62.948, 75.995, 91.972
)
t <- 1:12
weeddata <- data.frame(y = y, t = t)
require(quantreg)
formulas <- y ~ 100 * sb1 / (1 + 10 * sb2 * exp(-0.1 * sb3 * t))
snames <- c("sb1", "sb2", "sb3")
st <- c(1, 1, 1)
names(st) <- snames
anlrqsh1 <- nlrq(formulas, start = st, data = weeddata)
summary(anlrqsh1)
```

```{r}
## ----label=C14nlrq2, echo=TRUE, cache=TRUE-------------------------------
st <- c(2, 5, 3)
names(st) <- snames
anlrqsh2 <- nlrq(formulas, start = st, data = weeddata)
summary(anlrqsh2)
```

## 14.6 Polynomial approximation

```{r}
n <- 10 # polynomial of degree 10
m <- 101 # no. of data points
xi <- seq(-1, 1, length = m)
yi <- 1 / (1 + (5 * xi)^2)
plot(xi, yi, type = "l", lwd = 3, col = "gray", main = "Runge's Function")
title(sub = "Polynomial approximation is dot-dash line")

pfn <- function(p) max(abs(polyval(c(p), xi) - yi))

require(pracma)
pf <- polyfit(xi, yi, n)
print(pfn(pf))

lines(xi, polyval(pf, xi), col = "blue", lty = 4)
```

```{r}
## ----label=C14runge2, echo=TRUE, cache=TRUE------------------------------
## set up a matrix for the polynomial data
ndeg <- 10
Ar <- matrix(NA, nrow = 101, ncol = ndeg + 1)
Ar[, ndeg + 1] <- 1
for (j in 1:ndeg) { # align to match polyval
  Ar[, ndeg + 1 - j] <- xi * Ar[, ndeg + 2 - j]
}
cat("Check minimax function value for least squares fit\n")
print(minmaxw(pf, Ar, yi))
```

```{r}
apoly1 <- mmreg(Ar, yi)
apoly1$mad
pcoef <- apoly1$coeffs
pcoef
```

```{r}
sumabs(pcoef, Ar, yi)
sumsqr(pcoef, Ar, yi)
print(minmaxw(pcoef, Ar, yi))
```

```{r}
## ----label=C14runge3, echo=TRUE, cache=TRUE------------------------------
## LAD regression on Runge
apoly2 <- LADreg(Ar, yi)
apoly2$sad
pcoef2 <- apoly2$coeffs
pcoef2
sumabs(pcoef2, Ar, yi)
sumsqr(pcoef2, Ar, yi)
print(minmaxw(pcoef2, Ar, yi))
```

```{r}
## ----label=C14runge4, echo=TRUE, cache=TRUE------------------------------
require(adagio)
system.time(aadag <- pureCMAES(pf, pfn, rep(-200, 11), rep(200, 11)))
aadag
```
