---
title: "note14"
output: html_notebook
---

```{r}
options(paged.print = FALSE)
```

```{r}
library(tidymodels)
library(finetune)
library(doMC)
# registerDoMC(cores = 2)
# tidymodels_prefer()
```

```{r}
data(cells)
cells <- cells %>% select(-case)

set.seed(1304)
cell_folds <- vfold_cv(cells)

roc_res <- metric_set(roc_auc)
```

# 14 반복 검색

## 14.1 서포트 벡터 머신 모델

```{r}
library(tidymodels)
tidymodels_prefer()

svm_rec <-
  recipe(class ~ ., data = cells) %>%
  step_YeoJohnson(all_numeric_predictors()) %>%
  step_normalize(all_numeric_predictors())

svm_spec <-
  svm_rbf(cost = tune(), rbf_sigma = tune()) %>%
  set_engine("kernlab") %>%
  set_mode("classification")

svm_wflow <-
  workflow() %>%
  add_model(svm_spec) %>%
  add_recipe(svm_rec)
```

```{r}
cost()
rbf_sigma()
```

```{r}
svm_param <-
  svm_wflow %>%
  extract_parameter_set_dials() %>%
  update(rbf_sigma = rbf_sigma(c(-7, -1)))
svm_param
```

```{r}
# library(doMC)
# registerDoMC(cores = 2)
library(doParallel)
cl <- makePSOCKcluster(8)
registerDoParallel(cl)
```

```{r}
set.seed(1401)
start_grid <-
  svm_param %>%
  update(
    cost = cost(c(-6, 1)),
    rbf_sigma = rbf_sigma(c(-6, -4))
  ) %>%
  grid_regular(levels = 2)

set.seed(1402)
svm_initial <-
  svm_wflow %>%
  tune_grid(resamples = cell_folds, grid = start_grid, metrics = roc_res)
```

```{r}
collect_metrics(svm_initial)
```

## 14.2 베이지안 최적화

```{r}
ctrl <- control_bayes(verbose = TRUE)

set.seed(1403)
svm_bo <-
  svm_wflow %>%
  tune_bayes(
    resamples = cell_folds,
    metrics = roc_res,
    initial = svm_initial,
    param_info = svm_param,
    iter = 25,
    control = ctrl
  )
```

```{r}
show_best(svm_bo)
```

```{r}
autoplot(svm_bo, type = "performance")
```

```{r}
autoplot(svm_bo)
```

## 14.3 모의 어닐링

```{r}
ctrl_sa <- control_sim_anneal(verbose = TRUE, no_improve = 10L)

set.seed(1404)
svm_sa <-
  svm_wflow %>%
  tune_sim_anneal(
    resamples = cell_folds,
    metrics = roc_res,
    initial = svm_initial,
    param_info = svm_param,
    iter = 50,
    control = ctrl_sa
  )
```

```{r}
autoplot(svm_sa, type = "performance")
```

```{r}
autoplot(svm_sa, type = "parameter")
```

```{r}
stopCluster(cl)
```

