---
title: "note02"
output: 
  html_notebook:
    df_print: kable
---

```{r}
options(paged.print = FALSE)
```

# 2 Exploring Longitudinal Data on Change

## 2.1 Creating a longitudinal data set

```{r}
library(tidyverse)
```

```{r}
tolerance <- read_csv("https://stats.idre.ucla.edu/wp-content/uploads/2016/02/tolerance1.txt", col_names = T)
tolerance
```

```{r}
tolerance %>%
  count()
```

```{r}
tolerance %>%
  nrow()
```

```{r}
cor(tolerance[, 2:6]) %>%
  round(digits = 2)
```

```{r}
cor(tolerance[, 2:6]) %>%
  data.frame() %>%
  rownames_to_column("row") %>%
  pivot_longer(-row, names_to = "column", values_to = "correlation") %>%
  mutate(row = factor(row) %>% fct_rev(.)) %>%
  ggplot(aes(x = column, y = row)) +
  geom_raster(aes(fill = correlation)) +
  geom_text(aes(label = round(correlation, digits = 2)), size = 3.5) +
  scale_fill_gradient(low = "white", high = "red4", limits = c(0, 1)) +
  scale_x_discrete(NULL, position = "top", expand = c(0, 0)) +
  scale_y_discrete(NULL, expand = c(0, 0)) +
  theme(axis.ticks = element_blank()) +
  coord_fixed(ratio = 1)
```

```{r}
psych::lowerCor(tolerance[, 2:6])
```

```{r}
tolerance_pp <- read_csv("https://stats.idre.ucla.edu/wp-content/uploads/2016/02/tolerance1_pp.txt", col_names = T)
tolerance_pp # %>%
# slice(1:9, 76:80)
```

```{r}
tolerance_pp %>%
  distinct(id) %>%
  count()
```

```{r}
tolerance_pp %>%
  count(id)
```

```{r}
tolerance %>%
  pivot_longer(tol11:tol15, names_to = "age", values_to = "tolerance") %>%
  mutate(age = as.integer(str_remove(age, "tol"))) %>%
  arrange(id, age) %>%
  relocate(id, tolerance, age)
```

```{r}
tolerance_pp %>%
  mutate(age = str_c("tol", age)) %>%
  select(-time) %>%
  pivot_wider(names_from = age, values_from = tolerance)
```

## 2.2 Descriptive analysis of individual change over time

```{r}
tolerance_pp %>%
  ggplot(aes(x = age, y = tolerance)) +
  geom_point() +
  geom_line() +
  coord_cartesian(ylim = c(1, 4)) +
  facet_wrap(~id) +
  theme(panel.grid = element_blank())
# theme(aspect.ratio = 0.7)
```

```{r}
tolerance_pp %>%
  ggplot(aes(x = age, y = tolerance, group = id)) +
  geom_point() +
  stat_smooth(method = "loess", se = FALSE, span = .9) +
  coord_cartesian(ylim = c(1, 4)) +
  facet_wrap(~id) +
  theme(panel.grid = element_blank())
```

```{r}
by_id <-
  tolerance_pp %>%
  group_by(id) %>%
  nest()
by_id
```

```{r}
by_id$data[[1]]
```

```{r}
by_id$data[[1]] %>%
  mutate(age_minus_11 = age - 11)
```

```{r}
library(brms)
```

```{r}
fit2.1 <-
  brm(
    data = by_id$data[[1]],
    formula = tolerance ~ 1 + time,
    prior = prior(normal(0, 2), class = b),
    iter = 4000, chains = 4, cores = 4,
    seed = 2,
    file = "fits/fit02.01"
  )
```

```{r}
print(fit2.1)
```

```{r}
fit2.1$prior
```

```{r}
fit2.2 <-
  update(fit2.1,
    newdata = by_id$data[[2]],
    control = list(adapt_delta = .9),
    file = "fits/fit02.02"
  )
```

```{r}
fit2.2
```

```{r}
bayes_R2(fit2.2)
```

```{r}
bayes_R2(fit2.2, summary = FALSE) %>%
  str()
```

```{r}
bayes_R2(fit2.2, summary = FALSE) %>%
  data.frame() %>%
  ggplot(aes(R2)) +
  geom_density(fill = "black") +
  scale_x_continuous(expression(italic(R)[Bayesian]^2), limits = c(0, 1)) +
  scale_y_continuous(NULL, breaks = NULL) +
  theme(panel.grid = element_blank())
```

```{r}
bayes_R2(fit2.2, summary = FALSE) %>%
  data.frame() %>%
  summarize(
    mean = mean(R2),
    median = median(R2),
    mode = tidybayes::Mode(R2)
  )
```

```{r}
bayes_R2(fit2.2)
bayes_R2(fit2.2, robust = TRUE)
```

```{r}
fits <-
  by_id %>%
  mutate(model = map(data, ~ update(fit2.1, newdata = ., seed = 2)))
```

```{r}
fits
```

```{r}
mean_structure <-
  fits %>%
  mutate(coefs = map(model, ~ posterior_summary(.)[1:2, 1:2] %>%
    data.frame() %>%
    rownames_to_column("coefficients"))) %>%
  unnest(coefs) %>%
  select(-data, -model) %>%
  unite(temp, Estimate, Est.Error) %>%
  pivot_wider(names_from = coefficients, values_from = temp) %>%
  separate(b_Intercept, into = c("init_stat_est", "init_stat_sd"), sep = "_") %>%
  separate(b_time, into = c("rate_change_est", "rate_change_sd"), sep = "_") %>%
  mutate(across(where(is.character), ~ round(as.double(.), digits = 2))) %>%
  ungroup()
mean_structure
```

```{r}
residual_variance <-
  fits %>%
  mutate(
    residual_variance = map_dbl(model, ~ posterior_summary(.)[3, 1]^2)
  ) %>%
  mutate(across(is.double, round, digits = 2)) %>%
  select(id, residual_variance)
residual_variance
```

```{r}
r2 <-
  fits %>%
  mutate(r2 = map_dbl(model, ~ bayes_R2(., robust = TRUE)[1])) %>%
  mutate(across(is.double, round, digits = 2)) %>%
  select(id, r2)
r2
```

```{r}
table <-
  fits %>%
  unnest(data) %>%
  group_by(id) %>%
  slice(1) %>%
  select(id, male, exposure) %>%
  left_join(mean_structure, by = "id") %>%
  left_join(residual_variance, by = "id") %>%
  left_join(r2, by = "id") %>%
  rename(residual_var = residual_variance) %>%
  relocate(id, init_stat_est:r2) %>%
  ungroup()
table %>%
  flextable::flextable()
```

```{r}
table %>%
  pull(init_stat_est) %>%
  stem(scale = 2)
```

```{r}
table %>%
  pull(rate_change_est) %>%
  stem(scale = 2)
```

```{r}
table %>%
  pull(residual_var) %>%
  stem(scale = 2)
```

```{r}
table %>%
  pull(r2) %>%
  stem(scale = 2)
```

```{r, fig.width=2.5, fig.height=2.5}
by_id %>%
  unnest(data) %>%
  ggplot(aes(time, tolerance, group = id)) +
  geom_point() +
  geom_abline(
    data = mean_structure,
    aes(
      intercept = init_stat_est,
      slope = rate_change_est, group = id
    ),
    color = "blue"
  ) +
  scale_x_continuous(breaks = 0:4, labels = 0:4 + 11) +
  coord_cartesian(ylim = c(0, 4)) +
  facet_wrap(~id) +
  theme(panel.grid = element_blank())
```

## 2.3 Exploring differences in change across people

```{r}
tolerance_pp %>%
  ggplot(aes(age, tolerance)) +
  stat_smooth(method = "loess", se = FALSE, span = .9, size = 2) +
  stat_smooth(aes(group = id), method = "loess", se = FALSE, span = .9, size = 1 / 4) +
  coord_cartesian(ylim = c(0, 4)) +
  theme(panel.grid = element_blank()) +
  theme(aspect.ratio = 1)
```

```{r}
tolerance_pp %>%
  ggplot(aes(age, tolerance)) +
  stat_smooth(method = "lm", se = FALSE, span = .9, size = 2) +
  stat_smooth(aes(group = id), method = "lm", se = FALSE, span = .9, size = 1 / 4) +
  coord_cartesian(ylim = c(0, 4)) +
  theme(panel.grid = element_blank()) +
  theme(aspect.ratio = 1)
```

```{r}
fit2.3 <-
  update(fit2.1,
    newdata = tolerance_pp,
    file = "fits/fit02.03"
  )
```

```{r}
fit2.3
```

```{r}
fixef(fit2.3)
```

```{r}
tol_fitted <-
  mean_structure %>%
  mutate(
    `11` = init_stat_est + rate_change_est * 0,
    `15` = init_stat_est + rate_change_est * 4
  ) %>%
  select(id, `11`, `15`) %>%
  pivot_longer(-id, names_to = "age", values_to = "tolerance") %>%
  mutate(age = as.integer(age))
tol_fitted
```

```{r}
tol_fitted %>%
  ggplot(aes(x = age, y = tolerance, group = id)) +
  geom_line(color = "blue", size = 1 / 4) +
  geom_abline(
    intercept = fixef(fit2.3)[1, 1] + fixef(fit2.3)[2, 1] * -11,
    slope = fixef(fit2.3)[2, 1],
    color = "blue", size = 2
  ) +
  coord_cartesian(ylim = c(0, 4)) +
  theme(panel.grid = element_blank()) +
  theme(aspect.ratio = 1)
```

```{r}
mean_structure %>%
  pivot_longer(ends_with("est")) %>%
  group_by(name) %>%
  summarize(
    mean = mean(value),
    sd = sd(value)
  ) %>%
  mutate(across(where(is.numeric), round, digits = 2))
```

```{r}
mean_structure %>%
  select(init_stat_est, rate_change_est) %>%
  cor() %>%
  round(digits = 2)
```

```{r}
fit2.4 <-
  update(fit2.1,
    newdata = tolerance_pp,
    tolerance ~ 1 + time + male + time:male,
    file = "fits/fit02.04"
  )
```

```{r}
fit2.4
```

```{r}
fixef(fit2.4)
```

```{r}
tol_fitted_male <-
  tibble(
    male = rep(0:1, each = 2),
    age = rep(c(11, 15), times = 2)
  ) %>%
  mutate(time = age - 11) %>%
  mutate(tolerance = fixef(fit2.4)[1, 1] +
    fixef(fit2.4)[2, 1] * time +
    fixef(fit2.4)[3, 1] * male +
    fixef(fit2.4)[4, 1] * time * male) %>%
  mutate(sex = (if_else(male == 0, "female", "male")))
tol_fitted_male
```

```{r}
tol_fitted %>%
  left_join(tolerance_pp %>% select(id, male) %>% distinct(), by = "id") %>%
  mutate(sex = (if_else(male == 0, "female", "male"))) %>%
  ggplot(aes(age, tolerance, color = factor(male))) +
  geom_line(aes(group = id), size = 1 / 4) +
  geom_line(data = tol_fitted_male, size = 2) +
  coord_cartesian(ylim = c(0, 4)) +
  facet_wrap(~sex) +
  scale_color_viridis_d(end = .75) +
  theme(
    legend.position = "none",
    panel.grid = element_blank()
  )
```

```{r}
tolerance_pp <-
  tolerance_pp %>%
  mutate(exposure_01 = if_else(exposure > median(exposure), 1, 0))
```

```{r}
fit2.5 <-
  update(fit2.4,
    newdata = tolerance_pp,
    tolerance ~ 1 + time + exposure_01 + time:exposure_01,
    file = "fits/fit02.05"
  )
```

```{r}
fit2.5
```

```{r}
tol_fitted_exposure <-
  crossing(
    exposure_01 = 0:1,
    age = c(11, 15)
  ) %>%
  mutate(time = age - 11) %>%
  mutate(
    tolerance = fixef(fit2.5)[1, 1] +
      fixef(fit2.5)[2, 1] * time +
      fixef(fit2.5)[3, 1] * exposure_01 +
      fixef(fit2.5)[4, 1] * time * exposure_01,
    exposure = if_else(exposure_01 == 1, "high exposure", "low exposure") %>%
      factor(., levels = c("low exposure", "high exposure"))
  )

tol_fitted_exposure
```

```{r}
tol_fitted %>%
  # we need to add `exposure_01` values to `tol_fitted`
  left_join(tolerance_pp %>% select(id, exposure_01) %>% distinct(),
    by = "id"
  ) %>%
  mutate(exposure = factor(
    if_else(exposure_01 == 1, "high exposure", "low exposure"),
    levels = c("low exposure", "high exposure")
  )) %>%
  ggplot(aes(x = age, y = tolerance, color = exposure)) +
  geom_line(aes(group = id), size = 1 / 4) +
  geom_line(data = tol_fitted_exposure, size = 2) +
  coord_cartesian(ylim = c(0, 4)) +
  facet_wrap(~exposure) +
  scale_color_viridis_d(option = "A", end = .75) +
  theme(
    legend.position = "none",
    panel.grid = element_blank()
  )
```

```{r}
p1 <-
  mean_structure %>%
  pivot_longer(ends_with("est")) %>%
  mutate(
    name = factor(
      name,
      labels = c("Fitted initial status", "Fitted rate of change")
    )
  ) %>%
  left_join(tolerance_pp %>% select(id, male) %>% distinct(), by = "id") %>%
  ggplot(aes(factor(male), value, color = name)) +
  geom_point(alpha = 1 / 2) +
  labs(x = "male", y = NULL) +
  facet_wrap(~name, scale = "free_y", ncol = 1) +
  scale_color_viridis_d(option = "B", begin = .2, end = .7) +
  theme(
    legend.position = "none",
    panel.grid = element_blank()
  ) #+
# theme(aspect.ratio = 0.9)
p1
```

```{r}
p2 <-
  mean_structure %>%
  pivot_longer(ends_with("est")) %>%
  mutate(
    name = factor(name, labels = c("Fitted initial status", "Fitted rate of change"))
  ) %>%
  left_join(tolerance_pp %>% select(id, exposure) %>% distinct(),
    by = "id"
  ) %>%
  ggplot(aes(exposure, value, color = name)) +
  geom_point(alpha = 1 / 2) +
  scale_x_continuous(breaks = 0:2, limits = c(0, 2.4)) +
  labs(y = NULL) +
  facet_wrap(~name, scale = "free_y", ncol = 1) +
  scale_color_viridis_d(option = "B", begin = .2, end = .7) +
  theme(
    legend.position = "none",
    panel.grid = element_blank()
  ) #+
# theme(aspect.ratio = 0.9)

p2
```

```{r, fig.width=3, fig.height = 3}
library(patchwork)
p1 + p2 + scale_y_continuous(breaks = NULL)
```

## 2.4 Improving the precision and reliability of OLS / single-level-Bayesian-estimated rates of change: Lessons for research design
