---
title: "Chapter 3"
output: html_notebook
---

# 3 Subsetting

## 3.1 Data types

```{r}
x <- c(2.1, 4.2, 3.3, 5.4)
x[c(3, 1)]
x[c(1, 1)]
x[c(2.1, 2.9)]
```

```{r}
x[-c(3, 1)]
```

```{r}
try(x[c(-1, 2)])
```

```{r}
x[c(TRUE, TRUE, FALSE, FALSE)]
x[x > 3]
```

```{r}
x[c(TRUE, FALSE)]

x[c(TRUE, FALSE, TRUE, FALSE)]
```

```{r}
x[c(TRUE, TRUE, NA, FALSE)]
```

```{r}
x[]
```

```{r}
x[0]
```

```{r}
(y <- setNames(x, letters[1:4]))
y[c("d", "c", "a")]
z <- c(abc = 1, def = 2)
z[c("a", "d")]
```

```{r}
a <- matrix(1:9, nrow = 3)
colnames(a) <- c("A", "B", "C")
a
```

```{r}
a[c(TRUE, FALSE, TRUE), c("B", "A")]
```

```{r}
a[0, -2]
```

```{r}
(vals <- outer(1:5, 6:10, FUN = "paste", sep = ","))
```

```{r}
vals[c(4, 15)]
```

```{r}
select <- matrix(ncol = 2, byrow = TRUE, c(1, 1, 3, 1, 2, 4))
select
vals[select]
```

```{r}
df <- data.frame(x = 1:3, y = 3:1, z = letters[1:3])
df
```

```{r}
df[df$x == 2, ]
```

```{r}
df[c(1, 3), ]
```

```{r}
df[c("x", "z")]
```

```{r}
df[, c("x", "z")]
```

```{r}
str(df["x"])
```

```{r}
str(df[, "x"])
```

```{r}
mtcars[mtcars$cyl == 4, ]
mtcars[1:4, ]
mtcars[mtcars$cyl <= 5, ]
mtcars[mtcars$cyl == 4 | mtcars$cyl == 6, ]
```

```{r}
x <- 1:5
x[NA]
x[NA_real_]
```

```{r}
x <- outer(1:5, 1:5, FUN = "*")
upper.tri(x)
```

```{r}
x[!upper.tri(x)] <- NA
```

```{r}
mtcars[1:20, ]
```

## 3.2 Subsetting operators

```{r}
a <- list(a = 1, b = 2)
a[[1]]
```

```{r}
a[["a"]]
```

```{r}
b <- list(a = list(b = list(c = list(d = 1))))
b[[c("a", "b", "c", "d")]]
```

```{r}
x <- c(a = 1, b = 2)
x[1]
x[[1]]
```

```{r}
y <- list(a = 1, b = 2)
str(y[1])
str(y[[1]])
```

```{r}
z <- factor(c("a", "b"))
z[1]
z[1, drop = TRUE]
```

```{r}
a <- matrix(1:4, nrow = 2)
a[1, , drop = FALSE]
a[1, ]
```

```{r}
df <- data.frame(a = 1:2, b = 1:2)
str(df[1])
str(df[, "a", drop = FALSE])
str(df[, "a"])
```

```{r}
var <- "cyl"
mtcars$var

mtcars[[var]]
```

```{r}
x <- list(abc = 1)
x$a
x[["a"]]
```

```{r}
x <- 1:4
str(x[5])
str(x[NA_real_])
str(x[NULL])
```

## 3.3 Subsetting and assignment

```{r}
x <- 1:5
x[c(1, 2)] <- 2:3
x
```

```{r}
x[-1] <- 4:1
x
```

```{r}
x[c(1, 1)] <- 2:3
x
```

```{r}
try(x[c(1, NA)] <- c(1, 2))
```

```{r}
x[c(T, F, NA)] <- 1
x
```

```{r}
df <- data.frame(a = c(1, 10, NA))
df$a[df$a < 5] <- 0
df
```

```{r}
mtcars[] <- lapply(mtcars, as.integer)
mtcars
```

```{r}
x <- list(a = 1, b = 2)
x[["b"]] <- NULL
str(x)
```

```{r}
y <- list(a = 1)
y["b"] <- list(NULL)
y
```

## 3.3 Applications

```{r}
x <- c("m", "f", "u", "f", "f", "m", "m")
lookup <- c(m = "Male", f = "Female", u = NA)
lookup[x]
unname(lookup[x])
```

```{r}
c(m = "Known", f = "Known", u = "Unknown")[x]
```

```{r}
grades <- c(1, 2, 2, 3, 1)
info <- data.frame(
  grade = 3:1,
  desc = c("Excellent", "Good", "Poor"),
  fail = c(F, F, T)
)
info
```

```{r}
id <- match(grades, info$grade)
info[id, ]
```

```{r}
rownames(info) <- info$grade
info
info[as.character(grades), ]
```

```{r}
df <- data.frame(x = rep(1:3, each = 2), y = 6:1, z = letters[1:6])
df
```

```{r}
set.seed(10)
df[sample(nrow(df)), ]
```

```{r}
df[sample(nrow(df), 3), ]
```

```{r}
df[sample(nrow(df), 6, rep = TRUE), ]
```

```{r}
x <- c("b", "c", "a")
order(x)
x[order(x)]
```

```{r}
df2 <- df[sample(nrow(df)), 3:1]
df2
```

```{r}
df2[order(df2$x), ]
```

```{r}
df2[, order(names(df2))]
```

```{r}
df <- data.frame(x = c(2, 4, 1), y = c(9, 11, 6), n = c(3, 5, 1))
df
```

```{r}
rep(1:nrow(df), df$n)
```

```{r}
df[rep(1:nrow(df), df$n), ]
```

```{r}
df <- data.frame(x = 1:3, y = 3:1, z = letters[1:3])
df
df$z <- NULL
df
```

```{r}
df[setdiff(names(df), c("x", "z"))]
```

```{r}
mtcars[mtcars$gear == 5, ]
```

```{r}
mtcars[mtcars$gear == 5 & mtcars$cyl == 4, ]
```

```{r}
subset(mtcars, gear == 5)
```

```{r}
subset(mtcars, gear == 5 & cyl == 4)
```

```{r}
x <- sample(10) < 4
which(x)
```

```{r}
unwhich <- function(x, n) {
  out <- rep_len(FALSE, n)
  out[x] <- TRUE
  out
}

unwhich(which(x), 10)
```

```{r}
(x1 <- 1:10 %% 2 == 0)
(x2 <- which(x1))
```

```{r}
(y1 <- 1:10 %% 5 == 0)
(y2 <- which(y1))
```

```{r}
x1 & y1
```

```{r}
intersect(x2, y2)
```

```{r}
x1 | y1
```

```{r}
union(x2, y2)
```

```{r}
x1 & !y1
setdiff(x2, y2)
```

```{r}
xor(x1, y1)
setdiff(union(x2, y2), intersect(x2, y2))
```
