---
title: "Chapter 13"
output: html_notebook
---

# 13 Non-standard evaluation

```{r}
x <- seq(0, 2 * pi, length = 100)
sinx <- sin(x)
plot(x, sinx, type = "l")
```

## 13.1 Capturing expressions

```{r}
f <- function(x) {
  substitute(x)
}
str(f(1:10))
```

```{r}
x <- 10
f(x)
```

```{r}
y <- 13
f(x + y^2)
```

```{r}
g <- function(x) deparse(substitute(x))
str(g(1:10))
g(x)
g(x + y^2)
```

```{r}
x <- 1:4
y <- letters[1:4]
names(data.frame(x, y))
```

## 13.2 Non-standard evaluation in subset

```{r}
sample_df <- data.frame(a = 1:5, b = 5:1, c = c(5, 3, 1, 4, 1))
subset(sample_df, a >= 4)
```

```{r}
subset(sample_df, b == c)
```

```{r}
quote(1:10)
quote(x)
quote(x + y^2)
```

```{r}
eval(quote(x <- 1))
eval(quote(x))
```

```{r}
eval(quote(y))
```

```{r}
quote(2 + 2)
eval(quote(2 + 2))
```

```{r}
eval(quote(quote(2 + 2)))
```

```{r}
eval(eval(quote(quote(2 + 2))))
```

```{r}
x <- 10
eval(quote(x))

e <- new.env()
e$x <- 20
eval(quote(x), e)
```

```{r}
eval(quote(x), list(x = 30))
```

```{r}
eval(quote(x), data.frame(x = 40))
```

```{r}
eval(quote(a >= 4), sample_df)
eval(quote(b == c), sample_df)
```

```{r}
a <- 10
eval(quote(a), sample_df)
eval(10, sample_df)
```

```{r}
eval(quote(b), sample_df)
try(eval(b, sample_df))
```

```{r}
subset2 <- function(x, condition) {
  condition_call <- substitute(condition)
  r <- eval(condition_call, x)
  x[r, ]
}
subset2(sample_df, a >= 4)
```

```{r}
f <- function(argX) {
  list(
    quote(argX),
    substitute(argX),
    argX
  )
}

suppliedArgX <- 100
f(argX = suppliedArgX)
```

```{r}
eval(quote(eval(quote(eval(quote(2 + 2))))))
eval(eval(quote(eval(quote(eval(quote(2 + 2)))))))
quote(eval(quote(eval(quote(eval(quote(2 + 2)))))))
```

```{r}
subset2 <- function(x, condition) {
  condition_call <- substitute(condition)
  r <- eval(condition_call, x)
  x[r, , drop = FALSE]
}

sample_df2 <- data.frame(x = 1:10)
subset2(sample_df2, x > 8)
```

## 13.3 Scoping issues

```{r}
y <- 4
x <- 4
condition <- 4
condition_call <- 4

subset2(sample_df, a == 4)
subset2(sample_df, a == y)
subset2(sample_df, a == x)
subset2(sample_df, a == condition)
subset2(sample_df, a == condition_call)
```

```{r}
subset2 <- function(x, condition) {
  condition_call <- substitute(condition)
  r <- eval(condition_call, x, parent.frame())
  x[r, ]
}
x <- 4
subset2(sample_df, a == 4)
subset2(sample_df, a == y)
subset2(sample_df, a == x)
subset2(sample_df, a == condition)
subset2(sample_df, a == condition_call)
```

```{r}
subset2a <- function(x, condition) {
  condition_call <- substitute(condition)
  env <- list2env(x, parent = parent.frame())
  r <- eval(condition_call, env)
  x[r, ]
}
x <- 5
subset2a(sample_df, a == x)
```

]

## 13.4 Calling from another function

```{r}
subset2 <- function(x, condition) {
  condition_call <- substitute(condition)
  r <- eval(condition_call, x, parent.frame())
  x[r, ]
}

scramble <- function(x) x[sample(nrow(x)), ]

subscramble <- function(x, condition) {
  scramble(subset2(x, condition))
}

subscramble(sample_df, a >= 4)
```

```{r}
a <- 4
subscramble(sample_df, a == 4)
```

```{r}
a <- c(1, 1, 4, 4, 4, 4)
subscramble(sample_df, a >= 4)
```

```{r}
subset2_q <- function(x, condition) {
  r <- eval(condition, x, parent.frame())
  x[r, ]
}
```

```{r}
subset2 <- function(x, condition) {
  subset2_q(x, substitute(condition))
}

subscramble <- function(x, condition) {
  condition <- substitute(condition)
  scramble(subset2_q(x, condition))
}

subscramble(sample_df, a >= 3)
subscramble(sample_df, a >= 3)
```

## 13.5 Substitute

```{r}
library(lattice)
xyplot(mpg ~ disp, data = mtcars)
```

```{r}
x <- quote(mpg)
y <- quote(disp)
try(xyplot(x ~ y, data = mtcars))
```

```{r}
a <- 1
b <- 2
substitute(a + b + z)
```

```{r}
f <- function() {
  a <- 1
  b <- 2
  substitute(a + b + z)
}
f()
```

```{r}
a <- 1
b <- 2
pryr::subs(a + b + z)
```

```{r}
library(pryr)
pryr::subs(a + b, list(a = "y"))
pryr::subs(a + b, list(a = quote(y)))
pryr::subs(a + b, list(a = quote(y())))
```

```{r}
subs(a + b, list("+" = quote(f)))
#> f(a, b)
subs(a + b, list("+" = quote(`*`)))
```

```{r}
subs(y <- y + 1, list(y = 1))
```

```{r}
x <- quote(mpg)
y <- quote(disp)
subs(xyplot(x ~ y, data = mtcars))
```

```{r}
xyplot2 <- function(x, y, data = data) {
  substitute(xyplot(x ~ y, data = data))
}
xyplot2(mpg, disp, data = mtcars)
```

```{r}
x <- quote(a + b)
substitute(x, list(a = 1, b = 2))
```

```{r}
substitute_q <- function(x, env) {
  call <- substitute(substitute(y, env), list(y = x))
  eval(call)
}

x <- quote(a + b)
substitute_q(x, list(a = 1, b = 2))
```

## 13.6 The downsides of non-standard evaluation
