---
title: "note05"
output: html_notebook
---

# Session info

## 5 Treating Time More Flexibly

## 5.1 Variably spaced measurement occasions

```{r}
library(tidyverse)
```

```{r}
reading_pp <- read_csv("data/reading_pp.csv")
reading_pp
```

```{r}
reading_pp %>%
  ggplot(aes(age, wave)) +
  geom_vline(xintercept = c(6.5, 8.5, 10.5), color = "white") +
  geom_jitter(alpha = .5, height = .33, width = 0) +
  scale_x_continuous(breaks = c(6.5, 8.5, 10.5)) +
  scale_y_continuous(breaks = 1:3) +
  ggtitle("This is what occasion creep looks like.",
    subtitle = "As the waves go by, the variation of the ages widens and their central tendency\ncreeps away from the ideal point."
  ) +
  theme(panel.grid = element_blank())
```

```{r}
set.seed(5)
reading_pp %>%
  nest(data = c(wave, agegrp, age, piat)) %>%
  slice_sample(n = 9) %>%
  unnest(data) %>%
  mutate(id = ifelse(id < 10, str_c("0", id), id) %>% str_c("id = ", .)) %>%
  pivot_longer(contains("age")) %>%
  ggplot(aes(value, piat, color = name)) +
  geom_point(alpha = 2 / 3) +
  geom_smooth(method = "lm", se = FALSE, size = 1 / 2) +
  scale_color_viridis_d(NULL, option = "B", end = .5, direction = -1) +
  xlab("measure of age") +
  coord_cartesian(xlim = c(5, 12), ylim = c(0, 80)) +
  facet_wrap(~id) +
  theme(panel.grid = element_blank())
```

```{r}
reading_pp <-
  reading_pp %>%
  mutate(
    agegrp_c = agegrp - 6.5,
    age_c = age - 6.5
  )
reading_pp
```

```{r}
library(rethinking)
```

```{r}
n <- 1e6
set.seed(5)
lkj <-
  tibble(eta = c(1, 2, 3, 4)) %>%
  mutate(draws = purrr::map(eta, ~ rlkjcorr(n, K = 2, eta = .)[, 2, 1])) %>%
  unnest(draws)
lkj
```

```{r}
lkj %>%
  mutate(eta = factor(eta)) %>%
  ggplot(aes(draws, fill = eta, color = eta)) +
  geom_density(size = 0, alpha = 2 / 3) +
  geom_text(
    data = tibble(
      draws = c(.75, .35),
      y = c(.6, 1.05),
      label = c("eta = 1", "eta = 4"),
      eta = c(1, 4) %>% as.factor()
    ),
    aes(y = y, label = label)
  ) +
  scale_fill_viridis_d(option = "A", end = .5) +
  scale_color_viridis_d(option = "A", end = .5) +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(expression(rho)) +
  theme(
    panel.grid = element_blank(),
    legend.position = "none"
  )
```

```{r}
detach(package:rethinking, unload = TRUE)
library(brms)
```

```{r}
fit5.1 <-
  brm(
    data = reading_pp,
    family = gaussian,
    piat ~ 0 + Intercept + agegrp_c + (1 + agegrp_c | id),
    prior = c(
      prior(normal(100, 30), class = b, coef = Intercept),
      prior(normal(0, 30), class = b, coef = agegrp_c),
      prior(student_t(3, 0, 15), class = sd),
      prior(student_t(3, 0, 15), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    file = "fits/fit05.01"
  )
```

```{r}
fit5.2 <-
  brm(
    data = reading_pp,
    family = gaussian,
    piat ~ 0 + Intercept + age_c + (1 + age_c | id),
    prior = c(
      prior(normal(100, 30), class = b, coef = Intercept),
      prior(normal(0, 30), class = b, coef = age_c),
      prior(student_t(3, 0, 15), class = sd),
      prior(student_t(3, 0, 15), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    file = "fits/fit05.02"
  )
```

```{r}
print(fit5.1, digits = 3)
```

```{r}
print(fit5.2, digits = 3)
```

```{r}
fixef(fit5.1) %>% round(digits = 3)
```

```{r}
fixef(fit5.2) %>% round(digits = 3)
```

```{r}
VarCorr(fit5.1)$residual$sd %>% round(digits = 3)
```

```{r}
VarCorr(fit5.2)$residual$sd %>% round(digits = 3)
```

```{r}
fit5.1 <- add_criterion(fit5.1, c("loo", "waic"))
fit5.2 <- add_criterion(fit5.2, c("loo", "waic"))
```

```{r}
loo_compare(fit5.1, fit5.2, criterion = "waic") %>%
  print(simplify = FALSE)
```

```{r}
loo_compare(fit5.1, fit5.2, criterion = "loo") %>%
  print(simplify = FALSE)
```

```{r}
model_weights(fit5.1, fit5.2, weights = "waic") %>% round(digits = 3)
```

```{r}
model_weights(fit5.1, fit5.2, weights = "loo") %>% round(digits = 3)
```

## 5.2 Varying numbers of measurement occasions

```{r}
wages_pp <- read_csv("data/wages_pp.csv")
glimpse(wages_pp)
```

```{r}
wages_pp %>%
  select(id, exper, lnw, black, hgc, uerate) %>%
  filter(id %in% c(206, 332, 1028))
```

```{r}
wages_pp %>%
  count(id) %>%
  ggplot(aes(y = n)) +
  geom_bar() +
  scale_y_continuous("# measurement occasions", breaks = 1:13) +
  xlab("count of cases") +
  theme(panel.grid = element_blank())
```

```{r}
wages_pp %>%
  filter(id %in% c(206, 332, 1028)) %>%
  mutate(id = factor(id)) %>%
  ggplot(aes(exper, lnw, color = id)) +
  geom_point() +
  geom_line() +
  scale_color_viridis_d(option = "B", begin = .35, end = .8) +
  theme(panel.grid = element_blank())
```

```{r}
log(20172.11)
```

```{r}
log(20172.11 / (40 * 52))
```

```{r}
log(3.80)
```

```{r}
get_prior(
  data = wages_pp,
  family = gaussian,
  lnw ~ 0 + Intercept + exper + (1 + exper | id)
)
```

```{r}
fit5.3 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + exper + (1 + exper | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b, coef = exper),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 5,
    file = "fits/fit05.03"
  )
```

```{r}
print(fit5.3, digits = 3)
```

```{r}
post <-
  posterior_samples(fit5.3) %>%
  transmute(percent_change = 100 * (exp(b_exper) - 1))
post
```

```{r}
library(tidybayes)
post %>%
  ggplot(aes(x = percent_change, y = 0)) +
  stat_halfeye(.width = .95) +
  scale_y_continuous(NULL, breaks = NULL) +
  labs(
    title = "Percent change",
    x = expression(100 * (italic(e)^hat(gamma)[1][0]) - 1)
  ) +
  theme(panel.grid = element_blank())
```

```{r}
post %>%
  median_qi(percent_change)
```

```{r}
wages_pp <-
  wages_pp %>%
  rename(hgc_9 = hgc.9)
```

```{r}
wages_pp %>%
  pivot_longer(c(black, hgc_9)) %>%
  ggplot(aes(value)) +
  geom_bar() +
  facet_wrap(~name, scales = "free") +
  theme(panel.grid = element_blank())
```

```{r}
sd(wages_pp$hgc_9)
```

```{r}
fit5.4 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + hgc_9 + black + exper + exper:hgc_9 + exper:black + (1 + exper | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 5,
    file = "fits/fit05.04"
  )
```

```{r}
print(fit5.4, digits = 3)
```

```{r}
post <- posterior_samples(fit5.4)
```

```{r}
post %>%
  transmute(
    `sigma[0]^2` = sd_id__Intercept^2,
    `sigma[1]^2` = sd_id__exper^2,
    `sigma[epsilon]^2` = sigma^2
  ) %>%
  pivot_longer(everything()) %>%
  ggplot(aes(value, name)) +
  stat_halfeye(.widht = 95, normalize = "xy") +
  scale_y_discrete(NULL, labels = ggplot2:::parse_safe) +
  coord_cartesian(ylim = c(1.4, 3.4)) +
  theme(
    axis.ticks.y = element_blank(),
    panel.grid = element_blank()
  )
```

```{r}
post %>%
  select(starts_with("b_")) %>%
  set_names(str_c(
    "gamma",
    c("[0][0]", "[0][1]", "[0][2]", "[1][0]", "[1][1]", "[1][2]")
  )) %>%
  pivot_longer(everything()) %>%
  ggplot(aes(value, name)) +
  geom_vline(xintercept = 0, color = "white") +
  stat_pointinterval(.width = .95, size = 1 / 2) +
  scale_y_discrete(NULL, labels = ggplot2:::parse_safe) +
  theme(
    axis.ticks.y = element_blank(),
    panel.grid = element_blank()
  )
```

```{r}
fit5.5 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + hgc_9 + exper + exper:black + (1 + exper | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 5,
    file = "fits/fit05.05"
  )
```

```{r}
print(fit5.5, digits = 3)
```

```{r}
fit5.3 <- add_criterion(fit5.3, criterion = "waic")
fit5.4 <- add_criterion(fit5.4, criterion = "waic")
fit5.5 <- add_criterion(fit5.5, criterion = "waic")
```

```{r}
loo_compare(fit5.3, fit5.4, fit5.5, criterion = "waic") %>%
  print(simplify = FALSE)
```

```{r}
model_weights(fit5.3, fit5.4, fit5.5, weights = "waic") %>%
  round(digits = 3)
```

```{r}
nd <-
  crossing(
    black = 0:1,
    hgc_9 = c(0, 3)
  ) %>%
  expand(nesting(black, hgc_9),
    exper = seq(0, 11, length.out = 30)
  )
f <-
  fitted(fit5.5,
    newdata = nd,
    re_formula = NA
  ) %>%
  data.frame() %>%
  bind_cols(nd)
f
```

```{r}
f %>%
  mutate(
    black = factor(black, labels = c("Latinos and Whites", "Blacks")),
    hgc_9 = factor(hgc_9, labels = c("9th grade dropouts", "12th grade dropouts"))
  ) %>%
  ggplot(aes(exper, color = black, fill = black)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), size = 0, alpha = 1 / 4) +
  geom_line(aes(y = Estimate)) +
  scale_fill_viridis_d(NULL, option = "C", begin = .25, end = .75) +
  scale_color_viridis_d(NULL, option = "C", begin = .25, end = .75) +
  ylab("lnw") +
  coord_cartesian(ylim = c(1.6, 2.4)) +
  facet_wrap(~hgc_9) +
  theme(panel.grid = element_blank())
```

```{r}
nd <-
  wages_pp %>%
  filter(id %in% c(206, 332, 1028))
f <- fitted(fit5.5, newdata = nd) %>%
  data.frame() %>%
  bind_cols(nd)
f
```

```{r}
f %>%
  mutate(id = str_c("id = ", id)) %>%
  ggplot(aes(x = exper)) +
  # geom_pointrange(aes(y = Estimate, ymin = Q2.5, ymax = Q97.5, color = id))
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5, fill = id), alpha = 1 / 3) +
  geom_line(aes(y = Estimate, color = id), alpha = 2 / 3) +
  geom_point(aes(y = lnw)) +
  labs(subtitle = "The black dots are the original data. The colored lines and areas are\nthe participant-specific posterior means and 95% intervals.") +
  facet_wrap(~id) +
  theme(panel.grid = element_blank(), legend.position = "none")
```

```{r}
fit5.3$model
```

```{r}
wages_small_pp <- read.csv("data/wages_small_pp.csv") %>%
  rename(hgc_9 = hcg.9)
wages_small_pp
```

```{r}
wages_small_pp %>%
  count(id) %>%
  ggplot(aes(y = n)) +
  geom_bar() +
  scale_y_continuous("# measurement occasions", breaks = 1:13, limits = c(.5, 13)) +
  xlab("count of cases") +
  theme(panel.grid = element_blank())
```

```{r}
fit5.6 <-
  brm(
    data = wages_small_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + hgc_9 + exper + exper:black + (1 + exper | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    file = "fits/fit05.06"
  )
```

```{r}
print(fit5.6)
```

```{r}
post <- posterior_samples(fit5.6)
```

```{r}
v <-
  post %>%
  transmute(sigma_1 = sd_id__exper) %>%
  mutate(sigma_2_1 = sigma_1^2) %>%
  set_names("sigma[1]", "sigma[1]^2") %>%
  pivot_longer(everything())
```

```{r}
v %>%
  ggplot(aes(value, name)) +
  stat_halfeye(.width = .95, normalize = "xy") +
  scale_y_discrete(NULL, labels = ggplot2:::parse_safe) +
  theme(axis.ticks.y = element_blank(), panel.grid = element_blank())
```

```{r}
v %>%
  group_by(name) %>%
  mean_qi() %>%
  mutate(across(where(is.double), round, digits = 4))
```

```{r}
v %>%
  group_by(name) %>%
  median_qi() %>%
  mutate(across(where(is.double), round, digits = 4))
```

```{r}
v %>%
  group_by(name) %>%
  mode_qi() %>%
  mutate(across(where(is.double), round, digits = 4))
```

```{r}
fit5.7 <-
  brm(
    data = wages_small_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + hgc_9 + exper + exper:black + (1 + exper | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    control = list(adapt_delta = .99),
    file = "fits/fit05.07"
  )
```

```{r}
print(fit5.7)
```

```{r}
fit5.8 <-
  brm(
    data = wages_small_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + hgc_9 + exper + exper:black + (1 | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    file = "fits/fit05.08"
  )
```

```{r}
print(fit5.8)
```

```{r}
fit5.7 <- add_criterion(fit5.7, criterion = "waic")
fit5.8 <- add_criterion(fit5.8, criterion = "waic")
```

```{r}
loo_compare(fit5.7, fit5.8, criterion = "waic") %>%
  print(simplify = FALSE, digits = 3)
```

```{r}
tibble(x = c(0, 100)) %>%
  ggplot(aes(x)) +
  stat_function(fun = dgamma, n = 1e2, args = list(shape = 2, rate = 0.1)) +
  scale_y_continuous(NULL, breaks = NULL) +
  theme(panel.grid = element_blank())
```

```{r}
tibble(x = c(0, 2)) %>%
  ggplot(aes(x)) +
  stat_function(fun = dgamma, n = 1e2, args = list(shape = 2, rate = .1)) +
  scale_y_continuous(NULL, breaks = NULL) +
  theme(panel.grid = element_blank())
```

```{r}
fit5.9 <-
  brm(
    data = wages_small_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + hgc_9 + exper + exper:black + (1 + exper | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(gamma(2, 0.1), class = sd, group = id, coef = exper),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    file = "fits/fit05.09"
  )
```

```{r}
print(fit5.9, digits = 3)
```

```{r}
posterior_samples(fit5.9) %>%
  transmute(sigma_1 = sd_id__exper) %>%
  mutate(sigma_2_1 = sigma_1^2) %>%
  set_names("sigma[1]", "sigma[1]^2") %>%
  pivot_longer(everything()) %>%
  ggplot(aes(value, name)) +
  stat_halfeye(.width = .95, normalize = "xy") +
  scale_y_discrete(NULL, labels = ggplot2:::parse_safe) +
  theme(
    axis.ticks.y = element_blank(),
    panel.grid = element_blank()
  )
```

```{r}
posterior_samples(fit5.9) %>%
  transmute(sigma_1 = sd_id__exper) %>%
  mutate(sigma_2_1 = sigma_1^2) %>%
  set_names("sigma[1]", "sigma[1]^2") %>%
  pivot_longer(everything()) %>%
  ggplot(aes(value, name)) +
  stat_halfeye(.width = .95, normalize = "xy") +
  scale_y_discrete(NULL, labels = ggplot2:::parse_safe) +
  coord_cartesian(xlim = c(0, 0.01)) +
  theme(
    axis.ticks.y = element_blank(),
    panel.grid = element_blank()
  )
```

```{r}
posterior_samples(fit5.3) %>%
  median_qi(sd_id__exper)
```

```{r}
1 / 0.04137229
```

```{r}
tibble(x = c(0, 1)) %>%
  ggplot(aes(x)) +
  stat_function(fun = dgamma, n = 1e3, args = list(shape = 2, rate = 24.0716)) +
  scale_y_continuous(NULL, breaks = NULL) +
  theme(panel.grid = element_blank())
```

```{r}
fit5.10 <-
  brm(
    data = wages_small_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + hgc_9 + exper + exper:black + (1 + exper | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(gamma(2, 24.0716), class = sd, group = id, coef = exper),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    file = "fits/fit05.10"
  )
```

```{r}
print(fit5.10, digits = 3)
```

```{r}
tibble(
  `full data, student_t(3, 0, 1) prior` = VarCorr(fit5.3, summary = F)[[1]][[1]][1:4000, 2],
  `small data, student_t(3, 0, 1) prior` = VarCorr(fit5.7, summary = F)[[1]][[1]][, 2],
  `small data, gamma(2, 0.1) prior` = VarCorr(fit5.9, summary = F)[[1]][[1]][, 2],
  `small data, gamma(2, 24.0716) prior` = VarCorr(fit5.10, summary = F)[[1]][[1]][, 2]
) %>%
  pivot_longer(everything()) %>%
  mutate(name = factor(name,
    levels = c(
      "full data, student_t(3, 0, 1) prior",
      "small data, student_t(3, 0, 1) prior",
      "small data, gamma(2, 0.1) prior",
      "small data, gamma(2, 24.0716) prior"
    )
  )) %>%
  ggplot(aes(x = value, y = 0, fill = name == "full data, student_t(3, 0, 1) prior")) +
  geom_vline(xintercept = 0, color = "white") +
  stat_halfeye(.width = .95, normalize = "panels") +
  scale_y_continuous(NULL, breaks = NULL) +
  scale_fill_manual(values = c("grey75", "darkgoldenrod2")) +
  facet_wrap(~name, ncol = 1) +
  theme(legend.position = "none", panel.grid = element_blank())
```

```{r}
plot(fit5.4)
```

```{r}
library(bayesplot)
```

```{r}
post <- posterior_samples(fit5.4, add_chain = TRUE)
post
```

```{r}
mcmc_trace(post, pars = "sigma")
```

```{r}
mcmc_trace(post,
  pars = vars(starts_with("b")),
  facet_args = list(ncol = 2)
)
```

```{r}
post %>%
  mutate(
    `sigma[0]` = sd_id__Intercept,
    `sigma[1]` = sd_id__exper,
    `sigma[epsilon]` = sigma
  ) %>%
  mcmc_trace(
    pars = vars(starts_with("sigma[")),
    facet_args = list(labeller = label_parsed)
  ) +
  scale_color_viridis_d(option = "A") +
  scale_x_continuous(NULL, breaks = NULL) +
  ggtitle("I can't wait to show these traceplots to my mom.") +
  theme_grey() +
  theme(
    legend.position = "bottom",
    panel.grid = element_blank(),
    panel.grid.major.y = element_line(color = "white", size = 1 / 4),
    strip.text = element_text(size = 12)
  )
```

```{r}
mcmc_acf(post, pars = vars(starts_with("b_")), lags = 10) +
  theme_grey() +
  theme(panel.grid = element_blank())
```

```{r}
mcmc_acf(post, pars = vars(starts_with("sd_"), "sigma", starts_with("cor")), lags = 10) +
  theme_grey() +
  theme(
    panel.grid = element_blank(),
    strip.text = element_text(size = 7)
  )
```

```{r}
summary(fit5.4)
```

```{r}
library(posterior)
post_sum <-
  as_draws_df(fit5.4) %>%
  summarize_draws()
post_sum
```

```{r}
post_sum %>%
  pivot_longer(starts_with("ess")) %>%
  ggplot(aes(value)) +
  geom_histogram(binwidth = 100) +
  xlim(0, NA) +
  facet_wrap(~name) +
  theme(panel.grid = element_blank())
```

```{r}
post_sum %>%
  slice(1:10) %>%
  pivot_longer(contains("ess")) %>%
  mutate(ess = str_remove(name, "ess_")) %>%
  ggplot(aes(y = reorder(variable, value))) +
  geom_linerange(aes(xmin = 0, xmax = value)) +
  geom_point(aes(x = value)) +
  labs(
    x = "effective sample size",
    y = NULL
  ) +
  xlim(0, 4000) +
  facet_wrap(~ess) +
  theme(
    panel.grid = element_blank(),
    axis.text.y = element_text(hjust = 0),
    axis.ticks.y = element_blank()
  )
```

```{r}
post_sum %>%
  arrange(desc(ess_bulk)) %>%
  select(variable, ess_bulk) %>%
  slice(1:10)
```

```{r}
mcmc_acf(post, pars = vars(`r_id[12335,exper]`, `r_id[5968,Intercept]`, `r_id[10476,Intercept]`, `r_id[7117,Intercept]`), lags = 5) +
  theme_grey() +
  theme(
    panel.grid = element_blank(),
    strip.text = element_text(size = 10)
  )
```

```{r}
print(fit5.4)
```

```{r}
brms::rhat(fit5.4) %>% str()
```

```{r}
brms::rhat(fit5.4)[1:10]
```

```{r}
post_sum %>%
  select(variable, rhat)
```

```{r}
post_sum %>%
  ggplot(aes(rhat)) +
  geom_vline(xintercept = 1, color = "white") +
  geom_histogram(bindwidth = .0001) +
  theme(panel.grid = element_blank())
```

```{r}
mcmc_rhat(brms::rhat(fit5.4)[1:20]) +
  yaxis_text(hjust = 0)
```

## 5.3 Time-varying predictors

```{r}
unemployment_pp <- read_csv("data/unemployment_pp.csv")
unemployment_pp
```

```{r}
unemployment_pp %>%
  distinct(id) %>%
  count()
```

```{r}
unemployment_pp %>%
  filter(unemp == 0) %>%
  distinct(id) %>%
  count() %>%
  summarize(never_employed = 254 - n)
```

```{r}
unemployment_pp %>%
  ggplot(aes(months)) +
  geom_vline(xintercept = c(3, 8), color = "white") +
  geom_histogram(binwidth = .5) +
  theme(panel.grid = element_blank())
```

```{r}
unemployment_pp <-
  unemployment_pp %>%
  mutate(interview = ifelse(months < 3, 1, ifelse(months > 8, 3, 2)))
```

```{r}
unemployment_pp %>%
  ggplot(aes(interview)) +
  geom_bar() +
  theme(panel.grid = element_blank())
```

```{r}
unemployment_pp %>%
  select(-months, -cesd) %>%
  mutate(interview = str_c("int_", interview)) %>%
  pivot_wider(names_from = interview, values_from = unemp) %>%
  group_by(int_1, int_2, int_3) %>%
  count() %>%
  arrange(desc(n)) %>%
  flextable::flextable()
```

```{r}
get_prior(cesd ~ 0 + Intercept + months + (1 + months | id), data = unemployment_pp)
```

```{r}
fit5.11 <-
  brm(
    data = unemployment_pp,
    family = gaussian,
    cesd ~ 0 + Intercept + months + (1 + months | id),
    prior = c(
      prior(normal(14.5, 20), class = b, coef = Intercept),
      prior(normal(0, 10), class = b),
      prior(student_t(3, 0, 11.9), class = sd),
      prior(student_t(3, 0, 11.9), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    control = list(adapt_delta = .99),
    file = "fits/fit05.11"
  )
```

```{r}
print(fit5.11, digits = 3)
```

```{r}
as_draws_df(fit5.11) %>%
  transmute(
    `first day of job loss` = b_Intercept,
    `linear decline by month` = b_months
  ) %>%
  pivot_longer(everything()) %>%
  ggplot(aes(value, y = 0)) +
  stat_halfeye(.width = .95, normalize = "panels") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab("CES-D composite score") +
  facet_wrap(~name, scales = "free") +
  theme(panel.grid = element_blank())
```

```{r}
plot(conditional_effects(fit5.11), plot = FALSE)[[1]] +
  geom_hline(yintercept = 14.5, color = "grey50", linetype = 2) +
  coord_cartesian(ylim = c(0, 20)) +
  theme(panel.grid = element_blank())
```

```{r}
fit5.12 <-
  brm(
    data = unemployment_pp,
    family = gaussian,
    cesd ~ 0 + Intercept + months + unemp + (1 + months | id),
    prior = c(
      prior(normal(14.5, 20), class = b, coef = Intercept),
      prior(normal(0, 10), class = b),
      prior(student_t(3, 0, 11.9), class = sd),
      prior(student_t(3, 0, 11.9), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    control = list(adapt_delta = .99),
    file = "fits/fit05.12"
  )
```

```{r}
print(fit5.12)
```

```{r}
fixef(fit5.11)["months", ]
```

```{r}
fixef(fit5.12)["months", ]
```

```{r}
tibble(
  fit5.11 = as_draws_df(fit5.11) %>% pull("b_months"),
  fit5.12 = as_draws_df(fit5.12) %>% pull("b_months")
) %>%
  mutate(dif = fit5.12 - fit5.11) %>%
  ggplot(aes(dif, y = 0)) +
  stat_halfeye(.width = .95) +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(expression(paste("Difference in ", gamma[1][0]))) +
  theme(panel.grid = element_blank())
```

```{r}
as_draws_df(fit5.12) %>%
  ggplot(aes(b_unemp, y = 0)) +
  stat_halfeye(.width = .95) +
  scale_y_continuous(NULL, breaks = NULL) +
  theme(panel.grid = element_blank())
```

```{r}
fit5.11 <- add_criterion(fit5.11, criterion = "waic")
fit5.12 <- add_criterion(fit5.12, criterion = "waic")
```

```{r}
loo_compare(fit5.11, fit5.12, criterion = "waic") %>%
  print(simplify = FALSE)
```

```{r}
model_weights(fit5.11, fit5.12, weights = "waic") %>%
  round(digits = 3)
```

```{r}
nd <-
  tibble(
    months = rep(seq(0, 14, by = .5), 2),
    unemp = rep(0:1, each = length(months) / 2)
  ) %>%
  relocate(unemp)

f <-
  fitted(fit5.12,
    newdata = nd,
    re_formula = NA
  ) %>%
  data.frame() %>%
  bind_cols(nd)
f %>%
  ggplot(aes(x = months, group = unemp)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),
    fill = "grey67", alpha = 1 / 2
  ) +
  geom_line(aes(y = Estimate)) +
  scale_x_continuous("Months since job loss", breaks = seq(0, 14, by = 2)) +
  scale_y_continuous("CES-D", limits = c(5, 20)) +
  labs(subtitle = "Remain unemployed and employed") +
  theme(panel.grid = element_blank())
```

```{r}
nd <-
  tibble(
    unemp = rep(1:0, times = c(11, 19)),
    months = c(
      seq(from = 0, to = 5, by = .5),
      seq(from = 5, to = 14, by = .5)
    )
  )
f <- fitted(fit5.12,
  newdata = nd,
  re_formula = NA
) %>%
  data.frame() %>%
  bind_cols(nd)

fx <- fixef(fit5.12)[, 1]

f %>%
  ggplot(aes(months, group = unemp)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),
    fill = "grey67", alpha = 1 / 2
  ) +
  geom_line(aes(y = Estimate)) +
  geom_segment(
    x = 5, xend = 5,
    y = fx[1] + fx[2] * 5,
    yend = fx[1] + fx[2] * 5 + fx[3],
    size = 1 / 3, linetype = 2
  ) +
  annotate(
    geom = "text",
    x = 8, y = 14.5, label = "gamma[2][0]", parse = TRUE
  ) +
  geom_segment(
    x = 7, y = 14.5,
    xend = 5.5, yend = 14.5,
    arrow = arrow(length = unit(0.05, "inches"))
  ) +
  scale_x_continuous("Months since job loss", breaks = seq(0, 14, by = 2)) +
  scale_y_continuous("CES-D", limits = c(5, 20)) +
  labs(subtitle = "Reemployed at 5 months") +
  theme(panel.grid = element_blank())
```

```{r}
nd <-
  tibble(
    unemp = rep(1:0, times = c(21, 9)),
    months = c(
      seq(from = 0, to = 10, by = .5),
      seq(from = 10, to = 14, by = .5)
    )
  )

f <-
  fitted(fit5.12,
    newdata = nd,
    re_formula = NA
  ) %>%
  data.frame() %>%
  bind_cols(nd)

f %>%
  ggplot(aes(x = months, group = unemp)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),
    fill = "grey67", alpha = 1 / 2
  ) +
  geom_line(aes(y = Estimate)) +
  geom_segment(
    x = 10, xend = 10,
    y = fixef(fit5.12)[1, 1] + fixef(fit5.12)[2, 1] * 10,
    yend = fixef(fit5.12)[1, 1] + fixef(fit5.12)[2, 1] * 10 + fixef(fit5.12)[3, 1],
    size = 1 / 3, linetype = 2
  ) +
  annotate(
    geom = "text",
    x = 7, y = 13.5, label = "gamma[2][0]",
    parse = T
  ) +
  geom_segment(
    x = 8, xend = 9.5,
    y = 13.5, yend = 13.5,
    arrow = arrow(length = unit(0.05, "inches"))
  ) +
  scale_x_continuous("Months since job loss", breaks = seq(from = 0, to = 14, by = 2)) +
  scale_y_continuous("CES-D", limits = c(5, 20)) +
  labs(subtitle = "Reemployed at 10 months") +
  theme(panel.grid = element_blank())
```

```{r}
nd <-
  tibble(
    unemp = rep(c(1, 0, 1), times = c(11, 11, 9)),
    months = c(
      seq(from = 0, to = 5, by = .5),
      seq(from = 5, to = 10, by = .5),
      seq(from = 10, to = 14, by = .5)
    ),
    group = rep(letters[1:3], times = c(11, 11, 9))
  )

f <-
  fitted(fit5.12,
    newdata = nd,
    re_formula = NA
  ) %>%
  data.frame() %>%
  bind_cols(nd)

lines <-
  tibble(
    group = letters[1:2],
    x = c(5, 10)
  ) %>%
  mutate(
    xend = x,
    y = fixef(fit5.12)[1, 1] + fixef(fit5.12)[2, 1] * x,
    yend = fixef(fit5.12)[1, 1] + fixef(fit5.12)[2, 1] * x + fixef(fit5.12)[3, 1]
  )

arrow <-
  tibble(
    x = c(6.75, 8.25),
    y = 14,
    xend = c(5.5, 9.5),
    yend = c(14.5, 13.5)
  )
f %>%
  ggplot(aes(x = months)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5, group = group),
    fill = "grey67", alpha = 1 / 2
  ) +
  geom_line(aes(y = Estimate, group = group)) +
  geom_segment(
    data = lines,
    aes(
      x = x, xend = xend,
      y = y, yend = yend,
      group = group
    ),
    size = 1 / 3, linetype = 2
  ) +
  annotate(
    geom = "text",
    x = 7.5, y = 14, label = "gamma[2][0]",
    parse = T
  ) +
  geom_segment(
    data = arrow,
    aes(
      x = x, xend = xend,
      y = y, yend = yend
    ),
    arrow = arrow(length = unit(0.05, "inches"))
  ) +
  scale_x_continuous("Months since job loss", breaks = seq(from = 0, to = 14, by = 2)) +
  scale_y_continuous("CES-D", limits = c(5, 20)) +
  labs(subtitle = "Reemployed at 5 months\nunemployed again at 10") +
  theme(panel.grid = element_blank())
```

```{r}
nd <-
  tibble(
    unemp = rep(1:0, times = c(29, 22)),
    months = c(
      seq(from = 0, to = 14, by = .5),
      seq(from = 3.5, to = 14, by = .5)
    )
  )

f <-
  fitted(fit5.12,
    newdata = nd,
    re_formula = NA
  ) %>%
  data.frame() %>%
  bind_cols(nd) %>%
  mutate(label = str_c("unemp = ", unemp))

f %>%
  ggplot(aes(x = months, group = unemp)) +
  # new trick
  geom_abline(
    intercept = fixef(fit5.12)[1, 1],
    slope = fixef(fit5.12)[2, 1],
    color = "grey80", linetype = 2
  ) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),
    fill = "grey67", alpha = 1 / 2
  ) +
  geom_line(aes(y = Estimate)) +
  # another new trick
  geom_text(
    data = f %>% filter(months == 14),
    aes(label = label, y = Estimate), hjust = -.05
  ) +
  scale_x_continuous("Months since job loss", breaks = seq(from = 0, to = 14, by = 2)) +
  scale_y_continuous("CES-D", limits = c(5, 20)) +
  labs(subtitle = "Main effects of unemp and time") +
  # don't forget this part
  coord_cartesian(clip = "off") +
  theme(
    panel.grid = element_blank(),
    plot.margin = margin(6, 55, 6, 6)
  )
```

```{r}
v <-
  cbind(
    VarCorr(fit5.11, summary = FALSE)[[2]][[1]],
    VarCorr(fit5.12, summary = FALSE)[[2]][[1]]
  ) %>%
  data.frame() %>%
  set_names(str_c("fit5.", 11:12)) %>%
  transmute(
    fit5.11 = fit5.11^2,
    fit5.12 = fit5.12^2
  ) %>%
  mutate(`fit5.11 - fit5.12` = fit5.11 - fit5.12)
v %>%
  pivot_longer(everything()) %>%
  mutate(name = factor(name, levels = c("fit5.11", "fit5.12", "fit5.11 - fit5.12"))) %>%
  ggplot(aes(value, y = 0)) +
  stat_halfeye(.width = .95, normalize = "panels") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(expression(sigma[epsion]^2)) +
  facet_wrap(~name, scales = "free") +
  theme(panel.grid = element_blank())
```

```{r}
v %>%
  transmute(percent = (fit5.11 - fit5.12) / fit5.11) %>%
  median_qi() %>%
  mutate(across(where(is.double), round, digits = 3))
```

```{r}
fit5.13 <-
  brm(
    data = unemployment_pp,
    family = gaussian,
    cesd ~ 0 + Intercept + months + unemp + months:unemp + (1 + months | id),
    prior = c(
      prior(normal(14.5, 20), class = b, coef = Intercept),
      prior(normal(0, 10), class = b),
      prior(student_t(3, 0, 11.9), class = sd),
      prior(student_t(3, 0, 11.9), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    control = list(adapt_delta = .9),
    file = "fits/fit05.13"
  )
```

```{r}
print(fit5.13)
```

```{r}
nd <- tibble(
  unemp = rep(1:0, times = c(29, 22)),
  months = c(
    seq(0, 14, by = .5),
    seq(3.5, 14, by = .5)
  )
)

f <- fitted(fit5.13,
  newdata = nd,
  re_formula = NA
) %>%
  data.frame() %>%
  bind_cols(nd) %>%
  mutate(label = str_c("unemp = ", unemp))
f %>%
  ggplot(aes(months, group = unemp)) +
  geom_abline(
    intercept = fixef(fit5.13)[1, 1],
    slope = fixef(fit5.13)[2, 1],
    color = "grey80", linetype = 2
  ) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),
    fill = "grey67", alpha = 1 / 2
  ) +
  geom_line(aes(y = Estimate)) +
  geom_text(
    data = f %>% filter(months == 14),
    aes(label = label, y = Estimate), hjust = -.05
  ) +
  scale_x_continuous("Months since job loss", breaks = seq(0, 14, by = 2)) +
  scale_y_continuous("CES-D", limits = c(5, 20)) +
  labs(subtitle = "Main effects of unemp and time") +
  coord_cartesian(clip = "off") +
  theme(
    panel.grid = element_blank(),
    plot.margin = margin(6, 55, 6, 6)
  )
```

```{r}
as_draws_df(fit5.13) %>%
  ggplot(aes(b_months, y = 0)) +
  stat_halfeye(.width = .95) +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(expression(paste(gamma[1][0], ", the main effect for time"))) +
  theme(panel.grid = element_blank())
```

```{r}
fit5.14 <-
  brm(
    data = unemployment_pp,
    family = gaussian,
    cesd ~ 0 + Intercept + unemp + months:unemp + (1 + months:unemp | id),
    prior = c(
      prior(normal(14.5, 20), class = b, coef = Intercept),
      prior(normal(0, 10), class = b),
      prior(student_t(3, 0, 11.9), class = sd),
      prior(student_t(3, 0, 11.9), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    control = list(adapt_delta = .99),
    file = "fits/fit05.14"
  )
```

```{r}
print(fit5.14)
```

```{r}
fit5.13 <- add_criterion(fit5.13, "waic")
fit5.14 <- add_criterion(fit5.14, "waic")
```

```{r}
loo_compare(fit5.11, fit5.12, fit5.13, fit5.14, criterion = "waic") %>%
  print(simplify = F)
```

```{r}
model_weights(fit5.11, fit5.12, fit5.13, fit5.14, weights = "waic") %>%
  round(digits = 3)
```

```{r}
fit5.15 <-
  brm(
    data = unemployment_pp,
    family = gaussian,
    cesd ~ 0 + Intercept + unemp + months:unemp + (1 + unemp + months:unemp | id),
    prior = c(
      prior(normal(14.5, 20), class = b, coef = Intercept),
      prior(normal(0, 10), class = b),
      prior(student_t(3, 0, 11.9), class = sd),
      prior(student_t(3, 0, 11.9), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    control = list(adapt_delta = .95),
    file = "fits/fit05.15"
  )
```

```{r}
print(fit5.15)
```

```{r}
f <-
  fitted(fit5.15,
    newdata = nd,
    re_formula = NA
  ) %>%
  data.frame() %>%
  bind_cols(nd) %>%
  mutate(label = str_c("unemp = ", unemp))

f %>%
  ggplot(aes(x = months, group = unemp)) +
  geom_abline(
    intercept = fixef(fit5.15)[1, 1],
    slope = 0,
    color = "grey80", linetype = 2
  ) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),
    fill = "grey67", alpha = 1 / 2
  ) +
  geom_line(aes(y = Estimate)) +
  geom_text(
    data = f %>% filter(months == 14),
    aes(label = label, y = Estimate), hjust = -.05
  ) +
  scale_x_continuous("Months since job loss", breaks = seq(from = 0, to = 14, by = 2)) +
  scale_y_continuous("CES-D", limits = c(5, 20)) +
  labs(subtitle = "Constraining the effects time\namong the re-employed") +
  coord_cartesian(clip = "off") +
  theme(
    panel.grid = element_blank(),
    plot.margin = margin(6, 55, 6, 6)
  )
```

```{r}
f %>%
  filter(unemp == 1 & months == 0)
```

```{r}
fixef(fit5.15)["unemp:months", ]
```

```{r}
fixef(fit5.15)["unemp", ]
```

```{r}
nd <-
  tibble(
    unemp = 1:0,
    months = 12
  )

fitted(fit5.15,
  newdata = nd,
  re_formula = NA,
  summary = F
) %>%
  data.frame() %>%
  set_names(str_c(c("un", ""), "employed_cesd_at_12")) %>%
  transmute(difference = unemployed_cesd_at_12 - employed_cesd_at_12) %>%
  median_qi() %>%
  mutate_if(is.double, round, digits = 3)
```

```{r}
fit5.15 <- add_criterion(fit5.15, "waic")

loo_compare(fit5.11, fit5.12, fit5.13, fit5.14, fit5.15, criterion = "waic") %>%
  print(simplify = F)
```

```{r}
model_weights(fit5.11, fit5.12, fit5.13, fit5.14, fit5.15, weights = "waic") %>%
  round(digits = 3)
```

```{r}
hist(wages_pp$uerate)
```

```{r}
wages_pp <-
  wages_pp %>%
  mutate(uerate_7 = uerate - 7)
```

```{r}
fit5.16 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + exper + hgc_9 + black:exper + uerate_7 + (1 + exper | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 5,
    file = "fits/fit05.16"
  )
```

```{r}
print(fit5.16, digits = 3)
```

```{r}
wages_pp <-
  wages_pp %>%
  group_by(id) %>%
  mutate(uerate_id_mu = mean(uerate)) %>%
  ungroup() %>%
  mutate(uerate_id_dev = uerate - uerate_id_mu)
```

```{r}
fit5.17 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + exper + hgc_9 + black:exper + uerate_id_mu + uerate_id_dev +
      (1 + exper | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 5,
    file = "fits/fit05.17"
  )
```

```{r}
print(fit5.17, digits = 3)
```

```{r}
wages_pp <-
  wages_pp %>%
  group_by(id) %>%
  mutate(uerate_id_1 = first(uerate)) %>%
  ungroup() %>%
  mutate(uerate_id_1_dev = uerate - uerate_id_1)
```

```{r}
fit5.18 <-
  update(fit5.16,
    newdata = wages_pp,
    lnw ~ 0 + Intercept + exper + hgc_9 + black:exper + uerate_id_1 + uerate_id_1_dev +
      (1 + exper | id),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 5,
    file = "fits/fit05.18"
  )
```

```{r}
print(fit5.18, digits = 3)
```

```{r}
fit5.16 <- add_criterion(fit5.16, "waic")
fit5.17 <- add_criterion(fit5.17, "waic")
fit5.18 <- add_criterion(fit5.18, "waic")

loo_compare(fit5.16, fit5.17, fit5.18, criterion = "waic") %>%
  print(simplify = F)
```

```{r}
model_weights(fit5.16, fit5.17, fit5.18, weights = "waic") %>%
  round(digits = 3)
```

## 5.4 Recentering the effect of TIME

```{r}
medication_pp <- read_csv("data/medication_pp.csv")
medication_pp
```

```{r}
medication_pp <-
  medication_pp %>%
  mutate(reading = ifelse(time.of.day == 0, "8 am",
    ifelse(time.of.day < .6, "3 pm", "10 pm")
  ))
medication_pp %>%
  select(wave, day, reading, time.of.day:time667) %>%
  mutate(across(where(is.double), round, digits = 2))
```

```{r}
medication_pp %>%
  mutate(treat = str_c("treat = ", treat)) %>%
  group_by(treat, id) %>%
  count() %>%
  ggplot(aes(y = n, fill = treat)) +
  geom_bar() +
  scale_y_continuous(breaks = c(2, 12, 15:21)) +
  scale_fill_viridis_d(NULL, end = .8) +
  labs(
    x = "count of cases",
    y = "# measurement occasions"
  ) +
  theme(panel.grid = element_blank())
```

```{r}
medication_pp %>%
  ggplot(aes(pos)) +
  geom_histogram() +
  theme(panel.grid = element_blank())
```

```{r}
range(medication_pp$pos)
```

```{r}
fit5.19 <-
  brm(
    data = medication_pp,
    family = gaussian,
    pos ~ 0 + Intercept + time + treat + time:treat + (1 + time | id),
    prior = c(
      prior(normal(150, 50), class = b, coef = Intercept),
      prior(normal(0, 25), class = b),
      prior(student_t(3, 0, 50), class = sd),
      prior(student_t(3, 0, 50), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    file = "fits/fit05.19"
  )
```

```{r}
fit5.20 <-
  update(fit5.19,
    newdata = medication_pp,
    pos ~ 0 + Intercept + time333 + treat + time333:treat + (1 + time333 | id),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    file = "fits/fit05.20"
  )
```

```{r}
fit5.21 <-
  update(fit5.19,
    newdata = medication_pp,
    pos ~ 0 + Intercept + time667 + treat + time667:treat + (1 + time667 | id),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    file = "fits/fit05.21"
  )
```

```{r}
print(fit5.19)
```

```{r}
v <-
  as_draws_df(fit5.19) %>%
  transmute(
    sigma_2_0 = sd_id__Intercept^2,
    sigma_2_1 = sd_id__time^2,
    sigma_2_epsilon = sigma^2
  )
v %>%
  pivot_longer(everything()) %>%
  group_by(name) %>%
  median_qi() %>%
  mutate(across(where(is.double), round, digits = 2))
```

```{r}
v %>%
  set_names("sigma[0]^2", "sigma[1]^2", "sigma[epsilon]^2") %>%
  pivot_longer(everything()) %>%
  ggplot(aes(value, y = 0)) +
  stat_halfeye(.width = .95, normalize = "panels") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab("posterior") +
  facet_wrap(~name, scales = "free", labeller = label_parsed) +
  theme(panel.grid = element_blank(), strip.text = element_text(size = 11))
```

```{r}
nd <-
  crossing(
    treat = 0:1,
    time = seq(0, 7, length.out = 30)
  )
text <-
  tibble(
    treat = 0:1,
    time = 4,
    y = c(135, 197),
    label = c("control", "treatment"),
    angle = c(350, 15)
  )
fitted(fit5.19,
  newdata = nd,
  re_formula = NA
) %>%
  data.frame() %>%
  bind_cols(nd) %>%
  ggplot(aes(time, fill = treat, color = treat, group = treat)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), alpha = 1 / 3, size = 0) +
  geom_line(aes(y = Estimate)) +
  geom_text(data = text, aes(y = y, label = label, angle = angle)) +
  scale_fill_viridis_c(option = "A", begin = .3, end = .6) +
  scale_color_viridis_c(option = "A", begin = .3, end = .6) +
  labs(x = "days", y = "pos") +
  theme(
    legend.position = "none",
    panel.grid = element_blank()
  )
```

```{r}
print(fit5.20)
```

```{r}
print(fit5.21)
```

```{r}
tibble(name = str_c("fit5.", 19:21)) %>%
  mutate(fixef = map(name, ~ get(.) %>%
    fixef() %>%
    data.frame() %>%
    rownames_to_column("parameter"))) %>%
  unnest(fixef) %>%
  mutate(gamma = rep(c("gamma[0][0]", "gamma[1][0]", "gamma[0][1]", "gamma[1][1]"),
    times = 3
  )) %>%
  ggplot(aes(name, Estimate, ymin = Q2.5, ymax = Q97.5)) +
  geom_pointrange() +
  xlab(NULL) +
  coord_flip() +
  facet_wrap(~gamma, scales = "free_x", labeller = label_parsed, ncol = 4) +
  theme(
    axis.ticks.y = element_blank(),
    panel.grid = element_blank(),
    strip.text = element_text(size = 11)
  )
```

```{r}
tibble(name = str_c("fit5.", 19:21)) %>%
  mutate(fit = map(name, get)) %>%
  mutate(sigma_2_1 = map(fit, ~ VarCorr(., summary = F)[[1]][[1]][, 1]^2 %>%
    data.frame() %>%
    set_names("sigma_2_1"))) %>%
  unnest(sigma_2_1) %>%
  ggplot(aes(x = sigma_2_1, y = name)) +
  stat_halfeye(.width = c(.5, .95)) +
  scale_x_continuous(expression(sigma[1]^2), limits = c(0, NA)) +
  ylab(NULL) +
  theme(
    axis.ticks.y = element_blank(),
    panel.grid = element_blank()
  )
```

```{r}
tibble(name = str_c("fit5.", 19:21)) %>%
  mutate(fit = map(name, get)) %>%
  mutate(rho = map(fit, ~ VarCorr(., summary = F)[[1]][[2]][, 2, "Intercept"] %>%
    data.frame() %>%
    set_names("rho"))) %>%
  unnest(rho) %>%
  ggplot(aes(x = rho, y = name)) +
  stat_halfeye(.width = c(.5, .95)) +
  labs(
    x = expression(rho[0][1]),
    y = NULL
  ) +
  coord_cartesian(xlim = c(-1, 1)) +
  theme(
    axis.ticks.y = element_blank(),
    panel.grid = element_blank()
  )
```

```{r}
fit5.19 <- add_criterion(fit5.19, "waic")
fit5.20 <- add_criterion(fit5.20, "waic")
fit5.21 <- add_criterion(fit5.21, "waic")

loo_compare(fit5.19, fit5.20, fit5.21, criterion = "waic") %>%
  print(simplify = F)
```

```{r}
model_weights(fit5.19, fit5.20, fit5.21, weights = "waic") %>%
  round(digits = 3)
```

```{r}
fit5.22 <-
  brm(
    data = medication_pp,
    family = gaussian,
    pos ~ 0 + initial + final + initial:treat + final:treat + (0 + initial + final | id),
    prior = c(
      prior(normal(150, 50), class = b, coef = initial),
      prior(normal(150, 50), class = b, coef = final),
      prior(normal(0, 25), class = b),
      prior(student_t(3, 0, 50), class = sd),
      prior(student_t(3, 0, 50), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 5,
    file = "fits/fit05.22"
  )
```

```{r}
print(fit5.22)
```

```{r}
fit5.22 <- add_criterion(fit5.22, "waic")

loo_compare(fit5.19, fit5.20, fit5.21, fit5.22, criterion = "waic") %>%
  print(simplify = F)
```

```{r}
model_weights(fit5.19, fit5.20, fit5.21, fit5.22, weights = "waic") %>%
  round(digits = 3)
```
