---
title: "note03"
output: html_notebook
---

# 3 소프트웨어 탐색

## 3.1 작업 디렉토리 가져오기 및 설정

```{r}
x <- getwd()
setwd(x)
getwd()
```

## 3.2 새 RStudio 프로젝트 생성

## 3.3 작업 공간 저장

```{r}
# save.image()
```

## 3.4 명령 기록 보기

```{r}
history()
```

## 3.5 이전 명령의 결과 저장

```{r}
rnorm(10)
```

```{r}
x <- .Last.value
x
```

## 3.6 검색 경로를 통해 로드된 패키지 표시

```{r}
search()
```

## 3.7 설치된 패키지 목록 보기

```{r}
# library()
```

```{r}
installed.packages()[1:5, c("Package", "Version")]
```

## 3.8 패키지의 기능에 접근하기

```{r}
library(MASS)
data(mpg, package = "ggplot2")
my_model <- lda(cty ~ displ + year, data = mpg)
```

```{r}
detach(package:MASS)
```

## 3.9 내장 데이터셋에 접근하기

```{r}
head(pressure)
```

```{r}
# help(pressure)
```

```{r}
data()
```

```{r}
data(package = .packages(all.available = TRUE))
```

```{r}
data(Cars93, package = "MASS")
```

```{r}
data(package = "MASS")
```

## 3.10 CRAN에서 패키지 설치하기

## 3.11 GitHub에서 패키지 설치하기

```{r}
# devtools::install_github("thomasp85/tidygraph")
```

## 3.12 기본 CRAN 미러 설정 또는 변경

```{r}
options("repos")[[1]][1]
```

## 3.13 스크립트 실행

```{r}
source("hello.R")
```

```{r}
source("hello.R", echo = TRUE)
```

## 3.14 배치 스크립트 실행

```{r}
# Rscript --slave arith.R 2 3.1415
# ./arith.R 2 3.1415
```

## 3.15 R 홈 디렉토리 찾기

```{r}
Sys.getenv("R_HOME")
```

## 3.16 R 시작 사용자 지정

## 3.17 클라우드에서 R 및 RStudio 사용
