---
title: "note15"
output: html_notebook
---

# 15 간단한 프로그래밍

## 15.1 두 가지 대안 중에서 선택하기: if-else

```{r}
x <- -0.3

if (x < 0) {
  x <- 0
} else if (x > 1) {
  x <- 1
}
print(x)
```

```{r}
x <- c(-2, -1, 0, 1, 2)
if (all(x < 0)) {
  print("values are negative")
} else if (any(x < 0)) {
  print("some are negative")
}
```

## 15.2 루프로 반복하기

```{r}
for (x in 1:5) {
  cat(x, x^2, "\n")
}
```

```{r}
v <- 1:5
for (i in 1:5) {
  v[[i]] <- v[[i]]^2
}
v
```

```{r}
v <- 1:5
v <- v^2
v
```

## 15.3 함수 정의하기

```{r}
gcd <- function(a, b) {
  if (b == 0) {
    a
  } else {
    gcd(b, a %% b)
  }
}
gcd(14, 21)
```

```{r}
gcd <- function(a, b) {
  if (b == 0) {
    return(a)
  }
  gcd(b, a %% b)
}
gcd(14, 21)
```

## 15.4 지역 변수 생성

```{r}
unitInt <- function(x) {
  low <- min(x)
  high <- max(x)
  (x - low) / (high - low)
}
```

## 15.5 여러 대안 중에서 선택: 스위치

```{r}
who <- "Moe"
hair_type <- switch(who,
  Moe = "long",
  Larry = "fuzzy",
  Curly = "none"
)
hair_type
```

```{r}
s <- ""
num <- switch(s,
  one = 1,
  two = 2,
  three = 3,
  NA
)
num
```

```{r}
i <- 10
switch(as.character(i),
  "10" = "ten",
  "20" = "twenty",
  "30" = "thirty",
  "other"
)
```

## 15.6 함수 매개변수의 기본값 정의

```{r}
greet <- function(name) {
  cat("Hello,", name, "\n")
}
greet("Fred")
```

```{r}
greet <- function(name = "world") {
  cat("Hello,", name, "\n")
}
greet()
```

## 15.7 신호 오류

```{r}
balance <- 0
if (balance < 0) {
  stop("Funds exhausted.")
}
```

## 15.8 오류로부터 보호

```{r}
library(purrr)
safe_read <- possibly(read.csv, otherwise = NULL)
safe_read
```

```{r}
details <- safe_read("details.csv")
if (is.null(details)) {
  cat("Details are not available\n")
} else {
  print(details)
}
```

## 15.9 익명 함수 생성

```{r}
is_na_or_null <- function(x) {
  is.na(x) || is.null(x)
}
lst <- c(1, 2, NA, 3)
lst |>
  discard(is_na_or_null)
```

```{r}
lst |>
  discard(function(x) is.na(x) || is.null(x))
```

## 15.10 재사용 가능한 함수 모음 만들기

```{r}
# source("myLibrary.R)
```

## 15.11 코드를 자동으로 다시 들여쓰기
