---
title: "note02"
output: html_notebook
---

# 2 몇 가지 기본 사항

## 2.1 화면에 무언가 인쇄하기

```{r}
pi
sqrt(2)
```

```{r}
print(pi)
print(sqrt(2))
```

```{r}
print(matrix(c(1, 2, 3, 4), 2, 2))
```

```{r}
print(list("a", "b", "c"))
```

```{r}
cat("The zero occurs at", 2 * pi, "radians.", "\n")
```

```{r}
fib <- c(0, 1, 1, 2, 3, 5, 8, 13, 21, 34)
cat("The first few Fibonacci numbers are:", fib, "...\n")
```

## 2.2 Setting Variables

```{r}
x <- 3
y <- 4
z <- sqrt(x^2 + y^2)
print(z)
```

```{r}
x <- 3
print(x)

x <- c("fee", "fie", "foe", "fum")
print(x)
```

```{r}
x <<- 3
```

```{r}
foo <- 3
print(foo)
```

```{r}
5 -> fum
print(fum)
```

## 2.3 변수 나열

```{r}
x <- 10
y <- 50
z <- c("thee", "blind", "mice")
f <- function(n, p) sqrt(p * (1 - p) / n)
ls()
```

```{r}
ls.str()
```

```{r}
ls(all.names = TRUE)
```

## 2.4 변수 삭제

```{r}
rm(x)
#x
```

```{r}
rm(list = ls())
ls()
```

## 2.5 벡터 생성

```{r}
c(1, 1, 2, 3, 5, 8, 13, 21)
c(1 * pi, 2 * pi, 3 * pi, 4 * pi)
c("My", "twitter", "handle", "is", "@cmastication")
c(TRUE, TRUE, FALSE, TRUE)
```

```{r}
v1 <- c(1, 2, 3)
v2 <- c(4, 5, 6)
c(v1, v2)
```

```{r}
v3 <- c("A", "B", "C")
c(v1, v3)
```

```{r}
mode(3.1415)
mode("foo")
```

```{r}
mode(c(3.1415, "foo"))
```

## 2.6 기초 통계 계산

```{r}
x <- c(0, 1, 1, 2, 3, 5, 8, 13, 21, 34)
mean(x)
median(x)
sd(x)
var(x)
```

```{r}
y <- log(x + 1)
cor(x, y)
cov(x, y)
```

```{r}
x <- c(0, 1, 1, 2, 3, NA)
mean(x)
sd(x)
mean(x, na.rm = TRUE)
sd(x, na.rm = TRUE)
```

```{r}
data(cars)
purrr::map_dbl(cars, mean)
purrr::map_dbl(cars, sd)
purrr::map_dbl(cars, median)
```

```{r}
var(cars)
```

```{r}
cor(cars)
```

```{r}
cov(cars)
```

## 2.7 시퀀스 생성

```{r}
1:5
```

```{r}
seq(from = 1, to = 5, by = 2)
```

```{r}
rep(1, times = 5)
```

```{r}
0:9
10:19
9:0
```

```{r}
10:20 |> mean()
```

```{r}
seq(from = 0, to = 20)
seq(from = 0, to = 20, by = 2)
seq(from = 0, to = 20, by = 5)
```

```{r}
seq(from = 1.0, to = 2.0, length.out = 5)
```

```{r}
rep(pi, times = 5)
```

## 2.8 벡터 비교

```{r}
a <- 3
a == pi
a != pi
a < pi
a > pi
a <= pi
a >= pi
```

```{r}
v <- c(3, pi, 4)
w <- c(pi, pi, pi)
v == w
v < w
v <= w
v > w
v >= w
```

```{r}
v <- c(3, pi, 4)
v == pi
v != pi
```

```{r}
v <- c(3, pi, 4)
any(v == pi)
all(v == 0)
```

## 2.9 벡터 요소 선택

```{r}
fib <- c(0, 1, 1, 2, 3, 5, 8, 13, 21, 34)
fib
fib[1]
fib[2]
fib[3]
fib[4]
fib[5]
```

```{r}
fib[1:3]
fib[4:9]
```

```{r}
fib[c(1, 2, 4, 8)]
fib[-1]
```

```{r}
fib[1:3]
fib[-(1:3)]
```

```{r}
fib < 10
fib[fib < 10]
fib %% 2 == 0
fib[fib %% 2 == 0]
```

```{r}
v <- c(3, 6, 1, 9, 11, 16, 0, 3, 1, 45, 2, 8, 9, 6, -4)
v[v > median(v)]
```

```{r}
v[(v < quantile(v, 0.05)) | (v > quantile(v, 0.95))]
```

```{r}
v[abs(v - mean(v)) > sd(v)]
```

```{r}
v <- c(1, 2, 3, NA, 5)
v[is.na(v) & !is.null(v)]
```

```{r}
years <- c(1960, 1964, 1976, 1994)
names(years) <- c("Kennedy", "Johnson", "Carter", "Clinton")
years
```

```{r}
years["Carter"]
years["Clinton"]
```

```{r}
years[c("Carter", "Clinton")]
```

## 2.10 벡터 산술 수행

```{r}
v <- c(11, 12, 13, 14, 15)
w <- c(1, 2, 3, 4, 5)
v + w
v - w
v * w
v / w
w^v
```

```{r}
w
w + 2
w - 2
w * 2
w / 2
2^w
```

```{r}
w
mean(w)
w - mean(w)
```

```{r}
(w - mean(w)) / sd(w)
```

```{r}
w <- 1:5
w
sqrt(w)
log(w)
sin(w)
```

## 2.11 연산자 우선순위를 바로 잡기

```{r}
n <- 10
0:n - 1
```

## 2.12 타이핑을 줄이고 더 많이 달성하기

## 2.13 함수 호출 파이프라인 생성

```{r}
library(tidyverse)
data(mpg)
```

```{r}
mpg %>%
  filter(cty > 21) %>%
  head(3) %>%
  print()
```

```{r}
temp1 <- filter(mpg, cty > 21)
temp2 <- head(temp1, 3)
print(temp2)
```

```{r}
filtered_mpg <- filter(mpg, cty > 21)
selected_mpg <- select(filtered_mpg, cty, hwy)
ggplot(selected_mpg, aes(cty, hwy)) +
  geom_point()
```

```{r}
ggplot(select(filter(mpg, cty > 21), cty, hwy), aes(cty, hwy)) +
  geom_point()
```

```{r}
mpg %>%
  filter(cty > 21) %>%
  select(cty, hwy) %>%
  ggplot(aes(cty, hwy)) +
  geom_point()
```

```{r}
iris %>% head(3)
```

## 2.14 몇 가지 일반적인 실수 피하기

```{r}
ls
```

```{r}
x <- pi
x < -pi
```

```{r}
total <- 1 + 2 + 3
+4 + 5
total
```

```{r}
v <- 1
v == 0
v <- 0
print(v)
```

```{r}
n <- 5
1:n + 1
1:(n + 1)
```

```{r}
x <- rnorm(100)
n <- 5
MASS::truehist(x, n)
```
