---
title: "note09"
output: html_notebook
---

# 9 Functionals

## 9.1 Introduction

```{r}
randomise <- function(f) f(runif(1e3))
randomise(mean)
randomise(mean)
randomise(sum)
```

```{r}
library(purrr)
```

## 9.2 My first functional: map()

```{r}
triple <- function(x) x * 3
map(1:3, triple)
```

```{r}
map_chr(mtcars, typeof)
```

```{r}
map_lgl(mtcars, is.double)
```

```{r}
n_unique <- function(x) length(unique(x))
map_int(mtcars, n_unique)
```

```{r}
map_dbl(mtcars, mean)
```

```{r}
pair <- function(x) c(x, x)
try(map_dbl(1:2, pair))
```

```{r}
try(map_dbl(1:2, as.character))
```

```{r}
map_dbl(mtcars, function(x) length(unique(x)))
```

```{r}
map_dbl(mtcars, ~ length(unique(.x)))
```

```{r}
as_mapper(~ length(unique(.x)))
```

```{r}
x <- map(1:3, ~ runif(2))
str(x)
```

```{r}
x <- list(
  list(-1, x = 1, y = c(2), z = "a"),
  list(-2, x = 4, y = c(5, 6), z = "a"),
  list(-3, x = 8, y = c(9, 10, 11))
)
```

```{r}
map_dbl(x, "x")
```

```{r}
map_dbl(x, 1)
```

```{r}
map_dbl(x, list("y", 1))
```

```{r}
map_chr(x, "z", .default = NA)
```

```{r}
x <- list(1:5, c(1:10, NA))
map_dbl(x, ~ mean(.x, na.rm = TRUE))
```

```{r}
map_dbl(x, mean, na.rm = TRUE)
```

```{r}
plus <- function(x, y) x + y

x <- c(0, 0, 0, 0)
map_dbl(x, plus, runif(1))
```

```{r}
map_dbl(x, ~ plus(.x, runif(1)))
```

```{r}
bootstrap_summary <- function(x, f) {
  f(sample(x, replace = TRUE))
}
# simple_map(mtcars, bootstrap_summary, f = mean)
```

```{r}
trims <- c(0, 0.1, 0.2, 0.5)
x <- rcauchy(1000)
```

```{r}
map_dbl(trims, ~ mean(x, trim = .x))
```

```{r}
map_dbl(trims, function(trim) mean(x, trim = trim))
```

```{r}
map_dbl(trims, mean, x = x)
```

```{r}
as_mapper(c(1, 2))
```

```{r}
as_mapper(c("a", "b"))
```

```{r}
as_mapper(list(1, "b"))
```

```{r}
map(mtcars, as_mapper(1))
```

```{r}
get_class <- function(x) attr(x, "class")
pluck(mtcars, get_class)
```

```{r}
pluck(mtcars, attr_getter("class"))
```

```{r}
as_mapper(~ unif(2))
```

```{r}
map(1:3, ~ runif(2))
```

```{r}
map(1:3, runif(2))
```

```{r}
map_dbl(mtcars, sd)
```

```{r}
penguins <- palmerpenguins::penguins

penguins_numeric <- map_lgl(penguins, is.numeric)
map_dbl(penguins[penguins_numeric], sd, na.rm = TRUE)
```

```{r}
penguis_factor <- map_lgl(penguins, is.factor)
map_int(penguins[penguis_factor], ~ length(levels(.x)))
```

```{r}
trials <- map(1:100, ~ t.test(rpois(10, 10), rpois(10, 7)))
```

```{r}
library(ggplot2)

df_trials <- tibble::tibble(p_value = map_dbl(trials, "p.value"))
df_trials
```

```{r}
df_trials %>%
  ggplot(aes(x = p_value, fill = p_value < 0.05)) +
  geom_dotplot(binwidth = .01) +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.position = "top"
  )
```

```{r}
x <- list(
  list(1, c(3, 9)),
  list(c(3, 6), 7, c(4, 7, 6))
)

triple <- function(x) x * 3
try(map(x, map, .f = triple))
```

```{r}
map(x, map, triple)
```

```{r}
map(x, . %>% map(triple))
```

```{r}
map(x, function(l) map(l, triple))
```

```{r}
map(x, ~ map(.x, triple))
```

```{r}
formulas <- list(
  mpg ~ disp,
  mpg ~ I(1 / disp),
  mpg ~ disp + wt,
  mpg ~ I(1 / disp) + wt
)

map(formulas, lm, data = mtcars)
```

```{r}
bootstrap <- function(df) {
  df[sample(nrow(df), replace = TRUE), , drop = FALSE]
}

bootstraps <- map(1:10, ~ bootstrap(mtcars))
```

```{r}
bootstraps %>%
  map(~ lm(mpg ~ disp, data = .x)) %>%
  map(summary) %>%
  map_dbl("r.squared")
```

## 9.3 Purrr style

```{r}
by_cyl <- split(mtcars, mtcars$cyl)
by_cyl
```

```{r}
by_cyl %>%
  map(~ lm(mpg ~ wt, data = .x)) %>%
  map(coef) %>%
  map_dbl(2)
```

```{r}
by_cyl %>%
  lapply(function(data) lm(mpg ~ wt, data = data)) |>
  lapply(coef) |>
  vapply(function(x) x[[2]], double(1))
```

```{r}
models <- lapply(by_cyl, function(data) lm(mpg ~ wt, data = data))
vapply(models, function(x) coef(x)[[2]], double(1))
```

```{r}
slopes <- double(length(by_cyl))
for (i in seq_along(by_cyl)) {
  model <- lm(mpg ~ wt, data = by_cyl[[i]])
  slopes[[i]] <- coef(model)[[2]]
}
slopes
```

## 9.4 Map variants

```{r}
df <- data.frame(
  x = 1:3,
  y = 6:4
)
map(df, ~ .x * 2)
```

```{r}
df2 <- modify(df, ~ .x * 2)
df2
```

```{r}
simple_modify <- function(x, f, ...) {
  for (i in seq_along(x)) {
    x[[i]] <- f(x[[i]], ...)
  }
}
```

```{r}
xs <- map(1:8, ~ runif(10))
xs[[1]][[1]] <- NA
xs
```

```{r}
ws <- map(1:8, ~ rpois(10, 5) + 1)
ws
```

```{r}
map_dbl(xs, mean, na.rm = TRUE)
```

```{r}
map2_dbl(xs, ws, weighted.mean, na.rm = TRUE)
```

```{r}
simple_map2 <- function(x, y, f, ...) {
  out <- vecotr("list", length(x))
  for (i in seq_along(x)) {
    out[[i]] <- f(x[[i]], y[[i]], ...)
  }
  out
}
```

```{r}
welcome <- function(x) {
  cat("Welcome ", x, "!\n", sep = "")
}
names <- c("Hadley", "Jenny")
walk(names, welcome)
```

```{r}
temp <- tempfile()
dir.create(temp)

cyls <- split(mtcars, mtcars$cyl)
paths <- file.path(temp, paste0("cyl-", names(cyls), ".csv"))
walk2(cyls, paths, write.csv)

dir(temp)
```

```{r}
imap_chr(iris, ~ paste0("The first value of ", .y, " is ", .x[[1]]))
```

```{r}
x <- map(1:6, ~ sample(1000, 10))
imap_chr(x, ~ paste0("The highest value of ", .y, " is ", max(.x)))
```

```{r}
pmap_dbl(list(xs, ws), weighted.mean, na.rm = TRUE)
```

```{r}
trims <- c(0, 0.1, 0.2, 0.5)
x <- rcauchy(1000)

pmap_dbl(list(trim = trims), mean, x = x)
```

```{r}
params <- tibble::tribble(
  ~n, ~min, ~max,
  1L, 0, 1,
  2L, 10, 100,
  3L, 100, 1000
)
params
```

```{r}
pmap(params, runif)
```

```{r}
modify(mtcars, 1)
```

```{r}
cyls <- split(mtcars, mtcars$cyl)
paths <- file.path(temp, paste0("cyl-", names(cyls), ".csv"))
walk2(cyls, paths, write.csv)
```

```{r}
temp <- tempfile()
dir.create(temp)

cyls <- split(mtcars, mtcars$cyl)
names(cyls) <- file.path(temp, paste0("cyl-", names(cyls), ".csv"))
iwalk(cyls, ~ write.csv(.x, .y))
```

```{r}
mtcars %>%
  split(mtcars$cyl) %>%
  set_names(~ file.path(temp, paste0("cyl-", .x, ".csv"))) %>%
  iwalk(~ write.csv(.x, .y))
```

```{r}
trans <- list(
  disp = function(x) x * 0.0163871,
  am = function(x) factor(x, labels = c("auto", "manual"))
)
nm <- names(trans)
mtcars[nm] <- map(nm, ~ trans[[.x]](mtcars[[.x]]))
mtcars
```

```{r}
map2(trans, mtcars[nm], function(f, var) f(var))
```

## 9.5 Reduce family

```{r}
l <- map(1:4, ~ sample(1:10, 15, replace = T))
str(l)
```

```{r}
out <- l[[1]]
out <- intersect(out, l[[2]])
out <- intersect(out, l[[3]])
out <- intersect(out, l[[4]])
out
```

```{r}
reduce(l, intersect)
```

```{r}
simple_reduce <- function(x, f) {
  out <- x[[1]]
  for (i in seq(2, length(x))) {
    out <- f(out, x[[i]])
  }
  out
}
```

```{r}
accumulate(l, intersect)
```

```{r}
x <- c(4, 3, 10)
reduce(x, `+`)
```

```{r}
accumulate(x, `+`)
```

```{r}
reduce(1, `+`)
```

```{r}
reduce("a", `+`)
```

```{r}
reduce(integer(), `+`, .init = 0)
```

```{r}
try(reduce("a", `+`, .init = 0))
```

## 9.6 Predicate functionals

```{r}
df <- data.frame(x = 1:3, y = c("a", "b", "c"))
detect(df, is.factor)
detect_index(df, is.factor)
```

```{r}
str(keep(df, is.factor))
```

```{r}
str(discard(df, is.factor))
```

```{r}
df <- data.frame(
  num1 = c(0, 10, 20),
  num2 = c(5, 6, 7),
  chr1 = c("a", "b", "c"),
  stringsAsFactors = FALSE
)
df
```

```{r}
map_if(df, is.numeric, mean)
```

```{r}
str(modify_if(df, is.numeric, mean))
```

```{r}
str(map(keep(df, is.numeric), mean))
```

```{r}
simple_reduce <- function(x, f, default) {
  if (length(x) == 0L) {
    return(default)
  }
  if (length(x) == 1L) {
    return(x[[1L]])
  }

  out <- x[[1]]
  for (i in seq(2, length(x))) {
    out <- f(out, x[[i]])
  }
  out
}

simple_reduce(integer(0), `+`, default = 0)
simple_reduce(integer(0), `+`, default = 0L)
simple_reduce(1, `+`)
simple_reduce(1:3, `+`)
```

```{r}
span_r <- function(x, f) {
  idx <- unname(map_lgl(x, ~ f(.x)))
  rle <- rle(idx)

  if (!any(rle$values)) {
    return(integer(0))
  }
  longest <- max(rle$lengths[rle$values])
  longest_idx <- which(rle$values & rle$lengths == longest)[1]

  ind_before_longest <- sum(rle$lengths[seq_len(longest_idx - 1)])

  out_start <- ind_before_longest + 1L
  out_end <- ind_before_longest + longest
  out_start:out_end
}

span_r(c(0, 0, 0, 0, 0), is.na)
span_r(c(NA, 0, 0, 0, 0), is.na)
span_r(c(NA, 0, NA, NA, NA), is.na)
```

```{r}
arg_max <- function(x, f) {
  y <- map_dbl(x, f)
  x[y == max(y)]
}

arg_min <- function(x, f) {
  y <- map_dbl(x, f)
  x[y == min(y)]
}

arg_max(-5:5, function(x) x^2)
arg_min(-5:5, function(x) x^2)
```

```{r}
scale01 <- function(x) {
  rng <- range(x, na.rm = TRUE)
  (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
modify_if(mtcars, is.numeric, scale01)
```

```{r}
mtcars |>
  keep(is.numeric) |>
  map_dfr(scale01)
```

## 9.7 Base functionals

```{r}
a2d <- matrix(1:20, nrow = 5)
a2d
```

```{r}
apply(a2d, 1, mean)
```

```{r}
apply(a2d, 2, mean)
```

```{r}
a3d <- array(1:24, c(2, 3, 4))
apply(a3d, 1, mean)
apply(a3d, c(1, 2), mean)
```

```{r}
a1 <- apply(a2d, 1, identity)
identical(a2d, a1)
#> [1] FALSE

a2 <- apply(a2d, 2, identity)
identical(a2d, a2)
#> [1] TRUE
```

```{r}
integrate(sin, 0, pi)
```

```{r}
str(uniroot(sin, pi * c(1 / 2, 3 / 2)))
```

```{r}
str(optimize(sin, c(0, 2 * pi)))
```

```{r}
str(optimize(sin, c(0, pi), maximum = TRUE))
```

```{r}
fixed_point <- function(f, x_init, n_max = 10000, tol = 0.0001) {
  n <- 0
  x <- x_init
  y <- f(x)

  is_fixed_point <- function(x, y) {
    abs(x - y) < tol
  }

  while (!is_fixed_point(x, y)) {
    x <- y
    y <- f(y)

    # Make sure we eventually stop
    n <- n + 1
    if (n > n_max) {
      stop("Failed to converge.", call. = FALSE)
    }
  }

  x
}
```

```{r}
# Functions with fixed points
fixed_point(sin, x_init = 1)
fixed_point(cos, x_init = 1)
```

```{r}
# Functions without fixed points
add_one <- function(x) x + 1
try(fixed_point(add_one, x_init = 1))
```
