---
title: "note14"
output: html_notebook
---

# 14 R6

## 14.1 Introduction

```{r}
library(R6)
```

## 14.2 Classes and methods

```{r}
Accumulator <- R6Class("Accumulator", list(
  sum = 0,
  add = function(x = 1) {
    self$sum <- self$sum + x
    invisible(self)
  }
))
Accumulator
```

```{r}
x <- Accumulator$new()
x$add(4)
x$sum
```

```{r}
x$add(10)$add(10)$sum
```

```{r}
Person <- R6Class("Person", list(
  name = NULL,
  age = NA,
  initialize = function(name, age = NA) {
    stopifnot(is.character(name), length(name) == 1)
    stopifnot(is.numeric(age), length(age) == 1)

    self$name <- name
    self$age <- age
  }
))

try(hadley <- Person$new("Hadley", age = "thirty-eight"))
hadley <- Person$new("Hadley", age = 38)
hadley
```

```{r}
Person <- R6Class("Person", list(
  name = NULL,
  age = NA,
  initialize = function(name, age = NA) {
    stopifnot(is.character(name), length(name) == 1)
    stopifnot(is.numeric(age), length(age) == 1)

    self$name <- name
    self$age <- age
  },
  print = function(...) {
    cat("Person: \n")
    cat("  Name: ", self$name, "\n", sep = "")
    cat("  Age: ", self$age, "\n", sep = "")
    invisible(self)
  }
))

hadley2 <- Person$new("Hadley", age = 38)
hadley2
```

```{r}
hadley
```

```{r}
hadley2
```

```{r}
Accumulator <- R6Class("Accumulator")
Accumulator$set("public", "sum", 0)
Accumulator$set("public", "add", function(x = 1) {
  self$sum <- self$sum + x
  invisible(self)
})
```

```{r}
AccumulatorChatty <- R6Class(
  "AccumulatorChatty",
  inherit = Accumulator,
  public = list(
    add = function(x = 1) {
      cat("Adding ", x, "\n", sep = "")
      super$add(x = x)
    }
  )
)
x2 <- AccumulatorChatty$new()
x2$add(10)$add(1)$sum
```

```{r}
class(hadley2)
```

```{r}
names(hadley2)
```

```{r}
BankAccount <- R6Class(
  classname = "BankAccount",
  public = list(
    balance = 0,
    deposit = function(dep = 0) {
      self$balance <- self$balance + dep
      invisible(self)
    },
    withdraw = function(draw) {
      self$balance <- self$balance - draw
      invisible(self)
    }
  )
)

my_account <- BankAccount$new()
my_account$balance
my_account$
  deposit(5)$
  withdraw(15)$
  balance
```

```{r}
BankAccountStrict <- R6Class(
  classname = "BankAccountStrict",
  inherit = BankAccount,
  public = list(
    withdraw = function(draw = 0) {
      if (self$balance - draw < 0) {
        stop("Your `withdraw` must be smaller ",
          "than your `balace`.",
          call. = FALSE
        )
      }
      super$withdraw(draw = draw)
    }
  )
)

my_strict_account <- BankAccountStrict$new()
my_strict_account$balance
try(my_strict_account$
  deposit(5)$
  withdraw(15))
my_strict_account$balance
```

```{r}
BankAccountCharging <- R6Class(
  classname = "BankAccountCharging",
  inherit = BankAccount,
  public = list(
    withdraw = function(draw = 0) {
      if (self$balance - draw < 0) {
        draw <- draw + 1
      }
      super$withdraw(draw = draw)
    }
  )
)

my_charging_account <- BankAccountCharging$new()
my_charging_account$balance

my_charging_account$
  deposit(5)$
  withdraw(15)$
  withdraw(0)$balance
```

```{r}
suit <- c("SPADE", "HEARTS", "DIAMOND", "CLUB")
value <- c("A", 2:10, "J", "Q", "K")
cards <- paste(rep(value, 4), suit)
cards
```

```{r}
ShuffledDeck <- R6Class(
  classname = "ShuffledDeck",
  public = list(
    deck = NULL,
    initialize = function(deck = cards) {
      self$deck <- sample(deck)
    },
    reshuffle = function() {
      self$deck <- sample(cards)
      invisible(self)
    },
    n = function() {
      length(self$deck)
    },
    draw = function(n = 1) {
      if (n > self$n()) {
        stop("Only ", self$n(), " cards remaining.", call. = FALSE)
      }
      output <- self$deck[seq_len(n)]
      self$deck <- self$deck[-seq_len(n)]
      output
    }
  )
)

my_deck <- ShuffledDeck$new()

my_deck$draw(52)
try(my_deck$draw(10))
```

```{r}
my_deck$reshuffle()$draw(5)
my_deck$reshuffle()$draw(5)
```

```{r}
Timezone <- R6Class(
  classname = "Timezone",
  public = list(
    get = function() {
      Sys.timezone()
    },
    set = function(value) {
      stopifnot(value %in% OlsonNames())

      old <- self$get()
      Sys.setenv(TZ = value)
      invisible(old)
    }
  )
)

# tz <- Timezone$new()
# old <- tz$set("Antarctica/South_Pole")
# tz$get()
# tz$set(old)
# tz$get()
```

```{r}
WorkingDirectory <- R6Class(
  classname = "WorkingDirectory",
  public = list(
    get = function() {
      getwd()
    },
    set = function(value) {
      setwd(value)
    }
  )
)

wd <- WorkingDirectory$new()
wd$get()
# wd$set("~")
# wd$get()
```

## 14.3 Controlling access

```{r}
Person <- R6Class(
  "Person",
  public = list(
    initialize = function(name, age = NA) {
      private$name <- name
      private$age <- age
    },
    print = function(...) {
      cat("Person: \n")
      cat("  Name: ", private$name, "\n", sep = "")
      cat("  Age:  ", private$age, "\n", sep = "")
    }
  ),
  private = list(
    age = NA,
    name = NULL
  )
)

hadley3 <- Person$new("Hadley")
hadley3
hadley3$name
```

```{r}
Rando <- R6Class("Rando", active = list(
  random = function(value) {
    if (missing(value)) {
      runif(1)
    } else {
      stop("Can't set `$random`", call. = FALSE)
    }
  }
))
x <- Rando$new()
x$random
x$random
x$random
```

```{r}
Person <- R6Class(
  "Person",
  private = list(
    .age = NA,
    .name = NULL
  ),
  active = list(
    age = function(value) {
      if (missing(value)) {
        private$.age
      } else {
        stop("`$age` is read only", call. = FALSE)
      }
    },
    name = function(value) {
      if (missing(value)) {
        private$.name
      } else {
        stopifnot(is.character(value), length(value) == 1)
        private$.name <- value
        self
      }
    }
  ),
  public = list(
    initialize = function(name, age = NA) {
      private$.name <- name
      private$.age <- age
    }
  )
)

hadley4 <- Person$new("Hadley", age = 38)
hadley4$name
try(hadley4$name <- 10)
try(hadley4$age <- 20)
hadley4$age
```

```{r}
BankAccountStrict2 <- R6Class(
  "BankAccountStrict2",
  public = list(
    deposit = function(dep = 0) {
      private$balance <- private$balance + dep
      invisible(self)
    },
    withdraw = function(draw = 0) {
      if (private$balance - draw < 0) {
        stop(
          "Your `withdraw` must be smaller than your `balance`.",
          call. = FALSE
        )
      }
      private$balance <- private$balance - draw
      invisible(self)
    }
  ),
  private = list(
    balance = 0
  )
)
my_account_strict_2 <- BankAccountStrict2$new()
my_account_strict_2$deposit(5)
try(my_account_strict_2$withdraw(10))
my_account_strict_2$balance
```

```{r}
Password <- R6Class(
  "Password",
  public = list(
    print = function(...) {
      cat("<Password>: ********\n")
      invisible(self)
    },
    set = function(value) {
      private$password <- value
    },
    check = function(password) {
      identical(password, private$password)
    }
  ),
  private = list(password = NULL)
)

my_pw <- Password$new()
my_pw$set("snuffles")
my_pw$password
my_pw
my_pw$check("snuggles")
my_pw$check("snuffles")
str(my_pw)
```

```{r}
Rando <- R6::R6Class(
  classname = "Rando",
  private = list(
    last_random = NULL
  ),
  active = list(
    random = function(value) {
      if (missing(value)) {
        private$last_random <- runif(1)
        private$last_random
      } else {
        stop("Can't set `$random`.", call. = FALSE)
      }
    },
    previous = function(value) {
      if (missing(value)) {
        private$last_random
      }
    }
  )
)

x <- Rando$new()
x$random
x$random
x$previous
```

```{r}
A <- R6Class(
  "A",
  private = list(
    field = "foo",
    method = function() {
      "bar"
    }
  )
)

B <- R6Class(
  "B",
  inherit = A,
  public = list(
    test = function() {
      cat("Field:  ", super$field, "\n", sep = "")
      cat("Method: ", super$method(), "\n", sep = "")
    }
  )
)

B$new()$test()
```

## 14.4 Reference semantics

```{r}
y1 <- Accumulator$new()
y2 <- y1
y1$add(10)
c(y1 = y1$sum, y2 = y2$sum)
```

```{r}
y1 <- Accumulator$new()
y2 <- y1$clone()

y1$add(10)
c(y1 = y1$sum, y2 = y2$sum)
```

```{r}
TemporaryFile <- R6Class("TemporaryFile", list(
  path = NULL,
  initialize = function() {
    self$path <- tempfile()
  },
  finalize = function() {
    cat("Cleaning up ", self$path)
    unlink(self$path)
  }
))
tf <- TemporaryFile$new()
rm(tf)
```

## 14.5 Why R6?
