---
title: "note08"
output: html_notebook
---

# 8 Conditions

## 8.1 Introduction

```{r}
library(rlang)
```

## 8.2 Signalling conditions

```{r}
try(stop("This is what an error look like"))
```

```{r}
warning("This is what a warning looks like")
```

```{r}
message("This is what a message look like")
```

```{r}
f <- function() g()
g <- function() h()
h <- function() stop("This is an error!", call. = FALSE)
try(f())
```

```{r}
# options(warn = 0)
fw <- function() {
  cat("1\n")
  warning("W1")
  cat("2\n")
  warning("W2")
  cat("3\n")
  warning("W3")
}
fw()
```

```{r}
formals(1)
```

```{r}
file.remove("this-file-doesn't-exist")
```

```{r}
lag(1:3, k = 1.5)
```

```{r}
as.numeric(c("18", "30", "50+", "345,678"))
```

```{r}
fm <- function() {
  cat("1\n")
  message("M1")
  cat("2\n")
  message("M2")
  cat("3\n")
  message("M3")
}

fm()
```

```{r}
file.remove_strict <- function(path) {
  if (!file.exists(path)) {
    stop("Can't delete the file \"", path, "\" because it doesn't exist.",
      call. = FALSE
    )
  }
  file.remove(path)
}
try(file.remove_strict("mtcars.rds"))
```

```{r}
multiline_msg <- function(appendLF = TRUE) {
  message("first", appendLF = appendLF)
  message("second", appendLF = appendLF)
  cat("third")
  cat("fourth")
}
multiline_msg(appendLF = TRUE)
```

```{r}
multiline_msg(appendLF = FALSE)
```

## 8.3 Ignoring conditions

```{r}
f1 <- function(x) {
  try(log(x))
  10
}
f1("x")
```

```{r}
default <- NULL
try(default <- read.csv("possibly-bad-input.csv"), silent = TRUE)
default
```

```{r}
suppressWarnings({
  warning("Uhoh!")
  warning("Another warning")
  1
})
```

```{r}
suppressMessages({
  message("Hello there")
  2
})
```

```{r}
suppressWarnings({
  message("you can still see me")
  3
})
```

## 8.4 Handling conditions

```{r}
cnd <- catch_cnd(stop("An error"))
str(cnd)
```

```{r}
conditionMessage(cnd)
```

```{r}
conditionCall(cnd)
```

```{r}
f3 <- function(x) {
  tryCatch(
    error = function(cnd) NA,
    log(x)
  )
}
f3("x")
```

```{r}
tryCatch(
  error = function(cnd) 10,
  1 + 1
)
```

```{r}
tryCatch(
  error = function(cnd) 10,
  {
    message("Hi!")
    1 + 1
  }
)
```

```{r}
tryCatch(
  error = function(cnd) "error",
  message = function(cnd) "There",
  warning = function(cnd) "There warning",
  {
    message("Here")
    warning("test")
    stop("This code is never run!")
  }
)
```

```{r}
tryCatch(
  error = function(cnd) {
    paste0("--", conditionMessage(cnd), "--")
  },
  stop("This is an error")
)
```

```{r}
path <- tempfile()
tryCatch(
  {
    writeLines("Hi!", path)
  },
  finally = {
    unlink(path)
  }
)
```

```{r}
tryCatch(
  message = function(cnd) cat("Caught a message!\n"),
  {
    message("Someone there?")
    message("Why, yes!")
  }
)
```

```{r}
withCallingHandlers(
  message = function(cnd) cat("Caught a message!\n"),
  {
    message("Someone there?")
    message("Why, yes!")
  }
)
```

```{r}
withCallingHandlers(
  message = function(cnd) message("Second message"),
  message("Fist message")
)
```

```{r}
withCallingHandlers(
  message = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    message = function(cnd) cat("Level 1\n"),
    message("Hello")
  )
)
```

```{r}
tryCatch(
  message = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    message = function(cnd) cat("Level 1\n"),
    message("Hello")
  )
)
```

```{r}
withCallingHandlers(
  message = function(cnd) {
    cat("Level 2\n")
    cnd_muffle(cnd)
  },
  withCallingHandlers(
    message = function(cnd) cat("Level 1\n"),
    message("Hello")
  )
)
```

```{r}
withCallingHandlers(
  message = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    message = function(cnd) {
      cat("Level 1\n")
      cnd_muffle(cnd)
    },
    message("Hello")
  )
)
```

```{r}
f <- function() g()
g <- function() h()
h <- function() message("!")
```

```{r}
withCallingHandlers(f(), message = function(cnd) {
  lobstr::cst()
  cnd_muffle(cnd)
})
```

```{r}
tryCatch(f(), message = function(cnd) lobstr::cst())
```

```{r}
catch_cnd(stop("An error"))
```

```{r}
catch_cnd(abort("An error"))
```

```{r}
str(catch_cnd(stop("An error")))
```

```{r}
str(catch_cnd(abort("An error")))
```

```{r}
show_condition <- function(code) {
  tryCatch(
    error = function(cnd) "error",
    warning = function(cnd) "warning",
    message = function(cnd) "message",
    {
      code
      NULL
    }
  )
}
```

```{r}
show_condition(stop("!"))
show_condition(10)
show_condition(warning("?!"))
show_condition({
  10
  message("?")
  warning("?!")
})
```

```{r}
withCallingHandlers( # (1)
  message = function(cnd) message("b"),
  withCallingHandlers( # (2)
    message = function(cnd) message("a"),
    message("c")
  )
)
```

```{r}
show_condition2 <- function(code) {
  tryCatch(
    condition = function(cnd) {
      if (inherits(cnd, "error")) {
        return("error")
      }
      if (inherits(cnd, "warning")) {
        return("warning")
      }
      if (inherits(cnd, "message")) {
        return("message")
      }
    },
    {
      code
      NULL
    }
  )
}
```

```{r}
show_condition2(stop("!"))
show_condition2(10)
show_condition2(warning("?!"))
show_condition2({
  10
  message("?")
  warning("?!")
})
```

## 8.5 Custom conditions

```{r}
try(abort(
  "error_not_found",
  message = "Path `blah.csv` not found",
  path = "blah.csv"
))
```

```{r}
try(log(letters))
```

```{r}
try(log(1:10, base = letters))
```

```{r}
my_log <- function(x, base = exp(1)) {
  if (!is.numeric(x)) {
    abort(paste0(
      "`x` must be a numeric vecotr; not ", typeof(x), "."
    ))
  }
  if (!is.numeric(base)) {
    abort(paste0(
      "`base` must be a numeric vector; not ", typeof(base), "."
    ))
  }
  base::log(x, base = base)
}
```

```{r}
try(my_log(letters))
```

```{r}
try(my_log(1:10, base = letters))
```

```{r}
abort_bad_argument <- function(arg, must, not = NULL) {
  msg <- glue::glue("`{arg}` must {must}")
  if (!is.null(not)) {
    not <- typeof(not)
    msg <- glue::glue("{msg}; not {not}.")
  }

  abort("error_bad_argument",
    message = msg,
    arg = arg,
    must = must,
    not = not
  )
}
```

```{r}
stop_custum <- function(.subclass, message, call = NULL, ...) {
  err <- structure(
    list(
      message = message,
      call = call,
      ...,
    ),
    class = c(.subsclass, "error", "condition")
  )
  stop(err)
}

err <- catch_cnd(
  stop_custom("error_new", "This is a custom error", x = 10)
)
class(err)
err$x
```

```{r}
my_log <- function(x, base = exp(1)) {
  if (!is.numeric(x)) {
    abort_bad_argument("x", must = "be numeric", not = x)
  }
  if (!is.numeric(base)) {
    abort_bad_argument("base", must = "be numeric", not = base)
  }
  base::log(x, base = base)
}
```

```{r}
try(my_log(letters))
```

```{r}
try(my_log(1:10, base = letters))
```

```{r}
library(testthat)
err <- catch_cnd(my_log("a"))
expect_s3_class(err, "error_bad_argument")
expect_equal(err$arg, "x")
expect_equal(err$not, "character")
```

```{r}
tryCatch(
  error_bad_argument = function(cnd) "bad_argument",
  error = function(cnd) "other error",
  my_log("a")
)
#> [1] "bad_argument"
```

```{r}
tryCatch(
  error = function(cnd) "other error",
  error_bad_argument = function(cnd) "bad_argument",
  my_log("a")
)
```

## 8.6 Applications

```{r}
fail_with <- function(expr, value = NULL) {
  tryCatch(
    error = function(cnd) value,
    expr
  )
}
fail_with(log(10), NA_real_)
fail_with(log("x"), NA_real_)
```

```{r}
try2 <- function(expr, silent = FALSE) {
  tryCatch(
    error = function(cnd) {
      msg <- conditionMessage(cnd)
      if (!silent) {
        message("Error: ", msg)
      }
      structure(msg, class = "try-error")
    },
    expr
  )
}
try2(1)
```

```{r}
try2(stop("Hi"))
```

```{r}
try2(stop("hi"), silent = TRUE)
```

```{r}
foo <- function(expr) {
  tryCatch(
    error = function(cnd) error_val,
    {
      expr
      success_val
    }
  )
}
```

```{r}
does_error <- function(expr) {
  tryCatch(
    error = function(cnd) TRUE,
    {
      expr
      FALSE
    }
  )
}
```

```{r}
catch_cnd <- function(expr) {
  tryCatch(
    condition = function(cnd) cnd,
    {
      expr
      NULL
    }
  )
}
```

```{r}
safety <- function(expr) {
  tryCatch(
    error = function(cnd) {
      list(result = NULL, error = cnd)
    },
    list(result = expr, error = NULL)
  )
}

str(safety(1 + 10))
```

```{r}
str(safety(stop("Error!")))
```

```{r}
warning2error <- function(expr) {
  withCallingHandlers(
    warning = function(cnd) abort(conditionMessage(cnd)),
    expr
  )
}
try(warning2error({
  x <- 2^4
  warn("Hello")
}))
```

```{r}
catch_cnds <- function(expr) {
  conds <- list()
  add_cond <- function(cnd) {
    conds <<- append(conds, list(cnd))
    cnd_muffle(cnd)
  }
  withCallingHandlers(
    message = add_cond,
    warning = add_cond,
    expr
  )
  conds
}
```

```{r}
catch_cnds({
  inform("a")
  warn("b")
  inform("c")
})
```

```{r}
catch_cnds <- function(expr) {
  conds <- list()
  add_cond <- function(cnd) {
    conds <<- append(conds, list(cnd))
    cnd_muffle(cnd)
  }

  tryCatch(
    error = function(cnd) {
      conds <<- append(conds, list(cnd))
    },
    withCallingHandlers(
      message = add_cond,
      warning = add_cond,
      expr
    )
  )
  conds
}
```

```{r}
catch_cnds({
  inform("a")
  warn("b")
  abort("C")
})
```

```{r}
log <- function(message, level = c("info", "error", "fatal")) {
  level <- match.arg(level)
  signal(message, "log", level = level)
}
log("This code was run")
```

```{r}
record_log <- function(expr, path = stdout()) {
  withCallingHandlers(
    log = function(cnd) {
      cat(
        "[", cnd$level, "] ", cnd$message, "\n",
        sep = "",
        file = path, append = TRUE
      )
    },
    expr
  )
}

record_log(log("Hello"))
```

```{r}
ignore_log_levels <- function(expr, levels) {
  withCallingHandlers(
    log = function(cnd) {
      if (cnd$level %in% levels) {
        cnd_muffle(cnd)
      }
    },
    expr
  )
}

record_log(ignore_log_levels(log("Hello"), "info"))
```

```{r}
suppressErrors <- function(expr) {
  tryCatch(
    error = function(cnd) invisible(cnd),
    interrupt = function(cnd) {
      stop("Terminated by the user.",
        call. = FALSE
      )
    },
    expr
  )
}
```

```{r}
suppressConditions <- function(expr) {
  suppressErrors(suppressWarnings(suppressMessages(expr)))
}
```

```{r}
# The messages/warnings/conditions are suppressed successfully
error_obj <- suppressConditions({
  message("message")
  warning("warning")
  abort("error")
})

error_obj
#> <error/rlang_error>
#> error
#> Backtrace:
#>   1. global::suppressConditions(...)
#>  12. base::suppressMessages(expr)
#>  13. base::withCallingHandlers(...)
```

```{r}
message2error1 <- function(code) {
  withCallingHandlers(code, message = function(e) stop("error"))
}

try(message2error1({
  1
  message("hidden error")
  NULL
}))
```

```{r}
message2error2 <- function(code) {
  tryCatch(code, message = function(e) (stop("error")))
}

try(message2error2({
  1
  stop("hidden error")
  NULL
}))
```

```{r}
catch_cnds <- function(expr) {
  conds <- list()
  add_cond <- function(cnd) {
    conds <<- append(conds, list(cnd))
    cnd_muffle(cnd)
  }

  tryCatch(
    error = function(cnd) {
      conds <<- append(conds, list(cnd))
    },
    withCallingHandlers(
      message = add_cond,
      warning = add_cond,
      expr
    )
  )

  conds
}

# Test
catch_cnds({
  inform("message a")
  warn("warning b")
  inform("message c")
})
```

```{r}
bottles_of_beer <- function(i = 99) {
  message(
    "There are ", i,
    " bottles of beer on the wall, ", i,
    " bottles of beer."
  )
  while (i > 0) {
    tryCatch(
      Sys.sleep(1),
      interrupt = function(err) {
        i <<- i - 1
        if (i > 0) {
          message(
            "Take one down, pass it around, ", i,
            " bottle", if (i > 1) "s", " of beer on the wall."
          )
        }
      }
    )
  }
  message(
    "No more bottles of beer on the wall, ",
    "no more bottles of beer."
  )
}
# bottles_of_beer()
```

## 8.7 Quiz answers
