---
title: "note05"
output: html_notebook
---

```{r}
library(nlme)
options(
  width = 65,
  ## reduce platform dependence in printed output when testing
  digits = if (nzchar(Sys.getenv("R_TESTS"))) 3 else 5
)
```

# 5 Extending the Basic Linear Mixed-Effects Model

## 5.1 General Formulation of the Extended Model

## 5.2 Variance Functions for Modeling Heteroscedasticity

```{r}
vf1Fixed <- varFixed(~age)
vf1Fixed <- Initialize(vf1Fixed, data = Orthodont)
varWeights(vf1Fixed)
```

```{r}
1 / sqrt(8)
1 / sqrt(10)
```

```{r}
vf1Ident <- varIdent(c(Female = 0.5), ~ 1 | Sex)
vf1Ident <- Initialize(vf1Ident, Orthodont)
varWeights(vf1Ident)
```

```{r}
vf2Ident <- varIdent(form = ~ 1 | Sex, fixed = c(Female = 0.5))
vf2Ident <- Initialize(vf2Ident, Orthodont)
varWeights(vf2Ident)
```

```{r}
vf3Ident <- varIdent(form = ~ 1 | Sex * age)
vf3Ident <- Initialize(vf3Ident, Orthodont)
varWeights(vf3Ident)
```

```{r}
vf1Power <- varPower(1)
formula(vf1Power)
```

```{r}
vf2Power <- varPower(fixed = 0.5)
```

```{r}
vf3Power <- varPower(form = ~ fitted(.) | Sex, fixed = list(Male = 0.5, Female = 0))
```

```{r}
vf1Exp <- varExp(form = ~ age | Sex, fixed = c(Female = 0))
```

```{r}
vf1ConstPower <- varConstPower(
  power = 0.5,
  fixed = list(const = 1)
)
```

```{r}
vf1Comb <- varComb(
  varIdent(c(Female = 0.5), ~ 1 | Sex),
  varExp(1, ~age)
)
vf1Comb <- Initialize(vf1Comb, Orthodont)
varWeights(vf1Comb)
```

```{r}
head(Dialyzer)
```

```{r}
plot(Dialyzer, outer = ~QB)
```

```{r}
fm1Dial.lme <-
  lme(
    rate ~ (pressure + I(pressure^2) + I(pressure^3) + I(pressure^4)) * QB,
    data = Dialyzer,
    random = ~ pressure + I(pressure^2)
  )
fm1Dial.lme
```

```{r}
plot(fm1Dial.lme, resid(.) ~ pressure, abline = 0)
```

```{r}
fm2Dial.lme <- update(
  fm1Dial.lme,
  weights = varPower(form = ~pressure)
)
fm2Dial.lme
```

```{r}
plot(fm2Dial.lme, resid(., type = "p") ~ pressure, abline = 0)
```

```{r}
anova(fm1Dial.lme, fm2Dial.lme)
```

```{r}
intervals(fm2Dial.lme)
```

```{r}
plot(fm2Dial.lme, resid(.) ~ pressure | QB, abline = 0)
```

```{r}
fm3Dial.lme <- update(fm2Dial.lme,
  weights = varPower(form = ~ pressure | QB)
)
fm3Dial.lme
```

```{r}
anova(fm2Dial.lme, fm3Dial.lme)
```

```{r}
fm4Dial.lme <- update(fm2Dial.lme, weights = varConstPower(form = ~pressure))
fm4Dial.lme
```

```{r}
anova(fm2Dial.lme, fm4Dial.lme)
```

```{r}
plot(augPred(fm2Dial.lme), grid = T)
```

```{r}
anova(fm2Dial.lme)
```

```{r}
anova(fm2Dial.lme, Terms = 8:10)
```

```{r}
BodyWeight
```

```{r}
plot(BodyWeight, outer = ~Diet, aspect = 0.7, layout = c(3, 1))
```

```{r}
fm1BW.lme <-
  lme(
    weight ~ Time * Diet,
    data = BodyWeight,
    random = ~Time
  )
summary(fm1BW.lme)
```

```{r}
plot(fm1BW.lme)
```

```{r}
fm2BW.lme <- update(fm1BW.lme, weights = varPower(form = ~ fitted(.)))
summary(fm2BW.lme)
```

```{r}
anova(fm1BW.lme, fm2BW.lme)
```

```{r}
anova(fm2BW.lme, L = c("Time:Diet2" = 1, "Time:Diet3" = -1))
```

## 5.3 Correlation Structures for Modeling Dependence

```{r}
x <- seq(0, 3, by = .1)
isolinear <- function(s, p) 1 - (1 - s / p)
isogaussian <- function(s, p) 1 - exp(-(s / p)^2)
isoraquad <- function(s, p) (s / p)^2 / (1 + (s / p)^2)

c0 <- 0.1
p <- 1

plot(x, pmin(c0 + (1 - c0) * isogaussian(x, p), 1))
plot(x, pmin(c0 + (1 - c0) * isolinear(x, p), 1))
plot(x, pmin(c0 + (1 - c0) * isoraquad(x, p), 1))
```

```{r}
cs1CompSymm <- corCompSymm(value = 0.3, form = ~ 1 | Subject)
str(cs1CompSymm)
```

```{r}
cs2CompSym <- corCompSymm(value = 0.3, form = ~ age | Subject)
str(cs2CompSym)
```

```{r}
cs1CompSymm <- Initialize(cs1CompSymm, data = Orthodont)
head(corMatrix(cs1CompSymm))
```

```{r}
cs1Symm <- corSymm(
  value = c(0.2, 0.1, -0.1, 0, 0.2, 0),
  form = ~ 1 | Subject
)
cs1Symm <- Initialize(cs1Symm, data = Orthodont)
head(corMatrix(cs1Symm))
```

```{r}
cs1AR1 <- corAR1(0.8, form = ~ 1 | Subject)
cs1AR1 <- Initialize(cs1AR1, data = Orthodont)
head(corMatrix(cs1AR1))
```

```{r}
cs1ARMA <- corARMA(0.4, form = ~ 1 | Subject, q = 1)
cs1ARMA <- Initialize(cs1ARMA, data = Orthodont)
head(corMatrix(cs1ARMA))
```

```{r}
cs2ARMA <- corARMA(c(0.8, 0.4), form ~ 1 | Subject, p = 1, q = 1)
cs2ARMA <- Initialize(cs2ARMA, data = Orthodont)
head(corMatrix(cs2ARMA))
```

```{r}
spatDat <- data.frame(x = (0:4) / 4, y = (0:4) / 4)
spatDat
```

```{r}
cs1Exp <- corExp(1, form = ~ x + y)
cs1Exp <- Initialize(cs1Exp, spatDat)
corMatrix(cs1Exp)
```

```{r}
cs2Exp <- corExp(1, form = ~ x + y, metric = "manhattan")
cs2Exp <- Initialize(cs2Exp, spatDat)
corMatrix(cs2Exp)
```

```{r}
cs3Exp <- corExp(c(1, 0.2), form = ~ x + y, nugget = TRUE)
cs3Exp <- Initialize(cs3Exp, spatDat)
corMatrix(cs3Exp)
```

```{r}
head(Ovary)
str(Ovary)
```

```{r}
library(ggplot2)
ggplot(Ovary, aes(Time, follicles)) +
  geom_point() +
  facet_wrap(~Mare)
```

```{r}
fm1Ovar.lme <- lme(follicles ~ sin(2 * pi * Time) + cos(2 * pi * Time),
  data = Ovary, random = pdDiag(~ sin(2 * pi * Time))
)
summary(fm1Ovar.lme)
```

```{r}
ACF(fm1Ovar.lme)
```

```{r}
plot(ACF(fm1Ovar.lme, maxLag = 10), alpha = 0.01)
```

```{r}
fm2Ovar.lme <- update(fm1Ovar.lme, correlation = corAR1())
summary(fm2Ovar.lme)
```

```{r}
anova(fm1Ovar.lme, fm2Ovar.lme)
```

```{r}
intervals(fm1Ovar.lme)
```

```{r}
intervals(fm2Ovar.lme)
```

```{r}
fm3Ovar.lme <- update(fm1Ovar.lme, correlation = corARMA(q = 2))
summary(fm3Ovar.lme)
```

```{r}
anova(fm2Ovar.lme, fm3Ovar.lme)
```

```{r}
fm4Ovar.lme <- update(fm1Ovar.lme,
  correlation = corCAR1(form = ~Time)
)
anova(fm2Ovar.lme, fm4Ovar.lme, test = F)
```

```{r}
fm5Ovar.lme <- update(fm1Ovar.lme, corr = corARMA(p = 1, q = 1))
fm5Ovar.lme
```

```{r}
anova(fm2Ovar.lme, fm5Ovar.lme)
```

```{r}
plot(ACF(fm5Ovar.lme, maxLag = 10, resType = "n"), alpha = 0.01)
```

```{r}
Variogram(fm2BW.lme, form = ~Time)
```

```{r}
plot(Variogram(fm2BW.lme, form = ~Time, maxDist = 42))
```

```{r}
fm3BW.lme <- update(fm2BW.lme, correlation = corExp(form = ~Time))
fm3BW.lme
```

```{r}
intervals(fm3BW.lme)
```

```{r}
anova(fm2BW.lme, fm3BW.lme)
```

```{r}
plot(Variogram(fm3BW.lme, form = ~Time, maxDist = 42))
```

```{r}
fm4BW.lme <-
  update(fm3BW.lme, correlation = corExp(
    form = ~Time,
    nugget = TRUE
  ))
anova(fm3BW.lme, fm4BW.lme)
```

```{r}
plot(Variogram(fm3BW.lme, form = ~Time, maxDist = 42))
plot(Variogram(fm3BW.lme,
  form = ~Time, maxDist = 42,
  resType = "n", robust = TRUE
))
```

```{r}
fm5BW.lme <- update(fm3BW.lme, correlation = corRatio(form = ~Time))
fm6BW.lme <- update(fm3BW.lme, correlation = corSpher(form = ~Time))
fm7BW.lme <- update(fm3BW.lme, correlation = corLin(form = ~Time))
fm8BW.lme <- update(fm3BW.lme, correlation = corGaus(form = ~Time))
anova(
  fm3BW.lme, fm4BW.lme,
  fm5BW.lme, fm6BW.lme, fm7BW.lme, fm8BW.lme
)
```

## 5.4 Fitting Extended Linear Models with gls

```{r}
fm1Orth.gls <- gls(distance ~ Sex * I(age - 11), Orthodont,
  correlation = corSymm(form = ~ 1 | Subject),
  weights = varIdent(form = ~ 1 | age)
)
fm1Orth.gls
```

```{r}
intervals(fm1Orth.gls)
```

```{r}
fm2Orth.gls <-
  update(fm1Orth.gls, corr = corCompSymm(form = ~ 1 | Subject))
anova(fm1Orth.gls, fm2Orth.gls)
```

```{r}
fm3Orth.gls <- update(fm2Orth.gls, weights = NULL)
anova(fm2Orth.gls, fm3Orth.gls)
```

```{r}
plot(fm3Orth.gls, resid(., type = "n") ~ age | Sex) # Fig. 5.16
```

```{r}
fm4Orth.gls <- update(fm3Orth.gls,
  weights = varIdent(form = ~ 1 | Sex)
)
anova(fm3Orth.gls, fm4Orth.gls)
```

```{r}
qqnorm(fm4Orth.gls, ~ resid(., type = "n") | Sex)
```

```{r}
fm3Orth.lme <-
  lme(distance ~ Sex * I(age - 11),
    data = Orthodont,
    random = ~ I(age - 11) | Subject,
    weights = varIdent(form = ~ 1 | Sex)
  )
anova(fm3Orth.lme, fm4Orth.gls, test = FALSE)
```

```{r}
fm1Dial.gls <-
  gls(
    rate ~ (pressure + I(pressure^2) + I(pressure^3) + I(pressure^4)) * QB,
    Dialyzer
  )
fm1Dial.gls
```

```{r}
plot(fm1Dial.gls, resid(.) ~ pressure, abline = 0)
```

```{r}
fm2Dial.gls <- update(fm1Dial.gls,
  weights = varPower(form = ~pressure)
)
fm2Dial.gls
```

```{r}
plot(fm2Dial.gls, resid(.) ~ pressure, abline = 0)
```

```{r}
anova(fm1Dial.gls, fm2Dial.gls)
```

```{r}
ACF(fm2Dial.gls, form = ~ 1 | Subject)
```

```{r}
plot(ACF(fm2Dial.gls, form = ~ 1 | Subject), alpha = 0.01)
```

```{r}
fm3Dial.gls <- update(fm2Dial.gls,
  corr = corAR1(0.771, form = ~ 1 | Subject)
)
fm3Dial.gls
```

```{r}
intervals(fm3Dial.gls)
```

```{r}
anova(fm1Dial.gls, fm2Dial.gls, fm3Dial.gls)
```

```{r}
anova(fm3Dial.gls, fm2Dial.lme, test = FALSE)
```

```{r}
plot(ACF(fm3Dial.gls, form = ~ 1 | Subject), alpha = 0.01)
```

**Wehat Yield Trials**

```{r}
Wheat2
```

```{r}
fm1Wheat2 <- gls(yield ~ variety - 1, data = Wheat2)
fm1Wheat2
```

```{r}
Variogram(fm1Wheat2, form = ~ latitude + longitude)
```

```{r}
formula(fm1Wheat2)
```

```{r}
plot(Variogram(fm1Wheat2, form = ~ latitude + longitude, maxDist = 128),
  xlim = c(0, 32)
)
```

```{r}
fm2Wheat2 <- update(fm1Wheat2, corr = corSpher(c(28, 0.2),
  form = ~ latitude + longitude,
  nugget = TRUE
))
fm2Wheat2
```

```{r}
fm3Wheat2 <- update(fm1Wheat2, corr = corRatio(c(12.5, 0.2),
  form = ~ latitude + longitude, nugget = TRUE
))
fm3Wheat2
```

```{r}
anova(fm2Wheat2, fm3Wheat2)
anova(fm1Wheat2, fm3Wheat2)
```

```{r}
plot(Variogram(fm3Wheat2, resType = "n"))
```

```{r}
plot(fm3Wheat2, resid(., type = "n") ~ fitted(.), abline = 0)
```

```{r}
qqnorm(fm3Wheat2, ~ resid(., type = "n"))
```

```{r}
fm4Wheat2 <- update(fm3Wheat2, model = yield ~ variety)
anova(fm4Wheat2)
```

```{r}
anova(fm3Wheat2, L = c(-1, 0, 1))
```
