---
title: "note04"
output: html_notebook
---

```{r}
options(paged.print = FALSE)
```

# 4 Fitting Linear Mixed-Effects Models

## 4.1 Fitting Linear Models in S with lm and lmList

```{r}
library(nlme)
library(lattice)
```

```{r}
fm1Orth.lm <- lm(distance ~ age, Orthodont)
summary(fm1Orth.lm)
```

```{r}
par(mfrow = c(2, 2))
plot(fm1Orth.lm)
```

```{r}
fm2Orth.lm <- lm(distance ~ Sex * age, data = Orthodont)
summary(fm2Orth.lm)
```

```{r}
fm3Orth.lm <- lm(distance ~ Sex * age - Sex, data = Orthodont)
summary(fm3Orth.lm)
```

```{r}
bwplot(getGroups(Orthodont) ~ resid(fm2Orth.lm)) # Figure 4.2
```

```{r}
fm1Orth.lis <- lmList(distance ~ age | Subject, data = Orthodont)
fm1Orth.lis
```

```{r}
getGroupsFormula(Orthodont)
```

```{r}
summary(fm1Orth.lis)
```

```{r}
pairs(fm1Orth.lis, id = 0.01, adj = -0.5)
```

```{r}
fm2Orth.lis <- lmList(distance ~ I(age - 11), data = Orthodont)
pairs(fm2Orth.lis, id = 0.01, adj = -0.5, aspect = 1)
```

```{r}
intervals(fm2Orth.lis)
```

```{r}
plot(intervals(fm2Orth.lis))
```

```{r}
IGF
```

```{r}
plot(IGF, layout = c(5, 2))
```

```{r}
fm1IGF.lis <- lmList(IGF)
coef(fm1IGF.lis)
```

```{r}
plot(intervals(fm1IGF.lis))
```

```{r}
fm1IGF.lm <- lm(conc ~ age, data = IGF)
summary(fm1IGF.lm)
```

```{r}
par(mfrow = c(2, 2))
plot(fm1IGF.lm)
```

## 4.2 Fitting Linear Mixed-Effects Models with lme

```{r}
fm1Orth.lme <- lme(
  data = Orthodont,
  distance ~ I(age - 11),
  random = ~ I(age - 11) | Subject
)
```

```{r}
fm1Orth.lme
```

```{r}
fm2Orth.lme <- update(fm1Orth.lme, fixed = distance ~ Sex * I(age - 11))
summary(fm2Orth.lme)
```

```{r}
fitted(fm2Orth.lme, level = 0:1)
```

```{r}
resid(fm2Orth.lme, level = 1)
```

```{r}
resid(fm2Orth.lme, level = 1, type = "pearson")
```

```{r}
newOrth <- data.frame(
  Subject = rep(c("M11", "F03"), c(3, 3)),
  Sex = rep(c("Male", "Female"), c(3, 3)),
  age = rep(16:18, 2)
)
predict(fm2Orth.lme, newdata = newOrth)
```

```{r}
predict(fm2Orth.lme, data = newOrth, level = 0:1)
```

```{r}
fm2Orth.lmeM <- update(fm2Orth.lme, method = "ML")
summary(fm2Orth.lmeM)
```

```{r}
compOrth <- compareFits(coef(fm2Orth.lis), coef(fm1Orth.lme))
compOrth
```

```{r}
plot(compOrth, mark = fixef(fm1Orth.lme))
```

```{r}
comparePred(fm2Orth.lis, fm1Orth.lme, length.out = 1)
```

```{r, fig.width=4, fig.height=4}
plot(comparePred(fm2Orth.lis, fm1Orth.lme, length.out = 2), layout = c(8, 4), between = list(y = c(0, 0.5)))
```

```{r}
plot(compareFits(ranef(fm2Orth.lme), ranef(fm2Orth.lmeM)), mark = c(0, 0))
```

```{r}
fm4Orth.lm <- lm(distance ~ Sex * I(age - 11), data = Orthodont)
summary(fm4Orth.lm)
```

```{r}
anova(fm2Orth.lme, fm4Orth.lm)
```

```{r}
lm(conc ~ age, data = IGF)
# fm1IGF.lis <- lmList(conc ~ age, IGF)
# fm1IGF.lme <- lme(fm1IGF.lis)
# fm1IGF.lme
# intervals(fm1IGF.lme)
# summary(fm1IGF.lme)
```

```{r}
pd1 <- pdDiag(~age)
pd1
formula(pd1)
```

```{r}
fm2IGF.lme <- lme(conc ~ age, data = IGF, random = pdDiag(~age))
fm2IGF.lme
```

```{r}
lme(conc ~ age,
  data = IGF,
  random = list(Lot = pdDiag(~age))
)
```

```{r}
pd2 <- pdDiag(value = diag(2), form = ~age)
pd2
```

```{r}
formula(pd2)
```

```{r}
lme(conc ~ age, IGF, pdDiag(diag(2), ~age))
```

```{r}
Oats
```

```{r}
fm4Oats <- lme(yield ~ nitro, data = Oats, random = ~ 1 | Block / Variety)
summary(fm4Oats)
```

```{r}
fm4OatsB <-
  lme(
    yield ~ nitro,
    data = Oats,
    random = list(Block = pdCompSymm(~ Variety - 1))
  )
summary(fm4OatsB)
```

```{r}
anova(fm4Oats, fm4OatsB)
```

```{r}
fm4OatsB$modelStruct$reStruct$Block
```

```{r}
corMatrix(fm4OatsB$modelStruct$reStruct$Block)[1, 2]
```

```{r}
fm4OatsC <- lme(
  yield ~ nitro,
  data = Oats,
  random = list(Block = pdBlocked(list(pdIdent(~1), pdIdent(~ Variety - 1))))
)
summary(fm4OatsC)
```

**Cell Culture Bioassay with Crossed Random Effects**

```{r}
head(Assay)
```

```{r}
library(tidyverse)
Assay %>%
  ggplot(aes(dilut, logDens)) +
  geom_point(aes(color = as.factor(sample))) +
  geom_line(aes(group = sample, color = sample)) +
  facet_wrap(~Block)
```

```{r}
options(contrasts = c("contr.treatment", "contr.poly"))
fm1Assay <- lme(logDens ~ sample * dilut,
  data = Assay,
  random = pdBlocked(list(
    pdIdent(~1), pdIdent(~ sample - 1),
    pdIdent(~ dilut - 1)
  ))
)
fm1Assay
```

```{r}
anova(fm1Assay)
```

```{r}
Oxide
```

```{r}
formula(Oxide)
```

```{r}
fm1Oxide <- lme(Thickness ~ 1,
  data = Oxide,
  random = ~ 1 | Lot / Wafer
)
fm1Oxide
```

```{r}
intervals(fm1Oxide, which = "var-cov")
```

```{r}
fm2Oxide <- update(fm1Oxide, random = ~ 1 | Lot)
fm2Oxide
```

```{r}
anova(fm1Oxide, fm2Oxide)
```

```{r}
coef(fm1Oxide, level = 1)
```

```{r}
coef(fm1Oxide, level = 2)
```

```{r}
ranef(fm1Oxide, level = 2)
```

```{r}
ranef(fm1Oxide, level = 1:2)
```

```{r}
formula(Wafer)
```

```{r}
fm1Wafer <- lme(current ~ voltage + I(voltage^2),
  data = Wafer,
  random = list(
    Wafer = pdDiag(~ voltage + I(voltage^2)),
    Site = pdDiag(~ voltage + I(voltage^2))
  )
)
fm1Wafer <- lme(current ~ voltage + I(voltage^2),
  data = Wafer,
  random = pdDiag(~ voltage + voltage^2)
)
summary(fm1Wafer)
```

```{r}
fitted(fm1Wafer, level = 0)
```

```{r}
resid(fm1Wafer, level = 1:2)
```

```{r}
newWafer <-
  data.frame(
    Wafer = rep(1, 4),
    voltage = c(1, 1.5, 3, 3.5)
  )
newWafer
```

```{r}
predict(fm1Wafer, newdata = newWafer, level = 0:1)
```

```{r}
newWafer2 <- data.frame(
  Wafer = rep(1, 4),
  Site = rep(3, 4),
  voltage = c(1, 1.5, 3, 3.5)
)
predict(fm1Wafer, newdata = newWafer2, level = 0:2)
```

## 4.3 Examining a Fitted Model

```{r}
plot(fm2Orth.lme, Subject ~ resid(.), abline = 0)
```

```{r}
plot(fm2Orth.lme, resid(., type = "p") ~ fitted(.) | Sex, id = 0.05, adj = -0.3)
```

```{r}
fm3Orth.lme <-
  lme(distance ~ Sex + I(age - 11) + Sex:I(age - 11),
    data = Orthodont,
    random = ~ I(age - 11) | Subject,
    weights = varIdent(form = ~ 1 | Sex)
  )
fm3Orth.lme
```

```{r}
plot(fm3Orth.lme, resid(., type = "p") ~ fitted(.) | Sex, id = 0.05, adj = -0.3)
```

```{r}
plot(fm3Orth.lme, distance ~ fitted(.), id = 0.05, adj = -0.3)
```

```{r}
anova(fm2Orth.lme, fm3Orth.lme)
```

```{r}
qqnorm(fm3Orth.lme, ~ resid(.) | Sex)
```

```{r}
plot(fm2IGF.lme, resid(., type = "p") ~ fitted(.) | Lot, layout = c(5, 2))
```

```{r}
qqnorm(fm2IGF.lme, ~ resid(.), id = 0.05, adj = -0.75)
```

```{r}
plot(fm1Oxide)
```

```{r}
qqnorm(fm1Oxide)
```

```{r}
plot(fm1Wafer, resid(.) ~ voltage | Wafer)
```

```{r}
plot(fm1Wafer, resid(.) ~ voltage | Wafer,
  panel = function(x, y, ...) {
    panel.grid()
    panel.xyplot(x, y)
    panel.loess(x, y, lty = 2)
    panel.abline(0, 0)
  }
)
```

```{r}
with(
  Wafer,
  coef(lm(resid(fm1Wafer) ~ cos(4.19 * voltage) + sin(4.19 * voltage) - 1))
)
```

```{r}
nls(resid(fm1Wafer) ~ b3 * cos(w * voltage) + b4 * sin(w * voltage), Wafer,
  start = list(b3 = -0.0519, b4 = 0.1304, w = 4.19)
)
```

```{r}
fm2Wafer <- update(fm1Wafer,
  . ~ . + cos(4.5679 * voltage) + sin(4.5679 * voltage),
  random = list(
    Wafer = pdDiag(~ voltage + I(voltage^2)),
    Site = pdDiag(~ voltage + I(voltage^2))
  )
)
summary(fm2Wafer)
```

```{r}
summary(fm1Wafer)
```

```{r}
AIC(fm1Wafer, fm2Wafer)
```

```{r}
intervals(fm2Wafer)
```

```{r}
plot(fm2Wafer, resid(.) ~ voltage | Wafer,
  panel = function(x, y, ...) {
    panel.grid()
    panel.xyplot(x, y)
    panel.loess(x, y, lty = 2)
    panel.abline(0, 0)
  }
)
```

```{r}
qqnorm(fm2Wafer, aspect = 1)
```

```{r}
qqnorm(fm2Orth.lme, ~ ranef(.), id = 0.10, cex = 0.7)
```

```{r}
pairs(fm2Orth.lme, ~ ranef(.) | Sex, id = ~ Subject == "M13", adj = -0.3)
```

```{r}
fm2IGF.lme
```

```{r}
c(0.00031074, 0.0053722) / abs(fixef(fm2IGF.lme))
```

```{r}
fm3IGF.lme <- update(fm2IGF.lme, random = ~ age - 1)
fm3IGF.lme
```

```{r}
anova(fm2IGF.lme, fm3IGF.lme)
```

```{r}
qqnorm(fm1Oxide, ~ ranef(., level = 1), id = 0.10)
```

```{r}
qqnorm(fm1Oxide, ~ ranef(., level = 2), id = 0.10)
```

```{r}
fm2Wafer
```

```{r}
# fm3Wafer <- update(fm2Wafer,
#              random = list(Wafer = ~voltage+I(voltage^2),
#                            Site = pdDiag(~voltage+I(voltage^2))),
#                   control = list(msVerbose = TRUE, msMaxIter = 200)
#                   )
# fm3Wafer
# anova(fm2Wafer, fm3Wafer)
# fm4Wafer <- update(fm2Wafer,
#                   random = list(Wafer = ~ voltage + I(voltage^2),
#                   Site = pdBlocked(list(~1,
#                   ~voltage+I(voltage^2) - 1))),
#                   control = list(msVerbose = TRUE,
#                   msMaxIter = 200))
# fm4Wafer
# anova(fm3Wafer, fm4Wafer)
# qqnorm(fm4Wafer, ~ranef(., level = 2), id = 0.05,
#        cex = 0.7, layout = c(3, 1))
```

```{r}
fm1Machine <-
  lme(score ~ Machine, data = Machines, random = ~ 1 | Worker)

(fm3Machine <- update(fm1Machine, random = ~ Machine - 1 | Worker))
```
