---
title: "note07"
output: html_notebook
---

# 7 회귀기반 모형: 자기상관과 외부정보의 반영

## 7.1 자기상관

```{r}
library(forecast)
library(zoo)

Amtrak.data <- read.csv("data-raw/Amtrak data.csv")
ridership.ts <- ts(Amtrak.data$Ridership, start = c(1991, 1), end = c(2004, 3), freq = 12)
ridership.24.ts <- window(ridership.ts, start = c(1991, 1), end = c(1991, 24))

# Figure 7-2
Acf(ridership.24.ts, lag.max = 12, main = "")
```

```{r}
nValid <- 36
nTrain <- length(ridership.ts) - nValid
train.ts <- window(ridership.ts, start = c(1991, 1), end = c(1991, nTrain))
valid.ts <- window(ridership.ts, start = c(1991, nTrain + 1), end = c(1991, nTrain + nValid))

train.lm.trend.season <- tslm(train.ts ~ trend + I(trend^2) + season)
```

```{r}
# Figure 7-3
Acf(train.lm.trend.season$residuals, lag.max = 12, main = "")
```

```{r}
x <- Acf(train.lm.trend.season$residuals, lag.max = 12, main = "")$acf
```

```{r}
pacf(train.lm.trend.season$residuals)
```

## 7.2 자기상관 정보의 반영을 통한 예측력 향상: AR, ARIMA 모형

```{r}
train.lm.trend.season <- tslm(train.ts ~ trend + I(trend^2) + season)
train.res.arima <- Arima(train.lm.trend.season$residuals, order = c(1, 0, 0))
train.res.arima.pred <- forecast(train.res.arima, h = nValid)
print(train.res.arima.pred)
```

```{r}
# option 2: use coefficients multiplied by mean-centered series value
march2001.residual <- window(train.lm.trend.season$residuals, start = c(2001, 3), end = c(2001, 3))
plugin.forecast <- (march2001.residual - train.res.arima$coef[2]) * train.res.arima$coef[1] + train.res.arima$coef[2]
print(plugin.forecast)
```

```{r}
# Figure 7-4
plot(train.lm.trend.season$residuals,
  ylim = c(-250, 250), ylab = "Residuals",
  xlab = "Time", bty = "l", xaxt = "n", xlim = c(1991, 2006.25), main = ""
)
axis(1, at = seq(1991, 2006, 1), labels = format(seq(1991, 2006, 1)))
lines(train.res.arima.pred$fitted, lwd = 2, col = "blue")
lines(c(2004.25 - 3, 2004.25 - 3), c(-500, 3500))
lines(c(2004.25, 2004.25), c(-500, 3500))
text(1996.25, 225, "Training")
text(2002.75, 225, "Validation")
text(2005.25, 225, "Future")
arrows(2004 - 3, 200, 1991.25, 200, code = 3, length = 0.1, lwd = 1, angle = 30)
arrows(2004.5 - 3, 200, 2004, 200, code = 3, length = 0.1, lwd = 1, angle = 30)
arrows(2004.5, 200, 2006, 200, code = 3, length = 0.1, lwd = 1, angle = 30)
```

```{r}
summary(train.res.arima)
```

```{r}
# Figure 7-5
Acf(train.res.arima$residuals, lag.max = 12, main = "")
```

## 7.4 외부정보 추가하기

```{r}
library(forecast)
library(lubridate)

# Load and prepare data.
bike.df <- read.csv("data-raw/BikeSharingDaily.csv")
bike.df$Date <- as.Date(bike.df$dteday, format = "%Y-%m-%d")
bike.df$Month <- month(bike.df$Date, label = TRUE)
bike.df$DOW <- wday(bike.df$Date, label = TRUE)
bike.df$WorkingDay <- factor(bike.df$workingday, levels = c(0, 1), labels = c("Not_Working", "Working"))
bike.df$Weather <- factor(bike.df$weathersit, levels = c(1, 2, 3), labels = c("Clear", "Mist", "Rain_Snow"))

# Create dummy variables.
Month.dummies <- model.matrix(~ 0 + Month, data = bike.df)
DOW.dummies <- model.matrix(~ 0 + DOW, data = bike.df)
WorkingDay_Weather.dummies <- model.matrix(~ 0 + WorkingDay:Weather, data = bike.df)

# Change the names of the dummy variables.
colnames(Month.dummies) <- gsub("Month", "", colnames(Month.dummies))
colnames(DOW.dummies) <- gsub("DOW", "", colnames(DOW.dummies))
colnames(WorkingDay_Weather.dummies) <- gsub("WorkingDay", "", colnames(WorkingDay_Weather.dummies))
colnames(WorkingDay_Weather.dummies) <- gsub("Weather", "", colnames(WorkingDay_Weather.dummies))
colnames(WorkingDay_Weather.dummies) <- gsub(":", "_", colnames(WorkingDay_Weather.dummies))

# Set up training and validation sets.
x <- as.data.frame(cbind(Month.dummies[, -12], DOW.dummies[, -7], WorkingDay_Weather.dummies[, -6]))
y <- bike.df$cnt
nTotal <- length(y)
nValid <- 90
nTrain <- nTotal - nValid
xTrain <- x[1:nTrain, ]
yTrain <- y[1:nTrain]
xValid <- x[(nTrain + 1):nTotal, ]
yValid <- y[(nTrain + 1):nTotal]

# Fit tslm.
yTrain.ts <- ts(yTrain)
(formula <- as.formula(paste("yTrain.ts", paste(c("trend", colnames(xTrain)), collapse = "+"), sep = "~")))
bike.tslm <- tslm(formula, data = xTrain, lambda = 1)
options(scipen = 999, digits = 6)
summary(bike.tslm)
```

```{r}
# Make tslm forecasts.
bike.tslm.pred <- forecast(bike.tslm, newdata = xValid)
accuracy(bike.tslm.pred$mean, yValid)
```

```{r}
plot(bike.tslm.pred, ylim = c(0, 9000), xlab = "Days", ylab = "Daily Bike Rentals")
```

```{r}
# Fit tbats and make forecasts.
y.ts <- ts(y)
times.ts <- time(y.ts)
y.msts <- msts(y, seasonal.periods = c(7, 365.25))
times.msts <- time(y.msts)
yTrain.msts <- msts(yTrain, seasonal.periods = c(7, 365.25))
bike.tbats <- tbats(yTrain.msts) # , use.parallel = TRUE)#, num.cores = 12)
bike.tbats
```

```{r}
bike.tbats.pred <- forecast(bike.tbats, h = nValid)
accuracy(bike.tbats.pred$mean, yValid)
```

```{r}
# Compare the forecasts of tslm and tbats.
plot(bike.tslm.pred, ylim = c(0, 9000))
lines(window(y.ts, start = times.ts[nValid + 1]))
```

```{r}
plot(bike.tbats.pred, ylim = c(0, 9000))
lines(window(y.msts, start = times.msts[nValid + 1]))
```

```{r}
walmart.data <- read.csv("data-raw/WalMartStock.csv")
walmart.data$Date <- as.Date(walmart.data$Date, format = "%d-%b-%y")
close.ts <- ts(walmart.data$Close)

# Figure 7.10
par(mfrow = c(1, 1))
plot(walmart.data$Date, walmart.data$Close, type = "l", ylab = "Close Price ($)", xlab = "Time", xaxt = "n")
axis.Date(side = 1, walmart.data$Date, format = "%b-%y")
```

```{r}
# Figure 7.11
# par(mfrow = c(1,2))
Acf(close.ts, lag.max = 10, main = "ACF Plot for Close")
```

```{r}
Acf(diff(close.ts, 1), lag.max = 10, main = "ACF Plot for Differenced Series")
```

```{r}
# Table 7.4
Arima(close.ts, order = c(1, 0, 0))
```

```{r}
Arima(diff(close.ts, 1), order = c(1, 0, 0))
```
