---
title: "note02"
output: html_notebook
---

# 2 A Technical Overview of lattice

## 2.2 Dimension and physical layout

```{r}
library(lattice)
```

```{r}
# install.packages("MEMSS")
data(Oats, package = "MEMSS")
Oats
```

```{r, fig.width=4, fig.height=4}
tp1.oats <- xyplot(yield ~ nitro | Variety + Block, data = Oats, type = "o")
tp1.oats
```

```{r}
dim(tp1.oats)
```

```{r}
dimnames(tp1.oats)
```

```{r}
xtabs(~ Variety + Block, data = Oats)
```

```{r}
summary(tp1.oats)
```

```{r}
summary(tp1.oats[, 1])
```

```{r}
tp1.oats[, 1]
```

```{r}
t(tp1.oats)
```

```{r}
update(tp1.oats, aspect = "xy")
```

```{r, fig.asp=1}
update(tp1.oats, aspect = "xy", layout = c(0, 18))
```

```{r}
update(tp1.oats, aspect = "xy", layout = c(0, 18), between = list(x = c(0, 0, 0.5), y = 0.5))
```

## 2.3 Grouped displays

```{r, fig.width=7, fig.height=7}
dotplot(variety ~ yield | site, barley,
  layout = c(1, 6), aspect = c(0.7),
  groups = year, auto.key = list(space = "right")
)
```

## 2.4 Annotation: Captions, labels, and legends

```{r}

```

```{r}
key.variety <-
  list(
    space = "right",
    text = list(levels(Oats$Variety)),
    points = list(pch = 1:3, col = "black")
  )
xyplot(yield ~ nitro | Block, Oats,
  aspect = "xy", type = "o",
  groups = Variety, key = key.variety,
  lty = 1, pch = 1:3, col.line = "darkgrey",
  col.symbol = "black",
  xlab = "Nitrogen concentration (cwt/acre)",
  ylab = "Yield (bushels/acre)",
  main = "Yield of three varieties of oats",
  sub = "A 3 x 4 split-plot expertiment with 6 blocks"
)
```

## 2.5 Graphing the data

```{r}
barchart(Class ~ Freq | Sex + Age,
  data = as.data.frame(Titanic),
  groups = Survived, stack = TRUE, layout = c(4, 1),
  auto.key = list(title = "Survived", columns = 2)
)
```

```{r}
barchart(Class ~ Freq | Sex + Age,
  data = as.data.frame(Titanic),
  groups = Survived, stack = TRUE, layout = c(4, 1),
  auto.key = list(title = "Survived", columns = 2),
  scales = list(x = "free")
)
```

```{r}
bc.titanic <-
  barchart(Class ~ Freq | Sex + Age,
    data = as.data.frame(Titanic),
    groups = Survived, stack = TRUE, layout = c(4, 1),
    auto.key = list(title = "Survived", columns = 2),
    scales = list(x = "free")
  )
bc.titanic
```

```{r}
update(bc.titanic, panel = panel.barchart)
```

```{r}
update(bc.titanic, panel = function(...) {
  panel.barchart(...)
})
```

```{r}
update(bc.titanic,
  panel = function(...) {
    panel.grid(h = 0, v = -1)
    panel.barchart(...)
  }
)
```

```{r}
update(bc.titanic,
  panel = function(..., border) {
    panel.barchart(..., border = "transparent")
  }
)
```

```{r}
update(bc.titanic, border = "transparent")
```
