---
title: "note03"
output: html_notebook
---

# 3 Visualizing Univariate Distributions

## 3.1 Density Plot

```{r}
library(lattice)
```

```{r}
densityplot(~eruptions, data = faithful)
```

```{r}
densityplot(~eruptions,
  data = faithful,
  kernel = "rect",
  bw = 0.2,
  plot.points = "rug",
  n = 200
)
```

## 3.2 Large datasets

```{r}
library(latticeExtra)
data(gvhd10)
densityplot(~ log(FSC.H) | Days,
  data = gvhd10,
  plot.points = FALSE, ref = TRUE, layout = c(2, 4)
)
```

## 3.3 Histograms

```{r}
histogram(~ log2(FSC.H) | Days, gvhd10,
  xlab = "log Forward Scatter",
  type = "density",
  nint = 50,
  layout = c(2, 4)
)
```

## 3.4 Normal Q--Q plots

```{r}
data(Chem97, package = "mlmRev")
qqmath(~ gcsescore | factor(score),
  data = Chem97,
  f.value = ppoints(100)
)
```

```{r}
qqmath(~ gcsescore | gender, Chem97,
  groups = score,
  aspect = "xy",
  f.value = ppoints(100),
  auto.key = list(space = "right"),
  xlab = "Standard Normal Quantiles",
  ylab = "Average GCSE Score"
)
```

```{r}
library(MASS)
Chem97.pos <- subset(Chem97, gcsescore > 0)
with(
  Chem97.pos,
  boxcox(gcsescore ~ score * gender, lambda = seq(0, 4, 1 / 10))
)
```

```{r}
Chem97.mod <- transform(Chem97, gcsescore.trans = gcsescore^2.34)
qqmath(~ gcsescore.trans | gender, Chem97.mod,
  groups = score,
  f.value = ppoints(100), aspect = "xy",
  auto.key = list(space = "right", title = "score"),
  xlab = "Standard Normal Quantiles",
  ylab = "Transformed GCSE Score"
)
```

## 3.5 The empirical CDF

```{r}
library(latticeExtra)
ecdfplot(~ gcsescore | factor(score),
  data = Chem97,
  groups = gender,
  auto.key = list(columns = 2),
  subset = gcsescore > 0,
  xlab = "Average GCSE SCore"
)
```

```{r}
qqmath(
  data = Chem97,
  ~ gcsescore | factor(score),
  groups = gender,
  auto.key = list(points = FALSE, lines = TRUE, columns = 2),
  subset = gcsescore > 0,
  type = "l",
  distribution = qunif,
  prepanel = prepanel.qqmathline,
  aspect = "xy",
  xlab = "standard Normal Quantiles",
  ylab = "Average GCSE"
)
```

## 3.6 Two-sample Q--Q plots

```{r}
qq(
  data = Chem97, gender ~ gcsescore | factor(score),
  f.value = ppoints(100), aspect = 1
)
```

## 3.7 Box-and-whisker plots

```{r}
bwplot(
  data = Chem97,
  factor(score) ~ gcsescore | gender,
  xlab = "Average GCSE Score"
)
```

```{r}
bwplot(
  data = Chem97,
  gcsescore^2.34 ~ gender | factor(score),
  varwidth = TRUE,
  layout = c(6, 1),
  ylab = "Transformed GCSE score"
)
```

```{r}
bwplot(Days ~ log(FSC.H),
  data = gvhd10,
  xlab = "log(Forward Scatter)",
  ylab = "Days Past Transplant"
)
```

```{r}
bwplot(Days ~ log(FSC.H),
  data = gvhd10,
  panel = panel.violin,
  box.ration = 3,
  xlab = "log(Forward Scatter)",
  ylab = "Days Past Transplant"
)
```

## 3.8 Strip plots

```{r}
stripplot(factor(mag) ~ depth, data = quakes)
```

```{r}
stripplot(depth ~ factor(mag),
  data = quakes,
  jitter.data = TRUE,
  alpha = 0.6,
  xlab = "Magnitude (Richter)", ylab = "Depth (km"
)
```

```{r}
m <- lm(yield ~ variety + year + site, data = barley)
stripplot(sqrt(abs(residuals(m))) ~ site,
  data = barley,
  groups = year,
  jitter.data = TRUE,
  auto.key = list(points = TRUE, lines = TRUE, columns = 2),
  type = c("p", "a"),
  fun = median,
  ylab = expression(abs("Residual Barley Yield")^{
    1 / 2
  })
)
```
