---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(babynames)
```

```{r}
str_view(fruit, "berry")
```

```{r}
str_view(c("a", "ab", "ae", "bd", "ea", "eab"), "a.")
```

```{r}
str_view(fruit, "a...e")
```

```{r}
str_view(c("a", "ab", "abb"), "ab?")
```

```{r}
str_view(c("a", "ab", "abb"), "ab+")
```

```{r}
str_view(c("a", "ab", "abb"), "ab*")
```

```{r}
str_view(words, "[aeiou]x[aeiou]")
```

```{r}
str_view(words, "[^aeiou]y[^aeiou]")
```

```{r}
str_view(fruit, "apple|melon|nut")
```

```{r}
str_view(fruit, "aa|ee|ii|oo|uu")
```

```{r}
str_detect(c("a", "b", "c"), "[aeiou]")
```

```{r}
babynames |>
  filter(str_detect(name, "x")) |>
  count(name, wt = n, sort = TRUE)
```

```{r}
babynames |>
  group_by(year) |>
  summarize(prop_x = mean(str_detect(name, "x"))) |>
  ggplot(aes(x = year, y = prop_x)) +
  geom_line()
```

```{r}
x <- c("apple", "banana", "pear")
str_count(x, "p")
```

```{r}
str_count("abababa", "aba")
str_view("abababa", "aba")
```

```{r}
babynames |>
  count(name) |>
  mutate(
    vowels = str_count(name, "[aeiou]"),
    consonants = str_count(name, "[^aeiou]")
  )
```

```{r}
babynames |>
  count(name) |>
  mutate(
    name = str_to_lower(name),
    vowels = str_count(name, "[aeiou]"),
    consonants = str_count(name, "[^aeiou]")
  )
```

```{r}
x <- c("apple", "pear", "banana")
str_replace(x, "[aeiou]", "-")
str_replace_all(x, "[aeiou]", "-")
```

```{r}
df <- tribble(
  ~str,
  "<Sheryl>-F_34",
  "<Kisha>-F_45",
  "<Brandon>-N_33",
  "<Sharon>-F_38",
  "<Penny>-F_58",
  "<Justin>-M_41",
  "<Patricia>-F_84",
)
df
```

```{r}
df |>
  separate_wider_regex(
    str,
    patterns = c(
      "<",
      name = "[A-Za-z]+",
      ">-",
      gender = ".", "_",
      age = "[0-9]+"
    )
  )
```

```{r}
dot <- "\\."
str_view(dot)
str_view(c("abc", "a.c", "bef"), "a\\.c")
```

```{r}
x <- "a\\b"
str_view(x)
str_view(x, "\\\\")
```

```{r}
str_view(c("abc", "a.c", "a*c", "a c"), "a[.]c")
str_view(c("abc", "a.c", "a*c", "a c"), ".[*]c")
```

```{r}
str_view(fruit, "^a")
```

```{r}
str_view(fruit, "a$")
```

```{r}
str_view(fruit, "apple")
```

```{r}
str_view(fruit, "^apple$")
```

```{r}
x <- c("summary(x)", "summarize(df)", "rowsum(x)", "sum(x)")
str_view(x, "sum")
```

```{r}
str_view(x, "\\bsum\\b")
```

```{r}
str_view("abc", c("$", "^", "\\b"))
```

```{r}
str_replace_all("abc", c("$", "^", "\\b"), "--")
```

```{r}
x <- "abcd ABCD 12345 -!@#%."
str_view(x, "[abc]+")
str_view(x, "[a-z]+")
str_view(x, "[^a-z0-9]+")
```

```{r}
str_view("a-b-c", "[a-c]")
str_view("a-b-c", "[a\\-c]")
```

```{r}
x <- "abcd ABCD 12345 -!@#%."
str_view(x, "\\d+")
str_view(x, "\\D+")
str_view(x, "\\s+")
str_view(x, "\\S+")
str_view(x, "\\w+")
str_view(x, "\\W+")
```

```{r}
str_view(fruit, "(..)\\1")
```

```{r}
str_view(words, "^(..).*\\1$")
```

```{r}
sentences |>
  str_replace("(\\w+) (\\w+) (\\w+)", "\\1 \\3 \\2") |>
  str_view()
```

```{r}
sentences |>
  str_match("the (\\w+) (\\w+)") |>
  head()
```

```{r}
sentences |>
  str_match("the (\\w+) (\\w+)") |>
  as_tibble(.name_repair = "minimal") |>
  set_names("match", "word1", "word2")
```

```{r}
x <- c("a gray cat", "a grey dog")
str_match(x, "gr(e|a)y")
str_match(x, "gr(?:e|a)y")
```

```{r}
bananas <- c("banana", "Banana", "BANANA")
str_view(bananas, "banana")
```

```{r}
str_view(bananas, regex("banana", ignore_case = TRUE))
```

```{r}
x <- "Line 1\nLine 2\nLine 3"
str_view(x, ".Line")
```

```{r}
str_view(x, regex(".Line", dotall = TRUE))
```

```{r}
x <- "Line 1\nLine 2\nLine 3"
str_view(x, "^Line")
```

```{r}
str_view(x, regex("^Line", multiline = TRUE))
```

```{r}
phone <- regex(
  r"(
    \(?     # optional opening parens
    (\d{3}) # area code
    [)\-]?  # optional closing parens or dash
    \ ?     # optional space
    (\d{3}) # another three numbers
    [\ -]?  # optional space or dash
    (\d{4}) # four more numbers
  )",
  comments = TRUE
)

str_extract(c("514-791-8141", "(123) 456 7890", "123456"), phone)
```

```{r}
str_view(c("", "a", "."), fixed("."))
```

```{r}
str_view("x X", "X")
str_view("x X", fixed("X", ignore_case = TRUE))
```

```{r}
str_view("i İ ı I", fixed("İ", ignore_case = TRUE))
str_view("i İ ı I", coll("İ", ignore_case = TRUE, locale = "tr"))
```

```{r}
str_view(sentences, "^The")
```

```{r}
str_view(sentences, "^The\\b")
```

```{r}
str_view(sentences, "^(She|He|It|They)\\b")
```

```{r}
pos <- c("He is a boy", "She had a good time")
neg <- c("Shells come from the sea", "Hadley said 'It's a great day'")

pattern <- "^(She|He|It|They)\\b"
str_detect(pos, pattern)
str_detect(neg, pattern)
```

```{r}
str_view(words, "^[^aeiou]+$")
```

```{r}
str_view(words[!str_detect(words, "[aeiou]")])
```

```{r}
str_view(words, "a.*b|b.*a")
```

```{r}
words[str_detect(words, "a") & str_detect(words, "b")]
```

```{r}
words[
  str_detect(words, "a") &
    # str_detect(words, "e") &
    str_detect(words, "i") &
    # str_detect(words, "o") &
    str_detect(words, "u")
]
```

```{r}
str_view(sentences, "\\b(red|green|blue)\\b")
```

```{r}
rgb <- c("red", "green", "blue")
str_c("\\b(", str_flatten(rgb, "|"), ")\\b")
```

```{r}
cols <- colors()
cols <- cols[!str_detect(cols, "\\d")]
str_view(cols)
```

```{r}
pattern <- str_c("\\b(", str_flatten(cols, "|"), ")\\b")
str_view(sentences, pattern)
```
