---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(nycflights13)
```

```{r}
airlines
```

```{r}
airports
```

```{r}
planes
```

```{r}
weather
```

```{r}
planes |>
  count(tailnum) |>
  filter(n > 1)
```

```{r}
weather |>
  count(time_hour, origin) |>
  filter(n > 1)
```

```{r}
planes |>
  filter(is.na(tailnum))

weather |>
  filter(is.na(time_hour) | is.na(origin))
```

```{r}
flights |>
  count(time_hour, carrier, flight) |>
  filter(n > 1)
```

```{r}
airports |>
  count(alt, lat) |>
  filter(n > 1)
```

```{r}
flights2 <- flights |>
  mutate(id = row_number(), .before = 1)
flights2
```

```{r}
flights2 <- flights |>
  select(year, time_hour, origin, dest, tailnum, carrier)
flights2
```

```{r}
flights2 |>
  left_join(airlines)
```

```{r}
flights2 |>
  left_join(weather |> select(origin, time_hour, temp, wind_speed))
```

```{r}
flights2 |>
  left_join(planes |> select(tailnum, type, engines, seats))
```

```{r}
flights2 |>
  left_join(planes |> select(tailnum, type, engines, seats)) |>
  filter(tailnum == "N3ALAA")
```

```{r}
flights2 |>
  left_join(planes, by = join_by(tailnum))
```

```{r}
flights2 |>
  left_join(airports, join_by(dest == faa))
```

```{r}
flights2 |>
  left_join(airports, join_by(origin == faa))
```

```{r}
airports |>
  semi_join(flights2, join_by(faa == origin))
```

```{r}
airports |>
  semi_join(flights2, join_by(faa == dest))
```

```{r}
flights2 |>
  anti_join(airports, join_by(dest == faa)) |>
  distinct(dest)
```

```{r}
flights |>
  anti_join(planes, join_by(tailnum)) |>
  distinct(tailnum)
```

```{r}
x <- tribble(
  ~key, ~val_x,
  1, "x1",
  2, "x2",
  3, "x3"
)
y <- tribble(
  ~key, ~val_y,
  1, "y1",
  2, "y2",
  4, "y3"
)
```

```{r}
df1 <- tibble(key = c(1, 2, 2), val_x = c("x1", "x2", "x3"))
df2 <- tibble(key = c(1, 2, 2), val_y = c("y1", "y2", "y3"))
```

```{r}
df1 |>
  inner_join(df2, join_by(key))
```

```{r}
df <- tibble(name = c("John", "Simon", "Tracy", "Max"))
df |> cross_join(df)
```

```{r}
df <- tibble(id = 1:4, name = c("John", "Simon", "Tracy", "Max"))

df |> left_join(df, join_by(id < id))
```

```{r}
parties <- tibble(
  q = 1:4,
  party = ymd(c("2022-01-10", "2022-04-04", "2022-07-11", "2022-10-03"))
)
parties
```

```{r}
employees <- tibble(
  name = sample(babynames::babynames$name, 100),
  birthday = ymd("2022-01-01") + (sample(365, 100, replace = TRUE) - 1)
)
employees
```

```{r}
employees |>
  left_join(parties, join_by(closest(birthday >= party)))
```

```{r}
employees |>
  anti_join(parties, join_by(closest(birthday >= party)))
```

```{r}
parties <- tibble(
  q = 1:4,
  party = ymd(c("2022-01-10", "2022-04-04", "2022-07-11", "2022-10-03")),
  start = ymd(c("2022-01-01", "2022-04-04", "2022-07-11", "2022-10-03")),
  end = ymd(c("2022-04-03", "2022-07-11", "2022-10-02", "2022-12-31"))
)
parties
```

```{r}
parties |>
  inner_join(parties, join_by(overlaps(start, end, start, end), q < q)) |>
  select(start.x, end.x, start.y, end.y)
```

```{r}
parties <- tibble(
  q = 1:4,
  party = ymd(c("2022-01-10", "2022-04-04", "2022-07-11", "2022-10-03")),
  start = ymd(c("2022-01-01", "2022-04-04", "2022-07-11", "2022-10-03")),
  end = ymd(c("2022-04-03", "2022-07-10", "2022-10-02", "2022-12-31"))
)
parties
```

```{r}
employees |>
  inner_join(parties, join_by(between(birthday, start, end)), unmatched = "error")
```
