---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
mpg
```

```{r}
ggplot(mpg, aes(displ, hwy, color = class)) +
  geom_point()
```

```{r}
ggplot(mpg, aes(displ, hwy, shape = class)) +
  geom_point()
```

```{r}
ggplot(mpg, aes(displ, hwy, size = class)) +
  geom_point()
```

```{r}
ggplot(mpg, aes(displ, hwy, alpha = class)) +
  geom_point()
```

```{r}
ggplot(mpg, aes(displ, hwy)) +
  geom_point(color = "blue")
```

```{r}
ggplot(mpg, aes(displ, hwy)) +
  geom_smooth()
```

```{r}
ggplot(mpg, aes(displ, hwy, shape = drv)) +
  # geom_point() +
  geom_smooth()
```

```{r}
ggplot(mpg, aes(displ, hwy, linetype = drv)) +
  geom_smooth()
```

```{r}
ggplot(mpg, aes(displ, hwy, color = drv)) +
  geom_point() +
  geom_smooth(aes(linetype = drv))
```

```{r}
# Left
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth()

# Middle
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth(aes(group = drv))

# Right
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth(aes(color = drv), show.legend = FALSE)
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth()
```

```{r}
ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_point(
    data = mpg |> filter(class == "2seater"),
    color = "red"
  ) +
  geom_point(
    data = mpg |> filter(class == "2seater"),
    shape = "circle open", size = 3, color = "red"
  )
```

```{r}
ggplot(mpg, aes(x = hwy)) +
  geom_histogram(binwidth = 2)

ggplot(mpg, aes(x = hwy)) +
  geom_density()

ggplot(mpg, aes(x = hwy)) +
  geom_boxplot()
```

```{r}
library(ggridges)
ggplot(mpg, aes(hwy, drv, fill = drv, color = drv)) +
  geom_density_ridges(alpha = 0.5, show.legend = FALSE)
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  facet_wrap(~cyl)
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ cyl)
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ cyl)
# facet_grid(drv ~ cyl, scales = "free_y")
# facet_grid(drv ~ cyl, scales = "free_x")
# facet_grid(drv ~ cyl, scales = "free")
```

```{r}
ggplot(diamonds, aes(x = cut)) +
  geom_bar()
```

```{r}
diamonds |>
  count(cut) |>
  ggplot(aes(cut, n)) +
  geom_bar(stat = "identity")
```

```{r}
ggplot(diamonds, aes(x = cut, y = after_stat(prop), group = 1)) +
  geom_bar()
```

```{r}
ggplot(diamonds) +
  stat_summary(
    aes(x = cut, y = depth),
    fun.min = min,
    fun.max = max,
    fun = median
  )
```

```{r}
# Left
ggplot(mpg, aes(x = drv, color = drv)) +
  geom_bar()

# Right
ggplot(mpg, aes(x = drv, fill = drv)) +
  geom_bar()
```

```{r}
ggplot(mpg, aes(x = drv, fill = class)) +
  geom_bar()
```

```{r}
# Left
ggplot(mpg, aes(x = drv, fill = class)) +
  geom_bar(alpha = 1 / 5, position = "identity")

# Right
ggplot(mpg, aes(x = drv, color = class)) +
  geom_bar(fill = NA, position = "identity")
```

```{r}
# Left
ggplot(mpg, aes(x = drv, fill = class)) +
  geom_bar(position = "fill")

# Right
ggplot(mpg, aes(x = drv, fill = class)) +
  geom_bar(position = "dodge")
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(position = "jitter")
```

```{r}
nz <- map_data("nz")

ggplot(nz, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "white", color = "black")

ggplot(nz, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "white", color = "black") +
  coord_quickmap()
```

```{r}
bar <- ggplot(data = diamonds) +
  geom_bar(
    mapping = aes(x = clarity, fill = clarity),
    show.legend = FALSE,
    width = 1
  ) +
  theme(aspect.ratio = 1)

bar
bar + coord_flip()
bar + coord_polar()
```
