---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
x <- c("one", "two", "three", "four", "five")
x[c(3, 2, 5)]
```

```{r}
x[c(1, 1, 5, 5, 5, 2)]
```

```{r}
x[c(-1, -3, -5)]
```

```{r}
x <- c(10, 3, NA, 5, 8, 1, NA)

x[!is.na(x)]

x[x %% 2 == 0]
```

```{r}
x <- c(abc = 1, def = 2, xyz = 5)
x[c("xyz", "def")]
```

```{r}
x[]
```

```{r}
df <- tibble(
  x = 1:3,
  y = c("a", "e", "f"),
  z = runif(3)
)
df
```

```{r}
df[1, 2]
```

```{r}
df[, c("x", "y")]
```

```{r}
df[df$x > 1, ]
```

```{r}
df1 <- data.frame(x = 1:3)
df1[, "x"]
df1[, "x", drop = FALSE]
```

```{r}
df
```

```{r}
df |> filter(x > 1)
```

```{r}
df[!is.na(df$x) & df$x > 1, ]
```

```{r}
df[which(df$x > 1), ]
```

```{r}
df |> arrange(desc(x), y)
df[order(-df$x, df$y), ]
```

```{r}
df |> select(x, z)
df[, c("x", "z")]
```

```{r}
df |>
  filter(x > 1) |>
  select(y, z)
```

```{r}
df |> subset(x > 1, c(y, z))
```

```{r}
tb <- tibble(
  x = 1:4,
  y = c(10, 4, 1, 21)
)

# by position
tb[[1]]

# by name
tb[["x"]]
tb$x
```

```{r}
tb$z <- tb$x + tb$y
tb
```

```{r}
max(diamonds$carat)
```

```{r}
levels(diamonds$cut)
```

```{r}
diamonds |>
  pull(carat) |>
  mean()
```

```{r}
diamonds |>
  pull(cut) |>
  levels()
```

```{r}
df <- data.frame(x1 = 1)
df$x
df$z
```

```{r}
tb <- tibble(x1 = 1)
tb$x
tb$z
```

```{r}
l <- list(
  a = 1:3,
  b = "a string",
  c = pi,
  d = list(-1, -5)
)
l
```

```{r}
str(l[1:2])
```

```{r}
str(l[1])
```

```{r}
str(l[4])
```

```{r}
str(l[[1]])
str(l[[4]])
str(l$a)
```

```{r}
df <- tibble(a = 1, b = 2, c = "a", d = "b", e = 4)
df
```

```{r}
num_cols <- sapply(df, is.numeric)
num_cols
```

```{r}
df[, num_cols] <- lapply(df[, num_cols, drop = FALSE], \(x) x * 2)
df
```

```{r}
vapply(df, is.numeric, logical(1))
```

```{r}
diamonds |>
  group_by(cut) |>
  summarize(price = mean(price))
```

```{r}
tapply(diamonds$price, diamonds$cut, mean)
```

```{r}
with(mtcars, data.frame(
  cyl = sort(unique(cyl)),
  mean = tapply(disp, cyl, mean),
  n = tapply(disp, cyl, length)
))
```

```{r}
with(
  aggregate(
    disp ~ cyl,
    mtcars,
    function(x) c(mean = mean(x), n = length(x))
  ),
  as.data.frame(cbind(cyl, disp))
)
```

```{r}
aggregate(
  disp ~ cyl,
  mtcars,
  function(x) c(mean = mean(x), n = length(x))
)
```

```{r}
dfs <- split(mtcars, mtcars$cyl) # ~ group_by
res <- t(sapply(dfs, function(df) c(mean(df$disp), length(df$disp)))) # ~ summarise
res <- as.data.frame(cbind(as.numeric(names(dfs)), res), # attach cyl values
  row.names = 1:nrow(res)
) # name rows
colnames(res) <- c("cyl", "mean", "n") # name cols
```

```{r}
as.data.frame(sapply(dfs, function(df) c(mean(df$disp), length(df$disp))) |> t())
```

```{r}
hist(diamonds$carat)
```

```{r}
plot(diamonds$carat, diamonds$price)
```
