---
title: "note07"
output: html_notebook
---

```{r}
x <- c(5, 12, 13)
for (n in x) print(n^2)
```

```{r}
i <- 1
while (i <= 10) i <- i + 4
i
```

```{r}
i <- 1
while (TRUE) {
  i <- i + 4
  if (i > 10) break
}
i
```

```{r}
i <- 1
repeat {
  i <- i + 4
  if (i > 10) break
}
i
```

```{r}
u <- matrix(c(1, 2, 3, 1, 2, 4), ncol = 2)
u
v <- matrix(c(8, 12, 20, 15, 10, 2), ncol = 2)
v
```

```{r}
for (m in c("u", "v")) {
  z <- get(m)
  print(lm(z[, 2] ~ z[, 1]))
}
```

```{r}
ls()
get("z")
```

```{r}
x <- 2
y <- if (x == 2) x else x + 1
y
```

```{r}
x <- 3
y <- if (x == 2) x else x + 1
y
```

```{r}
x <- 2
if (x == 2) y <- x else y <- x + 1
y
```

```{r}
10 %/% 3
```

```{r}
x <- c(TRUE, FALSE, TRUE)
y <- c(TRUE, TRUE, FALSE)
```

```{r}
x & y
x && y
```

```{r}
x | y
x || y
```

```{r}
oddcount <- function(x) {
  k <- 0
  for (n in x) {
    if (n %% 2 == 1) k <- k + 1
  }
  invisible(k)
}
oddcount(1:10)
```

```{r}
g <- function() {
  tt <- function(x) {
    return(x^2)
  }
  return(tt)
}

myfunc <- g()
```

```{r}
g <- function(x) {
  return(x + 1)
}
formals(g)
body(g)
```

```{r}
f1 <- function(a, b) {
  return(a + b)
}
f2 <- function(a, b) {
  return(a - b)
}
f <- f1
f(3, 2)
f <- f2
f(3, 2)
```

```{r}
g <- function(h, a, b) h(a, b)
g(f1, 3, 2)
g(f2, 3, 2)
```

```{r}
g1 <- function(x) {
  return(sin(x))
}
g2 <- function(x) {
  return(sqrt(x^2 + 1))
}
g3 <- function(x) {
  return(2 * x - 1)
}

list(g1, g2, g3)
```

```{r}
plot(c(0, 1), c(-1, 1.5))
for (f in c(g1, g2, g3)) curve(f, 0, 1, add = T)
```

```{r}
g <- function(h, a, b) h(a, b)
formals(g) <- alist(x = )
body(g) <- quote(2 * x + 3)
g
g(3)
```

```{r}
w <- 12
f <- function(y) {
  d <- 8
  h <- function() {
    return(d * (w + y))
  }
  return(h())
}
environment(f)
```

```{r}
ls()
```

```{r}
ls.str()
```

```{r}
f <- function(y) {
  d <- 8
  return(h(d, y))
}
h <- function(dee, yyy) {
  print(ls())
  print(ls(envir = parent.frame(n = 1)))
  return(dee * (w + yyy))
}
f(2)
```

```{r}
w <- 12
f <- function(y) {
  d <- 8
  w <- w + 1
  y <- y - 2
  print(w)
  h <- function() {
    return(d * (w + y))
  }
  return(h())
}
t <- 4
f(t)
w
t
```

```{r}
f <- function() {
  a <- 1
  return(g(a) + a)
}

g <- function(aa) {
  b <- 2
  aab <- h(aa + b)
  return(aab)
}
h <- function(aaa) {
  c <- 3
  return(aaa + c)
}
f()
```

```{r}
showframe <- function(upn) {
  # determine the proper environment
  if (upn < 0) {
    env <- .GlobalEnv
  } else {
    env <- parent.frame(n = upn + 1)
  }
  # get the list of variable names
  vars <- ls(envir = env)
  # for each variable name, print its value
  for (vr in vars) {
    vrg <- get(vr, envir = env)
    if (!is.function(vrg)) {
      cat(vr, ":\n", sep = "")
      print(vrg)
    }
  }
}
```

```{r}
g <- function(aa) {
  b <- 2
  showframe(0)
  showframe(1)
  aab <- h(aa + b)
  return(aab)
}
f()
```

```{r}
m <- rbind(1:3, 20:22)
m
get("m")
```

```{r}
two <- function(u) {
  u <<- 2 * u
  z <- 2 * z
}
x <- 1
z <- 3
two(x)
x
u
```

```{r}
f <- function() {
  inc <- function() {
    x <<- x + 1
  }
  x <- 3
  inc()
  return(x)
}
f()
f()
```

```{r}
two2 <- function(u) {
  assign("u", 2 * u, pos = .GlobalEnv)
  z <- 2 * z
}
two2(x)
x
u
```

```{r}
counter <- function() {
  ctr <- 0
  f <- function() {
    ctr <<- ctr + 1
    cat("this count currently has value", ctr, "\n")
  }
  return(f)
}
c1 <- counter()
c1()
```

```{r}
c1
```

```{r}
c2 <- counter()
c2
```

```{r}
qs <- function(x) {
  if (length(x) <= 1) {
    return(x)
  }
  pivot <- x[1]
  therest <- x[-1]
  sv1 <- therest[therest < pivot]
  sv2 <- therest[therest >= pivot]
  sv1 <- qs(sv1)
  sv2 <- qs(sv2)
  return(c(sv1, pivot, sv2))
}
v <- sample(1:10)
v
qs(v)
```

```{r}
x <- 1:3
names(x) <- c("a", "b", "ab")
x
```

```{r}
x <- "names<-"(x, value = c("a1", "b2", "ab3"))
x
```

```{r}
x <- c(8, 88, 5, 12, 13)
x[3]
"["(x, 3)
```

```{r}
x <- "[<-"(x, 2:3, value = 99:100)
x
```

```{r}
newbookvec <- function(x) {
  tmp <- list()
  tmp$vec <- x
  tmp$wrts <- rep(0, length(x))
  class(tmp) <- "bookvec"
  return(tmp)
}
"[.bookvec" <- function(bv, subs) {
  return(bv$vec[subs])
}

"[<-.bookvec" <- function(bv, subs, value) {
  bv$wrts[subs] <- bv$wrts[subs] + 1
  bv$vec[subs] <- value
  return(bv)
}

b <- newbookvec(c(3, 4, 5, 5, 12, 13))
b
```

```{r}
attr(b, "class")
```

```{r}
b[2]
```

```{r}
b[2] <- 88
b
```

```{r}
# edit(f)
```

```{r}
`%a2b%` <- function(a, b) {
  return(a + 2 * b)
}
3 %a2b% 5
```

```{r}
z <- matrix(1:6, nrow = 3)
z
```

```{r}
f <- function(x) x / c(2, 8)
y <- apply(z, 1, f)
y
```

```{r}
y <- apply(z, 1, function(x) x / c(2, 8))
y
```
