---
title: "note09"
output: html_notebook
---

```{r}
?lm
```

```{r}
x <- c(1, 2, 3)
y <- c(1, 3, 8)
lmout <- lm(y ~ x)
class(lmout)
lmout
```

```{r}
print
```

```{r}
str(unclass(lmout))
```

```{r}
methods(print)
```

```{r}
getAnywhere(print.lm)
```

```{r}
stats:::print.lm
```

```{r}
lm
```

```{r}
stats::lm.fit
```

```{r}
j <- list(name = "Joe", salary = 55000, union = T)
class(j) <- "employee"
attributes(j)
```

```{r}
j
```

```{r}
print.employee <- function(wrkr) {
  cat(wrkr$name, "\n")
  cat("salary", wrkr$salary, "\n")
  cat("union member", wrkr$union, "\n")
}
```

```{r}
j
```

```{r}
methods(, "employee")
```

```{r}
k <- list(name = "Kate", salary = 68000, union = F, hrsthismonth = 2)
class(k) <- c("hrlyemployee", "employee")
k
```

```{r}
sum1toi <- function(i) {
  return(i * (i + 1) / 2)
}

ut <- function(inmat) {
  n <- nrow(inmat)
  rtrn <- list()
  class(rtrn) <- "ut"
  rtrn$mat <- vector(length = sum1toi(n))
  rtrn$ix <- sum1toi(0:(n - 1)) + 1
  for (i in 1:n) {
    ixi <- rtrn$ix[i]
    rtrn$mat[ixi:(ixi + i - 1)] <- inmat[1:i, i]
  }
  return(rtrn)
}
u <- ut(rbind(1:2, c(0, 2)))
u
```

```{r}
expandut <- function(utmat) {
  n <- length(utmat$ix)
  fullmat <- matrix(nrow = n, ncol = n)
  for (j in 1:n) {
    start <- utmat$ix[j]
    fin <- start + j - 1
    abovediagj <- utmat$mat[start:fin]
    fullmat[, j] <- c(abovediagj, rep(0, n - j))
  }
  return(fullmat)
}
expandut(u)
```

```{r}
print.ut <- function(utmat) {
  print(expandut(utmat))
}
u
```

```{r}
"%mut%" <- function(utmat1, utmat2) {
  n <- length(utmat1$ix) # numbers of rows and cols of matrix
  utprod <- ut(matrix(0, nrow = n, ncol = n))
  for (i in 1:n) { # compute col i of product
    startbi <- utmat2$ix[i]
    # initialize vector that will become bi[1]*a[1] + ... + bi[i]*a[i]
    prodcoli <- rep(0, i)
    for (j in 1:i) { # find bi[j]*a[j], add to prodcoli
      startaj <- utmat1$ix[j]
      bielement <- utmat2$mat[startbi + j - 1]
      prodcoli[1:j] <- prodcoli[1:j] +
        bielement * utmat1$mat[startaj:(startaj + j - 1)]
    }
    # now need to tack on the lower 0s
    startprodcoli <- sum1toi(i - 1) + 1
    utprod$mat[startbi:(startbi + i - 1)] <- prodcoli
  }
  return(utprod)
}
```

```{r}
test <- function() {
  utm1 <- ut(rbind(1:2, c(0, 2)))
  utm2 <- ut(rbind(3:2, c(0, 1)))
  utp <- utm1 %mut% utm2
  print(utm1)
  print(utm2)
  print(utp)
  utm1 <- ut(rbind(1:3, 0:2, c(0, 0, 5)))
  utm2 <- ut(rbind(4:2, 0:2, c(0, 0, 1)))
  utp <- utm1 %mut% utm2
  print(utm1)
  print(utm2)
  print(utp)
}
test()
```

```{r}
polyfit <- function(y, x, maxdeg) {
  pwrs <- powers(x, maxdeg)
  lmout <- list()
  class(lmout) <- "polyreg"
  for (i in 1:maxdeg) {
    lmo <- lm(y ~ pwrs[, 1:i])
    lmo$fitted.cvvalues <- lvoneout(y, pwrs[, 1:i, drop = F])
    lmout[[i]] <- lmo
  }
  lmout$x <- x
  lmout$y <- y
  lmout
}



powers <- function(x, dg) {
  pw <- matrix(x, nrow = length(x))
  prod <- x
  for (i in 2:dg) {
    prod <- prod * x
    pw <- cbind(pw, prod)
  }
  return(pw)
}

lvoneout <- function(y, xmat) {
  n <- length(y)
  predy <- vector(length = n)
  for (i in 1:n) {
    # regress, leaving out ith observation
    lmo <- lm(y[-i] ~ xmat[-i, ])
    betahat <- as.vector(lmo$coef)
    predy[i] <- betahat %*% c(1, xmat[i, ])
  }
  return(predy)
}

poly <- function(x, cfs) {
  val <- cfs[1]
  prod <- 1
  dg <- length(cfs) - 1
  for (i in 1:dg) {
    prod <- prod * x
    val <- val + cfs[i + 1] * prod
  }
}

print.polyreg <- function(fits) {
  maxdeg <- length(fits) - 2
  n <- length(fits$y)
  tbl <- matrix(nrow = maxdeg, ncol = 1)
  colnames(tbl) <- "MSPE"
  for (i in 1:maxdeg) {
    fi <- fits[[i]]
    errs <- fits$y - fi$fitted.cvvalues
    spe <- crossprod(errs, errs) # sum of squared prediction errors
    tbl[i, 1] <- spe / n
  }
  cat("mean squared prediction errors, by degree\n")
  print(tbl)
}
```

```{r}
set.seed(123)
n <- 60
x <- (1:n) / n
y <- vector(length = n)
for (i in 1:n) y[i] <- sin((3 * pi / 2) * x[i]) + x[i]^2 + rnorm(1, mean = 0, sd = 0.5)
plot(x, y)
```

```{r}
dg <- 15
(lmo <- polyfit(y, x, dg))
```

```{r}
setClass(
  "employee",
  representation(
    name = "character",
    salary = "numeric",
    union = "logical"
  )
)
```

```{r}
joe <- new("employee", name = "Joe", salary = 55000, union = T)
joe
```

```{r}
joe@salary
```

```{r}
slot(joe, "salary")
```

```{r}
joe@salary <- 65000
joe
```

```{r}
slot(joe, "salary") <- 88000
joe
```

```{r}
try(joe@salry <- 48000)
```

```{r}
setMethod(
  "show", "employee",
  function(object) {
    inorout <- ifelse(object@union, "is", "is not")
    cat(object@name, "has a salary of", object@salary, "and", inorout, "in the union", "\n")
  }
)
show(joe)
joe
```

```{r}
ls()
```

```{r}
ls(pattern = "ut")
```

```{r}
rm(list = ls())
```

```{r}
ls()
```
