---
title: "note05"
output: html_notebook
---

# DATA FRAMES

```{r}
kids <- c("Jack", "Jill")
ages <- c(12, 10)
d <- data.frame(kids, ages)
d
```

```{r}
d[[1]]
d$kids
```

```{r}
d[, 1]
```

```{r}
str(d)
```

```{r}
examsquiz <- read.table("input/exams.txt", header = TRUE)
examsquiz
```

```{r}
examsquiz[2:5, ]
```

```{r}
examsquiz[2:5, 2]
```

```{r}
class(examsquiz[2:5, 2])
mode(examsquiz[2:5, 2])
typeof(examsquiz[2:5, 2])
```

```{r}
examsquiz[2:5, 2, drop = FALSE]
```

```{r}
class(examsquiz[2:5, 2, drop = FALSE])
mode(examsquiz[2:5, 2, drop = FALSE])
typeof(examsquiz[2:5, 2, drop = FALSE])
```

```{r}
examsquiz[examsquiz$Exam.1 > 3.8, ]
```

```{r}
subset(examsquiz, Exam.1 > 3.0)
```

```{r}
complete.cases(mtcars)
```

```{r}
d
rbind(d, list("Laura", 19))
```

```{r}
eq <- cbind(examsquiz, diff = examsquiz$Exam.2 - examsquiz$Exam.1)
eq
```

```{r}
names(eq)[4] <- "ExamDiff"
eq
```

```{r}
d
d$one <- 1
d
```

```{r}
apply(examsquiz, 1, max)
apply(examsquiz, 2, max)
```

```{r}
examsquiz$name <- letters[1:nrow(examsquiz)]
examsquiz
```

```{r}
apply(examsquiz, 2, max)
```

```{r}
all2006 <- read.csv("input/2006.csv", header = TRUE, as.is = TRUE)
all2006
```

```{r}
all2006 <- all2006[all2006$Wage_Per == "Year", ]
all2006 <- all2006[all2006$Wage_Offered_From > 20000, ]
all2006 <- all2006[all2006$Prevailing_Wage_Amount > 200, ]
all2006
```

```{r}
all2006$rat <- with(all2006, Wage_Offered_From / Prevailing_Wage_Amount)
```

```{r}
str(all2006)
```

```{r}
dplyr::glimpse(all2006)
```

```{r}
medrat <- function(dataframe) {
  return(median(dtaframe$rat, na.rm = TRUE))
}
```

```{r}
se2006 <- all2006[grep("Software Engineer", all2006$Prevailing_Wage_Job_Title), ]
prg2006 <- all2006[grep("Computer", all2006$Prevailing_Wage_Job_Title), ]
ee2006 <- all2006[grep("Electrician", all2006$Prevailing_Wage_Job_Title), ]
se2006
prg2006
ee2006
```

```{r}
makecor <- function(corpname) {
  t <- all2006[all2006$Employer_Name == corpname, ]
  return(t)
}
```

```{r}
corplist <- c("YOMIWURI, INC.", "yomiwuri", "CLC OF CHANTILLY", "clc", " JPSC INC", "jpsc", "GOOGLE INC.", "google")
for (i in 1:(length(corplist) / 2)) {
  corp <- corplist[2 * i - 1]
  newdtf <- paste(corplist[2 * i], "2006", sep = "")
  assign(newdtf, makecor(corp), pos = .GlobalEnv)
}
```

```{r}
ls()
```

```{r}
dl <- lapply(d, sort)
dl
```
