---
title: "note02"
output: html_notebook
---

```{r}
x <- c(88, 5, 12, 13)
x <- c(x[1:3], 168, x[4])
x
```

```{r}
x <- c(1, 2, 4)
length(x)
```

```{r}
first1 <- function(x) {
  for (i in 1:length(x)) {
    if (x[i] == 1) break
  }
  return(i)
}
```

```{r}
x <- c()
x
length(x)
1:length(x)
```

```{r}
m <- matrix(c(1, 3, 2, 4), nrow = 2)
m
```

```{r}
m + 10:13
```

```{r}
y <- vector(length = 2)
y[1] <- 5
y[2] <- 12
```

```{r}
c(1, 2, 4) + c(6, 0, 9, 20, 22)
```

```{r}
x <- matrix(1:6, nrow = 3)
x + c(1, 2)
```

```{r}
2 + 3
`+`(2, 3)
```

```{r}
x <- c(1, 2, 4)
x + c(5, 0, -1)
x * c(5, 0, -1)
```

```{r}
x <- c(1, 2, 4)
x / c(5, 4, -1)
```

```{r}
y <- c(1.2, 3.9, 0.4, 0.12)
y[c(1, 3)]
```

```{r}
y[2:3]
```

```{r}
v <- 3:4
y[v]
```

```{r}
x <- c(4, 2, 17, 5)
y <- x[c(1, 1, 3)]
y
```

```{r}
z <- c(5, 12, 13)
z[-1]
```

```{r}
z[-(1:2)]
```

```{r}
i <- 2
1:i - 1
1:(i - 1)
```

```{r}
seq(from = 12, to = 30, by = 3)
```

```{r}
seq(from = 1.1, to = 2, length = 10)
```

```{r}
x <- c(5, 12, 13)
x <- c(5, 12, 13)
seq(x)
x <- NULL
seq(x)
```

```{r}
seq_along(double(0))
```

```{r}
x <- rep(8, 4)
x
```

```{r}
rep(c(5, 12, 13), 3)
```

```{r}
rep(1:3, 2)
```

```{r}
rep(c(5, 12, 13), each = 2)
```

```{r}
x <- 1:10
any(x > 8)
all(x > 88)
all(x > 88)
all(x > 0)
```

```{r}
findruns <- function(x, k) {
  n <- length(x)
  runs <- NULL
  for (i in 1:(n - k + 1)) {
    if (all(x[i:(i + k - 1)] == TRUE)) runs <- c(runs, i)
  }
  return(runs)
}
```

```{r}
y <- c(1, 0, 0, 1, 1, 1, 0, 1, 1)
findruns(y, 3)
findruns(y, 2)
findruns(y, 6)
```

```{r}
findruns1 <- function(x, k) {
  n <- length(x)
  runs <- vector(length = n)
  count <- 0
  for (i in 1:(n - k + 1)) {
    if (all(x[i:(i + k - 1)] == 1)) {
      count <- count + 1
      runs[count] <- i
    }
  }
  if (count > 0) {
    runs <- runs[1:count]
  } else {
    runs <- NULL
  }
  runs
}
findruns1(y, 3)
findruns1(y, 2)
findruns1(y, 6)
```

```{r}
preda <- function(x, k) {
  n <- length(x)
  k2 <- k / 2
  pred <- vector(length = n - k)
  for (i in 1:(n - k)) {
    if (sum(x[i:(i + (k - 1))]) >= k2) pred[i] <- 1 else pred[i] <- 0
  }
  return(mean(abs(pred - x[(k + 1):n])))
}
```

```{r}
predb <- function(x, k) {
  n <- length(x)
  k2 <- k / 2
  pred <- vector(length = n - k)
  sm <- sum(x[1:k])
  if (sm >= k2) pred[1] <- 1 else pred[1] <- 0
  if (n - k >= 2) {
    for (i in 2:(n - k)) {
      sm <- sm + x[i + k - 1] - x[i - 1]
      if (sm >= k2) pred[i] <- 1 else pred[i] <- 0
    }
  }
  return(mean(abs(pred - x[(k + 1):n])))
}
```

```{r}
predc <- function(x, k) {
  n <- length(x)
  k2 <- k / 2
  pred <- vector(length = n - k)
  csx <- c(0, cumsum(x))
  for (i in 1:(n - k)) {
    if (csx[i + k] - csx[i] >= k2) pred[i] <- 1 else pred[i] <- 0
  }
  return(mean(abs(pred - x[(k + 1):n])))
}
```

```{r}
x <- sample(0:1, 1000, replace = TRUE)
x
```

```{r}
bench::mark(
  preda(x, 3),
  predb(x, 3),
  predc(x, 3)
)
```

```{r}
u <- c(5, 2, 8)
v <- c(1, 3, 9)
u > v
```

```{r}
sqrt(1:9)
```

```{r}
y <- c(1.2, 3.9, 0.4)
z <- round(y)
z
```

```{r}
f <- function(x, c) {
  stopifnot("Vector c not allowed" = length(c) == 1)
  (x + c)^2
}
try(f(1:3, 1:3))
```

```{r}
x <- 1:8
z12 <- function(z) {
  return(c(z, z^2))
}
z12(x)
```

```{r}
# z12 <- function(z) return(z, z^2))

z12 <- function(z) {
  return(c(z, z^2))
}

sapply(x, z12)
```

```{r}
z
```

```{r}
x <- c(88, NA, 12, 168, 13)
x
mean(x)
mean(x, na.rm = TRUE)
x <- c(88, NULL, 12, 168, 13)
mean(x)
```

```{r}
x <- c(5, NA, 12)
mode(x[1])
mode(x[2])
typeof(x[1])
typeof(x[2])
```

```{r}

y <- c("abc", "def", NA)
mode(y[2])
mode(y[3])
typeof(y[2])
typeof(y[3])
```

```{r}
z <- NULL
for (i in 1:10) if (i %% 2 == 0) z <- c(z, i)
z
```

```{r}
z <- NA
for (i in 1:10) if (i %% 2 == 0) z <- c(z, i)
z
```

```{r}
u <- NULL
length(u)
v <- NA
length(v)
```

```{r}
z <- c(5, 2, -3, 8)
w <- z[z * z > 8]
w
```

```{r}
z * z > 8
```

```{r}
z[c(TRUE, FALSE, TRUE, TRUE)]
```

```{r}
x <- c(6, 1:3, NA, 12)
x[x > 5]
subset(x, x > 5)
```

```{r}
z <- c(5, 2, -3, 8)
which(z * z > 8)
```

```{r}
z * z > 8
```

```{r}
x <- rpois(10, 5)
x
first1a <- function(x) {
  return(which(x == 1)[1])
}
first1a(x)
```

```{r}
x <- 1:10
y <- ifelse(x %% 2 == 0, 5, 12)
y
```

```{r}
findud <- function(v) {
  vud <- v[-1] - v[-length(v)]
  return(ifelse(vud > 0, 1, -1))
}

udcorr <- function(x, y) {
  ud <- lapply(list(x, y), findud)
  return(mean(ud[[1]] == ud[[2]]))
}

x <- c(5, 12, 13, 3, 6, 0, 1, 15, 16, 8, 88)
y <- c(4, 2, 3, 23, 6, 10, 11, 12, 6, 3, 2)
udcorr(x, y)
```

```{r}
mean(findud(x) == findud(y))
```

```{r}
x
diff(x)
sign(diff(x))
```

```{r}
g <- c("M", "F", "F", "I", "M", "M", "F")
ifelse(g == "M", 1, ifelse(g == "F", 2, 3))
```

```{r}
args(ifelse)
```

```{r}
m <- which(g == "M")
f <- which(g == "F")
i <- which(g == "I")
```

```{r}
grps <- list()
for (gen in c("M", "F", "I")) grps[[gen]] <- which(g == gen)
grps
```

```{r}
x <- 1:3
y <- c(1, 3, 4)
x == y
```

```{r}
x <- 1:2
y <- c(1, 2)
x
y
identical(x, y)
typeof(x)
typeof(y)
```

```{r}
x <- c(1, 2, 4)
names(x)
names(x) <- c("a", "b", "ab")
names(x)
x
```

```{r}
x["b"]
```

```{r}
c(5, 2, "abc")
```

```{r}
c(4, 2, list(a = 1, b = 4))
```

```{r}
c(5, 2, c(1.5, 6))
```
