---
title: "note06"
output: html_notebook
---

```{r}
x <- c(5, 12, 13, 12)
xf <- factor(x)
xf
```

```{r}
str(xf)
```

```{r}
unclass(xf)
```

```{r}
attr(xf, "levels")
```

```{r}
length(xf)
```

```{r}
xff <- factor(x, levels = c(5, 12, 13, 88))
xff
```

```{r}
xff[2] <- 88
xff
```

```{r}
ages <- c(25, 26, 55, 37, 21, 42)
affils <- c("R", "D", "D", "R", "U", "D")
tapply(ages, affils, mean)
```

```{r}
d <- data.frame(list(
  gender = c("M", "M", "F", "M", "F", "F"),
  age = c(47, 59, 21, 32, 33, 24),
  income = c(55000, 88000, 32450, 76500, 123000, 45650)
))
d
```

```{r}
d$over25 <- ifelse(d$age > 25, 1, 0)
d
```

```{r}
tapply(d$income, list(d$gender, d$over25), mean)
```

```{r}
library(dplyr)
d %>%
  group_by(gender, over25) %>%
  summarize(mean = mean(income), .groups = "drop")
```

```{r}
by_g25 <- split(d$income, list(d$gender, d$over25))
by_g25
```

```{r}
sapply(by_g25, mean)
```

```{r}
g <- c("M", "F", "F", "I", "M", "M", "F")
split(1:7, g)
```

```{r}
text <- "the here means that the first item in this line of output is
item in this case our output consists of only one line and one
item so this is redundant but this notation helps to read
voluminous output that consists of many items spread over many
lines for example if there were two rows of output with six items
per row the second row would be labeled"

txt <- text |>
  gsub(text, pattern = "\n", replacement = "  ") |>
  strsplit(split = " +") |>
  unlist()
txt
```

```{r}
words <- split(1:length(txt), txt)
words
```

```{r}
aba <- read.csv("input/abalone.data", header = TRUE)
aba
```

```{r}
by(aba, aba$M, function(m) lm(m[, 2] ~ m[, 3]))
```

```{r}
u <- c(22, 8, 33, 6, 8, 29, -2)
fl <- list(x1 = c(5, 12, 13, 12, 13, 5, 13), x2 = c("a", "bc", "a", "a", "bc", "a", "a"))
df <- data.frame(u = u, fl)
df
```

```{r}
with(df, tapply(u, list(x1, x2), length))
```

```{r}
df %>%
  group_by(x1, x2) %>%
  summarize(length = length(u), .groups = "drop")
```

```{r}
table(fl)
```

```{r}
ct <- data.frame(
  Vote.for.X = c("Yes", "Yes", "No", "Not Sure", "No"),
  Vote.for.X.Last.Time = c("Yes", "No", "No", "Yes", "No")
)
ct
```

```{r}
cttab <- table(ct)
cttab
```

```{r}
table(c(5, 12, 13, 12, 8, 5))
```

```{r}
class(cttab)
str(cttab)
```

```{r}
cttab[1, 1]
cttab[1, ]
```

```{r}
cttab / 5
```

```{r}
ctt <- cttab

apply(cttab, 1, sum)
```

```{r}
str(addmargins(ctt))
```

```{r}
dimnames(ctt)
```

```{r}
cttab
```

```{r}
subtable <- function(tbl, subnames) {
  # get array of cell counts in tbl
  tblarray <- unclass(tbl)
  # we'll get the subarray of cell counts corresponding to subnames by
  # calling do.call() on the "[" function; we need to build up a list
  # of arguments first
  dcargs <- list(unclass(tblarray))
  ndims <- length(subnames) # number of dimensions
  for (i in 1:ndims) {
    dcargs[[i + 1]] <- subnames[[i]]
  }
  subarray <- do.call("[", dcargs)
  # now we'll build the new table, consisting of the subarray, the
  # numbers of levels in each dimension, and the dimnames() value, plus
  # the "table" class attribute
  dims <- lapply(subnames, length)
  subtbl <- array(subarray, dims, dimnames = subnames)
  class(subtbl) <- "table"
  return(subtbl)
}
```

```{r}
cond <- list(Vote.for.X = c("No", "Not Sure"), Voted.for.X.Last.Time = c("No", "Yes"))
subtable(cttab, cond)
```

```{r}
d <- c(5, 12, 13, 4, 3, 28, 12, 12, 9, 5, 5, 13, 5, 4, 12)
dtab <- table(d)
dtab
```

```{r}
df <- data.frame(d = d)
df %>%
  group_by(d) %>%
  count() %>%
  arrange(desc(n))
```

```{r}
df2 <- as.data.frame(cttab)

df2 %>%
  arrange(desc(Freq))
```

```{r}
tabdom <- function(tbl, k) {
  # create a data frame representation of tbl, adding a Freq column
  tbldf <- as.data.frame(tbl)
  # determine the proper positions of the frequencies in a sorted order
  freqord <- order(tbldf$Freq, decreasing = TRUE)
  # rearrange the data frame in that order, and take the first k rows
  dom <- tbldf[freqord, ][1:k, ]
  return(dom)
}
tabdom(cttab, 3)
```

```{r}
aba
names(aba)[1] <- "Gender"
aggregate(aba[, -1], list(aba$Gender), median)
```

```{r}
aba %>%
  group_by(Gender) %>%
  summarize(across(where(is.numeric), median))
```

```{r}
z <- c(0.88114802, 0.28532689, 0.58647376, 0.42851862, 0.46881514, 0.24226859, 0.05289197, 0.88035617)

binmarks <- seq(0, 1, by = 0.2)
binned <- cut(z, binmarks, include.lowest = TRUE, right = FALSE)
str(binned)
```

```{r}
str(cut(z, binmarks, include.lowest = TRUE, right = FALSE, labels = F))
```
