---
title: "R Notebook"
output: html_notebook
---

```{r}
### blind.R file ###
# full bind search method
# search - matrix with solutions x D
# fn - evaluation function
# type - "min" or "max"
# ... - extra parameters for fn
fsearch <- function(search, fn, type = "min", ...) {
  x <- apply(search, 1, fn, ...) # run fn over all search rows
  ib <- switch(type,
    min = which.min(x),
    max = which.max(x)
  )
  return(list(index = ib, sol = search[ib, ], eval = x[ib]))
}
```

```{r}
# depth-first full search method
# l - level of the tree
# b - branch of the tree
# domain - vector list of size D with domain values
# fn - eval function
# type - "min" or "max"
# D - dimension (number of variables)
# par - current parameters of solution vector
# bcur - current best sol
# ... - extra parameters for fn
dfsearch <- function(
    l = 1,
    b = 1,
    domain,
    fn,
    type = "min",
    D = length(domain),
    par = rep(NA, D),
    bcur = switch(type,
      min = list(sol = NULL, eval = Inf),
      max = list(sol = NULL, eval = -Inf)
    ),
    ...) {
  if ((l - 1) == D) { # "leave" with solution par to be tested:
    f <- fn(par, ...)
    fb <- bcur$eval
    ib <- switch(type,
      min = which.min(c(fb, f)),
      max = which.max(c(fb, f))
    )
    if (ib == 1) {
      return(bcur)
    } else {
      return(list(sol = par, eval = f))
    }
  } else {
    for (j in 1:length(domain[[l]])) # go through sub branches
    {
      par[l] <- domain[[l]][j]
      bcur <- dfsearch(l + 1, j, domain, fn, type,
        D = D,
        par = par, bcur = bcur, ...
      )
    }
    return(bcur)
  }
}
```

```{r}
binint <- function(x, D) {
  x <- rev(intToBits(x)[1:D]) # get D bits
  # remove extra 0s from raw type:
  as.numeric(unlist(strsplit(as.character(x), ""))[(1:D) * 2])
}


# convert binary vector into integer: code inspired in
# http://stackoverflow.com/questions/12892348/
# in-r-how-to-convert-binary-string-to-binary-or-decimal-value
intbin <- function(x) sum(2^(which(rev(x == 1)) - 1))
# sum a raw binary object x (evaluation function):
sumbin <- function(x) sum(as.numeric(x))
# max sin of binary raw object x (evaluation function):
maxsin <- function(x, Dim) sin(pi * (intbin(x)) / (2^Dim))
D <- 8 # number of dimensions
x <- 0:(2^D - 1) # integer search space
# set full search space in solutions x D:
search <- t(sapply(x, binint, D = D))
```

```{r}
# set the domain values (D binary variables):
domain <- vector("list", D)
for (i in 1:D) domain[[i]] <- c(0, 1) # bits
# sum of bits, fsearch:
```

```{r}
S1 <- fsearch(search, sumbin, "max") # full search
cat("fsearch best s:", S1$sol, "f:", S1$eval, "\n")
```

```{r}
# sum of bits, dfsearch:
S2 <- dfsearch(domain = domain, fn = sumbin, type = "max")
cat("dfsearch best s:", S2$sol, "f:", S2$eval, "\n")
```

```{r}
# max sin, fsearch:
Dim <- length(search[1, ]) # set Dim argument of maxim
S3 <- fsearch(search, maxsin, "max", Dim = Dim) # Dim used by maxsin
cat("fsearch best s:", S3$sol, "f:", S3$eval, "\n")
```

```{r}
# max sin, dfsearch: Dim is used by maxin
S4 <- dfsearch(domain = domain, fn = maxsin, type = "max", Dim = Dim)
cat("dfsearch best s:", S4$sol, "f:", S4$eval, "\n")
```

```{r}
source("Rcode/functions.R")
# auxiliary function that sets the optimum price for
# one bag type (D), assuming an independent influence of
# a particular price on the remaining bag prices:
ibag <- function(D) # D - type of bag
{
  x <- 1:1000 # price for each bag type
  # set search space for one bag:
  search <- matrix(ncol = 5, nrow = 1000)
  search[] <- 1
  search[, D] <- x
  S1 <- fsearch(search, profit, "max")
  S1$sol[D] # best price
}
```

```{r}
D <- 2
x <- 1:1000 # price for each bag type
# set search space for one bag:
search <- matrix(ncol = 5, nrow = 1000)
search[] <- 1
search[, D] <- x
search
```

```{r}
S1 <- fsearch(search, profit, "max")
S1$sol[D] # best price
```

```{r}
# compute the best price for all bag types:
S <- sapply(1:5, ibag)
# show the optimum solution:
cat("optimum s:", S, "f:", profit(S), "\n")
```

### 3.3 Grid Search

```{r}
### grid.R file ###

# standard grid search method (uses fsearch)
#    fn - evaluation function
#    lower - vector with lowest values for each dimension
#    upper - vector with highest values for each dimension
#    step - vector with step size for each dimension D
#    type - "min" or "max"
#    ... - extra parameters for fn
gsearch <- function(fn, lower, upper, step, type = "min", ...) {
  D <- length(step) # dimension
  domain <- vector("list", D) # domain values
  L <- vector(length = D) # auxiliary vector
  for (i in 1:D)
  {
    domain[[i]] <- seq(lower[i], upper[i], by = step[i])
    L[i] <- length(domain[[i]])
  }
  LS <- prod(L)
  s <- matrix(ncol = D, nrow = LS) # set the search space
  for (i in 1:D)
  {
    if (i == 1) E <- 1 else E <- E * L[i - 1]
    s[, i] <- rep(domain[[i]], length.out = LS, each = E)
  }
  fsearch(s, fn, type, ...) # best solution
}

# standard grid search method (uses dfsearch)
gsearch2 <- function(fn, lower, upper, step, type = "min", ...) {
  D <- length(step) # dimension
  domain <- vector("list", D) # domain values
  for (i in 1:D) domain[[i]] <- seq(lower[i], upper[i], by = step[i])
  dfsearch(domain = domain, fn = fn, type = type, ...) # solution
}

# nested grid search method (uses fsearch)
#    levels - number of nested levels
ngsearch <- function(fn, lower, upper, levels, step, type, ...) {
  stop <- FALSE
  i <- 1 # auxiliary objects
  bcur <- switch(type,
    min = list(sol = NULL, eval = Inf),
    max = list(sol = NULL, eval = -Inf)
  )
  while (!stop) # cycle while stopping criteria is not met
  {
    s <- gsearch(fn, lower, upper, step, type, ...)
    # if needed, update best current solution:
    if ((type == "min" && s$eval < bcur$eval) ||
      (type == "max" && s$eval > bcur$eval)) {
      bcur <- s
    }
    if (i < levels) # update step, lower and upper:
      {
        step <- step / 2
        interval <- (upper - lower) / 4
        lower <- sapply(lower, max, s$sol - interval)
        upper <- sapply(upper, min, s$sol + interval)
      }
    if (i >= levels || sum((upper - lower) <= step) > 0) {
      stop <- TRUE
    } else {
      i <- i + 1
    }
  }
  return(bcur) # best solution
}
```

```{r}
#| warning: false
setwd("Rcode")
getwd()
source("blind.R") # load the blind search methods
source("grid.R") # load the grid search methods
source("functions.R") # load the profit function
# grid search for all bag prices, step of 100$
PTM <- proc.time() # start clock
S1 <- gsearch(profit, rep(1, 5), rep(1000, 5), rep(100, 5), "max")
sec <- (proc.time() - PTM)[3] # get seconds elapsed
cat("gsearch best s:", S1$sol, "f:", S1$eval, "time:", sec, "s\n")
```

```{r}
53
PTM <- proc.time() # start clock
S2 <- gsearch2(profit, rep(1, 5), rep(1000, 5), rep(100, 5), "max")
sec <- (proc.time() - PTM)[3] # get seconds elapsed
cat("gsearch2 best s:", S2$sol, "f:", S2$eval, "time:", sec, "s\n")
```

```{r}
# nested grid with 3 levels and initial step of 500$
PTM <- proc.time() # start clock
S3 <- ngsearch(profit, rep(1, 5), rep(1000, 5), 3, rep(100, 5), "max")
sec <- (proc.time() - PTM)[3] # get seconds elapsed
```

```{r}
cat("ngsearch best s:", S3$sol, "f:", S3$eval, "time:", sec, "s\n")
```

```{r}
setwd("Rcode")
source("real-grid.R")
```

```{r}
setwd("Rcode")
source("test-mc.R")
```

```{r}
setwd("Rcode")
source("blind.R") # load the blind search methods
source("montecarlo.R") # load the monte carlo method
source("functions.R") # load the profit function
```

```{r}
mcsearch <- function(fn, lower, upper, N, type = "min", ...) {
  D <- length(lower)
  s <- matrix(nrow = N, ncol = D) # set the search space
  for (i in 1:N) s[i, ] <- runif(D, lower, upper)
  fsearch(s, fn, type, ...) # best solution
}
```

```{r}
N <- 100000 # set the number of samples
cat("monte carlo search (N:", N, ")\n")

# bag prices
cat("bag prices:")
S <- mcsearch(profit, rep(1, 5), rep(1000, 5), N, "max")
cat("s:", S$sol, "f:", S$eval, "\n")
```

```{r}
# real-value functions: sphere and rastrigin:
sphere <- function(x) sum(x^2)
rastrigin <- function(x) 10 * length(x) + sum(x^2 - 10 * cos(2 * pi * x))

D <- c(2, 30)
label <- "sphere"
for (i in 1:length(D))
{
  S <- mcsearch(sphere, rep(-5.2, D[i]), rep(5.2, D[i]), N, "min")
  cat(label, "D:", D[i], "s:", S$sol[1:2], "f:", S$eval, "\n")
}
label <- "rastrigin"
for (i in 1:length(D))
{
  S <- mcsearch(rastrigin, rep(-5.2, D[i]), rep(5.2, D[i]), N, "min")
  cat(label, "D:", D[i], "s:", S$sol[1:2], "f:", S$eval, "\n")
}
```

