---
title: "note06"
output: html_notebook
---

# 6 Modeling Discontinuous and Nonlinear Change

## 6.1 Discontinuous individual change

```{r}
library(tidyverse)
```

```{r}
wages_pp <- read_csv("data/wages_pp.csv")
wages_pp
```

```{r}
wages_pp %>%
  select(id, lnw, exper, ged, postexp) %>%
  mutate(`ged by exper` = ged * exper) %>%
  filter(id %in% c(206, 2365, 4384))
```

```{r}
wages_pp %>%
  filter(id %in% c(206, 2365, 4384)) %>%
  mutate(id = factor(id)) %>%
  ggplot(aes(exper, lnw)) +
  geom_point(aes(color = id), size = 4) +
  geom_line(aes(color = id)) +
  geom_text(aes(label = ged), size = 3) +
  scale_x_continuous(breaks = 0:13) +
  scale_color_viridis_d(option = "B", begin = .6, end = .9) +
  labs(caption = expression(italic("Note") * ': GED status is coded 0 = "not yet", 1 = "yes."')) +
  theme(
    panel.grid = element_blank(),
    plot.caption = element_text(hjust = 0)
  )
```

```{r}
wages_pp %>%
  group_by(id) %>%
  summarize(got_ged = sum(ged) > 0) %>%
  count(got_ged)
```

```{r}
wages_pp %>%
  filter(ged == 1) %>%
  group_by(id) %>%
  slice(1) %>%
  ggplot(aes(exper)) +
  geom_histogram(binwidth = 0.5) +
  labs(subtitle = expression(The ~ italic(timing) ~ of ~ the ~ the ~ GED ~ attainment ~ varies)) +
  theme(panel.grid = element_blank())
```

```{r}
wages_pp %>%
  select(id, lnw, exper, ged, postexp) %>%
  filter(id %in% c(206, 2365, 4384)) %>%
  mutate(id = factor(id)) %>%
  ggplot(aes(exper, ged)) +
  geom_point(aes(color = id), size = 4) +
  scale_x_continuous(breaks = 1:13) +
  scale_y_continuous(breaks = 0:1, limits = c(-0.2, 1.2)) +
  scale_color_viridis_d(option = "B", begin = .6, end = .9, breaks = NULL) +
  facet_wrap(~id) +
  theme(
    panel.grid = element_blank(),
    plot.caption = element_text(hjust = 0)
  )
```

```{r}
tibble(
  exper = c(0, 3, 3, 10),
  ged = rep(0:1, each = 2)
) %>%
  expand(
    model = letters[1:4],
    nesting(exper, ged)
  ) %>%
  mutate(exper2 = if_else(ged == 0, 0, exper - 3)) %>%
  mutate(lnw = case_when(
    model == "a" ~ 1.60 + 0.04 * exper,
    model == "b" ~ 1.65 + 0.04 * exper + 0.05 * ged,
    model == "c" ~ 1.75 + 0.04 * exper + 0.02 * exper2 * ged,
    model == "d" ~ 1.85 + 0.04 * exper + 0.01 * ged + 0.02 * exper * ged,
  ), model = fct_rev(model)) %>%
  ggplot(aes(exper, lnw)) +
  geom_line(aes(color = model), size = 1) +
  scale_color_viridis_d(option = "D", begin = 1 / 4, end = 3 / 4) +
  ylim(1.5, 2.5) +
  theme(panel.grid.minor = element_blank())
```

```{r}
plot_figure_6.2 <- function(data, mapping,
                            sizes = c(1, 1 / 4),
                            linetypes = c(1, 2),
                            ...) {
  ggplot(data, mapping) +
    geom_line(aes(size = model, linetype = model)) +
    geom_text(
      data = text,
      aes(label = label, hjust = hjust),
      size = 3, parse = T
    ) +
    geom_segment(
      data = arrow,
      aes(xend = xend, yend = yend),
      arrow = arrow(length = unit(0.075, "inches"), type = "closed"),
      size = 1 / 4
    ) +
    scale_size_manual(values = sizes) +
    scale_linetype_manual(values = linetypes) +
    scale_x_continuous(expand = expansion(mult = c(0, 0.05))) +
    scale_y_continuous(breaks = 0:4 * 0.2 + 1.6, expand = c(0, 0)) +
    coord_cartesian(ylim = c(1.6, 2.4)) +
    theme(
      legend.position = "none",
      panel.grid = element_blank()
    )
}

text <-
  tibble(
    exper = c(4.5, 4.5, 7.5, 7.5, 1),
    lnw = c(2.24, 2.2, 1.82, 1.78, 1.62),
    label = c(
      "Common~rate~of~change",
      "Pre-Post~GED~(pi[1][italic(i)])",
      "Elevation~differential",
      "on~GED~receipt~(pi[2][italic(i)])",
      "italic(LNW)~at~labor~force~entry~(pi[0][italic(i)])"
    ),
    hjust = c(.5, .5, .5, .5, 0)
  )

arrow <-
  tibble(
    exper = c(2.85, 5.2, 5.5, 1.7),
    xend = c(2, 6.8, 3.1, 0.05),
    lnw = c(2.18, 2.18, 1.8, 1.64),
    yend = c(1.84, 2.08, 1.9, 1.74)
  )

p1 <-
  tibble(
    exper = c(0, 3, 3, 10),
    ged = rep(0:1, each = 2)
  ) %>%
  expand(
    model = letters[1:2],
    nesting(exper, ged)
  ) %>%
  mutate(exper2 = if_else(ged == 0, 0, exper - 3)) %>%
  mutate(
    lnw = case_when(
      model == "a" ~ 1.75 + 0.04 * exper,
      model == "b" ~ 1.75 + 0.04 * exper + 0.05 * ged
    ),
    model = fct_rev(model)
  ) %>%
  plot_figure_6.2(aes(x = exper, y = lnw))
p1
```

```{r}
wages_pp %>%
  select(id, ged, exper, postexp) %>%
  filter(id >= 53)
```

```{r}
wages_pp_subset <-
  wages_pp %>%
  group_by(id) %>%
  filter(mean(ged) > 0) %>%
  filter(mean(ged) < 1) %>%
  ungroup() %>%
  select(id, ged, exper, postexp)
wages_pp_subset
```

```{r}
wages_pp_subset %>%
  filter(ged == 1) %>%
  group_by(id) %>%
  mutate(
    min_exper = min(exper),
    `exper - postexp` = exper - postexp
  )
```

```{r}
wages_pp_subset %>%
  filter(ged == 1) %>%
  group_by(id) %>%
  mutate(
    min_exper = min(exper),
    `exper - postexp` = exper - postexp
  ) %>%
  mutate(`exper - min_exper` = exper - min_exper)
```

```{r}
wages_pp %>%
  group_by(id) %>%
  filter(mean(ged) > 0 & mean(ged) < 1) %>%
  ungroup() %>%
  pivot_longer(c(exper, postexp), names_to = "temporal predictor") %>%
  filter(id < 250) %>%
  ggplot(aes(value, lnw)) +
  geom_line(aes(linetype = `temporal predictor`, color = `temporal predictor`)) +
  scale_color_viridis_d(option = "A", begin = 1 / 3, end = 2 / 3, direction = -1) +
  facet_wrap(~id, scales = "free_x") +
  theme(
    legend.position = c(5 / 6, .25),
    panel.grid = element_blank()
  )
```

```{r}
text <-
  tibble(
    exper = c(5, 5, 0.5, 0.5, 1),
    lnw = c(2.24, 2.2, 2, 1.96, 1.62),
    label = c(
      "Slope~differential",
      "Pre-Post~GED~(pi[3][italic(i)])",
      "Rate~of~change",
      "Pre~GED~(pi[1][italic(i)])",
      "italic(LNW)~at~labor~force~entry~(pi[0][italic(i)])"
    ),
    hjust = c(.5, .5, 0, 0, 0)
  )

arrow <-
  tibble(
    exper = c(5.2, 1.7, 1.7),
    xend = c(9.1, 1.7, 0.05),
    lnw = c(2.18, 1.93, 1.64),
    yend = c(2.15, 1.84, 1.74)
  )

p2 <-
  tibble(
    exper = c(0, 3, 3, 10),
    ged = rep(0:1, each = 2)
  ) %>%
  expand(
    model = letters[1:2],
    nesting(exper, ged)
  ) %>%
  mutate(postexp = ifelse(exper == 10, 1, 0)) %>%
  mutate(
    lnw = case_when(
      model == "a" ~ 1.75 + 0.04 * exper,
      model == "b" ~ 1.75 + 0.04 * exper + 0.15 * postexp
    ),
    model = fct_rev(model)
  ) %>%
  plot_figure_6.2(aes(x = exper, y = lnw)) +
  annotate(
    geom = "curve",
    x = 8.5, xend = 8.8,
    y = 2.195, yend = 2.109,
    arrow = arrow(length = unit(0.05, "inches"), type = "closed", ends = "both"),
    size = 1 / 4, linetype = 2, curvature = -0.85
  )

p2
```

```{r}
text <-
  tibble(
    exper = c(5, 5, 0.5, 0.5, 1, 7, 7),
    lnw = c(2.24, 2.2, 2, 1.96, 1.62, 1.78, 1.74),
    label = c(
      "Slope~differential",
      "Pre-Post~GED~(pi[3][italic(i)])",
      "Rate~of~change",
      "Pre~GED~(pi[1][italic(i)])",
      "italic(LNW)~at~labor~force~entry~(pi[0][italic(i)])",
      "Constant~elevation~differential",
      "on~GED~receipt~(pi[2][italic(i)])"
    ),
    hjust = c(.5, .5, 0, 0, 0, .5, .5)
  )

arrow <-
  tibble(
    exper = c(5.2, 1.7, 1.7, 6),
    xend = c(9.1, 1.7, 0.05, 3.1),
    lnw = c(2.18, 1.93, 1.64, 1.8),
    yend = c(2.15, 1.84, 1.74, 1.885)
  )

p3 <-
  tibble(
    exper = c(0, 3, 3, 10),
    ged = rep(0:1, each = 2)
  ) %>%
  expand(
    model = letters[1:3],
    nesting(exper, ged)
  ) %>%
  mutate(postexp = ifelse(exper == 10, 1, 0)) %>%
  mutate(
    lnw = case_when(
      model == "a" ~ 1.75 + 0.04 * exper,
      model == "b" ~ 1.75 + 0.04 * exper + 0.02 * ged,
      model == "c" ~ 1.75 + 0.04 * exper + 0.02 * ged + 0.1 * postexp
    ),
    model = fct_rev(model)
  ) %>%
  plot_figure_6.2(aes(x = exper, y = lnw),
    sizes = c(1, 1 / 4, 1 / 4),
    linetypes = c(1, 2, 2)
  ) +
  annotate(
    geom = "curve",
    x = 8.5, xend = 8.8,
    y = 2.185, yend = 2.125,
    arrow = arrow(length = unit(0.05, "inches"), type = "closed", ends = "both"),
    size = 1 / 4, linetype = 2, curvature = -0.85
  )

p3
```

```{r}
text <-
  tibble(
    exper = c(5, 5, 0.5, 0.5, 1, 7, 7, 8, 8, 8),
    lnw = c(2.28, 2.24, 2.1, 2.06, 1.62, 1.76, 1.72, 1.94, 1.9, 1.86),
    label = c(
      "Slope~differential",
      "Pre-Post~GED~(pi[3][italic(i)])",
      "Rate~of~change",
      "Pre~GED~(pi[1][italic(i)])",
      "italic(LNW)~at~labor~force~entry~(pi[0][italic(i)])",
      "GED~differential~at",
      "labor~force~entry~(pi[2][italic(i)])",
      "Elevation~differential",
      "on~GED~receipt",
      "(pi[2][italic(i)]+pi[3][italic(i)]*italic(EXPER))"
    ),
    hjust = c(.5, .5, 0, 0, 0, .5, .5, .5, .5, .5)
  )

arrow <-
  tibble(
    exper = c(5.2, 1.7, 1.7, 4.9, 6.2),
    xend = c(8.8, 1.7, 0.05, 0.05, 3.1),
    lnw = c(2.22, 2.03, 1.64, 1.745, 1.9),
    yend = c(2.18, 1.825, 1.74, 1.775, 1.9)
  )

p4 <-
  crossing(
    model = letters[1:4],
    point = 1:4
  ) %>%
  mutate(
    exper = ifelse(point == 1, 0,
      ifelse(point == 4, 10, 3)
    ),
    ged = c(0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1)
  ) %>%
  mutate(lnw = case_when(
    model %in% letters[1:3] ~ 1.75 + 0.04 * exper + 0.04 * ged + 0.01 * exper * ged,
    model == "d" ~ 1.75 + 0.04 * exper + 0.04 * ged
  )) %>%
  plot_figure_6.2(aes(x = exper, y = lnw),
    sizes = c(1, 1 / 4, 1 / 4, 1 / 4),
    linetypes = c(1, 2, 2, 2)
  ) +
  annotate(
    geom = "curve",
    x = 8.5, xend = 8.8,
    y = 2.205, yend = 2.145,
    arrow = arrow(length = unit(0.05, "inches"), type = "closed", ends = "both"),
    size = 1 / 4, linetype = 2, curvature = -0.85
  )

p4
```

```{r, fig.width=4, fig.height=4}
library(patchwork)
(p1 + p2) / (p3 + p4)
```

```{r}
library(brms)
```

```{r}
fit5.16 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + exper + hgc_9 + black:exper + uerate_7 + (1 + exper | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(stduent_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 5,
    file = "fits/fit05.16"
  )
```

```{r}
print(fit5.16, digits = 3)
```

```{r}
wages_pp <-
  wages_pp %>%
  rename(hgc_9 = hgc.9) %>%
  mutate(uerate_7 = uerate - 7)
```

```{r}
fit6.1 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + exper + hgc_9 + black:exper + uerate_7 + ged +
      (1 + exper + ged | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    file = "fits/fit06.01"
  )

fit6.2 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + exper + hgc_9 + black:exper + uerate_7 + ged +
      (1 + exper | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    file = "fits/fit06.02"
  )


fit6.3 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + exper + hgc_9 + black:exper + uerate_7 + postexp +
      (1 + exper + postexp | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    control = list(adapt_delta = .99),
    file = "fits/fit06.03"
  )


fit6.4 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + exper + hgc_9 + black:exper + uerate_7 + postexp +
      (1 + exper | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    file = "fits/fit06.04"
  )


# model f
fit6.5 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + exper + hgc_9 + black:exper + uerate_7 + ged + postexp +
      (1 + exper + ged + postexp | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    file = "fits/fit06.05"
  )

# model g
fit6.6 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + exper + hgc_9 + black:exper + uerate_7 + ged + postexp +
      (1 + exper + ged | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    file = "fits/fit06.06"
  )

# model h
fit6.7 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + exper + hgc_9 + black:exper + uerate_7 + ged + postexp +
      (1 + exper + postexp | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    control = list(adapt_delta = .99),
    file = "fits/fit06.07"
  )

# model i
fit6.8 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + exper + hgc_9 + black:exper + uerate_7 + ged + ged:exper +
      (1 + exper + ged + ged:exper | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    control = list(adapt_delta = .99),
    file = "fits/fit06.08"
  )

# model j
fit6.9 <-
  brm(
    data = wages_pp,
    family = gaussian,
    lnw ~ 0 + Intercept + exper + hgc_9 + black:exper + uerate_7 + ged + ged:exper +
      (1 + exper + ged | id),
    prior = c(
      prior(normal(1.335, 1), class = b, coef = Intercept),
      prior(normal(0, 0.5), class = b),
      prior(student_t(3, 0, 1), class = sd),
      prior(student_t(3, 0, 1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    file = "fits/fit06.09"
  )
```

```{r}
post <-
  tibble(
    model = letters[1:10],
    fit = c("fit5.16", str_c("fit6.", 1:9))
  ) %>%
  mutate(p = map(fit, ~ get(.) %>%
    posterior_summary() %>%
    data.frame() %>%
    rownames_to_column("parameter") %>%
    filter(!str_detect(parameter, "r_id\\[") & parameter != "lp__"))) %>%
  unnest(p)
```

```{r}
# wrangle
post %>%
  mutate(greek = case_when(
    parameter == "b_Intercept" ~ "gamma[0][0]",
    parameter == "b_hgc_9" ~ "gamma[0][1]",
    parameter == "b_exper" ~ "gamma[1][0]",
    parameter == "b_exper:black" ~ "gamma[1][2]",
    parameter == "b_uerate_7" ~ "gamma[2][0]",
    parameter == "b_ged" ~ "gamma[3][0]",
    parameter == "b_postexp" ~ "gamma[4][0]",
    parameter == "b_exper:ged" ~ "gamma[5][0]",
    parameter == "sd_id__Intercept" ~ "sigma[0]",
    parameter == "sd_id__exper" ~ "sigma[1]",
    parameter == "sd_id__ged" ~ "sigma[3]",
    parameter == "sd_id__postexp" ~ "sigma[4]",
    parameter == "sd_id__exper:ged" ~ "sigma[5]",
    parameter == "sigma" ~ "sigma[epsilon]",
    parameter == "cor_id__Intercept__exper" ~ "rho[0][1]",
    parameter == "cor_id__Intercept__ged" ~ "rho[0][3]",
    parameter == "cor_id__exper__ged" ~ "rho[1][3]",
    parameter == "cor_id__Intercept__postexp" ~ "rho[0][4]",
    parameter == "cor_id__Intercept__exper:ged" ~ "rho[0][5]",
    parameter == "cor_id__exper__postexp" ~ "rho[1][4]",
    parameter == "cor_id__exper__exper:ged" ~ "rho[1][5]",
    parameter == "cor_id__ged__postexp" ~ "rho[3][4]",
    parameter == "cor_id__ged__exper:ged" ~ "rho[3][5]"
  )) %>%
  mutate(model = fct_rev(model)) %>%
  # plot
  ggplot(aes(x = Estimate, xmin = Q2.5, xmax = Q97.5, y = model)) +
  geom_pointrange(size = 1 / 4, fatten = 1) +
  labs(
    title = "Marginal posteriors for models a thorugh j",
    x = NULL, y = NULL
  ) +
  theme(
    axis.text = element_text(size = 6),
    axis.text.y = element_text(hjust = 0),
    panel.grid = element_blank()
  ) +
  facet_wrap(~greek, labeller = label_parsed, scales = "free_x")
```

```{r}
fit5.16 <- add_criterion(fit5.16, criterion = "waic")
fit6.1 <- add_criterion(fit6.1, criterion = "waic")
fit6.2 <- add_criterion(fit6.2, criterion = "waic")
fit6.3 <- add_criterion(fit6.3, criterion = "waic")
fit6.4 <- add_criterion(fit6.4, criterion = "waic")
fit6.5 <- add_criterion(fit6.5, criterion = "waic")
fit6.6 <- add_criterion(fit6.6, criterion = "waic")
fit6.7 <- add_criterion(fit6.7, criterion = "waic")
fit6.8 <- add_criterion(fit6.8, criterion = "waic")
fit6.9 <- add_criterion(fit6.9, criterion = "waic")
```

```{r}
loo_compare(fit5.16,
  fit6.1,
  fit6.2,
  fit6.3,
  fit6.4,
  fit6.5,
  fit6.6,
  fit6.7,
  fit6.8,
  fit6.9,
  criterion = "waic"
) %>%
  data.frame() %>%
  rownames_to_column("fit") %>%
  arrange(fit) %>%
  mutate(model = letters[1:n()]) %>%
  ggplot(aes(
    x = waic, xmin = waic - se_waic, xmax = waic + se_waic,
    y = reorder(model, waic)
  )) +
  geom_pointrange(fatten = 1) +
  labs(x = expression(WAIC %+-% s.e.), y = "model") +
  theme(
    axis.text.y = element_text(hjust = 0),
    panel.grid = element_blank()
  )
```

```{r}
print(fit6.5, digits = 3)
```

```{r}
str(ranef(fit6.5))
```

```{r}
r <- tibble(
  `zeta[0]` = ranef(fit6.5)$id[, 1, "Intercept"],
  `zeta[1]` = ranef(fit6.5)$id[, 1, "exper"],
  `zeta[2]` = ranef(fit6.5)$id[, 1, "ged"],
  `zeta[4]` = ranef(fit6.5)$id[, 1, "postexp"]
)
```

```{r}
my_diag <- function(data, mapping, ...) {
  ggplot(data = data, mapping = mapping) +
    geom_density(fill = "black", size = 0) +
    scale_x_continuous(NULL, breaks = NULL) +
    scale_y_continuous(NULL, breaks = NULL)
}

my_upper <- function(data, mapping, ...) {
  ggplot(data = data, mapping = mapping) +
    geom_point(size = 1 / 10, alpha = 1 / 2) +
    scale_x_continuous(NULL, breaks = NULL) +
    scale_y_continuous(NULL, breaks = NULL)
}
```

```{r}
library(GGally)
r %>%
  ggpairs(
    upper = list(continuous = my_upper),
    diag = list(continuous = my_diag),
    lower = NULL,
    labeller = label_parsed
  )
```

```{r}
nd <-
  crossing(
    black = 0:1,
    hgc_9 = c(0, 3)
  ) %>%
  expand(nesting(black, hgc_9),
    exper = seq(from = 0, to = 11, by = 0.02)
  ) %>%
  mutate(
    ged = ifelse(exper < 3, 0, 1),
    postexp = ifelse(ged == 0, 0, exper - 3),
    uerate_7 = 0
  )

f <-
  fitted(fit6.5,
    re_formula = NA,
    newdata = nd
  ) %>%
  # wrangle
  data.frame() %>%
  bind_cols(nd) %>%
  mutate(
    race = ifelse(black == 0, "White/Latino", "Black"),
    hgc_9 = ifelse(hgc_9 == 0, "9th grade dropouts", "12th grade dropouts")
  ) %>%
  mutate(
    race = fct_rev(race),
    hgc_9 = fct_rev(hgc_9)
  )
```

```{r}
f %>%
  ggplot(aes(exper, Estimate,
    ymin = Q2.5, ymax = Q97.5,
    fill = race, color = race
  )) +
  geom_ribbon(size = 0, alpha = 1 / 4) +
  geom_line() +
  scale_fill_viridis_d(NULL, option = "C", begin = .25, end = .75) +
  scale_color_viridis_d(NULL, option = "C", begin = .25, end = .75) +
  scale_x_continuous(breaks = 0:5 * 2, expand = c(0, 0)) +
  scale_y_continuous("lnw",
    breaks = 1.6 + 0:4 * 0.2,
    expand = expansion(mult = c(0, 0.05))
  ) +
  coord_cartesian(ylim = c(1.6, 2.4)) +
  facet_wrap(~hgc_9) +
  theme(panel.grid = element_blank())
```

## 6.2 Using transformations to model nonlinear individual change

```{r}
fit4.6 <-
  brm(
    data = alcohol1_pp,
    family = gaussian,
    alcuse ~ 0 + Intercept + age_14 + coa + peer + age_14:peer +
      (1 + age_14 | id),
    prior = c(
      prior(student_t(3, 0, 2.5), class = sd),
      prior(student_t(3, 0, 2.5), class = sigma),
      prior(lkj(1), class = cor)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 4,
    file = "fits/fit04.06"
  )
```

```{r}
nd <-
  crossing(
    coa = 0:1,
    peer = c(.655, 1.381)
  ) %>%
  expand(nesting(coa, peer),
    age_14 = seq(0, 2, length.out = 30)
  )
fitted(fit4.6,
  newdata = nd,
  re_formula = NA
) %>%
  data.frame() %>%
  bind_cols(nd) %>%
  mutate(
    Estimate = Estimate^2,
    Q2.5 = Q2.5^2,
    Q97.5 = Q97.5^2
  ) %>%
  mutate(
    age = age_14 + 14,
    coa = ifelse(coa == 0, "coa = 0", "coa = 1"),
    peer = factor(peer)
  ) %>%
  ggplot(aes(age, color = peer, fill = peer)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), size = 0, alpha = 1 / 4) +
  geom_line(aes(y = Estimate, size = peer)) +
  scale_size_manual(values = c(1 / 2, 1)) +
  scale_fill_manual(values = c("blue3", "red3")) +
  scale_color_manual(values = c("blue3", "red3")) +
  scale_y_continuous("alcuse", breaks = 0:3, expand = c(0, 0)) +
  labs(subtitle = "High peer values are in red; low ones are in blue.") +
  coord_cartesian(xlim = c(13, 17), ylim = c(0, 3)) +
  facet_wrap(~coa) +
  theme(
    legend.position = "none",
    panel.grid = element_blank()
  )
```

```{r}
berkeley_pp <-
  read_csv("data/berkeley_pp.csv") %>%
  mutate(time = age)
berkeley_pp
```

```{r}
p1 <-
  berkeley_pp %>%
  ggplot(aes(time, iq)) +
  geom_point() +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 250))

p2 <-
  berkeley_pp %>%
  ggplot(aes(time, iq^2.3)) +
  geom_point() +
  scale_y_continuous(expression(iq^(2.3)),
    breaks = 0:6 * 5e4,
    limits = c(0, 3e5), expand = c(0, 0)
  )

p3 <-
  berkeley_pp %>%
  ggplot(aes(time^(1 / 2.3), iq)) +
  geom_point() +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 250)) +
  xlab(expression(time^(1 / 2.3)))

(p1 + p2 + p3) &
  scale_x_continuous(expand = expansion(mult = c(0, 0.05)), limits = c(0, NA)) &
  theme(panel.grid = element_blank())
```

## 6.3 Representing individual change using a polynomial function of TIME

```{r}
p1 <-
  tibble(
    x = 1,
    y = 9.5,
    label = c("No\nchange", "Linear\nchange", "Quadratic\nchange", "Cubic\nchange"),
    row = 1:4,
    col = "Shape"
  ) %>%
  ggplot(aes(x = x, y = y, label = label)) +
  geom_text(hjust = 0, vjust = 1, size = 3.25) +
  scale_x_continuous(expand = c(0, 0), limits = 1:2) +
  scale_y_continuous(expand = c(0, 0), limits = c(1, 10)) +
  theme_void() +
  theme(
    strip.background.y = element_blank(),
    strip.text.x = element_text(hjust = 0, size = 12),
    strip.text.y = element_blank()
  ) +
  facet_grid(row ~ col)
p1
```

```{r}
p2 <-
  tibble(
    x = c(1, 1, 1, 2, 1, 2, 2),
    y = c(9.5, 9.5, 9.5, 8.5, 9.5, 8.5, 7.25),
    label = c(
      "italic(Y[i][j])==pi[0][italic(i)]+epsilon[italic(ij)]",
      "italic(Y[i][j])==pi[0][italic(i)]+pi[1][italic(i)]*italic(TIME[ij])+epsilon[italic(ij)]",
      "italic(Y[i][j])==pi[0][italic(i)]+pi[1][italic(i)]*italic(TIME[ij])",
      "+pi[2][italic(i)]*italic(TIME[ij])^2+epsilon[italic(ij)]",
      "italic(Y[i][j])==pi[0][italic(i)]+pi[1][italic(i)]*italic(TIME[ij])",
      "+pi[2][italic(i)]*italic(TIME[ij])^2+pi[3][italic(i)]*italic(TIME[ij])^3",
      "+epsilon[italic(ij)]"
    ),
    row = c(1:3, 3:4, 4, 4),
    col = "Level-1 model"
  ) %>%
  ggplot(aes(x = x, y = y, label = label)) +
  geom_text(hjust = 0, vjust = 1, size = 3.25, parse = T) +
  scale_x_continuous(expand = c(0, 0), limits = c(1, 10)) +
  scale_y_continuous(expand = c(0, 0), limits = c(1, 10)) +
  theme_void() +
  theme(
    strip.background.y = element_blank(),
    strip.text.x = element_text(hjust = 0, size = 12),
    strip.text.y = element_blank()
  ) +
  facet_grid(row ~ col)
p2
```

```{r}
p3 <-
  tibble(
    x = 1,
    y = c(9.5, 9.5, 8.5, 9.5, 8.5, 7.5, 9.5, 8.5, 7.5, 6.5),
    label = c(
      "pi[0][italic(i)]==71",
      "pi[0][italic(i)]==71",
      "pi[1][italic(i)]==1.2",
      "pi[0][italic(i)]==50",
      "pi[1][italic(i)]==3.8",
      "pi[2][italic(i)]==-0.03",
      "pi[0][italic(i)]==30",
      "pi[1][italic(i)]==10",
      "pi[2][italic(i)]==-0.2",
      "pi[3][italic(i)]==0.0012"
    ),
    row = rep(1:4, times = 1:4),
    col = "Parameter\nvalues"
  ) %>%
  ggplot(aes(x = x, y = y, label = label)) +
  geom_text(hjust = 0, vjust = 1, size = 3.25, parse = T) +
  scale_x_continuous(expand = c(0, 0), limits = c(1, 10)) +
  scale_y_continuous(expand = c(0, 0), limits = c(1, 10)) +
  theme_void() +
  theme(
    strip.background.y = element_blank(),
    strip.text.x = element_text(hjust = 0, size = 12),
    strip.text.y = element_blank()
  ) +
  facet_grid(row ~ col)
p3
```

```{r}
# make the four small data sets
pi0 <- 71

d1 <- tibble(time = 0:100) %>%
  mutate(y = pi0)

pi0 <- 71
pi1 <- 1.2

d2 <- tibble(time = 0:100) %>%
  mutate(y = pi0 + pi1 * time)

pi0 <- 50
pi1 <- 3.8
pi2 <- -0.03

d3 <- tibble(time = 0:100) %>%
  mutate(y = pi0 + pi1 * time + pi2 * time^2)

pi0 <- 30
pi1 <- 10
pi2 <- -0.2
pi3 <- 0.0012

d4 <- tibble(time = 0:100) %>%
  mutate(y = pi0 + pi1 * time + pi2 * time^2 + pi3 * time^3)

# combine the data sets
p4 <-
  bind_rows(d1, d2, d3, d4) %>%
  # wrangle
  mutate(
    row = rep(1:4, each = n() / 4),
    col = "Plot of the true change trajectory"
  ) %>%
  # plot!
  ggplot(aes(x = time, y = y)) +
  geom_line() +
  scale_x_continuous(expression(italic(TIME)),
    expand = c(0, 0),
    breaks = 0:2 * 50, limits = c(0, 100)
  ) +
  scale_y_continuous(expression(italic(Y)),
    expand = c(0, 0),
    breaks = 0:2 * 100, limits = c(0, 205)
  ) +
  theme(
    panel.grid = element_blank(),
    strip.background = element_blank(),
    strip.text.x = element_text(hjust = 0, size = 12),
    strip.text.y = element_blank()
  ) +
  facet_grid(row ~ col)
p4
```

```{r, fig.width=4, fig.height=4, warning=FALSE}
(p1 | p2 | p3 | p4) +
  plot_annotation(title = "A taxonomy of polynomial individual change trajectories") +
  plot_layout(widths = c(1, 3, 2, 4))
```

```{r}
external_pp <-
  read.table("https://stats.idre.ucla.edu/wp-content/uploads/2020/01/external_pp.txt",
    header = T, sep = ","
  )

glimpse(external_pp)
```

```{r}
external_pp %>%
  distinct(id) %>%
  nrow()
```

```{r}
external_pp %>%
  distinct(id, female) %>%
  count(female) %>%
  mutate(percent = 100 * n / sum(n))
```

```{r}
external_pp %>%
  distinct(grade)
```

```{r}
external_pp %>%
  ggplot(aes(external)) +
  geom_histogram(binwidth = 1, boundary = 0) +
  xlim(0, 68) +
  theme(panel.grid = element_blank())
```

```{r}
subset <- c(1, 6, 11, 25, 34, 36, 40, 26)
external_pp_subset <-
  external_pp %>%
  filter(id %in% subset) %>%
  mutate(case = factor(id, levels = subset, labels = LETTERS[1:8]))
external_pp_subset
```

```{r}
# a and e
p1 <-
  external_pp_subset %>%
  filter(case %in% c("A")) %>%
  ggplot(aes(x = grade, y = external)) +
  geom_point() +
  stat_smooth(
    method = "lm", formula = y ~ x + I(x^2) + I(x^3) + I(x^4),
    se = F, size = 1 / 4, linetype = 2
  ) + # quartic
  stat_smooth(
    method = "lm", formula = y ~ x + I(x^2), # quadratic
    se = F, size = 1 / 2
  ) +
  scale_x_continuous(NULL,
    breaks = NULL,
    limits = c(0, 7), expand = c(0, 0)
  ) +
  scale_y_continuous(NULL, breaks = NULL) +
  facet_wrap(~case)

# e
p2 <-
  external_pp_subset %>%
  filter(case %in% c("E")) %>%
  ggplot(aes(x = grade, y = external)) +
  geom_point() +
  stat_smooth(
    method = "lm", formula = y ~ x + I(x^2) + I(x^3) + I(x^4),
    se = F, size = 1 / 4, linetype = 2
  ) + # quartic
  stat_smooth(
    method = "lm", formula = y ~ x + I(x^2) + I(x^3), # cubic
    se = F, size = 1 / 2
  ) +
  scale_x_continuous(NULL,
    breaks = NULL,
    limits = c(0, 7), expand = c(0, 0)
  ) +
  scale_y_continuous(NULL, breaks = NULL) +
  facet_wrap(~case)

# b
p3 <-
  external_pp_subset %>%
  filter(case %in% c("B")) %>%
  ggplot(aes(x = grade, y = external)) +
  geom_point() +
  stat_smooth(
    method = "lm", formula = y ~ x + I(x^2) + I(x^3) + I(x^4),
    se = F, size = 1 / 4, linetype = 2
  ) + # quartic
  stat_smooth(
    method = "lm", formula = y ~ x + I(x^2), # quadratic
    se = F, size = 1 / 2
  ) +
  scale_x_continuous(NULL,
    breaks = NULL,
    limits = c(0, 7), expand = c(0, 0)
  ) +
  scale_y_continuous(NULL, breaks = NULL) +
  facet_wrap(~case)

# f
p4 <-
  external_pp_subset %>%
  filter(case %in% c("F")) %>%
  ggplot(aes(x = grade, y = external)) +
  geom_point() +
  stat_smooth(
    method = "lm", formula = y ~ x + I(x^2) + I(x^3) + I(x^4),
    se = F, size = 1 / 2
  ) + # quartic
  scale_x_continuous(breaks = 0:7, limits = c(0, 7), expand = c(0, 0)) +
  scale_y_continuous(NULL, breaks = NULL) +
  facet_wrap(~case)

# c
p5 <-
  external_pp_subset %>%
  filter(case %in% c("C")) %>%
  ggplot(aes(x = grade, y = external)) +
  geom_point() +
  stat_smooth(
    method = "lm", formula = y ~ x + I(x^2) + I(x^3) + I(x^4),
    se = F, size = 1 / 4, linetype = 2
  ) + # quartic
  stat_smooth(
    method = "lm", formula = y ~ x, # linear
    se = F, size = 1 / 2
  ) +
  scale_x_continuous(NULL,
    breaks = NULL,
    limits = c(0, 7), expand = c(0, 0)
  ) +
  scale_y_continuous(NULL, breaks = NULL) +
  facet_wrap(~case)

# g
p6 <-
  external_pp_subset %>%
  filter(case %in% c("G")) %>%
  ggplot(aes(x = grade, y = external)) +
  geom_point() +
  stat_smooth(
    method = "lm", formula = y ~ x + I(x^2) + I(x^3) + I(x^4),
    se = F, size = 1 / 4, linetype = 2
  ) + # quartic
  stat_smooth(
    method = "lm", formula = y ~ x + I(x^2), # quadratic
    se = F, size = 1 / 2
  ) +
  scale_x_continuous(breaks = 0:7, limits = c(0, 7), expand = c(0, 0)) +
  scale_y_continuous(NULL, breaks = NULL) +
  facet_wrap(~case)

# d
p7 <-
  external_pp_subset %>%
  filter(case %in% c("D")) %>%
  ggplot(aes(x = grade, y = external)) +
  geom_point() +
  stat_smooth(
    method = "lm", formula = y ~ x + I(x^2) + I(x^3) + I(x^4),
    se = F, size = 1 / 4, linetype = 2
  ) + # quartic
  stat_smooth(
    method = "lm", formula = y ~ x, # linear
    se = F, size = 1 / 2
  ) +
  scale_x_continuous(NULL,
    breaks = NULL,
    limits = c(0, 7), expand = c(0, 0)
  ) +
  scale_y_continuous(NULL, breaks = NULL) +
  facet_wrap(~case)

# h
p8 <-
  external_pp_subset %>%
  filter(case %in% c("H")) %>%
  ggplot(aes(x = grade, y = external)) +
  geom_point() +
  stat_smooth(
    method = "lm", formula = y ~ x + I(x^2) + I(x^3) + I(x^4),
    se = F, size = 1 / 2
  ) + # quartic
  scale_x_continuous(breaks = 0:7, limits = c(0, 7), expand = c(0, 0)) +
  scale_y_continuous(NULL, breaks = NULL) +
  facet_wrap(~case)
```

```{r}
((p1 / p2) | (p3 / p4) | (p5 / p6) | (p7 / p8)) &
  coord_cartesian(ylim = c(0, 60)) &
  theme(panel.grid = element_blank())
```

```{r}
sample_statistics <-
  crossing(
    gender = c("boys", "girls"),
    sample = c("School", "CBCL Nonclinical")
  ) %>%
  mutate(
    n = c(300, 261, 300, 267),
    mean = c(10.8, 14.5, 10.7, 16.6),
    sd = c(8.4, 10.4, 8.6, 12.1)
  )

sample_statistics %>%
  flextable::flextable()
```

```{r}
sample_statistics %>%
  summarize(weighted_average = sum(n * mean) / sum(n))
```

```{r}
sample_statistics %>%
  summarise(pooled_sd = sqrt(sum((n - 1) * sd^2) / (sum(n) - 4)))
```

```{r}
# left
p1 <-
  tibble(x = seq(from = -30, to = 50, length.out = 200)) %>%
  mutate(d = dnorm(x, mean = 13, sd = 9.9)) %>%
  ggplot(aes(x = x, y = d)) +
  geom_area(fill = "black") +
  # scale_y_continuous(NULL, breaks = NULL) +
  labs(
    subtitle = expression("prior for " * gamma[0][0]),
    x = (expression(Normal(13 * ", " * 9.9)))
  ) +
  theme(panel.grid = element_blank())

# right
p2 <-
  tibble(x = seq(from = 0, to = 60, length.out = 200)) %>%
  mutate(d = dexp(x, rate = 1.0 / 9.9)) %>%
  ggplot(aes(x = x, y = d)) +
  geom_area(fill = "black") +
  # scale_y_continuous(NULL, breaks = NULL) +
  labs(
    subtitle = expression("priors for " * sigma[0] ~ and ~ sigma[epsilon]),
    x = (expression(Exponential(1 / 9.9)))
  ) +
  theme(panel.grid = element_blank())

# combine
p1 | p2
```

```{r}
fit6.10 <-
  brm(
    data = external_pp,
    family = gaussian,
    external ~ 1 + (1 | id),
    prior = c(
      prior(normal(13, 9.9), class = Intercept),
      prior(exponential(1.0 / 9.9), class = sd),
      prior(exponential(1.0 / 9.9), class = sigma)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    file = "fits/fit06.10"
  )
```

```{r}
# linear
fit6.11 <-
  brm(
    data = external_pp,
    family = gaussian,
    external ~ 0 + Intercept + time + (1 + time | id),
    prior = c(
      prior(normal(0, 4.95), class = b),
      prior(normal(13, 9.9), class = b, coef = Intercept),
      prior(exponential(1.0 / 9.9), class = sd),
      prior(exponential(1.0 / 9.9), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    file = "fits/fit06.11"
  )

# quadratic
fit6.12 <-
  brm(
    data = external_pp,
    family = gaussian,
    external ~ 0 + Intercept + time + I(time^2) + (1 + time + I(time^2) | id),
    prior = c(
      prior(normal(0, 4.95), class = b),
      prior(normal(13, 9.9), class = b, coef = Intercept),
      prior(exponential(1.0 / 9.9), class = sd),
      prior(exponential(1.0 / 9.9), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    control = list(adapt_delta = .99),
    file = "fits/fit06.12"
  )

# cubic
fit6.13 <-
  brm(
    data = external_pp,
    family = gaussian,
    external ~ 0 + Intercept + time + I(time^2) + I(time^3) + (1 + time + I(time^2) + I(time^3) | id),
    prior = c(
      prior(normal(0, 4.95), class = b),
      prior(normal(13, 9.9), class = b, coef = Intercept),
      prior(exponential(1.0 / 9.9), class = sd),
      prior(exponential(1.0 / 9.9), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    file = "fits/fit06.13"
  )
```

```{r}
fit6.10 <- add_criterion(fit6.10, criterion = "waic")
fit6.11 <- add_criterion(fit6.11, criterion = "waic")
fit6.12 <- add_criterion(fit6.12, criterion = "waic")
fit6.13 <- add_criterion(fit6.13, criterion = "waic")
```

```{r}
# order the parameters, which will come in handy in the next block
order <- c("gamma[0][0]", "gamma[1][0]", "gamma[2][0]", "gamma[3][0]", "sigma[epsilon]", "sigma[0]", "sigma[1]", "sigma[2]", "sigma[3]", "rho[0][1]", "rho[0][2]", "rho[0][3]", "rho[1][2]", "rho[1][3]", "rho[2][3]", "WAIC")

waic_summary <-
  loo_compare(fit6.10, fit6.11, fit6.12, fit6.13, criterion = "waic") %>%
  data.frame() %>%
  rownames_to_column("fit") %>%
  arrange(fit) %>%
  transmute(
    model = str_c("model ", letters[1:n()]),
    summary = str_c(formatC(waic, digits = 2, format = "f"), " (", formatC(se_waic, digits = 2, format = "f"), ")"),
    parameter = factor("WAIC", levels = order)
  )

waic_summary
```

```{r}
# extract and wrangle the posterior summaries
tibble(
  model = str_c("model ", letters[1:4]),
  fit = str_c("fit6.1", 0:3)
) %>%
  mutate(p = map(fit, ~ get(.) %>%
    posterior_summary() %>%
    data.frame() %>%
    rownames_to_column("parameter") %>%
    filter(!str_detect(parameter, "r_id\\[") & parameter != "lp__"))) %>%
  unnest(p) %>%
  mutate(greek = case_when(
    parameter == "b_Intercept" ~ "gamma[0][0]",
    parameter == "b_time" ~ "gamma[1][0]",
    parameter == "b_ItimeE2" ~ "gamma[2][0]",
    parameter == "b_ItimeE3" ~ "gamma[3][0]",
    parameter == "sd_id__Intercept" ~ "sigma[0]",
    parameter == "sd_id__time" ~ "sigma[1]",
    parameter == "sd_id__ItimeE2" ~ "sigma[2]",
    parameter == "sd_id__ItimeE3" ~ "sigma[3]",
    parameter == "sigma" ~ "sigma[epsilon]",
    parameter == "cor_id__Intercept__time" ~ "rho[0][1]",
    parameter == "cor_id__Intercept__ItimeE2" ~ "rho[0][2]",
    parameter == "cor_id__Intercept__ItimeE3" ~ "rho[0][3]",
    parameter == "cor_id__time__ItimeE2" ~ "rho[1][2]",
    parameter == "cor_id__time__ItimeE3" ~ "rho[1][3]",
    parameter == "cor_id__ItimeE2__ItimeE3" ~ "rho[2][3]"
  )) %>%
  mutate(
    summary = str_c(formatC(Estimate, digits = 2, format = "f"), " (", formatC(Est.Error, digits = 2, format = "f"), ")"),
    parameter = factor(greek, levels = order)
  ) %>%
  select(model, summary, parameter) %>%
  # add in the WAIC summary information
  bind_rows(waic_summary) %>%
  mutate(parameter = fct_rev(parameter)) %>%
  # plot!
  ggplot(aes(x = model, y = parameter, label = summary)) +
  geom_text(hjust = 1, size = 3) +
  scale_x_discrete(NULL, position = "top") +
  scale_y_discrete(NULL, labels = ggplot2:::parse_safe) +
  coord_cartesian(xlim = c(NA, 3.5)) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(hjust = 1, color = "black"),
    axis.text.y = element_text(hjust = 0, color = "black"),
    axis.line.x = element_line(size = 1 / 4),
    panel.grid = element_blank()
  )
```

```{r}
loo_compare(fit6.10, fit6.11, fit6.12, fit6.13, criterion = "waic") %>%
  print(simplify = F)
```

```{r}
# define the new data
nd <-
  external_pp_subset %>%
  distinct(id, case) %>%
  expand(nesting(id, case),
    time = seq(from = 0, to = 5, length.out = 50)
  ) %>%
  mutate(grade = time + 1)

# extract the fitted trajectories and wrangle
fitted(fit6.12, newdata = nd) %>%
  data.frame() %>%
  bind_cols(nd) %>%
  # plot!
  ggplot(aes(x = grade, y = Estimate)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),
    alpha = 1 / 4
  ) +
  geom_line(aes(y = Estimate)) +
  geom_point(
    data = external_pp_subset,
    aes(y = external)
  ) +
  scale_x_continuous(
    breaks = 0:7, labels = 0:7,
    expand = c(0, 0), limits = c(0, 7)
  ) +
  ylab("external") +
  coord_cartesian(ylim = c(0, 60)) +
  theme(panel.grid = element_blank()) +
  facet_wrap(~case, ncol = 4)
```

```{r}
fit6.14 <-
  brm(
    data = external_pp,
    family = gaussian,
    external ~ 0 + Intercept + time + I(time^2) + female + time:female + I(time^2):female +
      (1 + time + I(time^2) | id),
    prior = c(
      prior(normal(0, 4.95), class = b),
      prior(normal(13, 9.9), class = b, coef = Intercept),
      prior(exponential(1.0 / 9.9), class = sd),
      prior(exponential(1.0 / 9.9), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2500, warmup = 1000, chains = 3, cores = 3,
    seed = 6,
    control = list(adapt_delta = .99),
    file = "fits/fit06.14"
  )
```

```{r}
posterior_summary(fit6.14)[4:6, ] %>%
  data.frame() %>%
  mutate(parameter = str_c("gamma[", 0:2, "][1]")) %>%
  ggplot(aes(x = Estimate, xmin = Q2.5, xmax = Q97.5, y = parameter)) +
  geom_vline(xintercept = 0, color = "white") +
  geom_pointrange(fatten = 1, size = 1 / 4) +
  scale_y_discrete(NULL, labels = ggplot2:::parse_safe) +
  labs(
    subtitle = "How well did 'female' do?",
    x = "marginal posterior"
  ) +
  theme(panel.grid = element_blank())
```

```{r}
fit6.14 <- add_criterion(fit6.14, criterion = "waic")

loo_compare(fit6.12, fit6.14, criterion = "waic") %>% print(simplify = F)
```

## 6.4 Truly nonlinear trajectories

```{r}
library(tidyverse)
```

```{r}
foxngeese_pp <- read_csv("data/foxngeese_pp.csv")
foxngeese_pp
```

```{r}
foxngeese_pp %>%
  distinct(id)
```

```{r}
foxngeese_pp %>%
  count(id, name = "# games, per kid") %>%
  count(`# games, per kid`)
```

```{r}
foxngeese_pp %>%
  ggplot(aes(nmoves)) +
  geom_bar() +
  theme(panel.grid = element_blank())
```

```{r}
subset <- c("1", "4", "6", "7", "8", "11", "12", "15")

foxngeese_pp %>%
  filter(id %in% subset) %>%
  mutate(id = if_else(id < 10, str_c("0", id), as.character(id))) %>%
  ggplot(aes(game, nmoves)) +
  geom_point(size = 2 / 3) +
  scale_y_continuous(breaks = 0:5 * 5, limits = c(0, 25)) +
  facet_wrap(~id, ncol = 4, labeller = label_both) +
  theme(panel.grid = element_blank())
```

```{r}
sw_logistic <- function(pi0 = 15, pi1 = 0.3, game = 10) {
  1 + (19 / (1 + pi0 * exp(-pi1 * game)))
}
```

```{r}
crossing(
  pi0 = c(1.5, 15, 150),
  pi1 = c(0.1, 0.3, 0.5)
) %>%
  expand(nesting(pi0, pi1),
    game = 0:30
  ) %>%
  mutate(
    y = sw_logistic(pi0, pi1, game),
    pi0_f = factor(str_c("pi[0]==", pi0),
      levels = c("pi[0]==150", "pi[0]==15", "pi[0]==1.5")
    )
  ) %>%
  ggplot(aes(game, y, group = pi1)) +
  geom_line(aes(size = pi1)) +
  scale_size_continuous(expression(pi[i]), range = c(1 / 3, 1), breaks = c(0.1, 0.3, 0.5)) +
  scale_y_continuous("nmoves", limits = c(0, 25)) +
  facet_wrap(~pi0_f, labeller = label_parsed) +
  theme(panel.grid = element_blank())
```

```{r}
n <- 100
set.seed(6)
tibble(
  n = 1:n,
  gamma00 = rnorm(n, mean = 15, sd = 3),
  gamma10 = rnorm(n, mean = 0.2, sd = 0.1)
) %>%
  expand(nesting(n, gamma00, gamma10),
    game = 0:30
  ) %>%
  mutate(y = sw_logistic(gamma00, gamma10, game)) %>%
  ggplot(aes(game, y, group = n)) +
  geom_hline(yintercept = c(1, 20), color = "white") +
  geom_line(size = 1 / 4, alpha = 1 / 2) +
  scale_y_continuous(limits = c(1, 20)) +
  theme(panel.grid = element_blank())
```

```{r}
fit6.15 <-
  brm(
    data = foxngeese_pp,
    family = gaussian,
    bf(nmoves ~ 1 + (19.0 / (1.0 + g0 * exp(-g1 * game))),
      g0 + g1 ~ 1 + (1 | i | id),
      nl = TRUE
    ),
    prior = c(
      prior(normal(15, 3), nlpar = g0),
      prior(normal(0.2, 0.1), nlpar = g1),
      prior(exponential(1), class = sd, nlpar = g0),
      prior(exponential(10), class = sd, nlpar = g1),
      prior(exponential(1), class = sigma)
    ),
    # prior(lkj(4), class = cor)),
    iter = 2000, warmup = 1000, cores = 3, chains = 3,
    inits = 0,
    control = list(adapt_delta = .999),
    file = "fits/fit06.15"
  )
```

```{r}
print(fit6.15, digits = 3)
```

```{r}
print(fit6.15, digits = 3)
```

```{r}
nd <- tibble(game = seq(0, 30, by = 0.1))

p1 <-
  fitted(fit6.15,
    newdata = nd,
    re_formula = NA
  ) %>%
  data.frame() %>%
  bind_cols(nd) %>%
  ggplot(aes(game, Estimate, ymin = Q2.5, ymax = Q97.5)) +
  geom_hline(yintercept = c(1, 20), color = "white") +
  geom_ribbon(alpha = 1 / 4) +
  geom_line() +
  scale_y_continuous("nmoves", limits = c(0, 25), expand = c(0, 0)) +
  labs(subtitle = "Model A") +
  theme(panel.grid = element_blank())
p1
```

```{r}
foxngeese_pp <-
  foxngeese_pp %>%
  mutate(read_c = read - mean(read))
foxngeese_pp
```

```{r}
fit6.16 <-
  brm(
    data = foxngeese_pp,
    family = gaussian,
    bf(nmoves ~ 1 + (19.0 / (1.0 + g0 * exp(-g1 * game))),
      g0 + g1 ~ 1 + read_c + (1 | i | id),
      nl = TRUE
    ),
    prior = c(
      prior(normal(15, 3), nlpar = g0, coef = Intercept),
      prior(normal(0, 1), nlpar = g0, coef = read_c),
      prior(normal(0.2, 0.1), nlpar = g1, coef = Intercept),
      prior(normal(0, 0.1), nlpar = g1, coef = read_c),
      prior(exponential(1), class = sd, nlpar = g0),
      prior(exponential(10), class = sd, nlpar = g1),
      prior(exponential(1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, cores = 3, chains = 3,
    init = 0,
    control = list(adapt_delta = .999),
    file = "fits/fit06.16"
  )
```

```{r}
print(fit6.16)
```

```{r}
library(tidybayes)

as_draws_df(fit6.16) %>%
  ggplot(aes(b_g0_read_c, y = 0)) +
  stat_halfeye(.width = c(.8, .95)) +
  geom_vline(xintercept = -0.3745, linetype = 2) +
  annotate(
    geom = "text",
    x = -0.3745, y = 0.03,
    label = "Sinter and Willett's\npoint estimate",
    angle = 90, hjust = 0, size = 3
  ) +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(expression(gamma[0][1])) +
  theme(panel.grid = element_blank())
```

```{r}
nd <- crossing(
  game = seq(0, 30, by = 0.1),
  read_c = c(-1.58, 1.58)
)

p2 <-
  fitted(fit6.16,
    newdata = nd,
    re_formula = NA
  ) %>%
  data.frame() %>%
  bind_cols(nd) %>%
  mutate(read_c = ifelse(read_c < 0, "low (-1.58)", "high (1.58)")) %>%
  ggplot(aes(game, Estimate,
    ymin = Q2.5, ymax = Q97.5,
    fill = read_c, color = read_c
  )) +
  geom_hline(yintercept = c(1, 20), color = "white") +
  geom_ribbon(alpha = 1 / 4, size = 0) +
  geom_line() +
  scale_fill_viridis_d(option = "A", begin = .25, end = .75) +
  scale_color_viridis_d(option = "A", begin = .25, end = .75) +
  scale_y_continuous(NULL, breaks = NULL, limits = c(0, 25), expand = c(0, 0)) +
  labs(subtitle = "Model B") +
  theme(panel.grid = element_blank())

p1 + p2
```

```{r}
fit6.15 <- add_criterion(fit6.15, criterion = "waic")
fit6.16 <- add_criterion(fit6.16, criterion = "waic")
loo_compare(fit6.15, fit6.16, criterion = "waic") %>% print(simplify = FALSE)
```

```{r}
# define the new data
nd <-
  foxngeese_pp %>%
  distinct(id, read_c) %>%
  filter(id %in% subset) %>%
  expand(nesting(id, read_c),
    game = seq(from = 0, to = 30, by = 0.1)
  )


# extract the fitted trajectories
fitted(fit6.16, newdata = nd) %>%
  # wrangle
  data.frame() %>%
  bind_cols(nd) %>%
  # plot!
  ggplot(aes(x = game)) +
  geom_hline(yintercept = c(1, 20), color = "white") +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5, fill = read_c),
    alpha = 1 / 4, size = 0
  ) +
  geom_line(aes(y = Estimate, color = read_c)) +
  geom_point(
    data = foxngeese_pp %>% filter(id %in% subset),
    aes(y = nmoves),
    size = 2 / 3
  ) +
  scale_fill_viridis_c(
    option = "A", begin = .15, end = .85,
    limits = range(foxngeese_pp$read_c)
  ) +
  scale_color_viridis_c(
    option = "A", begin = .15, end = .85,
    limits = range(foxngeese_pp$read_c)
  ) +
  scale_y_continuous(breaks = 0:5 * 5, limits = c(0, 25), expand = c(0, 0)) +
  theme(panel.grid = element_blank()) +
  facet_wrap(~id, ncol = 4, labeller = label_both)
```

```{r}
text <-
  tibble(
    time = c(0, 1.2, 4.6, 8),
    y = c(102.5, 90, 87, 85),
    label = c(
      "alpha==100",
      "pi[1]==0.01",
      "pi[1]==0.02",
      "pi[1]==0.1"
    )
  )

p1 <-
  crossing(
    alpha = 100,
    pi1 = c(0.01, 0.02, 0.1)
  ) %>%
  expand(nesting(alpha, pi1),
    time = seq(from = 0, to = 10, by = 0.01)
  ) %>%
  mutate(y = alpha - (1 / (pi1 * time))) %>%
  ggplot(aes(x = time, y = y, group = pi1)) +
  geom_hline(yintercept = 100, color = "white") +
  geom_line() +
  geom_text(
    data = text,
    aes(label = label),
    size = 3, hjust = 0, parse = T
  ) +
  labs(
    title = "Hyperbola",
    y = expression(E(italic(Y)))
  ) +
  coord_cartesian(ylim = c(0, 100)) +
  theme(panel.grid = element_blank())

p1
```

```{r}
text <-
  tibble(
    time = c(0, 3.5, 7.5, 10, 1.5),
    y = c(102.5, 94, 91, 77, 8),
    label = c(
      "alpha==100",
      "pi[2]==0.015",
      "pi[2]==0",
      "pi[2]==-0.0015",
      "pi[1]==0.02~('for all curves')"
    ),
    hjust = c(0, 0, 0, 1, 0)
  )

p2 <-
  crossing(
    alpha = 100,
    pi1 = 0.02,
    pi2 = c(0.015, 0, -0.0015)
  ) %>%
  expand(nesting(alpha, pi1, pi2),
    time = seq(from = 0, to = 10, by = 0.01)
  ) %>%
  mutate(y = alpha - (1 / (pi1 * time + pi2 * time^2))) %>%
  ggplot(aes(x = time, y = y, group = pi2)) +
  geom_hline(yintercept = 100, color = "white") +
  geom_line() +
  geom_text(
    data = text,
    aes(label = label, hjust = hjust),
    size = 3, parse = T
  ) +
  labs(
    title = "Inverse polynomial",
    y = expression(E(italic(Y)))
  ) +
  coord_cartesian(ylim = c(0, 100)) +
  theme(panel.grid = element_blank())

p2
```

```{r}
# left
text <-
  tibble(
    time = 10,
    y = c(100.5, 39, 16, 1),
    label = c(
      "pi[1]==0.3",
      "pi[1]==0.2",
      "pi[1]==0.1",
      "pi[0]==5~('for all curves')"
    ),
    vjust = c(0, .5, .5, 0)
  )

p3 <-
  crossing(
    pi0 = 5,
    pi1 = c(0.1, 0.2, 0.3)
  ) %>%
  expand(nesting(pi0, pi1),
    time = seq(from = 0, to = 10, by = 0.01)
  ) %>%
  mutate(y = pi0 * exp(pi1 * time)) %>%
  ggplot(aes(x = time, y = y, group = pi1)) +
  geom_hline(yintercept = 100, color = "white") +
  geom_line() +
  geom_text(
    data = text,
    aes(label = label, vjust = vjust),
    size = 3, hjust = 1, parse = T
  ) +
  labs(
    title = "Exponential (simple)",
    y = expression(E(italic(Y)))
  ) +
  coord_cartesian(ylim = c(0, 100)) +
  theme(panel.grid = element_blank())

# right
text <-
  tibble(
    time = c(0, 10, 10, 10, 7),
    y = c(102.5, 98, 83, 63, 20),
    label = c(
      "alpha==100",
      "pi[1]==0.3",
      "pi[1]==0.2",
      "pi[1]==0.1",
      "pi[0]==20~('for all curves')"
    ),
    hjust = c(0, 1, 1, 1, 1)
  )

p4 <-
  crossing(
    alpha = 100,
    pi0 = 20,
    pi1 = c(0.1, 0.2, 0.3)
  ) %>%
  expand(nesting(alpha, pi0, pi1),
    time = seq(from = 0, to = 10, by = 0.01)
  ) %>%
  mutate(y = alpha - (alpha - pi0) * exp(-pi1 * time)) %>%
  ggplot(aes(x = time, y = y, group = pi1)) +
  geom_hline(yintercept = 100, color = "white") +
  geom_line() +
  geom_text(
    data = text,
    aes(label = label, hjust = hjust),
    size = 3, parse = T
  ) +
  labs(
    title = "Negative exponential",
    y = expression(E(italic(Y)))
  ) +
  coord_cartesian(ylim = c(0, 100)) +
  theme(panel.grid = element_blank())
```

```{r, fig.width=4, fig.height=4}
(p1 + p2) / (p3 + p4)
```

```{r}
text <-
  tibble(
    time = c(0.2, 9.8, 9.8, 9.8, 1),
    y = c(102.5, 87, 63, 46, 10),
    label = c(
      "alpha==100",
      "pi[1]==1",
      "pi[1]==5",
      "pi[1]==10",
      "pi[0]==10~('for all curves')"
    ),
    hjust = c(0, 1, 1, 1, 0)
  )

crossing(
  alpha = 100,
  pi0 = 10,
  pi1 = c(1, 5, 10)
) %>%
  expand(nesting(alpha, pi0, pi1),
    time = seq(from = 0, to = 10, by = 0.01)
  ) %>%
  mutate(y = pi0 + ((alpha - pi0) * time) / (pi1 + time)) %>%
  ggplot(aes(x = time, y = y, group = pi1)) +
  geom_hline(yintercept = 100, color = "white") +
  geom_line() +
  geom_text(
    data = text,
    aes(label = label, hjust = hjust),
    size = 3, parse = T
  ) +
  scale_x_continuous(breaks = 0:5 * 2, expand = c(0, 0), limits = c(0, 10)) +
  scale_y_continuous(expression(E(italic(Y))),
    expand = c(0, 0), limits = c(0, 110)
  ) +
  labs(title = "Thurstone's learning equation") +
  theme(panel.grid = element_blank())
```

```{r}
n <- 100

alpha <- 20
set.seed(6)
tibble(
  n = 1:n,
  pi0 = rnorm(n, mean = 2, sd = 1),
  pi1 = rnorm(n, mean = 5, sd = 2)
) %>%
  expand(nesting(n, pi0, pi1),
    game = 0:30
  ) %>%
  mutate(y = pi0 + (((alpha - pi0) * game) / (pi1 + game))) %>%
  ggplot(aes(game, y, group = n)) +
  geom_hline(yintercept = c(1, 20), color = "white") +
  geom_line(size = 1 / 4, alpha = 1 / 2) +
  theme(panel.grid = element_blank())
```

```{r}
fit6.17 <-
  brm(
    data = foxngeese_pp,
    family = gaussian,
    bf(nmoves ~ g0 + (((20 - g0) * game) / (g1 + game)),
      g0 + g1 ~ 1 + (1 | i | id),
      nl = TRUE
    ),
    prior = c(
      prior(normal(2, 1), nlpar = g0),
      prior(normal(5, 2), nlpar = g1),
      prior(exponential(1), class = sd, nlpar = g0),
      prior(exponential(1), class = sd, nlpar = g1),
      prior(exponential(1), class = sigma),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, cores = 3, chains = 3,
    inits = 0,
    control = list(adapt_delta = .99),
    file = "fits/fit06.17"
  )
```

```{r}
print(fit6.17)
```

```{r}
# define the new data
nd <-
  foxngeese_pp %>%
  distinct(id) %>%
  filter(id %in% subset) %>%
  expand(id, game = seq(from = 1, to = 30, by = 0.1))

# extract the fitted trajectories
fitted(fit6.17, newdata = nd) %>%
  # wrangle
  data.frame() %>%
  bind_cols(nd) %>%
  # plot!
  ggplot(aes(x = game)) +
  geom_hline(yintercept = c(1, 20), color = "white") +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),
    alpha = 1 / 4, size = 0
  ) +
  geom_line(aes(y = Estimate)) +
  geom_point(
    data = foxngeese_pp %>% filter(id %in% subset),
    aes(y = nmoves),
    size = 2 / 3
  ) +
  scale_y_continuous(breaks = 0:5 * 5, expand = c(0, 0)) +
  coord_cartesian(ylim = c(0, 25)) +
  theme(panel.grid = element_blank()) +
  facet_wrap(~id, ncol = 4, labeller = label_both)
```

```{r}
fit6.17 <- add_criterion(fit6.17, criterion = "waic")

loo_compare(fit6.15, fit6.17, criterion = "waic") %>% print(simplify = F)
```

## 6.5 Bonus: The logistic growth model

```{r}
dogs <-
  read_delim("extra_data/dogs.txt", "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  rename(dog = Dog)
dogs
```

```{r}
dogs <-
  dogs %>%
  pivot_longer(-dog, values_to = "y") %>%
  mutate(trial = str_remove(name, "T.") %>% as.double())
```

```{r, fig.width=4, fig.height=3}
set.seed(6)

subset <- sample(1:30, size = 8)
subset <- sample(1:30) # , size = 8)

dogs %>%
  filter(dog %in% subset) %>%
  ggplot(aes(trial, y)) +
  geom_point() +
  scale_y_continuous(breaks = 0:1) +
  facet_wrap(~dog, ncol = 5, labeller = label_both) +
  theme(panel.grid = element_blank())
```

```{r}
bernoulli_likelihood <- function(p, data) {
  n <- length(data)
  z <- sum(data)
  p^z * (1 - p)^(n - z)
}
```

```{r}
data <- c(1, 1, 0, 1, 1)
p <- 0.5
bernoulli_likelihood(0.99, data)
```

```{r}
rowSums(t(replicate(10000, rbernoulli(1000, p = 0.8)))) %>% table()
```

```{r}
data <- c(0, 1, 1, 1, 1)

tibble(p = seq(0, 1, length.out = 200)) %>%
  mutate(d = bernoulli_likelihood(p, data)) %>%
  ggplot(aes(p, d)) +
  geom_line() +
  geom_vline(xintercept = .8, linetype = 3) +
  scale_x_continuous(expression(italic(p)), breaks = 0:5 / 5) +
  ylab("likelihood") +
  theme(panel.grid = element_blank())
```

```{r}
mean(data)
```

```{r}
n <- 100
z <- 80
data <- rep(1:0, times = c(z, n - z))
tibble(p = seq(0, 1, length.out = 200)) %>%
  mutate(d = bernoulli_likelihood(p, data)) %>%
  ggplot(aes(x = p, y = d)) +
  geom_line() +
  geom_vline(xintercept = z / n, linetype = 3) +
  scale_x_continuous(expression(italic(p)), breaks = 0:5 / 5) +
  ylab("likelihood") +
  theme(panel.grid = element_blank())
```

```{r}
tibble(
  p = seq(.001, .999, by = .001)
) %>%
  mutate(odds = p / (1 - p)) %>%
  mutate(log_odds = log(odds)) %>%
  ggplot(aes(p, y = log_odds)) +
  geom_vline(xintercept = .5, color = "white", linetype = 2) +
  geom_hline(yintercept = 0, color = "white", linetype = 2) +
  geom_line() +
  scale_x_continuous(expression(italic(p)),
    breaks = 0:4 / 4,
    labels = c("0", ".25", ".5", ".75", "1"),
    expand = c(0, 0), limits = 0:1
  ) +
  scale_y_continuous(expression(italic(p) ~ (log ~ odds)), breaks = -2:2 * 2) +
  coord_cartesian(ylim = c(-4.5, 4.5)) +
  theme(panel.grid = element_blank(), aspect.ratio = 1)
```

```{r}
# how many simulations?
n <- 1e3

set.seed(6)

tibble(
  iter = 1:n,
  # notice we set the parameters on the log-odds scale
  b0 = rnorm(n, mean = -2, sd = 1),
  b1 = rnorm(n, mean = 0.25, sd = 0.25)
) %>%
  expand(nesting(iter, b0, b1),
    trial = seq(from = 0, to = 24, length.out = 50)
  ) %>%
  # here we use the inverse logit function to convert the liner model to the probability metric
  mutate(y = inv_logit_scaled(b0 + b1 * trial)) %>%
  # plot!
  ggplot(aes(x = trial, y = y, group = iter)) +
  geom_hline(yintercept = .5, color = "white") +
  geom_line(size = 1 / 4, alpha = 1 / 4) +
  scale_y_continuous(expression(italic(p[i][j])),
    breaks = 0:4 / 4, labels = c("0", ".25", ".5", ".75", "1"),
    expand = c(0, 0), limits = 0:1
  ) +
  labs(subtitle = "prior predictive check") +
  theme(panel.grid = element_blank())
```

```{r}
fit6.18 <-
  brm(
    data = dogs,
    family = bernoulli,
    y ~ 0 + Intercept + trial + (1 + trial | dog),
    prior = c(
      prior(normal(-2, 1), class = b, coef = Intercept),
      prior(normal(0.25, 0.25), class = b),
      prior(exponential(1), class = sd),
      prior(lkj(4), class = cor)
    ),
    iter = 2000, warmup = 1000, cores = 3, chains = 3,
    seed = 6,
    file = "fits/fit06.18"
  )
```

```{r}
print(fit6.18)
```

```{r}
post <- as_draws_df(fit6.18)
post
```

```{r}
post %>%
  expand(nesting(b_Intercept, b_trial),
    trial = seq(0, 25, by = 0.1)
  ) %>%
  mutate(prob = inv_logit_scaled(b_Intercept + b_trial * trial)) %>%
  ggplot(aes(trial, prob)) +
  geom_hline(yintercept = 0:1, color = "white") +
  stat_lineribbon(.width = .95, fill = alpha("grey67", .5)) +
  scale_y_continuous("probability of sucess", breaks = 0:1, limits = 0:1) +
  labs(
    title = "The population-level leraning curve",
    subtitle = expression(We ~ get ~ the ~ overall ~ success ~ probability ~ over ~ time ~ with ~ logit^
      {
        -1
      } * (gamma[0][0] + gamma[1][0] * italic(trial[j])) * ".")
  ) +
  theme(panel.grid = element_blank())
```

```{r}
threshold <-
  post %>%
  transmute(threshold = -b_Intercept / b_trial) %>%
  mean_qi()
threshold
```

```{r}
# adjust for plotting
threshold <-
  threshold %>%
  expand(nesting(threshold, .lower, .upper),
    prob = 0:1
  )


# wrangle
post %>%
  expand(nesting(b_Intercept, b_trial),
    trial = seq(from = 0, to = 25, by = 0.1)
  ) %>%
  mutate(prob = inv_logit_scaled(b_Intercept + b_trial * trial)) %>%
  # plot
  ggplot(aes(x = trial, y = prob)) +
  geom_hline(yintercept = 0:1, color = "white") +
  geom_hline(yintercept = .5, linetype = 2, color = "white") +
  stat_lineribbon(.width = .95, fill = alpha("grey67", .5)) +
  geom_smooth(
    data = threshold,
    aes(x = threshold, xmin = .lower, xmax = .upper),
    stat = "identity",
    fill = "black", color = "black", alpha = 1 / 8
  ) +
  scale_y_continuous("probability of success", breaks = 0:2 / 2, labels = c("0", ".5", "1")) +
  labs(
    title = "The population-level threshold",
    subtitle = expression(-gamma[0][0] / gamma[1][0] * " marks the typical half-way point for learning."),
    x = "trial"
  ) +
  theme(panel.grid = element_blank())
```

```{r}
pi <-
  bind_rows(
    post %>%
      select(ends_with("Intercept]")) %>%
      mutate(across(everything(), ~ . + post$b_Intercept)) %>%
      set_names(1:30),
    post %>%
      select(ends_with("trial]")) %>%
      mutate(across(everything(), ~ . + post$b_trial)) %>%
      set_names(1:30)
  ) %>%
  mutate(
    iter = rep(1:3000, times = 2),
    pi = rep(c("p0", "p1"), each = n() / 2)
  ) %>%
  pivot_longer(-c(iter, pi)) %>%
  pivot_wider(names_from = pi, values_from = value)

pi %>%
  ggplot(aes(p0, p1, group = name)) +
  stat_ellipse(geom = "polygon", level = 0.1, alpha = 1 / 2) +
  labs(
    title = "Dog-level intercepts and slopes",
    subtitle = "Each ellipse marks off the 10% posterior interval.",
    x = expression(pi[0][italic(i)] ~ (log ~ odds)),
    y = expression(pi[1][italic(i)] ~ (log ~ odds))
  ) +
  coord_fixed() +
  theme(panel.grid = element_blank())
```

```{r}
posterior_summary(fit6.18)[3:4, ]
```

```{r, fig.width=4, fig.height=4}
nd <-
  crossing(
    dog = subset,
    trial = seq(0, 25, length.out = 100)
  )
fitted(fit6.18, newdata = nd) %>%
  data.frame() %>%
  bind_cols(nd) %>%
  ggplot(aes(x = trial)) +
  geom_hline(yintercept = 0:1, color = "white") +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), alpha = 1 / 4) +
  geom_line(aes(y = Estimate)) +
  geom_point(data = dogs %>% filter(dog %in% subset), aes(y = y)) +
  scale_y_continuous("y", breaks = 0:1) +
  facet_wrap(~dog, ncol = 5, labeller = label_both) +
  theme(panel.grid = element_blank())
```

```{r}
pi %>%
  mutate(threshold = -p0 / p1) %>%
  group_by(name) %>%
  tidybayes::mean_qi(threshold) %>%
  ggplot(aes(
    x = threshold, xmin = .lower, xmax = .upper,
    y = reorder(name, threshold)
  )) +
  geom_pointrange(fatten = 1) +
  scale_y_discrete("dogs, ranked by threshold", breaks = NULL) +
  xlim(0, 25) +
  labs(
    title = expression(50 * "%" ~ threshold),
    subtitle = expression(-pi[0][italic(i)] / pi[1][italic(i)] * " marks the point where the " * italic(i) * "th dog has acquired the skill half way."),
    x = "trial"
  ) +
  theme(panel.grid = element_blank())
```

```{r, fig.width=4, fig.height=4}
threshold <-
  pi %>%
  mutate(threshold = -p0 / p1) %>%
  group_by(name) %>%
  tidybayes::mean_qi(threshold) %>%
  mutate(dog = name %>% as.double()) %>%
  select(dog, threshold) %>%
  filter(dog %in% subset) %>%
  expand(nesting(dog, threshold), point = 1:3) %>%
  mutate(
    trial = ifelse(point == 1, -Inf, threshold),
    prob = ifelse(point == 3, -Inf, .5)
  )

nd <- crossing(
  dog = subset,
  trial = seq(0, 25, length.out = 100)
)

fitted(fit6.18, newdata = nd) %>%
  data.frame() %>%
  bind_cols(nd) %>%
  ggplot(aes(x = trial)) +
  geom_hline(yintercept = 0:1, color = "white") +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), alpha = 1 / 4) +
  geom_line(aes(y = Estimate)) +
  geom_path(data = threshold, aes(y = prob), linetype = 2) +
  scale_y_continuous("success probability", breaks = 0:2 / 2, labels = c("0", ".5", "1")) +
  facet_wrap(~dog, ncol = 5, labeller = label_both) +
  theme(panel.grid = element_blank())
```
