---
title: "note01"
output: html_notebook
---

```{r}
mean(abs(rnorm(100)))
```

```{r}
rnorm(10)
```

```{r}
x <- c(1, 2, 4)
x
```

```{r}
q <- c(x, x, 8)
q
```

```{r}
x[2:3]
```

```{r}
mean(x)
```

```{r}
sd(x)
```

```{r}
y <- mean(x)
y
```

```{r}
mean(Nile)
sd(Nile)
```

```{r}
hist(Nile)
```

```{r}
oddcount <- function(x) {
  k <- 0
  for (n in x) {
    if (n %% 2 == 1) k <- k + 1
  }
  return(k)
}
oddcount(c(1, 3, 5))
oddcount(c(1, 2, 3, 7, 9))
```

```{r}
z <- c(2, 6, 7)
oddcount(z)
```

```{r}
f <- function(x) {
  return(x + y)
}
y <- 3
f(5)
```

```{r}
x <- c(5, 12, 13)
x
length(x)
mode(x)
typeof(x)
```

```{r}
y <- "abc"
length(y)
mode(y)
typeof(y)
```

```{r}
z <- c("abc", "29 88")
length(z)
mode(z)
```

```{r}
u <- paste("abc", "de", "f")
u
```

```{r}
v <- strsplit(u, " ")
v
```

```{r}
m <- rbind(c(1, 4), c(2, 2))
m
m %*% c(1, 1)
```

```{r}
m[1, 2]
m[2, 2, drop = FALSE]
```

```{r}
m[1, , drop = FALSE]
```

```{r}
m[, 2, drop = FALSE]
```

```{r}
x <- list(u = 2, v = "abc")
x
```

```{r}
hn <- hist(Nile)
print(hn)
```

```{r}
str(hn)
```

```{r}
d <- data.frame(kids = c("Jack", "Jill"), ages = c(12, 10))
d
```

```{r}
summary(d)
```

```{r}
lma <- lm(mpg ~ wt, data = mtcars)
attributes(lma)
```

```{r}
lma$coef
```

```{r}
lma
```

```{r}
summary(lma)
```

```{r}
getwd()
```

```{r}
?"["
```

```{r}
example(seq)
```

```{r}
example(persp)
```

```{r}
help.search("multivariate normal")
```
