---
title: "note12"
output: html_notebook
---

# 12 Interacting with Trellis Displays

## 12.2 Viewports, trellis.vpname(), and trellis.focus()

```{r}
library(lattice)
library(grid)
```

```{r}
current.vpTree()
```

```{r}
trellis.vpname("xlab", prefix = "plot1")
trellis.vpname("strip", column = 2, row = 1, prefix = "plot2")
try(trellis.focus("panel", column = 2, row = 1))
try(trellis.focus())
```

## 12.3 Interactive additions

```{r}
data(Chem97, package = "mlmRev")
```

```{r}
qqmath(
  ~ gcsescore | factor(score),
  data = Chem97,
  groups = gender,
  f.value = function(n) ppoints(100),
  aspect = "xy",
  page = function(n) {
    cat("Click on plot to place legend", fill = TRUE)
    ll <- grid.locator(unit = "npc")
    if (!is.null(ll)) {
      draw.key(simpleKey(levels(factor(Chem97$gender))),
        vp = viewport(x = ll$x, y = ll$y),
        draw = TRUE
      )
    }
  }
)
```

```{r}
state <- data.frame(state.x77, state.region)
p <-
  xyplot(
    Murder ~ Life.Exp | state.region,
    data = state,
    layout = c(2, 2),
    type = c("p", "g"),
    subscripts = TRUE
  )
p
while (!is.null(fp <- trellis.focus())) {
  if (fp$col > 0 & fp$row > 0) {
    panel.identify(labels = rownames(state))
  }
}
```

```{r}
state <- data.frame(state.x77, state.region)

## Figure 12.2
xyplot(Murder ~ Life.Exp | state.region,
  data = state,
  layout = c(2, 2), type = c("p", "g"), subscripts = TRUE
)
while (!is.null(fp <- trellis.focus())) {
  if (fp$col > 0 & fp$row > 0) {
    panel.identify(labels = rownames(state))
  }
}
```

```{r}
qqmath(~ (1000 * Population / Area),
  data = state,
  ylab = "Population Density (per square mile)",
  xlab = "Standard Normal Quantiles",
  scales = list(y = list(log = TRUE, at = 10^(0:3)))
)
trellis.focus()
do.call(panel.qqmathline, trellis.panelArgs())
panel.identify.qqmath(labels = row.names(state))
trellis.unfocus()
```

```{r}
env <- environmental
env$ozone <- env$ozone^(1 / 3)
splom(env, pscales = 0, col = "grey")
trellis.focus("panel", 1, 1, highlight = FALSE)
# panel.link.splom(pch = 16, col = "black")
trellis.unfocus()
```

## 12.4 Other uses

```{r}
state$name <- with(
  state,
  reorder(
    reorder(factor(rownames(state)), Frost),
    as.numeric(state.region)
  )
)
p1 <- dotplot(
  name ~ Frost | reorder(state.region, Frost),
  data = state,
  layout = c(1, 4),
  scales = list(y = list(relation = "free"))
)
p1
```

```{r}
trellis.currentLayout()
```

```{r}
p1
heights <-
  sapply(
    seq_len(nrow(trellis.currentLayout())),
    function(i) {
      trellis.focus("panel", column = 1, row = i, highlight = FALSE)
      h <- diff(current.panel.limits()$ylim)
      trellis.unfocus()
      h
    }
  )
heights
```

```{r}
update(trellis.last.object(),
  par.settings = list(layout.heights = list(panel = heights))
)
```
