---
title: "note10"
output: html_notebook
---

# 10 Function factories

## 10.1 Introduction

```{r}
power1 <- function(exp) {
  function(x) {
    x^exp
  }
}

square <- power1(2)
cube <- power1(3)
```

```{r}
square(3)
cube(3)
```

```{r}
library(rlang)
library(ggplot2)
library(scales)
```

## 10.2 Factory fundamentals

```{r}
square
```

```{r}
cube
```

```{r}
env_print(square)
env_print(cube)
```

```{r}
fn_env(square)$exp
fn_env(cube)$exp
```

```{r}
x <- 2
square <- power1(x)
x <- 3
square(2)
```

```{r}
power2 <- function(exp) {
  force(exp)
  function(x) {
    x^exp
  }
}
x <- 2
square <- power2(x)
x <- 3
square(2)
```

```{r}
new_counter <- function() {
  i <- 0

  function() {
    i <<- i + 1
    i
  }
}
counter_one <- new_counter()
counter_two <- new_counter()
```

```{r}
counter_one()
counter_one()
counter_two()
```

```{r}
f1 <- function(n) {
  x <- runif(n)
  m <- mean(x)
  function() m
}

g1 <- f1(1e6)
lobstr::obj_size(g1)
```

```{r}
f2 <- function(n) {
  x <- runif(n)
  m <- mean(x)
  rm(x)
  function() m
}
g2 <- f2(1e6)
lobstr::obj_size(g2)
```

```{r}
x <- runif(10)
y <- runif(10)
plot(x, y, lwd = 10)
```

```{r}
f_lin <- approxfun(x, y)
f_con <- approxfun(x, y, method = "constant")

identical(f_lin(x), y)
identical(f_con(x), y)
```

```{r}
x_new <- runif(1000)
x_new <- seq(min(x), max(x), length.out = 1000)
plot(x, y, lwd = 10)
points(x_new, f_lin(x_new), col = "cornflowerblue", pch = 16)
points(x_new, f_con(x_new), col = "firebrick", pch = 16)
```

```{r}
f_lin(range(x))
f_con(range(x))

(eps <- .Machine$double.neg.eps)
```

```{r}
f_lin(c(min(x) - eps, max(x) + eps))
f_con(c(min(x) - eps, max(x) + eps))
```

```{r}
f_lin <- approxfun(x, y, rule = 2)
f_con <- approxfun(x, y, method = "constant", rule = 2)

f_lin(c(-Inf, Inf))
#> [1] 0.402 0.175
f_con(c(-Inf, Inf))
#> [1] 0.402 0.175
```

```{r}
f_lin <- approxfun(x, y, yleft = 5)
f_con <- approxfun(x, y, method = "constant", yleft = 5, yright = -5)

f_lin(c(-Inf, Inf))
f_con(c(-Inf, Inf))
```

```{r}
f_con <- approxfun(x, y, method = "constant", f = .5)

plot(x, y, lwd = 10)
points(x_new, f_con(x_new), pch = 16)
```

```{r}
x <- runif(10)
f_ecdf <- ecdf(x)
class(f_ecdf)
```

```{r}
plot(x, f_ecdf(x), lwd = 10, ylim = 0:1)
```

```{r}
x_new <- runif(1000)
plot(x, f_ecdf(x), lwd = 10, ylim = 0:1)
points(x_new, f_ecdf(x_new), ylim = 0:1)
```

```{r}
pick <- function(i) {
  force(i)
  function(x) x[[i]]
}

x <- 1:10
pick(1)(x)

identical(
  lapply(mtcars, pick(5)),
  lapply(mtcars, function(x) x[[5]])
)
```

```{r}
moment <- function(i) {
  force(i)
  function(x) sum((x - mean(x))^i) / length(x)
}
m1 <- moment(1)
m2 <- moment(2)
x <- runif(100)
stopifnot(all.equal(m1(x), 0))
stopifnot(all.equal(m2(x), var(x) * 99 / 100))
```

```{r}
i <- 0
new_counter2 <- function() {
  i <<- i + 1
  i
}
new_counter2()
i
new_counter2()
i
i <- 0
new_counter2()
```

```{r}
new_counter3 <- function() {
  i <- 0
  function() {
    i <- i + 1
    i
  }
}

new_counter_3 <- new_counter3()
new_counter_3()
new_counter_3()
```

## 10.3 Graphical factories

```{r}
y <- c(12345, 123456, 1234567)
comma_format()(y)
```

```{r}
number_format(scale = 1e-3, suffix = " K")(y)
```

```{r}
df <- data.frame(x = 1, y = y)
core <- ggplot(df, aes(x, y)) +
  geom_point() +
  scale_x_continuous(breaks = 1, labels = NULL) +
  labs(x = NULL, y = NULL)
```

```{r}
core
```

```{r}
core + scale_y_continuous(
  labels = comma_format()
)
```

```{r}
core + scale_y_continuous(
  labels = number_format(scale = 1e3, suffix = " K")
)
```

```{r}
core + scale_y_continuous(
  labels = scientific_format()
)
```

```{r}
sd <- c(1, 5, 15)
n <- 100
df <- data.frame(x = rnorm(3 * n, sd = sd), sd = rep(sd, n))
df
```

```{r}
ggplot(df, aes(x)) +
  geom_histogram(binwidth = 2) +
  facet_wrap(~sd, scales = "free_x") +
  labs(x = NULL)
```

```{r}
binwidth_bins <- function(n) {
  force(n)
  function(x) {
    (max(x) - min(x)) / n
  }
}

ggplot(df, aes(x)) +
  geom_histogram(binwidth = binwidth_bins(20)) +
  facet_wrap(~sd, scales = "free_x") +
  labs(x = NULL)
```

```{r}
base_bins <- function(type) {
  fun <- switch(type,
    Sturges = nclass.Sturges,
    scott = nclass.scott,
    FD = nclass.FD,
    stop("Unknown type", call. = FALSE)
  )

  function(x) {
    (max(x) - min(x)) / fun(x)
  }
}

ggplot(df, aes(x)) +
  geom_histogram(binwidth = base_bins("FD")) +
  facet_wrap(~sd, scales = "free_x") +
  labs(x = NULL)
```

```{r}
plot_dev <- function(ext, dpi = 96) {
  force(dpi)

  switch(ext,
    eps = ,
    ps = function(path, ...) {
      grDevices::postscript(
        file = filename, ..., onefile = FALSE,
        horizontal = FALSE, paper = "special"
      )
    },
    pdf = function(filename, ...) grDevices::pdf(file = filename, ...),
    svg = function(filename, ...) svglite::svglite(file = filename, ...),
    emf = ,
    wmf = function(...) grDevices::win.metafile(...),
    png = function(...) grDevices::png(..., res = dpi, units = "in"),
    jpg = ,
    jpeg = function(...) grDevices::jpeg(..., res = dpi, units = "in"),
    bmp = function(...) grDevices::bmp(..., res = dpi, units = "in"),
    tiff = function(...) grDevices::tiff(..., res = dpi, units = "in"),
    stop("Unknown graphics extension: ", ext, call. = FALSE)
  )
}

plot_dev("pdf")
plot_dev("png")
```

## 10.4 Statistical factories

```{r}
boxcox1 <- function(x, lambda) {
  stopifnot(length(lamba) == 1)

  if (lambda == 0) {
    log(x)
  } else {
    (x^lambda - 1) / lambda
  }
}
```

```{r}
boxcox2 <- function(lambda) {
  if (lambda == 0) {
    function(x) log(x)
  } else {
    function(x) (x^lambda - 1) / lambda
  }
}
```

```{r}
stat_boxcox <- function(lambda) {
  stat_function(aes(color = lambda), fun = boxcox2(lambda), size = 1)
}

ggplot(data.frame(x = c(0, 5)), aes(x)) +
  lapply(c(0.5, 1, 1.5), stat_boxcox) +
  scale_color_viridis_c(limits = c(0, 1.5))
```

```{r}
ggplot(data.frame(x = c(0, 5)), aes(x)) +
  stat_function(aes(color = 0.5), fun = boxcox2(0.5), size = 1) +
  stat_function(aes(color = 1), fun = boxcox2(1), size = 1) +
  stat_function(aes(color = 1.5), fun = boxcox2(1.5), size = 1)
```

```{r}
ggplot(data.frame(x = c(0.01, 1)), aes(x)) +
  lapply(c(0.5, 0.25, 0.1, 0), stat_boxcox) +
  scale_colour_viridis_c(limits = c(0, 1.5))
```

```{r}
boot_permute <- function(df, var) {
  n <- nrow(df)
  force(var)

  function() {
    col <- df[[var]]
    col[sample(n, replace = TRUE)]
  }
}

boot_mtcars1 <- boot_permute(mtcars, "mpg")
boot_mtcars1()
```

```{r}
boot_mtcars1()
```

```{r}
boot_model <- function(df, formula) {
  mod <- lm(formula, data = df)
  fitted <- unname(fitted(mod))
  resid <- unname(resid(mod))
  rm(mod)

  function() {
    fitted + sample(resid)
  }
}

boot_mtcars2 <- boot_model(mtcars, mpg ~ wt)
boot_mtcars2()
boot_mtcars2()
```

```{r}
lprob_poisson <- function(lambda, x) {
  n <- length(x)
  (log(lambda) * sum(x)) - (n * lambda) - sum(lfactorial(x))
}
x1 <- c(41, 30, 31, 38, 29, 24, 30, 29, 31, 38)
```

```{r}
lprob_poisson(10, x1)
lprob_poisson(20, x1)
lprob_poisson(30, x1)
```

```{r}
ll_poisson1 <- function(x) {
  n <- length(x)

  function(lambda) {
    log(lambda) * sum(x) - n * lambda - sum(lfactorial(x))
  }
}
```

```{r}
ll_poisson2 <- function(x) {
  n <- length(x)
  sum_x <- sum(x)
  c <- sum(lfactorial(x))

  function(lambda) {
    log(lambda) * sum_x - n * lambda - c
  }
}
```

```{r}
ll1 <- ll_poisson2(x1)
```

```{r}
ll1(10)
ll1(20)
ll1(30)
```

```{r}
optimize(ll1, c(0, 100), maximum = TRUE)
```

```{r}
optimize(lprob_poisson, c(0, 100), x = x1, maximum = TRUE)
```

```{r}
boxcox3 <- function(x) {
  function(lambda) {
    if (lambda == 0) {
      log(x)
    } else {
      (x^lambda - 1) / lambda
    }
  }
}

boxcox_airpassengers <- boxcox3(AirPassengers)

plot(boxcox_airpassengers(0))
plot(boxcox_airpassengers(1))
plot(boxcox_airpassengers(2))
plot(boxcox_airpassengers(3))
```

```{r}
boot_mtcars1 <- boot_permute(mtcars, "mpg")

lobstr::obj_size(mtcars)
lobstr::obj_size(boot_mtcars1)
lobstr::obj_sizes(mtcars, boot_mtcars1)
```

```{r}
bench::mark(
  llp1 = optimise(ll_poisson1(x1), c(0, 100), maximum = TRUE),
  llp2 = optimise(ll_poisson2(x1), c(0, 100), maximum = TRUE)
)
```

```{r}
bench_poisson <- function(x_length) {
  x <- rpois(x_length, 100L)

  bench::mark(
    llp1 = optimise(ll_poisson1(x), c(0, 100), maximum = TRUE),
    llp2 = optimise(ll_poisson2(x), c(0, 100), maximum = TRUE),
    time_unit = "ms"
  )
}

performances <- purrr::map_dfr(10^(1:5), bench_poisson)

df_perf <- data.frame(
  x_length = rep(10^(1:5), each = 2),
  method   = rep(attr(performances$expression, "description"), 5),
  median   = performances$median
)

ggplot(df_perf, aes(x_length, median, col = method)) +
  geom_point(size = 2) +
  geom_line(linetype = 2) +
  scale_x_log10() +
  labs(
    x = "Length of x",
    y = "Execution Time (ms)",
    color = "Method"
  ) +
  theme(legend.position = "top")
```

## 10.5 Function factories + functionals

```{r}
names <- list(
  square = 2,
  cube = 3,
  root = 1 / 2,
  cuberoot = 1 / 3,
  reciprocal = -1
)
funs <- purrr::map(names, power1)
funs$root(64)
```

```{r}
with(funs, root(100))
```

```{r}
attach(funs)
root(100)
detach(funs)
```

```{r}
rlang::env_bind(globalenv(), !!!funs)
root(100)
```

```{r}
rlang::env_unbind(globalenv(), names(funs))
```
