---
title: "note25"
output: html_notebook
---

# 25 Rewriting R code in C++

## 25.1 Introduction

```{r}
library(Rcpp)
```

## 25.2 Getting started with C++

```{r}
cppFunction("int add(int x, int y, int z) {
  int sum = x + y + z;
  return sum;
}")
add
add(1, 2, 3)
```

```{r}
signR <- function(x) {
  if (x > 0) {
    1
  } else if (x == 0) {
    0
  } else {
    -1
  }
}

cppFunction("
int signC(int x) {
  if (x > 0) {
    return 1;
  } else if (x == 0) {
    return 0;
  } else {
    return -1;
  }
}
")
```

```{r}
sumR <- function(x) {
  total <- 0
  for (i in seq_along(x)) {
    total <- total + x[i]
  }
  total
}

cppFunction("
double sumC(NumericVector x) {
  int n = x.size();
  double total = 0;
  for(int i = 0; i < n; ++i) {
    total += x[i];
  }
  return total;
}")
```

```{r}
x <- runif(1e4)
bench::mark(
  sum(x),
  sumC(x),
  sumR(x)
)
```

```{r}
pdistR <- function(x, ys) {
  sqrt((x - ys)^2)
}

cppFunction("
NumericVector pdistC(double x, NumericVector ys) {
  int n = ys.size();
  NumericVector out(n);

  for(int i = 0; i < n; ++i) {
    out[i] = sqrt(pow(ys[i] - x, 2.0));
  }
  return out;
}
")
```

```{r}
y <- runif(1e6)
bench::mark(
  pdistR(0.5, y),
  pdistC(0.5, y)
)
```

```{r}
sourceCpp("cpp/meanC.cpp")
```

```{r}
cppFunction("
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double meanC(NumericVector x) {
  int n = x.size();
  double total = 0;

  for(int i = 0; i < n; ++i) {
    total += x[i];
  }
  return total / n;
}

/*** R
x <- runif(1e5)
bench::mark(
  mean(x),
  meanC(x)
)
*/
")
```

```{r}
cppFunction("
double meanC(NumericVector x) {
  int n = x.size();
  double y = 0;

  for(int i = 0; i < n; ++i) {
    y += x[i] / n;
  }
  return y;
}

NumericVector cumsumC(NumericVector x) {
  int n = x.size();
  NumericVector out(n);

  out[0] = x[0];
  for(int i = 1; i < n; ++i) {
    out[i] = out[i - 1] + x[i];
  }
  return out;
}

bool anyC(LogicalVector x) {
  int n = x.size();

  for(int i = 0; i < n; ++i) {
    if (x[i]) return true;
  }
  return false;
}

int PositionC(Function pred, List x) {
  int n = x.size();

  for(int i = 0; i < n; ++i) {
    LogicalVector res = pred(x[i]);
    if (res[0]) return i + 1;
  }
  return 0;
}

NumericVector pminC(NumericVector x, NumericVector y) {
  int n = std::max(x.size(), y.size());
  NumericVector x1 = rep_len(x, n);
  NumericVector y1 = rep_len(y, n);

  NumericVector out(n);

  for (int i = 0; i < n; ++i) {
    out[i] = std::min(x1[i], y1[i]);
  }

  return out;
}
")
```

```{r}
cppFunction("
NumericVector cumprodC(NumericVector x) {
  int n = x.size();
  NumericVector out(n);

  out[0] = x[0];
  for (int i = 1; i < n; ++i) {
    out[i]  = out[i - 1] * x[i];
  }
  return out;
}

NumericVector cumminC(NumericVector x) {
  int n = x.size();
  NumericVector out(n);

  out[0] = x[0];
  for (int i = 1; i < n; ++i) {
    out[i]  = std::min(out[i - 1], x[i]);
  }
  return out;
}

NumericVector cummaxC(NumericVector x) {
  int n = x.size();
  NumericVector out(n);

  out[0] = x[0];
  for (int i = 1; i < n; ++i) {
    out[i]  = std::max(out[i - 1], x[i]);
  }
  return out;
}
")
```

```{r}
cppFunction('
NumericVector diffC(NumericVector x) {
  int n = x.size();
  NumericVector out(n - 1);

  for (int i = 1; i < n; i++) {
    out[i - 1] = x[i] - x[i - 1];
  }
  return out ;
}

NumericVector difflagC(NumericVector x, int lag = 1) {
  int n = x.size();

  if (lag >= n) stop("`lag` must be less than `length(x)`.");

  NumericVector out(n - lag);

  for (int i = lag; i < n; i++) {
    out[i - lag] = x[i] - x[i - lag];
  }
  return out;
}
')
```

```{r}
cppFunction('
NumericVector rangeC(NumericVector x) {
  double omin = x[0], omax = x[0];
  int n = x.size();

  if (n == 0) stop("`length(x)` must be greater than 0.");

  for (int i = 1; i < n; i++) {
    omin = std::min(x[i], omin);
    omax = std::max(x[i], omax);
  }

  NumericVector out(2);
  out[0] = omin;
  out[1] = omax;
  return out;
}
')
```

```{r}
cppFunction("
double varC(NumericVector x) {
  int n = x.size();

  if (n < 2) {
    return NA_REAL;
  }

  double mx = 0;
  for (int i = 0; i < n; ++i) {
    mx += x[i] / n;
  }

  double out = 0;
  for (int i = 0; i < n; ++i) {
    out += pow(x[i] - mx, 2);
  }

  return out / (n - 1);
}
")
```

## 25.3 Other classes

```{r}
sourceCpp("cpp/mpe.cpp")
mod <- lm(mpg ~ wt, data = mtcars)
mpe(mod)
```

```{r}
cppFunction("
RObject callWithOne(Function f) {
  return f(1);
}
")
callWithOne(function(x) x + 1)
callWithOne(paste)
```

```{r}
cppFunction('
NumericVector attribs() {
  NumericVector out = NumericVector::create(1, 2, 3);

  out.names() = CharacterVector::create("a", "b", "c");
  out.attr("my-attr") = "my-value";
  out.attr("class") = "my-class";

  return out;
}
')
attribs()
```

## 25.4 Missing values

```{r}
cppFunction("
List scalar_missings() {
  int int_s = NA_INTEGER;
  String chr_s = NA_STRING;
  bool lgl_s = NA_LOGICAL;
  double num_s = NA_REAL;

  return List::create(int_s, chr_s, lgl_s, num_s);
}
")
str(scalar_missings())
```

```{r}
evalCpp("NAN == 1")
evalCpp("NAN < 1")
evalCpp("NAN > 1")
evalCpp("NAN == NAN")
```

```{r}
evalCpp("NAN && TRUE")
evalCpp("NAN || TRUE")
```

```{r}
evalCpp("NAN + 1")
evalCpp("NAN - 1")
evalCpp("NAN / 1")
evalCpp("NAN * 1")
```

```{r}
cppFunction("
List missing_sampler() {
  return List::create(
    NumericVector::create(NA_REAL),
    IntegerVector::create(NA_INTEGER),
    LogicalVector::create(NA_LOGICAL),
    CharacterVector::create(NA_STRING)
  );
}
")
str(missing_sampler())
```

```{r}
sourceCpp("cpp/minC.cpp")
minC(c(2:4, NA))
minC(c(2:4, NA), na_rm = TRUE)
minC(c(NA, NA), na_rm = TRUE)
```

```{r}
sourceCpp("cpp/anyC.cpp")
anyC(c(NA, TRUE))
anyC(c(NA, TRUE), na_rm = TRUE)
```

```{r}
sourceCpp("cpp/cumsumC.cpp")
cumsumC(c(1, NA, 2, 4))
cumsumC(c(1, NA, 2, 4), na_rm = TRUE)
```

```{r}
sourceCpp("cpp/diffC.cpp")
diffC(c(1, 3, NA, 10))
diffC(c(1, 3, NA, 10), na_rm = TRUE)
```

## 25.5 Standard Template Library

```{r}
cppFunction("
double sum3(NumericVector x) {
  double total = 0;

  NumericVector::iterator it;
  for(it = x.begin(); it != x.end(); ++it) {
    total += *it;
  }
  return total;
}
")
```

```{r}
cppFunction("
double sum4(NumericVector xs) {
  double total = 0;

  for(const auto &x : xs) {
    total += x;
  }
  return total;
}
")
```

```{r}
cppFunction("
double sum5(NumericVector x) {
  return std::accumulate(x.begin(), x.end(), 0.0);
}
")
```

```{r}
sourceCpp("cpp/findInterval2.cpp")
```

```{r}
sourceCpp("cpp/duplicatedC.cpp")
x <- sample(1:10, 100000, replace = TRUE)
# x
bench::mark(
  duplicated(x),
  duplicatedC(x)
)
```

```{r}
sourceCpp("cpp/inC.cpp")
x <- sample(1:10, 100000, replace = TRUE)
y <- sample(1)
```

```{r}
inC(y, x)
```

## 25.6 Case studies

```{r}
gibbs_r <- function(N, thin) {
  mat <- matrix(nrow = N, ncol = 2)
  x <- y <- 0

  for (i in 1:N) {
    for (j in 1:thin) {
      x <- rgamma(1, 3, y * y + 4)
      y <- rnorm(1, 1 / (x + 1), 1 / sqrt(2 * (x + 1)))
    }
    mat[i, ] <- c(x, y)
  }
  mat
}

cppFunction("
NumericMatrix gibbs_cpp(int N, int thin) {
  NumericMatrix mat(N, 2);
  double x = 0, y = 0;

  for(int i = 0; i < N; i++) {
    for(int j = 0; j < thin; j++) {
      x = rgamma(1, 3, 1 / (y * y + 4))[0];
      y = rnorm(1, 1 / (x + 1), 1 / sqrt(2 * (x + 1)))[0];
    }
    mat(i, 0) = x;
    mat(i, 1) = y;
  }

  return(mat);
}
")

bench::mark(
  gibbs_r(100, 10),
  gibbs_cpp(100, 10),
  check = FALSE
)
```

```{r}
vacc1a <- function(age, female, ily) {
  p <- 0.25 + 0.3 * 1 / (1 - exp(0.04 * age)) + 0.1 * ily
  p <- p * if (female) 1.25 else 0.75
  p <- max(0, p)
  p <- min(1, p)
  p
}
```

```{r}
vacc1 <- function(age, female, ily) {
  n <- length(age)
  out <- numeric(n)
  for (i in seq_len(n)) {
    out[i] <- vacc1a(age[i], female[i], ily[i])
  }
  out
}
```

```{r}
vacc2 <- function(age, female, ily) {
  p <- 0.25 + 0.3 * 1 / (1 - exp(0.04 * age)) + 0.1 * ily
  p <- p * ifelse(female, 1.25, 0.75)
  p <- pmax(0, p)
  p <- pmin(1, p)
  p
}

vacc2_ <- function(age, female, ily) {
  p <- 0.25 + 0.3 * 1 / (1 - exp(0.04 * age)) + 0.1 * ily
  p <- p * 0.75 + p * 0.5 * female
  p[p < 0] <- 0
  p[p > 1] <- 1
  p
}
```

```{r}
sourceCpp("cpp/vacc.cpp")
```

```{r}
n <- 1000
age <- rnorm(n, mean = 50, sd = 10)
female <- sample(c(T, F), n, rep = TRUE)
ily <- sample(c(T, F), n, prob = c(0.8, 0.2), rep = TRUE)

stopifnot(
  all.equal(vacc1(age, female, ily), vacc2(age, female, ily)),
  all.equal(vacc1(age, female, ily), vacc2_(age, female, ily)),
  all.equal(vacc1(age, female, ily), vacc3(age, female, ily))
)
```

```{r}
bench::mark(
  vacc1 = vacc1(age, female, ily),
  vacc2 = vacc2(age, female, ily),
  vacc2_ = vacc2_(age, female, ily),
  vacc3 = vacc3(age, female, ily)
)
```

## 25.7 Using Rcpp in a package

## 25.8 Learning more

## 25.9 Acknowledgments
