---
title: "note18"
output: html_notebook
---

# 18 Expressions

## 18.1 Introduction

```{r}
library(rlang)
library(lobstr)
```

```{r}
z <- rlang::expr(y <- x * 10)
z
```

```{r}
x <- 4
eval(z)
y
```

## 18.2 Abstract syntax trees

```{r}
ast(f(x, "y", 1))
```

```{r}
ast(f(g(1, 2), h(3, 4, i())))
```

```{r}
ast(
  f(x, y)
)
```

```{r}
ast(y <- x)
```

```{r}
ast(y < -x)
```

```{r}
ast(y <- x * 10)
```

```{r}
expr(`<-`(y, `*`(x, 10)))
```

```{r}
ast(f(g(h())))
```

```{r}
ast(1 + 2 + 3)
```

```{r}
ast((x + y) * z)
```

```{r}
ast(f(g(h(i(1, 2, 3)))))
```

```{r}
ast(f(1, g(2, h(3, i()))))
```

```{r}
ast(f(g(1, 2), h(3, i(4, 5))))
```

```{r}
ast(`x` + `y`)
```

```{r}
ast(x**y)
```

```{r}
ast(1 -> x)
```

```{r}
ast(function(x = 1, y = 2) {})
```

```{r}
ast(
  if (FALSE) {
    1
  } else if (FALSE) {
    2
  } else if (TRUE) 3
)
```

## 18.3 Expressions

```{r}
identical(expr(TRUE), TRUE)
identical(expr(1), 1)
identical(expr(1L), 1L)
identical(expr("x"), "x")
```

```{r}
expr(x)
sym("x")
```

```{r}
as_string(expr(x))
```

```{r}
str(expr(x))
is.symbol(expr(x))
```

```{r}
syms(list("x", "y"))
```

```{r}
ast(read.table("important.csv", row.names = FALSE))
```

```{r}
x <- expr(read.table("important.csv", row.names = FALSE))
typeof(x)
is.call(x)
```

```{r}
x[[1]]
is.symbol(x[[1]])
```

```{r}
as.list(x[-1])
```

```{r}
x[[2]]
x$row.names
```

```{r}
length(x) - 1
```

```{r}
call_standardise(x)
```

```{r}
x$header <- TRUE
x
```

```{r}
ast(foo())
```

```{r}
ast("foo"())
```

```{r}
ast(pkg::foo(1))
```

```{r}
ast(obj$foo(1))
```

```{r}
ast(foo(1)(2))
```

```{r}
call2("mean", x = expr(x), na.rm = TRUE)
```

```{r}
call2("<-", expr(x), 10)
```

```{r}
is_atomic(expr(1))
is_atomic(expr(c(1, 1)))
is_call(expr(c(1, 1)))
```

```{r}
expr(read.csv("foo.csv", header = TRUE))[-1]
```

```{r}
x <- 1:10
call2(median, x, na.rm = TRUE)
call2(expr(median), x, na.rm = TRUE)
call2(median, expr(x), na.rm = TRUE)
call2(expr(median), expr(x), na.rm = TRUE)
```

```{r}
call_standardise(quote(mean(1:10, na.rm = TRUE)))
call_standardise(quote(mean(n = T, 1:10)))
call_standardise(quote(mean(x = 1:10, , TRUE)))
```

```{r}
call_standardise(quote(mean.default(1:10, na.rm = TRUE)))
call_standardise(quote(mean.default(n = T, 1:10)))
call_standardise(quote(mean.default(x = 1:10, , TRUE)))
```

```{r}
x <- expr(foo(x = 1))
x
names(x) <- c("x", "")
x
names(x) <- c("", "x")
x
```

```{r}
call2("if", call2(">", sym("x"), 1), "a", "b")
```

```{r}
ast(`if`(x > 1, "a", "b"))
```

## 18.4 Parsing and grammar

```{r}
ast(1 + 2 * 3)
```

```{r}
ast(!x %in% y)
```

```{r}
ast(1 + 2 + 3)
```

```{r}
ast(2^2^3)
```

```{r}
ast(x <- y <- z)
```

```{r}
x1 <- "y <- x + 10"
x1
is.call(x1)
```

```{r}
x2 <- parse_expr(x1)
x2
is.call(x2)
```

```{r}
x3 <- "a <- 1; a + 1"
parse_exprs(x3)
```

```{r}
as.list(parse(text = x1))
```

```{r}
z <- expr(y <- x + 10)
expr_text(z)
```

```{r}
cat(expr_text(expr({
  # This is a comment
  x <- `x` + 1
})))
```

```{r}
ast(f((1)))
```

```{r}
ast(`(`(1 + 1))
```

```{r}
ast(((1 + 1)))
```

```{r}
ast({
  b <- c(c = 1)
})
```

```{r}
ast(-2^2)
```

```{r}
!1 + !1
ast(!1 + !1)
```

```{r}
x1 <- x2 <- x3 <- 0
(x3 <- 0)
```

```{r}
ast(x + y %+% z)
```

```{r}
ast(x^y %+% z)
```

```{r}
try(parse_expr("x + 1; y + 1"))
```

```{r}
try(parse_expr("a +"))
```

```{r}
try(parse_expr("f())"))
```

```{r}
try(parse(text = "a +"))
```

```{r}
try(parse(text = "f())"))
```

```{r}
expr <- expr(g(a + b + c + d + e + f + g + h + i + j + k + l + m +
  n + o + p + q + r + s + t + u + v + w + x + y + z))

deparse(expr)
```

```{r}
expr_text(expr)
```

```{r}
d <- 1
pairwise.t.test(2, d + d + d + d + d + d + d + d +
  d + d + d + d + d + d + d + d + d)
```

## 18.5 Walking AST with recursive functions

```{r}
expr_type <- function(x) {
  if (rlang::is_syntactic_literal(x)) {
    "constant"
  } else if (is.symbol(x)) {
    "symbol"
  } else if (is.call(x)) {
    "call"
  } else if (is.pairlist(x)) {
    "pairlist"
  } else {
    typeof(x)
  }
}
expr_type(expr("a"))
expr_type(expr(x))
expr_type(expr(f(1, 2)))
```

```{r}
switch_expr <- function(x, ...) {
  switch(expr_type(x),
    ...,
    stop("Don't know how to handle type ", typeof(x), call. = FALSE)
  )
}
```

```{r}
recurse_call <- function(x) {
  switch_expr(x,
    symbol = ,
    constant = ,
    call = ,
    pairlist =
    )
}
```

```{r}
expr_type(expr(TRUE))
expr_type(expr(T))
```

```{r}
logical_abbr_rec <- function(x) {
  switch_expr(
    x,
    constant = FALSE,
    symbol = as_string(x) %in% c("F", "T")
  )
}
logical_abbr_rec(expr(TRUE))
logical_abbr_rec(expr(T))
```

```{r}
logical_abbr <- function(x) {
  logical_abbr_rec(enexpr(x))
}

logical_abbr(T)
#> [1] TRUE
logical_abbr(FALSE)
#> [1] FALSE
```

```{r}
logical_abbr_rec <- function(x) {
  switch_expr(x,
    # Base cases
    constant = FALSE,
    symbol = as_string(x) %in% c("F", "T"),

    # Recursive cases
    call = ,
    pairlist = purrr::some(x, logical_abbr_rec)
  )
}

logical_abbr(mean(x, na.rm = T))
#> [1] TRUE
logical_abbr(function(x, na.rm = T) FALSE)
#> [1] TRUE
```

```{r}
ast(x <- 10)
```

```{r}
find_assign_rec <- function(x) {
  switch_expr(
    x,
    constant = ,
    symbol = character()
  )
}
find_assign <- function(x) find_assign_rec(enexpr(x))
find_assign("x")
find_assign(x)
```

```{r}
flat_map_chr <- function(.x, .f, ...) {
  purrr::flatten_chr(purrr::map(.x, .f, ...))
}

flat_map_chr(letters[1:3], ~ rep(., sample(3, 1)))
```

```{r}
find_assign_rec <- function(x) {
  switch_expr(x,
    # Base cases
    constant = ,
    symbol = character(),

    # Recursive cases
    pairlist = flat_map_chr(as.list(x), find_assign_rec),
    call = {
      if (is_call(x, "<-")) {
        as_string(x[[2]])
      } else {
        flat_map_chr(as.list(x), find_assign_rec)
      }
    }
  )
}

find_assign(a <- 1)
find_assign({
  a <- 1
  {
    b <- 2
  }
})
```

```{r}
find_assign({
  a <- 1
  a <- 2
})
```

```{r}
find_assign({
  a <- b <- c <- 1
})
```

```{r}
find_assign_call <- function(x) {
  if (is_call(x, "<-") && is_symbol(x[[2]])) {
    lhs <- as_string(x[[2]])
    children <- as.list(x)[-1]
  } else {
    lhs <- character()
    children <- as.list(x)
  }

  c(lhs, flat_map_chr(children, find_assign_rec))
}

find_assign_rec <- function(x) {
  switch_expr(x,
    # Base cases
    constant = ,
    symbol = character(),

    # Recursive cases
    pairlist = flat_map_chr(x, find_assign_rec),
    call = find_assign_call(x)
  )
}

find_assign(a <- b <- c <- 1)
find_assign(system.time(x <- print(y <- 5)))
```

```{r}
find_T_call <- function(x) {
  if (is_call(x, "T")) {
    x <- as.list(x)[-1]
    purrr::some(x, logical_abbr_rec)
  } else {
    purrr::some(x, logical_abbr_rec)
  }
}

logical_abbr_rec <- function(x) {
  switch_expr(
    x,
    # Base cases
    constant = FALSE,
    symbol = as_string(x) %in% c("F", "T"),

    # Recursive cases
    pairlist = purrr::some(x, logical_abbr_rec),
    call = find_T_call(x)
  )
}

logical_abbr <- function(x) {
  logical_abbr_rec(enexpr(x))
}
```

```{r}
logical_abbr(T(1, 2, 3))
logical_abbr(T(T, T(3, 4)))
logical_abbr(T(T))
logical_abbr(T())
logical_abbr()
logical_abbr(c(T, T, T))
```

```{r}
ast(names(x) <- x)
```

```{r}
flat_map_chr <- function(.x, .f, ...) {
  purrr::flatten_chr(purrr::map(.x, .f, ...))
}

find_assign <- function(x) unique(find_assign_rec(enexpr(x)))

find_assign_call <- function(x) {
  if (is_call(x, "<-") && is_symbol(x[[2]])) {
    lhs <- as_string(x[[2]])
    children <- as.list(x)[-1]
  } else {
    if (is_call(x, "<-") && is_call(x[[2]])) {
      lhs <- expr_text(x[[2]])
      children <- as.list(x)[-1]
    } else {
      lhs <- character()
      children <- as.list(x)
    }
  }

  c(lhs, flat_map_chr(children, find_assign_rec))
}

find_assign_rec <- function(x) {
  switch_expr(
    x,
    # Base cases
    constant = , symbol = character(),
    # Recursive cases
    pairlist = flat_map_chr(x, find_assign_rec),
    call = find_assign_call(x)
  )
}

# Tests functionality
find_assign(x <- y)
find_assign(names(x))
find_assign(names(x) <- y)
find_assign(names(x(y)) <- y)
find_assign(names(x(y)) <- y <- z)
```

```{r}
find_assign_call <- function(x) {
  if (is_call(x)) {
    lhs <- expr_text(x)
    children <- as.list(x)[-1]
  } else {
    lhs <- character()
    children <- as.list(x)
  }

  c(lhs, flat_map_chr(children, find_assign_rec))
}

find_assign_rec <- function(x) {
  switch_expr(
    x,
    # Base cases
    constant = ,
    symbol = character(),

    # Recursive cases
    pairlist = flat_map_chr(x, find_assign_rec),
    call = find_assign_call(x)
  )
}

find_assign(x <- y)
find_assign(names(x(y)) <- y <- z)
find_assign(mean(sum(1:3)))
```

## 18.6 Specialised data structures

```{r}
f <- expr(function(x, y = 10) x + y)
args <- f[[2]]
args
typeof(args)
```

```{r}
pl <- pairlist(x = 1, y = 2)
length(pl)
pl$x
```

```{r}
missing_arg()
typeof(missing_arg())
```

```{r}
is_missing(missing_arg())
```

```{r}
f <- expr(function(x, y = 10) x + y)
args <- f[[2]]
is_missing(args[[1]])
```

```{r}
f <- expr(function(...) list(...))
args <- f[[2]]
is_missing(args[[1]])
```

```{r}
m <- missing_arg()
try(m)
```

```{r}
exp1 <- parse(text = c("
                       x <- 4
                       x"))
exp2 <- expression(x <- 4, x)

typeof(exp1)
typeof(exp2)
```

```{r}
exp1
exp2
```

```{r}
length(exp1)
exp1[[1]]
```
