---
title: "note07"
output: html_notebook
---

# 7 Environments

## 7.1 Introduction

```{r}
library(rlang)
```

## 7.2 Environment basics

```{r}
e1 <- rlang::env(
  a = FALSE,
  b = "a",
  c = 2.3,
  d = 1:3
)
```

```{r}
e1$d <- e1
```

```{r}
e1
```

```{r}
env_print(e1)
```

```{r}
env_names(e1)
```

```{r}
identical(global_env(), current_env())
```

```{r}
try(global_env() == current_env())
```

```{r}
e2a <- env(d = 4, e = 5)
e2b <- env(e2a, a = 1, b = 2, c = 3)
```

```{r}
env_parent(e2b)
```

```{r}
env_parent(e2a)
```

```{r}
e2c <- env(empty_env(), d = 4, e = 5)
e2d <- env(e2c, a = 1, b = 2, c = 3)
```

```{r}
env_parents(e2c)
```

```{r}
env_parents(e2d)
```

```{r}
env_parents(e2b, last = empty_env())
```

```{r}
x <- 0
f <- function() {
  x <<- 1
}
f()
x
```

```{r}
e3 <- env(x = 1, y = 2)
e3$x
```

```{r}
e3$z <- 3
e3[["z"]]
```

```{r}
try(e3[[1]])
```

```{r}
try(e3[c("x", "y")])
```

```{r}
e3$xyz
```

```{r}
try(env_get(e3, "xyz"))
```

```{r}
env_get(e3, "xyz", default = NA)
```

```{r}
env_poke(e3, "a", 100)
e3$a
```

```{r}
env_bind(e3, a = 10, b = 20)
env_names(e3)
```

```{r}
env_has(e3, "a")
```

```{r}
e3$a <- NULL
env_has(e3, "a")
```

```{r}
env_unbind(e3, "a")
env_has(e3, "a")
```

```{r}
env_bind_lazy(current_env(), b = {
  Sys.sleep(1)
  1
})
system.time(print(b))
system.time(print(b))
```

```{r}
env_bind_active(current_env(), z1 = function(val) runif(1))
z1
z1
```

```{r}
e1 <- env()
e1$loop <- e1

env_print(e1)
```

```{r}
lobstr::ref(e1)
```

```{r}
e1 <- env()
e2 <- env()
e1$loop <- e2
e2$dedoop <- e1

lobstr::ref(e1)
lobstr::ref(e2)
```

```{r}
e3 <- env()
env_poke(e3, "a", 100)
e3$a
env_poke(e3, "a", 200)
e3$a
```

```{r}
env_poke2 <- function(env, name, value) {
  if (env_has(env, name)) {
    abort(paste0("\"", name, "\" is already assigned to a value."))
  }
  env_poke(env, name, value)
  invisible(env)
}
env_poke2(e3, "b", 100)
e3$b
try(env_poke2(e3, "b", 200))
e3$b
```

```{r}
rebind <- function(name, value, env = caller_env()) {
  if (identical(env, empty_env())) {
    stop("Can't find `", name, "`", call. = FALSE)
  } else if (env_has(env, name)) {
    env_poke(env, name, value)
  } else {
    rebind(name, value, env_parent(env))
  }
}
try(rebind("a", 10))
a <- 5
rebind("a", 10)
a
```

## 7.3 Recursing over environments

```{r}
where <- function(name, env = caller_env()) {
  if (identical(env, empty_env())) {
    # Base case
    stop("Can't find ", name, call. = FALSE)
  } else if (env_has(env, name)) {
    # Success case
    env
  } else {
    # Recursive case
    where(name, env_parent(env))
  }
}
```

```{r}
try(where("yyy"))
```

```{r}
x <- 5
where("x")
```

```{r}
where("mean")
```

```{r}
e4a <- env(empty_env(), a = 1, b = 2)
e4b <- env(e4a, x = 10, a = 11)
```

```{r}
where("a", e4b)
where("b", e4b)
try(where("c", e4c))
```

```{r}
f <- function(..., env = caller_env()) {
  if (identical(env, empty_env())) {

  } else if (success) {

  } else {
    f(..., env = env_parent(env))
  }
}
```

```{r}
f2 <- function(..., env = caller_env()) {
  while (!identical(env, empty_env())) {
    if (success) {
      # success case
      return()
    }
    # inspect parent
    env <- env_parent(env)
  }

  # base case
}
```

```{r}
where2 <- function(name, env = caller_env(), results = list()) {
  if (identical(env, empty_env())) {
    # Base case
    results
  } else {
    # Recursive case
    if (env_has(env, name)) {
      results <- c(results, env)
    }
    where2(name, env_parent(env), results)
  }
}

# Test
e1a <- env(empty_env(), a = 1, b = 2)
e1b <- env(e1a, b = 10, c = 11)
e1c <- env(e1b, a = 12, d = 13)

where2("a", e1c)
```

```{r}
fget <- function(name, env = caller_env(), inherits = TRUE) {
  # Base case
  if (env_has(env, name)) {
    obj <- env_get(env, name)

    if (is.function(obj)) {
      return(obj)
    }
  }

  if (identical(env, emptyenv()) || !inherits) {
    stop("Could not find a function called \"", name, "\".",
      call. = FALSE
    )
  }

  # Recursive Case
  fget(name, env_parent(env))
}

# Test
mean <- 10
fget("mean", inherits = TRUE)
try(fget("mean", inherits = FALSE))
```

## 7.4 Special environments

```{r}
search()
```

```{r}
search_envs()
```

```{r}
y <- 1
f <- function(x) x + y
fn_env(f)
```

```{r}
e <- env()
e$g <- function() 1
fn_env(e$g)
```

```{r}
g <- function(x) {
  if (!env_has(current_env(), "a")) {
    message("Defining a")
    a <- 1
  } else {
    a <- a + 1
  }
  a
}
g(10)
g(10)
```

```{r}
h <- function(x) {
  a <- 2
  x + a
}
y <- h(1)
y
```

```{r}
h2 <- function(x) {
  a <- x * 2
  current_env()
}

e <- h2(x = 10)
env_print(e)
```

```{r}
plus <- function(x) {
  function(y) x + y
}
plus_one <- plus(1)
plus_one
```

```{r}
plus_one(2)
```

```{r}
search_envs()
```

```{r}
env_parents(global_env())
```

```{r}
f1 <- function(x1) {
  f2 <- function(x2) {
    f3 <- function(x3) {
      x1 + x2 + x3
      print("f3")
      print(env_print())
    }
    f3(3)
    print("f2")
    print(env_print())
  }
  f2(2)
  print("f1")
  print(env_print())
}

f1(1)
```

```{r}
fget2 <- function(name, env = caller_env()) {
  # Base case
  if (env_has(env, name)) {
    obj <- env_get(env, name)

    if (is.function(obj)) {
      return(list(fun = obj, env = env))
    }
  }

  if (identical(env, emptyenv())) {
    stop("Could not find a function called \"", name, "\"",
      call. = FALSE
    )
  }

  # Recursive Case
  fget2(name, env_parent(env))
}

fstr <- function(fun_name, env = caller_env()) {
  if (!is.character(fun_name) && length(fun_name) == 1) {
    stop("`fun_name` must be a string.", call. = FALSE)
  }
  fun_env <- fget2(fun_name, env)

  list(
    where = fun_env$env,
    enclosing = fn_env(fun_env$fun)
  )
}

# Test
fstr("mean")
```

## 7.5 Call stacks

```{r}
f <- function(x) {
  g(x = 2)
}
g <- function(x) {
  h(x = 3)
}
h <- function(x) {
  lobstr::cst()
}
f(x = 1)
```

```{r}
# a <- function(x) b(x)
# b <- function(x) c(x)
# c <- function(x) x
# a(f())
```

```{r}
ls(all.names = TRUE)
```

```{r}
ls2 <- function(env = caller_env()) {
  sort(env_names(env))
}
ls2()
```

## 7.6 As data structures

```{r}
my_env <- new.env(parent = emptyenv())
my_env$a <- 1

get_a <- function() {
  my_env$a
}
set_a <- function(value) {
  old <- my_env$a
  my_env$a <- value
  invisible(old)
}
get_a()
(set_a(10))
```

## 7.7 Quiz answers
