---
title: "note06"
output: html_notebook
---

# 6 Trivariate Displays

## 6.1 Three-dimensional scatter plots

```{r}
library(lattice)
```

```{r}
quakes$Magnitude <- equal.count(quakes$mag, 4)
cloud(depth ~ lat * long | Magnitude,
  data = quakes,
  zlim = rev(range(quakes$depth)),
  screen = list(z = 105, x = -70),
  panel.aspect = 0.75,
  xlab = "Latitude", ylab = "Longitude", zlab = "Depth"
)
```

```{r}
cloud(depth ~ lat * long | Magnitude,
  data = quakes,
  zlim = rev(range(quakes$depth)),
  panel.aspect = 0.75,
  screen = list(z = 80, x = -70),
  zoom = 0.7,
  scales = list(z = list(arrows = FALSE, distance = 2)),
  xlab = list("Latitude", rot = 80),
  ylab = list("Longitude", rot = -5),
  zlab = list("Depth\n(km)", rot = 90)
)
```

```{r}
p <-
  cloud(depth ~ long + lat, quakes,
    zlim = c(690, 30),
    pch = ".", cex = 1.5, zoom = 1,
    xlab = NULL, ylab = NULL, zlab = NULL,
    par.settings = list(
      axis.line = list(col = "transparent")
    ),
    scales = list(draw = FALSE)
  )
p
```

```{r, fig.width=4, fig.height=8}
npanel <- 4
rotz <- seq(-30, 30, length = npanel)
roty <- c(3, 0)
update(p[rep(1, 2 * npanel)],
  layout = c(2, npanel),
  panel = function(..., screen) {
    crow <- current.row()
    ccol <- current.column()
    panel.cloud(..., screen = list(
      z = rotz[crow],
      x = -60,
      y = roty[ccol]
    ))
  }
)
```

```{r}
state.info <-
  data.frame(
    name = state.name,
    area = state.x77[, "Area"],
    long = state.center$x,
    lat = state.center$y,
    population = 1000 * state.x77[, "Population"]
  )
state.info$density <- with(state.info, population / area)
cloud(density ~ long + lat,
  data = state.info,
  subset = !name %in% c("Alaska", "Hawaii"),
  type = "h", lwd = 2, zlim = c(0, max(state.info$density)),
  scales = list(arrows = FALSE)
)
```

## 6.2 Surfaces and two-way tables

```{r}
data(Cars93, package = "MASS")
Cars93
```

```{r}
cor.Cars93 <- cor(Cars93[, !sapply(Cars93, is.factor)], use = "pair")
df <- cor.Cars93
abbrname <- abbreviate(rownames(df))
dimnames(df) <- list(abbrname, abbrname)
print(round(df, 2))
```

```{r}
data(Chem97, package = "mlmRev")
Chem97$gcd <-
  with(Chem97, cut(gcsescore, breaks = quantile(gcsescore, ppoints(11, a = 1))))
ChemTab <- xtabs(~ score + gcd + gender, Chem97)
ChemTab
```

```{r}
ChemTabDf <- as.data.frame.table(ChemTab)
ChemTabDf
```

```{r}
env <- environmental
env$ozone <- env$ozone^(1 / 3)
env$Radiation <- equal.count(env$radiation, 4)
cloud(ozone ~ wind + temperature | Radiation, env, layout = c(4, 1))
```

```{r}
splom(env[1:4])
```

```{r}
fm1.env <- lm(ozone ~ radiation * temperature * wind, env)
fm1.env
```

```{r}
fm2.env <- loess(ozone ~ wind * temperature * radiation,
  data = env,
  span = 0.75, degree = 1
)
fm2.env
```

```{r}
fm3.env <- loess(ozone ~ wind * temperature * radiation, env,
  parametric = c("radiation", "wind"),
  span = 0.75, degree = 2
)
fm3.env
```

```{r}
library(locfit)
fm4.env <- locfit(ozone ~ wind * temperature * radiation, env)
```

```{r}
w.mesh <- with(env, do.breaks(range(wind), 50))
t.mesh <- with(env, do.breaks(range(temperature), 50))
r.mesh <- with(env, do.breaks(range(radiation), 3))
grid <- expand.grid(wind = w.mesh, temperature = t.mesh, radiation = r.mesh)
grid
```

```{r}
grid[["fit.linear"]] <- predict(fm1.env, newdata = grid)
grid[["fit.loess.1"]] <- as.vector(predict(fm2.env, newdata = grid))
grid[["fit.loess.2"]] <- as.vector(predict(fm3.env, newdata = grid))
grid[["fit.locfit"]] <- predict(fm4.env, newdata = grid)
```

```{r, fig.asp = 1}
wireframe(fit.linear + fit.loess.1 + fit.loess.2 + fit.locfit ~ wind * temperature | radiation,
  data = grid,
  outer = TRUE,
  shade = TRUE,
  # perspective = FALSE,
  zlab = ""
)
```

```{r, fig.asp=1}
levelplot(fit.linear + fit.loess.1 + fit.loess.2 + fit.locfit ~
  wind * temperature | radiation,
data = grid,
aspect = 1
)
```

```{r, fig.asp=1}
contourplot(fit.locfit ~ wind * temperature | radiation,
  data = grid,
  aspect = 0.7, layout = c(1, 4),
  cuts = 15,
  label.stye = "align"
)
```

```{r}
levelplot(volcano)
contourplot(volcano, cuts = 20, label = FALSE)
wireframe(volcano, panel.aspect = 0.7, zoom = 1, lwd = 0.5)
```

```{r}
levelplot(cor.Cars93,
  scales = list(x = list(rot = 90))
)
```

```{r}
ord <- order.dendrogram(as.dendrogram(hclust(dist(cor.Cars93))))
levelplot(cor.Cars93[ord, ord],
  at = do.breaks(c(-1.0, 1.0), 20),
  scales = list(x = list(rot = 90))
)
```

```{r}
tick.at <- pretty(range(sqrt(ChemTabDf$Freq)))
levelplot(sqrt(Freq) ~ score * gcd | gender,
  data = ChemTabDf,
  shrink = c(0.7, 1), aspect = "iso",
  colorkey = list(labels = list(at = tick.at, labels = tick.at^2))
)
```

```{r}
cloud(Freq ~ score * gcd | gender,
  data = ChemTabDf, type = "h",
  aspect = c(1.5, 0.75), panel.aspect = 0.75
)
```

```{r}
library(latticeExtra)
cloud(Freq ~ score * gcd | gender,
  data = ChemTabDf,
  screen = list(z = -40, x = -25),
  zoom = 1.1,
  col.facet = "grey",
  xbase = 0.6,
  ybase = 0.6,
  par.settings = list(box.3d = list(col = "transparent")),
  aspect = c(1.5, 0.75),
  panel.aspect = 0.75,
  panel.3d.cloud = panel.3dbars
)
```

## 6.3 Theoretical surfaces

```{r}
library(copula)
```

```{r}
n <- 25
grid <-
  expand.grid(
    u = do.breaks(c(0.01, 0.99), n),
    v = do.breaks(c(0.01, 0.99), n)
  )
grid
```

```{r}
grid$frank <- with(grid, dCopula(cbind(u, v), frankCopula(2)))
grid$gumbel <- with(grid, dCopula(cbind(u, v), gumbelCopula(1.2)))
grid$normal <- with(grid, dCopula(cbind(u, v), normalCopula(.4)))
grid$t <- with(grid, dCopula(cbind(u, v), tCopula(0.4)))
```

```{r}
wireframe(frank + gumbel + normal + t ~ u * v,
  data = grid,
  outer = TRUE, zlab = "",
  screen = list(z = -30, x = -50),
  layout = c(4, 1),
  lwd = 0.5
)
```

```{r}
wireframe(frank + gumbel + normal + t ~ u * v,
  data = grid,
  outer = TRUE, zlab = "",
  screen = list(z = -30, x = -50),
  scales = list(z = list(log = TRUE)),
  layout = c(4, 1),
  lwd = 0.5
)
```

```{r}
kx <- function(u, v) {
  cos(u) * (r + cos(u / 2) * sin(t * v) - sin(u / 2) * sin(2 * t * v))
}

ky <- function(u, v) {
  sin(u) * (r + cos(u / 2) * sin(t * v) - sin(u / 2) * sin(2 * t * v))
}

kz <- function(u, v) {
  sin(u / 2) * sin(t * v) + cos(u / 2) * sin(t * v)
}
n <- 50
u <- seq(0.3, 1.25, length = n) * 2 * pi
v <- seq(0, 1, length = n) * 2 * pi
um <- matrix(u, length(u), length(u))
vm <- matrix(v, length(v), length(v), byrow = TRUE)
r <- 2
t <- 1
```

```{r}
wireframe(kz(um, vm) ~ kx(um, vm) + ky(um, vm),
  shade = TRUE,
  screen = list(z = 170, x = -60),
  alpha = 0.75,
  panel.aspect = 0.6,
  aspect = c(1, 0.4),
)
```

## 6.4 Choosing a palette for false-color plots

```{r}
data(USAge.df, package = "latticeExtra")
USAge.df
```

```{r}
library(RColorBrewer)
brewer.div <-
  colorRampPalette(brewer.pal(11, "Spectral"), interpolate = "spline")
brewer.div
```

```{r}
levelplot(Population ~ Year * Age | Sex,
  data = USAge.df,
  cuts = 199,
  col.regions = brewer.div(200),
  aspect = "iso"
)
```
