---
title: "note05"
output: html_notebook
---

# 5 Scatter Plots and Extensions

## 5.1 The standard scatter plot

```{r}
library(lattice)
library(latticeExtra)
```

```{r}
quakes
```

```{r}
xyplot(lat ~ long | cut(depth, 2), data = quakes)
```

```{r}
xyplot(lat ~ long | cut(depth, 3),
  data = quakes,
  aspect = "iso", pch = ".", cex = 2, type = c("p", "g"),
  xlab = "Longitude", ylab = "Lattitude",
  strip = strip.custom(strip.names = TRUE, var.name = "Depth")
)
```

```{r}
xyplot(lat ~ long,
  data = quakes, aspect = "iso",
  groups = cut(depth, breaks = quantile(depth, ppoints(4, 1))),
  auto.key = list(columns = 3), title = "Depth",
  xlab = "Longitude", ylab = "Latitude"
)
```

```{r, fig.width=5, fig.height=5}
depth.col <- grey.colors(100)[cut(quakes$depth, 100, label = FALSE)]
depth.ord <- rev(order(quakes$depth))
xyplot(lat ~ long,
  data = quakes[depth.ord, ],
  aspect = "iso", type = c("p", "g"), col = "black",
  pch = 21, fill = depth.col[depth.ord], cex = 2,
  xlab = "longitude", ylab = "latitude"
)
```

## 5.2 Advanced indexing using subscripts

```{r, paged.print=FALSE}
quakes$Magnitude <- equal.count(quakes$mag, 4)
quakes$Magnitude
```

```{r}
quakes$color <- depth.col
quakes.ordered <- quakes[depth.ord, ]
quakes.ordered
```

```{r}
xyplot(lat ~ long | Magnitude,
  data = quakes.ordered, col = "black",
  aspect = "iso",
  fill_color = quakes.ordered$color,
  cex = 1,
  panel = function(x, y, fill_color, ..., subscripts) {
    fill <- fill_color[subscripts]
    panel.grid(h = -1, v = -1)
    panel.xyplot(x, y, pch = 21, fill = fill, ...)
  }
)
```

```{r}
depth.breaks <- do.breaks(range(quakes.ordered$depth), 50)
quakes.ordered$color <-
  level.colors(quakes.ordered$depth, at = depth.breaks, col.regions = grey.colors)
xyplot(lat ~ long | Magnitude,
  data = quakes.ordered,
  aspect = "iso", groups = color, cex = 1, col = "black",
  panel = function(x, y, groups, ..., subscripts) {
    fill <- groups[subscripts]
    panel.grid(h = 1, v = -1)
    panel.xyplot(x, y, pch = 21, fill = fill, ...)
  },
  legend = list(
    right = list(
      fun = draw.colorkey,
      args = list(
        key = list(
          col = grey.colors,
          at = depth.breaks
        ),
        draw = FALSE
      )
    )
  ),
  xlab = "Longitude",
  ylab = "Latitude"
)
```

## 5.3 Variants using the type argument

```{r}
data(Earthquake, package = "MEMSS")
Earthquake
```

```{r}
xyplot(accel ~ distance,
  data = Earthquake,
  panel = function(...) {
    panel.grid(h = -1, v = -1)
    panel.xyplot(...)
    panel.loess(...)
  },
  xlab = "Distance From Epicenter (km)",
  ylab = "Maximum Horizontal Accleration (g)"
)
```

```{r}
xyplot(accel ~ distance,
  data = Earthquake,
  type = c("g", "p", "smooth"),
  scales = list(log = 2),
  xlab = "Distance From Epicenter (km)",
  ylab = "Maximum Horizontal Acceleration (g)"
)
```

```{r}
# install.packages("locfit")
library(locfit)
Earthquake$Magnitude <-
  equal.count(Earthquake$Richter, 3, overlap = 0.1)
coef <- coef(lm(log2(accel) ~ log2(distance), data = Earthquake))
xyplot(accel ~ distance | Magnitude,
  data = Earthquake,
  aspect = "iso",
  scales = list(log = 2),
  col.line = "grey", lwd = 2,
  panel = function(...) {
    panel.abline(reg = coef)
    panel.locfit(...)
  },
  xlab = "Distance From Epicenter (km)",
  ylab = "Maximum Horizontal Acceleration (g)"
)
```

```{r}
xyplot(min.temp + max.temp + precip ~ day | month,
  data = SeatacWeather,
  ylab = "Temperature and Rainfall",
  type = "l",
  lty = 1
)
```

```{r}
maxp <- max(SeatacWeather$precip, na.rm = TRUE)
p1 <-
  xyplot(min.temp + max.temp + I(80 * precip / maxp) ~ day | month,
    data = SeatacWeather,
    lty = 1, col = "black",
    type = c("l", "l", "h"),
    ylab = "Temperature and Rainfall",
    distribute.type = TRUE
  )
p1
```

```{r}
update(trellis.last.object(),
  ylab = "Temperature (Fahrenheit) \n and Rainfall (inches)",
  panel = function(...) {
    panel.xyplot(...)
    if (panel.number() == 2) {
      at <- pretty(c(0, maxp))
      panel.axis("right",
        half = FALSE,
        at = at * 80 / maxp, labels = at
      )
    }
  }
)
```

## 5.4 Scatter-plot variants for large data

```{r}
library("hexbin")
data(gvhd10, package = "latticeExtra")
xyplot(asinh(SSC.H) ~ asinh(FL2.H) | Days,
  data = gvhd10,
  aspect = 1, panel = panel.hexbinplot,
  .aspect.ratio = 1,
  trans = sqrt
)
```

## 5.5 Scatter-plot matrix

```{r}
USArrests
```

```{r, fig.width=5, fig.height=5}
splom(USArrests)
```

```{r, fig.width=5, fig.height=5}
splom(~ USArrests[c(3, 1, 2, 4)] | state.region,
  pscales = 0, type = c("g", "p", "smooth")
)
```

```{r, fig.width=5, fig.height=5}
splom(~ data.frame(mpg, disp, hp, drat, wt, qsec),
  data = mtcars,
  groups = cyl, pscales = 0,
  varnames = c(
    "Miles\nper\ngallon", "Displacement\n(cu. in.)",
    "Gross\nhorsepower", "Rear\naxle\nratio",
    "Weight", "1/4 mile\ntime"
  ),
  auto.key = list(columns = 3, title = "Number of Cylinders")
)
```

```{r, fig.width=5, fig.height=5}
splom(~ mtcars[c(1, 3:7)], data = mtcars, groups = cyl)
```

```{r, fig.width=5, fig.height=5}
splom(mtcars[c(1, 3:7)], groups = mtcars$cyl)
```

## 5.6 Parallel coordinates plot

```{r}
parallel(~ mtcars[c(1, 3:7)] | factor(cyl),
  data = mtcars,
  groups = carb, layout = c(3, 1),
  auto.key = list(space = "top", columns = 3)
)
```

```{r, fig.asp=1}
parallelplot(~ asinh(gvhd10[c(3, 2, 4, 1, 5)]),
  data = gvhd10,
  col = "black",
  subset = (Days == "13"), alpha = 0.01, lty = 1,
  horizontal.axis = FALSE
)
```
