---
title: "R Notebook"
output: html_notebook
---

# 18 Memory

## 18.1 Object size

```{r}
library(pryr)
```

```{r}
object_size(1:10)
object_size(mean)
object_size(mtcars)
```

```{r}
sizes <- sapply(0:50, function(n) object_size(seq_len(n)))
plot(0:50, sizes, xlab = "Length", ylab = "Size (bytes)", type = "s")
```

```{r}
object_size(numeric())
object_size(logical())
object_size(raw())
object_size(list())
```

```{r}
plot(0:50, sizes - 40,
  xlab = "Length",
  ylab = "Bytes excluding overhead", type = "n"
)
abline(h = 0, col = "grey80")
abline(h = c(8, 16, 32, 48, 64, 128), col = "grey80")
abline(a = 0, b = 4, col = "grey90", lwd = 4)
lines(sizes - 40, type = "s")
```

```{r}
x <- 1:1e6
object_size(x)
y <- list(x, x, x)
object_size(y)
object_size(x, y)
```

```{r}
x1 <- 1:1e6
y1 <- list(1:1e6, 1:1e6, 1:1e6)

object_size(x1)
object_size(y1)
object_size(x1, y1)
object_size(x1) + object_size(y1) == object_size(x1, y1)
```

```{r}
object_size("banana")
object_size(rep("banana", 10))
```

```{r}
vec <- lapply(0:50, function(i) c("ba", rep("na", i)))
str <- lapply(vec, paste0, collapse = "")
object_size(vec)
object_size(str)
```

## 18.2 Memory usage and garbage collection

```{r}
library(pryr)
mem_used()
```

```{r}
mem_change(x <- 1:1e6)
```

```{r}
mem_change(rm(x))
```

```{r}
mem_change(NULL)
mem_change(NULL)
```

```{r}
mem_change(x <- 1:1e6)
mem_change(y <- x)
mem_change(rm(x))
mem_change(rm(y))
```

```{r}
f1 <- function() {
  x <- 1:1e6
  10
}
mem_change(x <- f1())
object_size(x)
```

```{r}
f2 <- function() {
  x <- 1:1e6
  a ~ b
}
mem_change(y <- f2())
object_size(y)
```

```{r}
f3 <- function() {
  x <- 1:1e6
  function() 10
}
mem_change(z <- f3())
object_size(z)
```

## 18.3 Memory profiling with lineprof

```{r}
read_delim <- function(file, header = TRUE, sep = ",") {
  # Determine number of fields by reading first line
  first <- scan(file,
    what = character(1), nlines = 1,
    sep = sep, quiet = TRUE
  )
  p <- length(first)

  # Load all fields as character vectors
  all <- scan(file,
    what = as.list(rep("character", p)),
    sep = sep, skip = if (header) 1 else 0, quiet = TRUE
  )

  # Convert from strings to appropriate types (never to factors)
  all[] <- lapply(all, type.convert, as.is = TRUE)

  # Set column names
  if (header) {
    names(all) <- first
  } else {
    names(all) <- paste0("V", seq_along(all))
  }

  # Convert list into data frame
  as.data.frame(all)
}
```

```{r}
library(ggplot2)
write.csv(diamonds, "output/test_diamonds.csv", row.names = FALSE)
```

```{r}
library(lineprof)

# source("code/read-delim.R")
prof <- lineprof(read_delim("output/test_diamonds.csv"))
# shine(prof)
```

## 18.4 Modification in place

```{r}
x <- 1:10
x[5] <- 10
```

```{r}
library(pryr)
x <- 1:10
c(address(x), refs(x))
```

```{r}
y <- x
c(address(y), refs(y))
```

```{r}
x <- 1:5
y <- x
rm(y)
refs(x)
```

```{r}
x <- 1:5
y <- x
z <- x
refs(x)
```

```{r}
x <- 1:10
y <- x
c(address(x), address(y))

x[5] <- 6L
c(address(x), address(y))
```

```{r}
x <- 1:10
tracemem(x)

x[5] <- 6L

y <- x
x[5] <- 6L
```

```{r}
f <- function(x) x
{
  x <- 1:10
  f(x)
  refs(x)
}

# Sum is primitive, so no increment
{
  x <- 1:10
  sum(x)
  refs(x)
}

# f() and g() never evaluate x, so refs don't increment
f <- function(x) 10
g <- function(x) substitute(x)

{
  x <- 1:10
  f(x)
  refs(x)
}
{
  x <- 1:10
  g(x)
  refs(x)
}
```

```{r}
x <- data.frame(matrix(runif(100 * 1e4), ncol = 100))
medians <- vapply(x, median, numeric(1))

for (i in seq_along(medians)) {
  x[, i] <- x[, i] - medians[i]
}
```

```{r}
for (i in 1:5) {
  x[, i] <- x[, i] - medians[i]
  print(c(address(x), refs(x)))
}
```

```{r}
y <- as.list(x)

for (i in 1:5) {
  y[[i]] <- y[[i]] - medians[i]
  print(c(address(y), refs(y)))
}
```
