---
title: "Chapter 8"
output: html_notebook
---

# 8 Enviroments

## 8.1 Environment basics

```{r}
e <- new.env()
e$a <- FALSE
e$b <- "a"
e$c <- 2.3
e$d <- 1:3
```

```{r}
e$b <- e$d
```

```{r}
e$b <- 1:3
```

```{r}
search()
```

```{r}
as.environment("package:stats")
```

```{r}
e <- new.env()
parent.env(e)
ls(e)
```

```{r}
e$a <- 1
e$b <- 2
ls(e)
e$a
```

```{r}
e$.a <- 2
ls(e)
ls(e, all.names = TRUE)
```

```{r}
str(e)
ls.str(e)
```

```{r}
e$c <- 3
e$c
e[["c"]]
get("c", envir = e)
```

```{r}
e <- new.env()
e$a <- 1
e$a <- NULL
ls(e)

rm("a", envir = e)
ls(e)
```

```{r}
x <- 10
exists("x", envir = e)
exists("x", envir = e, inherits = FALSE)
```

```{r}
identical(globalenv(), environment())
try(globalenv() == environment())
```

## 8.2 Recursing over environments

```{r}
library(pryr)
x <- 5
where("x")
where("mean")
```

```{r}
where <- function(name, env = parent.frame()) {
  if (identical(env, emptyenv())) {
    # Base case
    stop("Can't find ", name, call. = FALSE)
  } else if (exists(name, envir = env, inherits = FALSE)) {
    # Success case
    env
  } else {
    # Recursive case
    where(name, parent.env(env))
  }
}
```

```{r}
pryr::where
```

```{r}
is_empty <- function(x) identical(x, emptyenv())

f2 <- function(..., env = parent.frame()) {
  while (!is_empty(env)) {
    if (sucess) {
      # success case
      return()
    }
    # inspect parent
    env <- parent.env(env)
  }

  # base case
}
```

## 8.3 Function environments

```{r}
y <- 1
f <- function(x) x + y
environment(f)
```

```{r}
e <- new.env()
e$g <- function() 1
```

```{r}
environment(sd)
```

```{r}
where("sd")
```

```{r}
x <- 1:10
sd(x)

var <- function(x, na.rm = TRUE) 100
sd(x)
```

```{r}
g <- function(x) {
  if (!exists("a", inherits = FALSE)) {
    message("Defining a")
    a <- 1
  } else {
    a <- a + 1
  }
  a
}
g(10)
g(10)
```

```{r}
h <- function(x) {
  a <- 2
  x + 2
}
y <- h(1)
y
```

```{r}
plus <- function(x) {
  function(y) x + y
}
plus_one <- plus(1)
identical(parent.env(environment(plus_one)), environment(plus))
```

```{r}
h <- function() {
  x <- 10
  function() {
    x
  }
}
i <- h()
x <- 20
i()
```

```{r}
f2 <- function() {
  x <- 10
  function() {
    def <- get("x", environment())
    cll <- get("x", parent.frame())
    list(defined = def, called = cll)
  }
}
g2 <- f2()
x <- 20
str(g2())
```

```{r}
x <- 0
y <- 10
f <- function() {
  x <- 1
  g()
}

g <- function() {
  x <- 2
  h()
}

h <- function() {
  x <- 3
  x + y
}
f()
```

## 8.4 Binding names to values

```{r}
# _abc <- 1)
# if <- 10)
?Reserved
```

```{r}
`a + b` <- 3
`:)` <- "smile"
`    ` <- "spaces"
ls()
```

```{r}
x <- 0
f <- function() {
  x <<- 1
}
f()
x
```

```{r}
rebind <- function(name, value, env = parent.frame()) {
  if (identical(env, emptyenv())) {
    stop("Can't find ", name, call. = FALSE)
  } else if (exists(name, envir = env, inherits = FALSE)) {
    assign(name, value, envir = env)
  } else {
    rebind(name, value, parent.env(env))
  }
}
try(rebind("a", 10))
```

```{r}
a <- 5
rebind("a", 10)
a
```

## 8.5 Explicit environments

```{r}
modify <- function(x) {
  x$a <- 2
  invisible()
}

x_l <- list()
x_l$a <- 1
modify(x_l)
x_l$a
```

```{r}
x_e <- new.env()
x_e$a <- 1
modify(x_e)
x_e$a
```

```{r}
x <- 1
e1 <- new.env()
get("x", envir = e1)

e2 <- new.env(parent = emptyenv())
try(get("x", envir = e2))
```

```{r}
my_env <- new.env(parent = emptyenv())
my_env$a <- 1

get_a <- function() {
  my_env$a
}
set_a <- function(value) {
  old <- my_env$a
  my_env$a <- value
  invisible(old)
}
```

## 8.6 Quiz answers
