---
title: "Chapter 6"
output: html_notebook
---

# 6 Functions

```{r}
x <- 10
f1 <- function(x) {
  function() {
    x + 10
  }
}
f1(1)()
```

```{r}
`+`(1, `*`(2, 3))
```

```{r}
mean(, TRUE, x = c(1:10, NA))
mean(c(1:10, NA), na.rm = TRUE)
```

```{r}
f2 <- function(a, b) {
  a * 10
}
f2(10, stop("This is an error!"))
```

## 6.1 Function components

```{r}
f <- function(x) x^2
f
formals(f)
body(f)
environment(f)
```

```{r}
sum
formals(sum)
body(sum)
environment(sum)
```

```{r}
objs <- mget(ls("package:base"), inherits = TRUE)
funs <- Filter(is.function, objs)
a <- lapply(funs, formals)
b <- lapply(a, length)
which.max(unlist(b))
a[968]
```

## 6.2 Lexical scoping

```{r}
x <- 10
x
```

```{r}
f <- function() {
  x <- 1
  y <- 2
  c(x, y)
}
f()
rm(f)
```

```{r}
x <- 2
g <- function() {
  y <- 1
  c(x, y)
}
g()
rm(x, g)
```

```{r}
x <- 1
h <- function() {
  y <- 2
  i <- function() {
    z <- 3
    c(x, y, z)
  }
  i()
}
h()
rm(x, h)
```

```{r}
j <- function(x) {
  y <- 2
  function() {
    c(x, y)
  }
}
k <- j(1)
k()
rm(j, k)
```

```{r}
l <- function(x) x + 1
m <- function() {
  l <- function(x) x * 2
  l(10)
}
m()
rm(l, m)
```

```{r}
n <- function(x) x / 2
o <- function() {
  n <- 10
  n(n)
}
o()
rm(n, o)
```

```{r}
j <- function() {
  if (!exists("a")) {
    a <- 1
  } else {
    a <- 1 + 1
  }
  a
}
j()
j()
rm(j)
```

```{r}
f <- function() x
x <- 15
f()

x <- 20
f()
```

```{r}
f <- function() x + 1
codetools::findGlobals(f)
```

```{r}
environment(f) <- emptyenv()
try(f())
```

```{r}
`(` <- function(e1) {
  if (is.numeric(e1) && runif(1) < 0.1) {
    e1 + 1
  } else {
    e1
  }
}
replicate(50, (1 + 2))
#>  [1] 3 3 3 3 4 3 3 3 3 3 3 3 3 3 4 3 3 4 3 3 4 3 4 4 3 3 3 3 3 3 3 3 3 3 3
#> [36] 3 3 3 4 3 3 3 3 3 3 3 3 3 3 3
rm("(")
```

```{r}
c <- 10
c(c = c)
```

```{r}
f <- function(x) {
  f <- function(x) {
    f <- function(x) {
      x^2
    }
    f(x) + 1
  }
  f(x) * 2
}
f(10)
```

## 6.3 Every operation is a function call

```{r}
x <- 10
y <- 5
x + y
`+`(x, y)
```

```{r}
for (i in 1:2) print(i)
`for`(i, 1:2, print(i))
```

```{r}
if (i == 1) print("yes!") else print("no.")
`if`(i == 1, print("yes!"), print("no."))
```

```{r}
x[3]
`[`(x, 3)
```

```{r}
{
  print(1)
  print(2)
  print(3)
}
`{`(print(1), print(2), print(3))
```

```{r}
add <- function(x, y) x + y
sapply(1:10, add, 3)
sapply(1:5, `+`, 3)
sapply(1:5, "+", 3)
```

```{r}
x <- list(1:3, 4:9, 10:12)
sapply(x, "[", 2)
sapply(x, function(x) x[2])
```

## 6.4 Function arguments

```{r}
f <- function(abcdef, bcde1, bcde2) {
  list(a = abcdef, b1 = bcde1, b2 = bcde2)
}
str(f(1, 2, 3))
str(f(2, 3, abcdef = 1))
str(f(2, 3, a = 1))
try(str(f(1, 3, b = 1)))
```

```{r}
mean(1:10)
mean(1:10, trim = 0.05)
```

```{r}
mean(x = 1:10)
```

```{r}
mean(1:10, n = T)
mean(1:10, , FALSE)
mean(1:10, 0.05)
mean(, TRUE, x = c(1:10, NA))
```

```{r}
args <- list(1:10, na.rm = TRUE)
do.call(mean, args)
```

```{r}
f <- function(a = 1, b = 2) {
  c(a, b)
}
f()
```

```{r}
g <- function(a = 1, b = a * 2) {
  c(a, b)
}
g()
g(10)
g(10, 2)
```

```{r}
h <- function(a = 1, b = d) {
  d <- (a + 1)^2
  c(a, b)
}
h()
h(10)
```

```{r}
i <- function(a, b) {
  c(missing(a), missing(b))
}
i()
i(a = 1)
i(b = 2)
i(1, 2)
```

```{r}
f <- function(x) {
  10
}
f(stop("This is an error!"))
```

```{r}
f <- function(x) {
  force(x)
  10
}
try(f(stop("This is an error!")))
```

```{r}
add <- function(x) {
  function(y) x + y
}
adders <- lapply(1:10, add)
adders[[1]](10)
adders[[10]](10)
```

```{r}
add <- function(x) {
  force(x)
  function(y) x + y
}
adders2 <- lapply(1:10, add)
adders2[[1]](10)
adders2[[10]](10)
```

```{r}
f <- function(x = ls()) {
  a <- 1
  x
}
f()

f(ls())
```

```{r}
x <- NULL
if (!is.null(x) && x > 0) {}

a <- NULL
!is.null(a) && a > 0
```

```{r}
try(if (is.null(a)) stop("a is null"))
```

```{r}
a <- NULL
try(!is.null(a) || stop("a is null"))
```

```{r}
plot(1:5, bty = "u")
```

```{r}
plot(1:5, labels = FALSE)
```

```{r}
f <- function(...) {
  names(list(...))
}
f(a = 1, b = 2)
```

```{r}
sum(1, 2, NA, na.mr = TRUE)
```

```{r}
x <- sample(replace = TRUE, 20, x = c(1:10, NA))
y <- runif(min = 0, max = 1, 20)
cor(m = "k", y = y, u = "p", x = x)
```

```{r}
f1 <- function(x =
                 {
                   y <- 1
                   2
                 },
               y = 0)
{
  x + y
}
f1()
```

```{r}
f2 <- function(x = z) {
  z <- 100
  x
}
f2()
```

## 6.5 Special calls

```{r}
`%+%` <- function(a, b) paste0(a, b)
"new" %+% " string"
```

```{r}
"new" %+% " string"
`%+%`("new", " string")
```

```{r}
`% %` <- function(a, b) paste(a, b)
`%'%` <- function(a, b) paste(a, b)
`%/\\%` <- function(a, b) paste(a, b)
"a" % % "b"
"a" %'% "b"
"a" %/\% "b"
```

```{r}
`%-%` <- function(a, b) paste0("(", a, " %-% ", b, ")")
"a" %-% "b" %-% "c"
```

```{r}
`%||%` <- function(a, b) if (!is.null(a)) a else b
NULL %||% 3
```

```{r}
`second<-` <- function(x, value) {
  x[2] <- value
  x
}
x <- 1:10
second(x) <- 5L
x
```

```{r}
library(pryr)
x <- 1:10
address(x)
second(x) <- 6L
address(x)
```

```{r}
`modify<-` <- function(x, position, value) {
  x[position] <- value
  x
}
modify(x, 1) <- 10
x
```

```{r}
x <- `modify<-`(x, 1, 10)
x
```

```{r}
try(modify(get("x"), 1) <- 10)
```

```{r}
try(get("x") <- `modify<-`(get("x"), 1, 10))
```

```{r}
x <- c(a = 1, b = 2, c = 3)
names(x)
#> [1] "a" "b" "c"
names(x)[2] <- "two"
names(x)
```

## 6.6 Return values

```{r}
f <- function(x) {
  if (x < 10) {
    0
  } else {
    10
  }
}
f(5)
f(15)
```

```{r}
f <- function(x) {
  x$a <- 2
  x
}
x <- list(a = 1)
f(x)
```

```{r}
f1 <- function() 1
f2 <- function() invisible(1)
f1()
f2()
f1() == 1
f2() == 1
```

```{r}
(f2())
```

```{r}
a <- 2
(a <- 2)
```

```{r}
(a <- b <- c <- d <- 2)
(a <- (b <- (c <- (d <- 2))))
```

```{r}
in_dir <- function(dir, code) {
  old <- setwd(dir)
  on.exit(setwd(old))
  force(code)
}

getwd()
in_dir("~", getwd())
```

## 6.7 Quiz answers
