---
title: "Chapter 19"
output: html_notebook
---

# 19 High performance functions with Rcpp

## 19.1 Getting started with C++

```{r}
library(Rcpp)
```

```{r}
cppFunction("
int add(int x, int y, int z) {
  int sum = x + y + z;
  return sum;
}
")
add
```

```{r}
add(1, 2, 3)
```

```{r}
one <- function() 1L
cppFunction("int one() {
return 1;
}")
one()
```

```{r}
signR <- function(x) {
  if (x > 0) {
    1
  } else if (x == 0) {
    0
  } else {
    -1
  }
}

cppFunction("
int signC(int x) {
  if (x > 0) {
    return 1;
  } else if (x == 0) {
    return 0;
  } else {
    return -1;
  }
}")
signC(1)
```

```{r}
sumR <- function(x) {
  total <- 0
  for (i in seq_along(x)) {
    total <- total + x[i]
  }
  total
}
```

```{r}
cppFunction("double sumC(NumericVector x) {
  int n = x.size();
  double total = 0;
  for(int i = 0; i < n; ++i) {
    total += x[i];
  }
  return total;
}")
sumC(1:10)
```

```{r}
library(microbenchmark)
```

```{r}
x <- runif(1e3)
microbenchmark(
  sum(x),
  sumC(x),
  sumR(x)
)
```

```{r}
pdistR <- function(x, ys) {
  sqrt((x - ys)^2)
}

cppFunction("NumericVector pdistC(double x, NumericVector ys) {
  int n = ys.size();
  NumericVector out(n);

  for(int i = 0; i < n; ++i) {
    out[i] = sqrt(pow(ys[i] - x, 2.0));
  }
  return out;
}")
pdistR(10, 1:10)
```

```{r}
cppFunction("NumericVector rowSumsC(NumericMatrix x) {
  int nrow = x.nrow();
  int ncol = x.ncol();
  NumericVector out(nrow);

  for (int i = 0; i < nrow; i++) {
    double total = 0;
    for (int j = 0; j < ncol; j++) {
      total += x(i, j);
    }
    out[i] = total;
  }
  return out;
}")
set.seed(1014)
x <- matrix(sample(100), 10)
rowSums(x)
rowSumsC(x)
```

```{r}
sourceCpp("cpp/meanC.cpp")
```

## 19.2 Attributes and other classes

```{r}
sourceCpp("cpp/attribs.cpp")
attribs()
```

```{r}
sourceCpp("cpp/mpe.cpp")
mod <- lm(mpg ~ wt, data = mtcars)
mpe(mod)
```

```{r}
sourceCpp("cpp/callWithOne.cpp")
callWithOne(function(x) x + 1)
callWithOne(paste)
```

## 19.3 Missing values

```{r}
sourceCpp("cpp/scalar_missings.cpp")
```

```{r}
str(scalar_missings())
```

```{r}
evalCpp("NAN == 1")
evalCpp("NAN < 1")
evalCpp("NAN > 1")
evalCpp("NAN == NAN")
```

```{r}
evalCpp("NAN && TRUE")
evalCpp("NAN || FALSE")
```

```{r}
evalCpp("NAN + 1")
evalCpp("NAN - 1")
evalCpp("NAN / 1")
evalCpp("NAN * 1")
```

```{r}
str(missing_sampler())
```

```{r}
is_naC(c(NA, 5.4, 3.2, NA))
```

```{r}
is_naC2(c(NA, 5.4, 3.2, NA))
```

## 19.4 Rcpp sugar

```{r}
pdistR <- function(x, ys) {
  sqrt((x - ys)^2)
}
```

```{r}
cppFunction("
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
NumericVector pdistC2(double x, NumericVector ys) {
  return sqrt(pow((x - ys), 2));
}
")
```

```{r}
microbenchmark(
  pdistR(1, 1:10),
  pdistC2(1, 1:10)
)
```

```{r}
any_naR <- function(x) any(is.na(x))
cppFunction("#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
bool any_naC(NumericVector x) {
  return is_true(any(is_na(x)));
}")

x0 <- runif(1e5)
x1 <- c(x0, NA)
x2 <- c(NA, x0)

microbenchmark(
  any_naR(x0), any_naC(x0),
  any_naR(x1), any_naC(x1),
  any_naR(x2), any_naC(x2)
)
```

## 19.5 The STL

```{r}
cppFunction("
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double sum3(NumericVector x) {
  double total = 0;

  NumericVector::iterator it;
  for(it = x.begin(); it != x.end(); ++it) {
    total += *it;
  }
  return total;
}")
sum3(1:1000)
```

```{r}
cppFunction("
#include <numeric>
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double sum4(NumericVector x) {
  return std::accumulate(x.begin(), x.end(), 0.0);
}
")
sum4(1:1000)
```

```{r}
sourceCpp("cpp/rleC.cpp")
```

```{r}
sourceCpp("cpp/duplicatedC.cpp")
```

```{r}
sourceCpp("cpp/tableC.cpp")
```

## 19.6 Case studies

```{r}
gibbs_r <- function(N, thin) {
  mat <- matrix(nrow = N, ncol = 2)
  x <- y <- 0

  for (i in 1:N) {
    for (j in 1:thin) {
      x <- rgamma(1, 3, y * y + 4)
      y <- rnorm(1, 1 / (x + 1), 1 / sqrt(2 * (x + 1)))
    }
    mat[i, ] <- c(x, y)
  }
  mat
}
```

```{r}
sourceCpp("cpp/gibbs_cpp.cpp")
```

```{r}
microbenchmark(
  gibbs_r(100, 10),
  gibbs_cpp(100, 10)
)
```

```{r}
vacc1a <- function(age, female, ily) {
  p <- 0.25 + 0.3 * 1 / (1 - exp(0.04 * age)) + 0.1 * ily
  p <- p * if (female) 1.25 else 0.75
  p <- max(0, p)
  p <- min(1, p)
  p
}
```

```{r}
vacc1 <- function(age, female, ily) {
  n <- length(age)
  out <- numeric(n)
  for (i in seq_len(n)) {
    out[i] <- vacc1a(age[i], female[i], ily[i])
  }
  out
}
```

```{r}
vacc2 <- function(age, female, ily) {
  p <- 0.25 + 0.3 * 1 / (1 - exp(0.04 * age)) + 0.1 * ily
  p <- p * ifelse(female, 1.25, 0.75)
  p <- pmax(0, p)
  p <- pmin(1, p)
  p
}
```

```{r}
sourceCpp("cpp/vacc3.cpp")
```

```{r}
n <- 1000
age <- rnorm(n, mean = 50, sd = 10)
female <- sample(c(T, F), n, rep = TRUE)
ily <- sample(c(T, F), n, prob = c(0.8, 0.2), rep = TRUE)

stopifnot(
  all.equal(vacc1(age, female, ily), vacc2(age, female, ily)),
  all.equal(vacc1(age, female, ily), vacc3(age, female, ily))
)
```

```{r}
microbenchmark(
  vacc1 = vacc1(age, female, ily),
  vacc2 = vacc2(age, female, ily),
  vacc3 = vacc3(age, female, ily)
)
```

## 19.7 Using Rcpp in a package

## 19.8 Learning more

## 19.9 Acknowledgments
