---
title: "note02"
output: html_notebook
---

# 2 시계열 데이터 객체

## 2.1 날짜/시간 데이터 클래스

```{r}
date <- as.Date(c("2021-01-31", "202-02-28", "2021-03-31"))
date
```

```{r}
date <- as.Date(c("21/01/31", "21/02/28", "21/03/31"), format = "%y/%m/%d")
date
```

```{r}
class(date)
mode(date)
typeof(date)
unclass(date)
```

```{r}
ct <- as.POSIXct("2021-01-31 12:34:56")
ct
class(ct)
unclass(ct)
```

```{r}
lt <- as.POSIXlt("2021-01-31 12:34:56")
lt
class(lt)
unclass(lt)
```

```{r}
lt <- as.POSIXlt("1900-01-01 00:00:00")
unclass(lt)
```

```{r}
library(zoo)
```

```{r}
ym <- as.yearmon("2007-02")
ym
class(ym)
unclass(ym)
```

```{r}
as.yearmon("2007-02-01")
```

```{r}
yq <- as.yearqtr("2007-02")
class(yq)
unclass(yq)
```

## 2.2 시계열 데이터 객체

```{r}
ts(1:10, frequency = 4, start = c(1959, 2))
```

```{r}
if (!require(xts)) {
  install.packages("xts")
  library(xts)
}
library(xts)
```

```{r}
set.seed(345)
xts(rnorm(5), order.by = as.Date("2008-08-01") + 0:4)
```

```{r}
as.xts(ts(1:10, frequency = 4, start = c(1959, 2)))
```

```{r}
if (!require("tsibble")) {
  install.packages("tsibble")
  library(tsibble)
}
```

```{r}
library(dplyr)
set.seed(345)
x <- data.frame(
  date = as.Date("2008-01-01") + 0:9,
  id = 1:10,
  x1 = rnorm(10),
  x2 = rep("a", 10)
)
x
```

```{r}
as_tsibble(x, key = id, index = date)
```

```{r}
as_tsibble(x, index = date)
```

## 2.3 시계열 데이터 import

```{r}
students.all <-
  readxl::read_excel(
    "./data-raw/students.xlsx",
    sheet = 1,
    na = "-",
    skip = 16,
  )
students.all
```

```{r}
students <-
  students.all %>%
  filter(지역규모 == "계") %>%
  select(-지역규모)
students
```

```{r}
students$연도 <- as.Date(paste0(students$연도, "-01-01"))
students
```

```{r}
students.ts <- ts(students, frequency = 1, start = 1999)
students.xts <- as.xts(students[-1], order.by = students$연도)
students.tsibble <- as_tsibble(students, index = 연도)
students.tsibble
```

```{r}
employees <- read.csv(
  "./data-raw/employees-by-industry_20210206234505.csv",
  header = TRUE,
  na = "-",
  strip.white = TRUE,
  stringsAsFactors = FALSE
)
names(employees) <- c("time", "total", "employees.edu")
employees
```

```{r}
employees <-
  employees %>%
  mutate(time = as.Date(paste0(time, ". 01"), format = "%Y. %m. %d"))
employees
```

```{r}
employees.ts <- ts(employees, start = c(2013, 01), frequency = 12)
employees.xts <- xts(employees[, 2:3], order.by = employees[, 1])
employees.tsibble <- as_tsibble(employees, index = time)
```

```{r}
covid19 <-
  read.csv(
    "./data-raw/COVID19.csv",
    header = TRUE,
    na = "-",
    strip.white = TRUE
  )
colnames(covid19) <- c("category", "status", "date", "value")
covid19 <- covid19[, c(3, 1, 2, 4)]
covid19
```

```{r}
covid19$date <- as.Date(covid19$date, "%Y. %m. %d")
covid19
```

```{r}
table(covid19$category)
```

```{r}
covid19 <-
  covid19 |>
  filter(stringr::str_detect(category, "세")) |>
  filter(category != "세종")
```

```{r}
covid19$value <- ifelse(is.na(covid19$value), 0, covid19$value)
covid19
```

```{r}
covid19 <-
  covid19 |>
  tidyr::pivot_wider(names_from = category, values_from = value)
#  tidyr::spread(category, value)
covid19
```

```{r}
covid19.ts <- ts(covid19[, 2:11], frequency = 365, start = c(2020, 04, 09))
covid19.xts <- as.xts(covid19[, 3:11], order.by = covid19$date)
covid19.tsibble <- as_tsibble(covid19, index = date)
```

```{r}
dataset <- ls()
target <-
  stringr::str_detect(dataset, "students") |
    stringr::str_detect(dataset, "employees") |
    stringr::str_detect(dataset, "covid19")
dataset[target]
```

```{r}
save(list = dataset[target], file = "./data-tidied/dataset.rdata")
```
