---
title: "note07"
output: html_notebook
---

```{r}
# install.packages("fable")
# install.packages("fable.prophet")
# install.packages("feasts")
```

```{r}
load("./data-tidied/dataset.rdata")
library(dplyr)
library(lubridate)
library(tsibble)
library(feasts)
library(fable)
library(fable.prophet)
library(ggplot2)
theme_set(theme_gray(base_family = "NanumGothic"))
```

# 7 시계열 forecasting Part II - 시계열 분석 프레임워크

## 7.1 성능 분석 지수

## 7.2 fable 프레임워크

```{r}
students.tsibble |>
  select(연도, 학생수계) |>
  mutate(year = yearmonth(연도)) |>
  as_tsibble(index = year) ->
students.selected

split <- floor(nrow(students.selected) * 0.8)
students.tsibble.tr <- students.selected[1:split, ]
students.tsibble.test <- students.selected[(split + 1):nrow(students.selected), ]
```

```{r}
model.fable.students <- model(
  students.tsibble.tr,
  ets = ETS(학생수계),
  # arima = ARIMA(학생수계),
  naive = NAIVE(학생수계),
  tslm = TSLM(학생수계 ~ trend()),
  rw = RW(학생수계),
  mean = MEAN(학생수계),
  nnetar = NNETAR(학생수계),
  prophet = fable.prophet::prophet(학생수계)
)
```

```{r}
forecast.fable.students <- forecast(model.fable.students, h = 10)
```

```{r}
autoplot(forecast.fable.students, students.selected, level = NULL)
```

```{r}
accuracy(forecast.fable.students, students.tsibble.test) |>
  arrange(RMSE)
```

```{r}
best.model.fable.students <-
  model.fable.students |>
  select(ets, prophet)
```

```{r}
best.model.fable.students |>
  forecast(h = 10) |>
  autoplot(students.selected, alpha = 0.6, level = NULL) +
  autolayer(fitted(best.model.fable.students))
```

```{r}
employees$yearmonth <- yearmonth(employees$time)
employees.tsibble <- as_tsibble(employees, index = yearmonth)
```

```{r}
split <- floor(nrow(employees.tsibble) * 0.9)
n <- nrow(employees.tsibble)
employees.tsibble.tr <- employees.tsibble[1:split, ]
employees.tsibble.test <- employees.tsibble[(split + 1):n, ]
```

```{r}
model.fable.employees <-
  employees.tsibble.tr |>
  model(
    ets = ETS(total),
    arima = ARIMA(total),
    naive = NAIVE(total),
    tslm = TSLM(total ~ trend() + season(12)),
    rw = RW(total),
    mean = MEAN(total),
    nnetar = NNETAR(total),
    propeht = prophet(total)
  )
```

```{r}
forecast.fable.employees <-
  model.fable.employees |>
  forecast(h = 24)
```

```{r}
forecast.fable.employees |>
  autoplot(employees.tsibble, level = NULL) +
  labs(
    title = "fable로 생성한 8가지 모델 예측 플롯",
    x = "연월", y = "취업자수"
  )
```

```{r}
forecast.fable.employees |>
  accuracy(employees.tsibble.test) |>
  arrange(RMSE)
```

```{r}
best.model.fable.employees <-
  model.fable.employees |>
  select(naive, rw)
```

```{r}
best.model.fable.employees |>
  forecast(h = 12) |>
  autoplot(employees.tsibble, level = NULL, lwd = 1) +
  autolayer(fitted(best.model.fable.employees), lwd = 1) +
  geom_point(aes(yearmonth, total)) +
  labs(title = "전체 취업자수 예측 모델", x = "연월", y = "취업자수")
```

```{r}
fill.covid19.tsibble <- fill_gaps(covid19.tsibble, `0-9세` = 0)
```

```{r}
split <- floor(nrow(fill.covid19.tsibble) * 0.9)
n <- nrow(fill.covid19.tsibble)
fill.covid19.tsibble.tr <- fill.covid19.tsibble[1:split, ]
fill.covid19.tsibble.test <- fill.covid19.tsibble[(split + 1):n, ]
```

```{r}
model.covid19.tsibble <-
  fill.covid19.tsibble.tr |>
  model(
    ets = ETS(`0-9세`),
    arima = ARIMA(`0-9세`),
    naive = NAIVE(`0-9세`),
    tslm = TSLM(`0-9세`),
    rw = RW(`0-9세`),
    mean = MEAN(`0-9세`),
    nnetar = NNETAR(`0-9세`),
    prophet = prophet(`0-9세`)
  )
```

```{r}
forecast.covid19.tsibble <-
  model.covid19.tsibble |>
  forecast(h = 120, time = 100) # reduce time for NNETAR
```

```{r}
forecast.covid19.tsibble |>
  autoplot(fill.covid19.tsibble, level = NULL) +
  labs(
    title = "코로나 확진자(0-9세)에 대한 8가지 모델 예측 결과",
    x = "날짜", y = "확진자수"
  )
```

```{r}
forecast.covid19.tsibble |>
  accuracy(fill.covid19.tsibble.test) |>
  arrange(RMSE)
```

```{r}
best.model.covid19.tsibble <-
  model.covid19.tsibble |>
  select(prophet)
```

```{r}
best.model.covid19.tsibble |>
  forecast(h = 120) |>
  autoplot(fill.covid19.tsibble, lwd = 1, alpha = 0.6) +
  autolayer(fitted(best.model.covid19.tsibble), lwd = 1) +
  geom_point(aes(date, `0-9세`)) +
  labs(
    title = "코로나 확진자수(0-9세) 예측",
    x = "연월일", y = "확진자수"
  )
```

## 7.3 modeltime 프레임워크

```{r}
# install.packages("modeltime")
library(modeltime)
library(tidymodels)
```

```{r}
splits.students <- initial_time_split(students, prop = 0.8)
splits.students
```

```{r}
model_fit_arima <-
  arima_reg() |>
  set_engine("auto_arima") |>
  fit(학생수계 ~ 연도, data = training(splits.students))
```

```{r}
model_fit_ets <-
  exp_smoothing() |>
  set_engine("ets") |>
  fit(학생수계 ~ 연도, data = training(splits.students))
```

```{r}
model_fit_prophet <-
  prophet_reg() |>
  set_engine("prophet") |>
  fit(학생수계 ~ 연도, data = training(splits.students))
```

```{r}
model_fit_lm <- linear_reg() |>
  set_engine("lm") |>
  fit(학생수계 ~ 연도, data = training(splits.students))
```

```{r}
model_fit_nnetar <- nnetar_reg() |>
  set_engine("nnetar") |>
  fit(학생수계 ~ 연도, data = training(splits.students))
```

```{r}
model_fit_tbats <- seasonal_reg() |>
  set_engine("tbats") |>
  fit(학생수계 ~ 연도, data = training(splits.students))
```

```{r}
models_tbl <-
  modeltime_table(
    model_fit_arima,
    model_fit_ets,
    model_fit_prophet,
    model_fit_lm,
    model_fit_nnetar,
    model_fit_tbats
  )
models_tbl
```

```{r}
calibration_tbl <-
  models_tbl |>
  modeltime_calibrate(new_data = testing(splits.students))
calibration_tbl
```

```{r}
calibration_tbl |>
  modeltime_forecast(
    new_data = testing(splits.students),
    actual_data = students
  ) |>
  plot_modeltime_forecast(
    .interactive = FALSE,
    .conf_interval_show = FALSE
  ) +
  labs(
    title = "modeltime을 사용한 전체 학생수 6개 모델 예측 결과",
    x = "연도",
    y = "학생수"
  )
```

```{r}
calibration_tbl |>
  modeltime_accuracy() |>
  arrange(rmse)
```

```{r}
model_fit_ets2 <-
  exp_smoothing() |>
  set_engine("ets") |>
  fit(학생수계 ~ 연도, data = students)

model_fit_tbats2 <-
  seasonal_reg() |>
  set_engine("tbats") |>
  fit(학생수계 ~ 연도, data = students)
```

```{r}
best_models_tbl <-
  modeltime_table(
    model_fit_ets2,
    model_fit_tbats2
  )
```

```{r}
best_models_tbl |>
  modeltime_forecast(h = "10 years", actual_data = students) |>
  plot_modeltime_forecast(
    .interactive = FALSE,
    .conf_interval_show = FALSE
  )
```

```{r}
splits.employees <- initial_time_split(employees, prop = 0.9)
splits.employees
```

```{r}
model_fit_arima <- arima_reg() |>
  set_engine("auto_arima") |>
  fit(total ~ time, data = training(splits.employees))
```

```{r}
model_fit_ets <- exp_smoothing() |>
  set_engine("ets") |>
  fit(total ~ time, data = training(splits.employees))
```

```{r}
model_fit_prophet <- prophet_reg() |>
  set_engine(engine = "prophet") |>
  fit(total ~ time, data = training(splits.employees))
```

```{r}
model_fit_lm <- linear_reg() |>
  set_engine("lm") |>
  fit(total ~ time + factor(lubridate::month(time, label = TRUE), ordered = FALSE),
    data = training(splits.employees)
  )
```

```{r}
model_fit_nnetar <- nnetar_reg() |>
  set_engine("nnetar") |>
  fit(total ~ time, data = training(splits.employees))
```

```{r}
model_fit_tbats <- seasonal_reg() |>
  set_engine("tbats") |>
  fit(total ~ time, data = training(splits.employees))
```

```{r}
models_tbl <-
  modeltime_table(
    model_fit_arima,
    model_fit_ets,
    model_fit_prophet,
    model_fit_lm,
    model_fit_nnetar,
    model_fit_tbats
  )
models_tbl
```

```{r}
calibration_tbl <- models_tbl |>
  modeltime_calibrate(new_data = testing(splits.employees))
calibration_tbl
```

```{r}
calibration_tbl |>
  modeltime_forecast(
    new_data = testing(splits.employees),
    actual_data = employees
  ) |>
  plot_modeltime_forecast(
    .interactive = FALSE,
    .conf_interval_show = FALSE
  ) +
  labs(
    title = "modeltime을 사용한 신규 취업자수 6개 모델 예측 결과",
    x = "연도", y = "취업자수"
  ) +
  theme(text = element_text(family = "NanumGothic"))
```

```{r}
calibration_tbl |>
  modeltime_accuracy() |>
  arrange(rmse)
```

```{r}
model_fit_lm3 <- linear_reg() |>
  set_engine("lm") |>
  fit(total ~ time + factor(lubridate::month(time, label = TRUE), ordered = FALSE),
    data = employees
  )

model_fit_nnetar3 <- nnetar_reg() |>
  set_engine("nnetar") |>
  fit(total ~ time, data = employees)

best_models_tbl <-
  modeltime_table(
    model_fit_lm3,
    model_fit_nnetar3
  )
```

```{r}
best_models_tbl |>
  modeltime_forecast(
    h = "3 years",
    actual_data = employees
  ) |>
  plot_modeltime_forecast(
    .interactive = FALSE
  )
```

```{r}
splits.covid19 <- initial_time_split(covid19, prop = 0.9)
splits.covid19
```

```{r}
model_fit_arima <- arima_reg() |>
  set_engine("auto_arima")

model_fit_ets <- exp_smoothing() |>
  set_engine("ets")

model_fit_prophet <- prophet_reg() |>
  set_engine("prophet")

model_fit_lm <- linear_reg() |>
  set_engine("lm")

model_fit_nnetar <- nnetar_reg() |>
  set_engine("nnetar")

model_fit_tbats <- seasonal_reg() |>
  set_engine("tbats")

model_list <-
  list(
    model_fit_arima,
    model_fit_prophet,
    model_fit_ets,
    model_fit_lm,
    model_fit_nnetar,
    model_fit_tbats
  )

fitted_model_list <- lapply(model_list, function(m) fit(m, `0-9세` ~ date, data = training(splits.covid19)))
```

```{r}
models_tbl <- do.call(modeltime_table, fitted_model_list)
models_tbl
```

```{r}
calibration_tbl <- models_tbl |>
  modeltime_calibrate(new_data = testing(splits.covid19))
```

```{r}
calibration_tbl |>
  modeltime_forecast(
    new_data = testing(splits.covid19),
    actual_data = covid19
  ) |>
  plot_modeltime_forecast(
    .interactive = FALSE,
    .conf_interval_show = FALSE
  ) +
  labs(title = "modeltime을 사용한 코로나 확진자수") +
  theme(text = element_text(family = "NanumGothic"))
```

```{r}
calibration_tbl |>
  modeltime_accuracy() |>
  arrange(rmse)
```

```{r}
best_models <- model_list[c(4, 3)]
best_fitted_model_list <- lapply(best_models, function(m) {
  fit(m, `0-9세` ~ date,
    data = covid19
  )
})
best_fitted_model <- do.call(modeltime_table, best_fitted_model_list)
best_fitted_model |>
  modeltime_forecast(
    h = "3 months",
    actual_data = covid19
  ) |>
  plot_modeltime_forecast(
    .interactive = FALSE
  ) +
  labs(
    title = "코로나 확진자수(0-9세) 모델 예측 결과",
    x = "날짜", y = "확진자수"
  ) +
  theme(text = element_text(family = "NanumGothic"))
```
