---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
students <- read_csv("https://pos.it/r4ds-students-csv")
students
```

```{r}
students <- read_csv("https://pos.it/r4ds-students-csv", na = c("N/A", ""))
students
```

```{r}
students |>
  rename(
    student_id = `Student ID`,
    full_name = `Full Name`
  )
```

```{r}
students |> janitor::clean_names()
```

```{r}
students |>
  janitor::clean_names() |>
  mutate(meal_plan = factor(meal_plan))
```

```{r}
students |>
  janitor::clean_names() |>
  mutate(
    meal_plan = factor(meal_plan),
    age = parse_number(if_else(age == "five", "5", age))
  )
```

```{r}
read_csv(
  "The first line of metadata
  The second line of metadata
  x,y,z
  1,2,3",
  skip = 2
)
```

```{r}
read_csv(
  "The first line of metadata
  The second line of metadata
  x,y,z
  1,2,3
  4,5,6",
  skip = 2,
  col_names = FALSE
)
```

```{r}
read_csv("
  logical,numeric,date,string
  TRUE,1,2021-01-15,abc
  false,4.5,2021-02-15,def
  T,Inf,2021-02-16,ghi
")
```

```{r}
simple_csv <- "
  x
  10
  .
  20
  30"
read_csv(simple_csv)
```

```{r}
df <- read_csv(
  simple_csv,
  col_types = list(x = col_double())
)
```

```{r}
problems(df)
```

```{r}
read_csv(simple_csv, na = ".")
```

```{r}
another_csv <- "
x,y,z
1,2,3"

read_csv(
  another_csv,
  col_types = cols(.default = col_character())
)
```

```{r}
read_csv(
  another_csv,
  col_types = cols_only(x = col_character())
)
```

```{r}
sales_files <- c(
  "https://pos.it/r4ds-01-sales",
  "https://pos.it/r4ds-02-sales",
  "https://pos.it/r4ds-03-sales"
)
read_csv(sales_files, id = "file")
```

```{r}
#write_csv(students, "students.csv")
#read_csv("students.csv")
```

```{r}
tibble(
  x = c(1, 2, 5),
  y = c("h", "m", "g"),
  z = c(0.08, 0.83, 0.60)
)
```

```{r}
tribble(
  ~x, ~y, ~z,
  1, "h", 0.08,
  2, "m", 0.83,
  5, "g", 0.60
)
```
