---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(nycflights13)
```

```{r}
x <- c(1, 2, 3, 5, 7, 11, 13)
x * 2
```

```{r}
df <- tibble(x)
df |>
  mutate(y = x * 2)
```

```{r}
flights |>
  filter(dep_time > 600 & dep_time < 2000 & abs(arr_delay) < 20)
```

```{r}
flights |>
  mutate(
    daytime = dep_time > 600 & dep_time < 2000,
    approx_ontime = abs(arr_delay) < 20,
    .keep = "used",
    # .before = 1
  )
```

```{r}
x <- c(1 / 49 * 49, sqrt(2)^2)
x == c(1, 2)
```

```{r}
print(x, digits = 16)
```

```{r}
near(x, c(1, 2))
```

```{r}
NA > 5
10 == NA
NA == NA
```

```{r}
is.na(c(TRUE, NA, FALSE))
is.na(c(1, NA, 3))
is.na(c("a", NA, "b"))
```

```{r}
flights |>
  filter(is.na(dep_time))
```

```{r}
flights |>
  filter(month == 1, day == 1) |>
  arrange(dep_time)
```

```{r}
flights |>
  filter(month == 1, day == 1) |>
  arrange(desc(is.na(dep_time)), dep_time)
```

```{r}
df <- tibble(x = c(TRUE, FALSE, NA))
df |>
  mutate(
    and = x & NA,
    or = x | NA
  )
```

```{r}
flights |>
  filter(month == 11 | month == 12)
```

```{r}
flights |>
  mutate(
    nov = month == 1,
    final = nov | 12,
    .keep = "used"
  )
```

```{r}
flights |>
  filter(month %in% c(11, 12))
```

```{r}
c(1, 2, NA) == NA
c(1, 2, NA) %in% NA
```

```{r}
flights |>
  filter(dep_time %in% c(NA, 800))
```

```{r}
flights |>
  group_by(year, month, day) |>
  summarize(
    all_delayed = all(dep_delay <= 60, na.rm = TRUE),
    any_long_delay = any(arr_delay >= 300, na.rm = TRUE),
    .groups = "drop"
  )
```

```{r}
flights |>
  # group_by(year, month, day) |>
  summarize(
    all_delayed = mean(dep_delay <= 60, na.rm = TRUE),
    any_long_delay = sum(arr_delay >= 300, na.rm = TRUE),
    # .groups = "drop"
    .by = c(year, month, day)
  )
```

```{r}
flights |>
  filter(arr_delay > 0) |>
  group_by(year, month, day) |>
  summarize(
    behind = mean(arr_delay),
    n = n(),
    .groups = "drop"
  )
```

```{r}
flights |>
  group_by(year, month, day) |>
  summarize(
    behind = mean(arr_delay[arr_delay > 0], na.rm = TRUE),
    ahead = mean(arr_delay[arr_delay < 0], na.rm = TRUE),
    n = n(),
    .groups = "drop"
  )
```

```{r}
x <- c(-3:3, NA)
if_else(x > 0, "+ve", "-ve", NA)
if_else(x > 0, "+ve", "-ve", "???")
if_else(x < 0, -x, x)
```

```{r}
x1 <- c(NA, 1, 2, NA)
y1 <- c(3, NA, 4, 6)
if_else(is.na(x1), y1, x1)
```

```{r}
if_else(x == 0, "0", if_else(x < 0, "-ve", "+ve"), "???")
```

```{r}
case_when(
  x < 0 ~ "-ve",
  x > 0 ~ "+ve",
  TRUE ~ "???"
)
```

```{r}
flights |>
  mutate(
    status = case_when(
      is.na(arr_delay) ~ "cancelled",
      arr_delay < -30 ~ "very early",
      arr_delay < -15 ~ "early",
      abs(arr_delay) <= 15 ~ "on time",
      arr_delay < 60 ~ "late",
      arr_delay < Inf ~ "very late",
    ),
    .keep = "used"
  )
```
