---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(babynames)
```

```{r}
string1 <- "This is a string"
string2 <- 'If I want to include a "quote" inside a string, I use single quotes'
```

```{r}
double_quote <- "\"" # or '"'
single_quote <- "'" # or "'"
backslash <- "\\"
```

```{r}
x <- c(single_quote, double_quote, backslash)
str_view(x)
writeLines(x)
```

```{r}
tricky <- "double_quote <- \"\\\"\" # or '\"'
single_quote <- '\\'' # or \"'\""
str_view(tricky)
```

```{r}
tricky <- r"[double_quote <- "\"" # or '"'
single_quote <- '\'' # or "'"]"
str_view(tricky)
```

```{r}
x <- c("one\ntwo", "one\ttwo", "\u00b5", "\U0001f604")
x
```

```{r}
str_view(x)
```

```{r}
str_c("x", "y")
str_c("x", "y", "z")
str_c("Hello ", c("John", "Susan"))
```

```{r}
df <- tibble(name = c("Flora", "David", "Terra", NA))
df |> mutate(greeting = str_c("Hi ", name, "!"))
df |> mutate(greeting = paste0("Hi ", name, "!"))
```

```{r}
df |>
  mutate(
    greeting1 = str_c("Hi ", coalesce(name, "you"), "!"),
    greeting2 = coalesce(str_c("Hi ", name, "!"), "Hi!")
  )
```

```{r}
df |> mutate(greeting = str_glue("Hi {name}!"))
```

```{r}
df |> mutate(greeting = str_glue("{{Hi {name}!}}"))
```

```{r}
str_flatten(c("x", "y", "z"))
str_flatten(c("x", "y", "z"), ", ")
str_flatten(c("x", "y", "z"), ", ", last = ", and ")
```

```{r}
df <- tribble(
  ~name, ~fruit,
  "Carmen", "banana",
  "Carmen", "apple",
  "Marvin", "nectarine",
  "Terence", "cantaloupe",
  "Terence", "papaya",
  "Terence", "mandarin"
)

df |>
  group_by(name) |>
  summarize(fruits = str_flatten(fruit, ", "))
```

```{r}
df1 <- tibble(x = c("a,b,c", "d,e", "f"))
df1 |>
  separate_longer_delim(x, delim = ",")
```

```{r}
df2 <- tibble(x = c("1211", "131", "21"))
df2 |>
  separate_longer_position(x, width = 1)
```

```{r}
df3 <- tibble(x = c("a10.1.2022", "b10.2.2011", "e15.1.2015"))
df3 |>
  separate_wider_delim(
    x,
    delim = ".",
    names = c("code", "edition", "year")
  )
```

```{r}
df4 <- tibble(x = c("202215TX", "202122LA", "202325CA"))
df4 |>
  separate_wider_position(
    x,
    width = c(year = 4, age = 2, state = 2)
  )
```

```{r}
df <- tibble(x = c("1-1-1", "1-1-2", "1-3", "1-3-2", "1"))
try(df |>
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z")
  ))
```

```{r}
debug <- df |>
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z"),
    too_few = "debug"
  )
debug
```

```{r}
debug |> filter(!x_ok)
```

```{r}
df |>
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z"),
    too_few = "align_start"
  )
```

```{r}
df <- tibble(x = c("1-1-1", "1-1-2", "1-3-5-6", "1-3-2", "1-3-5-7-9"))

df |>
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z"),
    too_many = "debug"
  )
```

```{r}
df |>
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z"),
    too_many = "drop"
  )
```

```{r}
df |>
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z"),
    too_many = "merge"
  )
```

```{r}
str_length(c("a", "R for data science", NA))
```

```{r}
babynames |>
  count(length = str_length(name), wt = n)
```

```{r}
babynames |>
  filter(str_length(name) == 15) |>
  count(name, wt = n, sort = TRUE)
```

```{r}
x <- c("Apple", "Banana", "Pear")
str_sub(x, 1, 3)
```

```{r}
str_sub(x, -3, -1)
```

```{r}
str_sub("a", 1, 5)
```

```{r}
babynames |>
  mutate(
    first = str_sub(name, 1, 1),
    last = str_sub(name, -1, -1)
  )
```

```{r}
charToRaw("Hadley")
charToRaw("이경근")
```

```{r}
x1 <- "text\nEl Ni\xf1o was particularly bad this year"
read_csv(x1)

x2 <- "text\n\x82\xb1\x82\xf1\x82\xc9\x82\xbf\x82\xcd"
read_csv(x2)
```

```{r}
read_csv(x1, locale = locale(encoding = "Latin1"))
read_csv(x2, locale = locale(encoding = "Shift-JIS"))
```

```{r}
u <- c("\u00fc", "u\u0308")
str_view(u)
```

```{r}
str_length(u)
#> [1] 1 2
str_sub(u, 1, 1)
```

```{r}
u[[1]] == u[[2]]
str_equal(u[[1]], u[[2]])
```

```{r}
stringi::stri_locale_list()
```

```{r}
str_to_upper(c("i", "ı"))
str_to_upper(c("i", "ı"), locale = "tr")
```

```{r}
str_sort(c("a", "c", "ch", "h", "z"))
str_sort(c("a", "c", "ch", "h", "z"), locale = "cs")
```
