---
title: "note07"
output: html_notebook
---

# 7 문자열과 날짜

## 7.1 문자열 길이 구하기

```{r}
nchar("Moe")
nchar("Curly")
```

```{r}
s <- c("Moe", "Larry", "Curly")
nchar(s)
```

```{r}
length("Moe")
length(c("Moe", "Larry", "Curly"))
```

## 7.2 문자열 연결

```{r}
paste("Everybody", "loves", "stats.")
```

```{r}
paste("Everybody", "loves", "stats.", sep = "-")
```

```{r}
paste("Everybody", "loves", "stats.", sep = "")
paste0("Everybody", "loves", "stats.")
```

```{r}
paste("The square root of twice pi is approximately", sqrt(2 * pi))
```

```{r}
stooges <- c("Moe", "Larry", "Curly")
paste(stooges, "loves", "stats.")
```

```{r}
paste(stooges, "loves", "stats", collapse = ", and ")
```

## 7.3 부분 문자열 추출

```{r}
substr("Statistics", 1, 4)
substr("Statistics", 7, 10)
```

```{r}
ss <- c("Moe", "Larry", "Curly")
substr(ss, 1, 3)
```

```{r}
cities <- c("New York, NY", "Los Angeles, CA", "Peoria, IL")
substr(cities, nchar(cities) - 1, nchar(cities))
```

## 7.4 구분 기호에 따라 문자열 분할하기

```{r}
path <- "/home/mike/data/trials.csv"
strsplit(path, "/")
```

```{r}
strsplit(path, "/")[[1]]
```

```{r}
paths <- c(
  "/home/mike/data/trials.csv",
  "/home/mike/data/errors.csv",
  "/home/mike/corr/reject.doc"
)
strsplit(paths, "/")
```

## 7.5 부분 문자열 바꾸기

```{r}
str <- "Curly is the smart one. Curly is funny, too."
sub("Curly", "Moe", str)
```

```{r}
gsub("Curly", "Moe", str)
```

## 7.6 문자열의 모든 쌍별 조합 생성하기

```{r}
locations <- c("NY", "LA", "CHI", "HOU")
treatments <- c("T1", "T2", "T3")
outer(locations, treatments, paste, sep = "-")
```

```{r}
outer(treatments, treatments, paste, sep = "-")
```

```{r}
expand.grid(treatments, treatments)
```

```{r}
m <- outer(treatments, treatments, paste, sep = "-")
m[!lower.tri(m)]
```

## 7.7 현재 날짜 얻기

```{r}
Sys.Date()
class(Sys.Date())
```

## 7.8 문자열을 날짜로 변환하기

```{r}
as.Date("2018-12-31")
```

```{r}
as.Date("12/31/2018", format = "%m/%d/%Y")
```

## 7.9 날짜를 문자열로 변환

```{r}
format(Sys.Date())
as.character(Sys.Date())
```

```{r}
format(Sys.Date(), format = "%m/%d/%Y")
```

## 7.10 년, 월, 일을 날짜로 변환

```{r}
year <- 2018
month <- 12
day <- 31
as.Date(ISOdate(year, month, day))
```

```{r}
ISOdate(2020, 2, 29)
```

```{r}
as.Date(ISOdate(2020, 2, 29))
```

```{r}
years <- c(2010, 2011, 2012, 2014)
months <- c(1, 1, 1, 1, 1)
days <- c(15, 21, 20, 18, 17)
ISOdate(years, months, days)
as.Date(ISOdate(years, months, days))
```

```{r}
as.Date(ISOdate(years, 1, days))
```

## 7.11 율리우스력 날짜 구하기

```{r}
d <- as.Date("2019-03-15")
as.integer(d)
```

```{r}
jd <- julian(d)
jd
```

```{r}
as.integer(as.Date("1970-01-01"))
as.integer(as.Date("1970-01-02"))
as.integer(as.Date("1970-01-03"))
```

## 7.12 날짜 부분 추출하기

```{r}
d <- as.Date("2019-03-15")
p <- as.POSIXlt(d)
p$mday
p$mon
p$year + 1900
```

```{r}
d <- as.Date("2020-04-02")
as.POSIXlt(d)$wday
as.POSIXlt(d)$yday
```

```{r}
as.POSIXlt(d)$year # Oops!
as.POSIXlt(d)$year + 1900
```

## 7.13 날짜 시퀀스 생성

```{r}
s <- as.Date("2019-01-01")
e <- as.Date("2019-02-01")
seq(from = s, to = e, by = 1)
```

```{r}
seq(from = s, by = 1, length.out = 7)
```

```{r}
seq(from = s, by = "month", length.out = 12)
```

```{r}
seq(from = s, by = "3 months", length.out = 4)
```

```{r}
seq(from = s, by = "year", length.out = 10)
```

```{r}
seq(as.Date("2019-01-29"), by = "month", len = 3)
```
