---
title: "note11"
output: html_notebook
---

```{r}
library(tidyverse)
library(broom)
library(faraway)
```

# 11 선형 회귀 및 분산 분석

## 11.1 단순 선형 회귀 수행하기

```{r}
set.seed(42)
x <- rnorm(100)
e <- rnorm(100, mean = 0, sd = 5)
y <- 5 + 15 * x + e

lm(y ~ x)
```

```{r}
df <- data.frame(x, y)
lm(y ~ x, data = df)
```

## 11.2 다중 선형 회귀 수행하기

```{r}
set.seed(42)
u <- rnorm(100)
v <- rnorm(100, mean = 3, sd = 2)
w <- rnorm(100, mean = -3, sd = 1)
e <- rnorm(100, mean = 0, sd = 3)
y <- 5 + 4 * u + 3 * v + 2 * w + e
```

```{r}
lm(y ~ u + v + w)
```

```{r}
df <- data.frame(y, u, v, w)
lm(y ~ u + v + w, data = df)
```

## 11.3 회귀 통계 얻기

```{r}
m <- lm(y ~ u + v + w)
summary(m)
```

```{r}
coef(m)
```

```{r}
confint(m)
```

```{r}
resid(m)
```

```{r}
deviance(m)
```

```{r}
anova(m)
```

```{r}
vcov(m)
```

```{r}
summary(m)
```

## 11.4 회귀 요약의 이해

```{r}
summary(m)$call
```

## 11.5 절편 없이 선형 회귀 수행하기

```{r}
m2 <- lm(y ~ x + 0)
summary(m2)
```

```{r}
confint(m2)
```

## 11.6 종속 변수와 상관관계가 높은 변수만 회귀

```{r}
load("./data/pred.rdata")
```

```{r}
best_pred <-
  as_tibble(pred) %>%
  select(-resp) |>
  map_dbl(cor, y = pred$resp) %>%
  sort(decreasing = TRUE) %>%
  .[1:4] %>%
  names() %>%
  pred[.]
best_pred
```

```{r}
mod <- lm(pred$resp ~ as.matrix(best_pred))
summary(mod)
```

## 11.7 상호작용 항으로 선형 회귀 수행하기

## 11.8 최상의 회귀 변수 선택

```{r}
set.seed(4)
n <- 150
x1 <- rnorm(n)
x2 <- rnorm(n, 1, 2)
x3 <- rnorm(n, 3, 1)
x4 <- rnorm(n, -2, 2)
e <- rnorm(n, 0, 3)
y <- 4 + x1 + 5 * x3 + e
```

```{r}
full.model <- lm(y ~ x1 + x2 + x3 + x4)
summary(full.model)
```

```{r}
reduced.model <- step(full.model, direction = "backward")
```

```{r}
summary(reduced.model)
```

```{r}
min.model <- lm(y ~ 1)
fwd.model <- step(
  min.model,
  direction = "forward",
  scope = (~ x1 + x2 + x3 + x4),
  trace = 0
)
summary(fwd.model)
```

```{r}
full.model <- lm(y ~ (x1 + x2 + x3 + x4)^4)
summary(full.model)
```

```{r}
reduced.model <- step(full.model, direction = "backward")
```

```{r}
summary(reduced.model)
```

## 11.9 데이터의 하위 집합에 대한 회귀

```{r}
n <- 1000
x <- rnorm(n)
e <- rnorm(n, 0, .5)
y <- 3 + 2 * x + e
lm(y ~ x, subset = 1:500)
```

```{r}
lm(y ~ x, subset = 1:floor(length(x) / 2))
```

```{r}
load("./data/lab_df.rdata")
lm(y ~ x, data = lab_df, subset = (lab == "NJ"))
```

## 11.10 회귀 공식 내에서 표현식 사용하기

```{r}
load("./data/df_squared.rdata")
m <- lm(y ~ u + I(u^2), data = df_squared)
predict(m, newdata = data.frame(u = 13.4))
```

## 11.11 다항식 회귀

```{r}
m <- lm(y ~ poly(x, 3, raw = TRUE))
summary(m)
```

```{r}
summary(lm(y ~ x + I(x^2) + I(x^3)))
```

## 11.12 변환된 데이터에 대한 회귀

```{r}
load("./data/df_decay.rdata")
z <- df_decay$z
t <- df_decay$time

plot(t, z)
plot(t, log(z))
```

```{r}
m <- lm(log(z) ~ t)
summary(m)
```

## 11.13 최적의 전력 변환 찾기(Box-Cox 절차)

```{r}
set.seed(9)
x <- 10:100
eps <- rnorm(length(x), sd = 5)
y <- (x + eps)^(-1 / 1.5)
```

```{r}
plot(x, y)
```

```{r}
m <- lm(y ~ x)
summary(m)
```

```{r}
augmented_m <- augment(m)
augmented_m %>%
  ggplot(aes(.fitted, .resid)) +
  geom_point()
```

```{r}
plot(m)
```

```{r}
plot(m, which = 1)
```

```{r}
bc <- MASS::boxcox(m)
```

```{r}
lambda <- bc$x[which.max(bc$y)]
lambda
```

```{r}
z <- y^lambda
m2 <- lm(z ~ x)
summary(m2)
```

```{r}
m2 <- lm(I(y^lambda) ~ x)
```

```{r}
augmented_m2 <- augment(m2)
augmented_m2 %>%
  ggplot(aes(.fitted, .resid)) +
  geom_point()
```

## 11.14 회귀 계수에 대한 신뢰 구간 형성

```{r}
load("./data/conf.rdata")
m <- lm(y ~ x1 + x2)
confint(m)
```

```{r}
confint(m, level = 0.99)
```

## 11.15 회귀 잔차 플로팅

```{r}
m <- lm(y ~ x1 + x2)
augmented_m <- augment(m)
augmented_m %>%
  ggplot(aes(.fitted, .resid)) +
  geom_point()
```

## 11.16 선형 회귀 진단하기

```{r}
m <- lm(y ~ x1 + x2)
plot(m)
```

```{r}
car::outlierTest(m)
```

```{r}
par(mfrow = c(2, 2))
plot(m)
```

```{r}
load(file = "./data/bad.rdata")
m <- lm(y2 ~ x3 + x4)
par(mfrow = (c(2, 2))) # this gives us a 2x2 plot
plot(m)
```

```{r}
car::outlierTest(m)
```

## 11.17 영향력 있는 관찰 식별

```{r}
influence.measures(m)
```

## 11.18 자기상관에 대한 잔차 검정(Durbin-Watson 검정)

```{r}
load(file = "./data/ac.rdata")
```

```{r}
m1 <- lm(y1 ~ x)
lmtest::dwtest(m1)
```

```{r}
acf(resid(m1))
```

```{r}
m2 <- lm(y2 ~ x)
lmtest::dwtest(m2)
```

```{r}
acf(resid(m2))
```

```{r}
lmtest::dwtest(m2, alternative = "two.sided")
```

## 11.19 새로운 가치 예측

```{r}
load("./data/pred2.rdata")
m <- lm(y ~ u + v + w)
preds <- data.frame(u = 3.1, v = 4.0, w = 5.5)
predict(m, newdata = preds)
```

```{r}
preds <- data.frame(
  u = c(3.0, 3.1, 3.2, 3.3),
  v = c(3.9, 4.0, 4.1, 4.2),
  w = c(5.3, 5.5, 5.7, 5.9)
)
predict(m, newdata = preds)
```

## 11.20 예측 구간 형성

```{r}
predict(m, newdata = preds, interval = "prediction")
```

## 11.21 일원 분산 분석 수행

```{r}
month.abb
```

```{r}
load("./data/anova.rdata")
GSPC_df %>%
  mutate(month = factor(mon, levels = month.abb)) %>%
  group_by(month) %>%
  summarize(r_mean = mean(r)) %>%
  ggplot(aes(month, r_mean)) +
  geom_point()
```

```{r}
oneway.test(r ~ mon, data = GSPC_df)
```

```{r}
oneway.test(r ~ mon, data = GSPC_df, subset = tail(seq_along(r), 2500))
```

```{r}
oneway.test(r ~ mon, data = GSPC_df, subset = tail(seq_along(r), 2500), var.equal = TRUE)
```

```{r}
m <- aov(r ~ mon, data = GSPC_df)
summary(m)
```

## 11.22 교호 작용도 만들기

```{r}
data(rats)
interaction.plot(rats$poison, rats$treat, rats$time)
```

## 11.23 그룹 평균 간의 차이 찾기

```{r}
load(file = "./data/anova.rdata")
oneway.test(r ~ wday, subset = 1:2500, data = GSPC_df)
```

```{r}
m <- aov(r ~ wday, subset = 1:2500, data = GSPC_df)
TukeyHSD(m)
```

```{r}
plot(TukeyHSD(m))
```

## 11.24 강력한 ANOVA 수행(Kruskal-Wallis 검정)

```{r}
load(file = "./data/student_data.rdata")
student_data
```

```{r}
hist(student_data$midterm)
```

```{r}
kruskal.test(midterm ~ hw, data = student_data)
```

## 11.25 ANOVA를 이용한 모델 비교

```{r}
load(file = "./data/anova2.rdata")
m1 <- lm(y ~ u)
m2 <- lm(y ~ u + v)
m3 <- lm(y ~ u + v + w)
```

```{r}
anova(m1, m2, m3)
```
