---
title: "note14"
output: html_notebook
---

# 14 시계열 분석

## 14.1 시계열 데이터 표현 하기

```{r}
library(zoo)
```

```{r}
x <- c(3, 4, 1, 4, 8)
dt <- seq(as.Date("2018-01-01"), as.Date("2018-01-05"), by = "days")
ts <- zoo(x, dt)
ts
```

```{r}
library(xts)
ts <- xts(x, dt)
ts
```

```{r}
prices <- c(132.45, 130.85, 130.00, 129.55, 130.85)
dates <- as.Date(c(
  "2010-01-04", "2010-01-05", "2010-01-06",
  "2010-01-07", "2010-01-08"
))
ibm.daily <- zoo(prices, dates)
ibm.daily
```

```{r}
prices <- c(131.18, 131.20, 131.17, 131.15, 131.17)
seconds <- c(9.5, 9.500278, 9.500556, 9.500833, 9.501111)
ibm.sec <- zoo(prices, seconds)
print(ibm.sec)
```

```{r}
coredata(ibm.daily)
```

```{r}
index(ibm.daily)
```

```{r}
#vignette("zoo")
```

## 14.2 시계열 데이터 그리기

```{r}
load("data/ibm.rdata")
library(xts)

main <- "IBM: Historical vs. Inflation-Adjusted"
lty <- c("dotted", "solid")

ibm.infl |> head()

plot(ibm.infl, lty = lty, main = main, legend.loc = "left")
```

## 14.3 가장 오래된 또는 가장 최근의 관찰을 추출하기

```{r}
ibm <- ibm.infl$ibm
head(ibm)
tail(ibm)
```

```{r}
first(ibm, "2 week")
```

```{r}
last(ibm, "month")
```

## 14.4 시계열의 부분 집합화

```{r}
head(ibm)
```

```{r}
ibm[2]
ibm[2:4]
```

```{r}
ibm[as.Date("2010-01-05")]
```

```{r}
ibm["2010-01-05"]
```

```{r}
dates <- seq(as.Date("2010-01-04"), as.Date("2010-01-08"), by = 2)
ibm[dates]
```

```{r}
window(ibm, start = as.Date("2010-01-05"), end = as.Date("2010-01-07"))
```

```{r}
ibm["201001"]
```

```{r}
ibm["2009/2011"] |> head()
```

```{r}
ibm["2009/201001"] |> head()
```

```{r}
ibm["200906/201005"] |> head()
```

## 14.5 여러 시계열 병합

```{r}
load(file = "./data/ibm.rdata")
head(ibm)
head(cpi)
```

```{r}
merge(ibm, cpi) |> head()
```

```{r}
na.locf(merge(ibm, cpi)) |> head()
```

```{r}
head(merge(ibm, cpi, all = FALSE))
```

## 14.6 시계열 채우기 또는 채우기

```{r}
head(cpi)
```

```{r}
max(index(cpi))
```

```{r}
dates <- seq(from = min(index(cpi)), to = max(index(cpi)), by = 1)
empty <- zoo(, dates)
head(empty)
```

```{r}
filled.cpi <- merge(cpi, empty, all = TRUE)
filled.cpi |> head()
```

```{r}
filled.cpi <- na.locf(merge(cpi, empty, all = TRUE))
head(filled.cpi)
```

```{r}
tail(filled.cpi)
```

```{r}
filled.ibm <- na.locf(merge(ibm, zoo(, index(cpi))))
head(merge(filled.ibm, cpi, all = FALSE))
```

```{r}
filled_data <- merge(ibm, filled.cpi, all = FALSE)
head(filled_data)
```

```{r}
combined_data <- merge(ibm, cpi, all = TRUE)
head(combined_data)
```

```{r}
combined_spline <- na.spline(combined_data)
```

## 14.7 시계열 지연

```{r}
ibm.daily
```

```{r}
lag(ibm.daily, k = 1, na.pad = TRUE)
```

```{r}
lag(ibm.daily, k = -1, na.pad = TRUE)
```

## 14.8 연속적인 차이 계산하기

```{r}
ibm.daily
```

```{r}
diff(ibm.daily)
```

```{r}
head(cpi, 24)
```

```{r}
head(diff(cpi, lag = 12), 24)
```

## 14.9 시계열에 대한 계산 수행

```{r}
ibm.daily
diff(ibm.daily)
```

```{r}
diff(ibm.daily) / ibm.daily * 100
```

```{r}
log(ibm.daily)
```

```{r}
diff(log(ibm.daily))
```

## 14.10 이동 평균 계산

```{r}
ibm_year <- ibm["2016"]
ma_ibm <- rollmean(ibm_year, 7, align = "right")
ma_ibm <- merge(ma_ibm, ibm_year)
plot(ma_ibm)
```

## 14.11 달력 기간별 기능 적용

```{r}
ibm_5 <- ibm["2012/2017"]
head(ibm_5)
tail(ibm_5)
```

```{r}
ibm_mm <- apply.monthly(ibm_5, mean)
head(ibm_mm)
```

```{r}
ibm_vol <- sqrt(251) * apply.monthly(as.xts(diff(log(ibm_5))), sd)
plot(ibm_vol, main = "IBM: Monthly Volatility")
```

## 14.12 롤링 함수 적용하기

```{r}
ibm_sds <- rollapply(ibm_5, width = 30, FUN = sd, by = 30, align = "right")
ibm_sds <- na.omit(ibm_sds)
head(ibm_sds)
```

## 14.13 자기상관 함수의 플롯팅

```{r}
load("data/ts_acf.rdata")
acf(ts1, main = "Significant Autocorrelations")
```

```{r}
acf(ts2, main = "Insignificannt Autocorrelations")
```

## 14.14 자기상관을 위한 시계열 테스트

```{r}
Box.test(ts1)
```

```{r}
Box.test(ts2)
```

```{r}
Box.test(ts1, type = "Ljung-Box")
Box.test(ts2, type = "Ljung-Box")
```

## 14.15 부분 자기상관 함수 플롯하기

```{r}
pacf(ts1, main = "Significant Partial Autocorrelations")
```

```{r}
pacf(ts2, main = "Insignificant Partial Autocorrelations")
```

## 14.16 두 시계열 사이의 지연 상관 관계 찾기

```{r}
library(forecast)
load(file = "./data/bnd_cmty.Rdata")
b <- coredata(bonds)[, 1]
c <- coredata(cmdtys)[, 1]

Ccf(b, c, main = "Bonds vs. Commodities")
```

```{r}
cor(b, c)
```

## 14.17 시계열 추세 제거

```{r}
# data("data/yield.Rdata")

x <- 1980:2020
y <- 120 + 2.5 * (x - 1990) + rnorm(length(x), 0, sd = 20)
years <- seq(as.Date("1980-01-01"), as.Date("2020-01-01"), by = "years")
yield <- zoo(y, years)
m <- lm(coredata(yield) ~ index(yield))
detr <- zoo(resid(m), index(yield))
autoplot(detr)
```

```{r}
library(ggplot2)
library(patchwork)
d <- autoplot(detr, geom = "point") +
  labs(
    x = "Year",
    y = "Yield Dev (bu/ac)",
    title = "IL Corn Yield Deviation from Trend (bu/ac)"
  )

dp <- autoplot(detr / yield, geom = "point") +
  labs(
    x = "Year",
    y = "Yield Dev (bu/ac)",
    title = "IL Corn Yield Deviation from Trend (bu/ac)"
  )

d / dp
```

## 14.18 ARIMA 모델 맞추기

```{r}
# install.packages("fpp2")
library(forecast)
library(fpp2)
plot(ausbeer)
```

```{r}
auto.arima(ausbeer)
```

```{r}
autoplot(ausbeer)
```

```{r}
auto.arima(ausbeer, seasonal = FALSE)
```

```{r}
arima(ausbeer, order = c(3, 2, 2))
```

```{r}
m <- arima(x = ausbeer, order = c(3, 2, 2))
confint(m)
```

## 14.19 중요하지 않은 ARIMA 계수 제거

```{r}
m1 <- auto.arima(euretail)
m1
confint(m1, level = .98)
```

```{r}
m2 <- arima(euretail,
  order = c(0, 1, 3), seasonal = c(0, 1, 1),
  fixed = c(0, NA, NA, NA)
)
m2
confint(m2, level = .98)
```

## 14.21 ARIMA 모델에서 예측하기

```{r}
checkresiduals(m)
```

```{r}
checkresiduals(m1)
```

```{r}
checkresiduals(m2)
```

## 14.21 ARIMA 모델에서 예측하기

```{r}
m <- arima(euretail, order = c(0, 1, 3), seasonal = c(0, 1, 1), fixed = c(0, NA, NA, NA))
fc_m <- forecast(m)
fc_m
```

```{r}
fc_m$mean
```

## 14.22 예측 그리기

```{r}
autoplot(fc_m)
```

```{r}
autoplot(fc_m) +
  ylab("Euro Index") +
  xlab("Year/Quarter") +
  ggtitle("Forecasted Retail Index") +
  theme_bw()
```

## 14.23 평균 회귀 테스트

```{r}
library(tseries)
library(fpp2)
autoplot(goog200)
adf.test(goog200)
```

```{r}
autoplot(hsales)
adf.test(hsales)
```

```{r}
library(xts)
data("sample_matrix")
xts_obj <- as.xts(sample_matrix, dateFormat = "Date")[, "Close"]
adf.test(coredata(xts_obj))
```

```{r}
# install.packages("fUnitRoots")
library(fUnitRoots)
adfTest(coredata(ts1), type = "nc")
```

## 14.24 시계열 평활화

```{r}
library(KernSmooth)
```

```{r}
t <- seq(from = -10, to = 10, length.out = 201)
noise <- rnorm(201)
y <- sin(t) + noise
plot(t, y)
```

```{r}
gridsize <- length(y)
bw <- dpill(t, y, gridsize = gridsize)
lp <- locpoly(x = t, y = y, bandwidth = bw, gridsize = gridsize)
smooth <- lp$y

ggplot() +
  geom_line(aes(t, y)) +
  geom_line(aes(t, smooth), linetype = 2)
```
