---
title: "note05"
output: html_notebook
---

# 5 Control flow

## 5.1 Introduction

## 5.2 Choices

```{r}
grade <- function(x) {
  if (x > 90) {
    "A"
  } else if (x > 80) {
    "B"
  } else if (x > 50) {
    "C"
  } else {
    "F"
  }
}
```

```{r}
x1 <- if (TRUE) 1 else 2
x2 <- if (FALSE) 1 else 2
c(x1, x2)
```

```{r}
greet <- function(name, birthday = FALSE) {
  paste0(
    "Hi ", name,
    if (birthday) " and HAPPY BIRTHDAY"
  )
}
greet("Maria", FALSE)
greet("Maria", TRUE)
```

```{r}
try(if ("x") 1)
```

```{r}
try(if (logical()) 1)
```

```{r}
try(if (NA) 1)
```

```{r}
try(if (c(TRUE, FALSE)) 1)
```

```{r}
x <- 1:10
ifelse(x %% 5 == 0, "XXX", as.character(x))
```

```{r}
ifelse(x %% 2 == 0, "even", "odd")
```

```{r}
dplyr::case_when(
  x %% 35 == 0 ~ "fizz buzz",
  x %% 5 == 0 ~ "fizz",
  x %% 7 == 0 ~ "buzz",
  is.na(x) ~ "???",
  TRUE ~ as.character(x)
)
```

```{r}
x_option <- function(x) {
  if (x == "a") {
    "option 1"
  } else if (x == "b") {
    "option 2"
  } else if (x == "c") {
    "option3"
  } else {
    stop("Invalid `x` value")
  }
}
```

```{r}
x_option2 <- function(x) {
  switch(x,
    a = "option 1",
    b = "option 2",
    c = "option 3",
    stop("Invalid `x` value")
  )
}
```

```{r}
(switch("c",
  a = 1,
  b = 2
))
```

```{r}
legs <- function(x) {
  switch(x,
    cow = ,
    hose = ,
    dog = 4,
    human = ,
    chicken = 2,
    plant = 0,
    stop("Unknown input")
  )
}
legs("cow")
legs("dog")
```

```{r}
ifelse(TRUE, 1, "no")
ifelse(FALSE, 1, "no")
ifelse(NA, 1, "no")
```

```{r}
ifelse(logical(), 1, "no")
ifelse(NaN, 1, "no")
ifelse(NA_character_, 1, "no")
ifelse("a", 1, "no")
ifelse("true", 1, "no")
```

```{r}
x <- 1:10
if (length(x)) "not empty" else "empty"
```

```{r}
x <- numeric()
if (length(x)) "not empty" else "empty"
```

## 5.3 Loops

```{r}
for (i in 1:3) {
  print(i)
}
```

```{r}
i <- 100
for (i in 1:3) {}
i
```

```{r}
for (i in 1:10) {
  if (i < 3) {
    next
  }
  print(i)
  if (i >= 5) {
    break
  }
}
```

```{r}
means <- c(1, 50, 20)
out <- vector("list", length(means))
for (i in 1:length(means)) {
  out[[i]] <- rnorm(10, means[[i]])
}
out
```

```{r}
means <- c()
out <- vector("list", length(means))
for (i in seq_along(means)) {
  out[[i]] <- rnorm(10, means[[i]])
}
```

```{r}
xs <- as.Date(c("2020-01-01", "2010-01-01"))
xs
```

```{r}
for (x in xs) {
  print(x)
}
```

```{r}
for (i in seq_along(xs)) {
  print(xs[[i]])
}
```

```{r}
x <- numeric()
out <- vector("list", length(x))
for (i in 1:length(x)) {
  out[i] <- x[i]^2
}
out
```

```{r}
xs <- c(1, 2, 3)
for (x in xs) {
  xs <- c(xs, x * 2)
}
xs
```

```{r}
for (i in 1:3) {
  i <- i * 2
  print(i)
}
```

## 5.4 Quiz answers
