---
title: "note03"
output: html_notebook
---

# 3 Vectors

## 3.1 Introduction

## 3.2 Atomic vectors

```{r}
lgl_var <- c(TRUE, FALSE)
int_var <- c(1L, 6L, 10L)
dbl_var <- c(1, 2.5, 4.5)
chr_var <- c("These are", "some strings")
```

```{r}
c(c(1, 2), c(3, 4))
```

```{r}
typeof(lgl_var)
typeof(int_var)
typeof(dbl_var)
typeof(chr_var)


length(lgl_var)
length(int_var)
length(dbl_var)
length(chr_var)
```

```{r}
NA > 5
10 * NA
!NA
```

```{r}
NA^0
NA | TRUE
NA & FALSE
```

```{r}
x <- c(NA, 5, NA, 10)
x == NA
is.na(x)
```

```{r}
str(c("a", 1))
```

```{r}
x <- c(FALSE, FALSE, TRUE)
as.numeric(x)
sum(x)
mean(x)
```

```{r}
as.integer(c("1", "1.5", "a"))
```

```{r}
as.raw(42)
charToRaw("A")
```

```{r}
complex(length.out = 1, real = 1, imaginary = 1)
```

```{r}
c(1, FALSE)
c("a", 1)
c(TRUE, 1L)
```

```{r}
1 == "1"
-1 < FALSE
"one" < 2
```

```{r}
c(FALSE, NA_character_)
```

```{r}
a <- 1:10
x <- a
attr(x, "test") <- "test"
names(x) <- letters[1:10]
is.atomic(x)
is.numeric(x)
is.vector(x)
is.vector(a)
```

## 3.3 Attributes

```{r}
a <- 1:3
attr(a, "x") <- "abcdef"
attr(a, "x")
```

```{r}
attr(a, "y") <- 4:6
attributes(a)
```

```{r}
a <- structure(
  1:3,
  x = "abcdef",
  y = 4:6
)
str(attributes(a))
```

```{r}
attributes(x[[1]])
attributes(sum(a))
```

```{r}
x <- c(a = 1, b = 2, c = 3)
x <- 1:3
names(x) <- c("a", "b", "c")
x <- setNames(1:3, c("a", "b", "c"))
x
```

```{r}
x <- unname(x)
names(x) <- NULL
```

```{r}
x <- matrix(1:6, nrow = 2, ncol = 3)
x
```

```{r}
y <- array(1:12, c(2, 3, 2))
y
```

```{r}
z <- 1:6
dim(z) <- c(3, 2)
z
```

```{r}
x <- 1:10
is.null(dim(x))
is.matrix(matrix(x))
is.array(matrix(x))
```

```{r}
str(1:3)
str(matrix(1:3))
str(matrix(1:3, nrow = 1))
str(array(1:3, 3))
```

```{r}
setNames
```

```{r}
s <- setNames(, c("a", "b", "c"))
s
```

```{r}
unname
```

```{r}
df <- data.frame(a = 1:10, b = 2:11)
df
```

```{r}
unname(df)
```

```{r}
x <- 1:10
nrow(x)
ncol(x)
```

```{r}
NROW(x)
NROW(x)
```

```{r}
x1 <- array(1:5, c(1, 1, 5))
x2 <- array(1:5, c(1, 5, 1))
x3 <- array(1:5, c(5, 1, 1))
str(x1)
str(x2)
str(x3)
```

```{r}
foo <- structure(1:5, comment = "my attribute")
foo
attributes(foo)
```

```{r}
attr(foo, which = "c")
```

## 3.4 S3 atomic

```{r}
x <- factor(c("a", "b", "b", "a"))
x
```

```{r}
typeof(x)
attributes(x)
```

```{r}
sex_char <- c("m", "m", "m")
sex_factor <- factor(sex_char, levels = c("m", "f"))
sex_factor
table(sex_char)
table(sex_factor)
```

```{r}
grade <- ordered(c("b", "b", "a", "c"), levels = c("c", "b", "a"))
grade
```

```{r}
today <- Sys.Date()
typeof(today)
attributes(today)
today
```

```{r}
date <- as.Date("1969-12-31")
unclass(date)
```

```{r}
now_ct <- as.POSIXct("2018-08-01 22:00", tz = "UTC")
now_ct
typeof(now_ct)
attributes(now_ct)
unclass(now_ct)
```

```{r}
structure(now_ct, tzone = "Asia/Tokyo")
structure(now_ct, tzone = "America/New_York")
structure(now_ct, tzone = "Australia/Lord_Howe")
structure(now_ct, tzone = "Europe/Paris")
```

```{r}
one_week_1 <- as.difftime(1, units = "weeks")
one_week_1

typeof(one_week_1)
attributes(one_week_1)
unclass(one_week_1)
```

```{r}
one_week_2 <- as.difftime(7, units = "days")
one_week_2

typeof(one_week_2)
attributes(one_week_2)
unclass(one_week_2)
```

```{r}
x <- table(mtcars[c("vs", "cyl", "am")])
x
```

```{r}
typeof(x)
attributes(x)
```

```{r}
f1 <- factor(letters)
f1
as.integer(f1)
```

```{r}
levels(f1) <- rev(levels(f1))
f1
as.integer(f1)
```

```{r}
factor(as.character(f1), levels = rev(letters))
```

```{r}
f2 <- factor(letters) |> rev()
f2
as.integer(f2)
```

```{r}
f3 <- factor(letters, levels = rev(letters))
f3
as.integer(f2)
```

```{r}

```

## 3.5 Lists

```{r}
l1 <- list(
  1:3,
  "a",
  c(TRUE, FALSE, TRUE),
  c(2.3, 5.9)
)
typeof(l1)
str(l1)
```

```{r}
lobstr::obj_size(mtcars)
l2 <- list(mtcars, mtcars, mtcars, mtcars)
lobstr::obj_size(l2)
```

```{r}
l3 <- list(list(list(list(1))))
str(l3)
```

```{r}
l4 <- list(list(1, 2), c(3, 4))
str(l4)
```

```{r}
l5 <- c(list(1, 2), c(3, 4))
str(l5)
```

```{r}
list(1:3)
as.list(1:3)
```

```{r}
l <- list(1:3, "a", TRUE, 1.0)
dim(l) <- c(2, 2)
l
```

```{r}
l[[1, 1]]
```

```{r}
lobstr::ref(1:2)
lobstr::ref(list(1:2, 2))
```

```{r}
(1:2)[3]
(1:2)[NA]
```

```{r}
as.list(1:2)[3]
as.list(1:2)[NA]
```

```{r}
is.vector(as.vector(mtcars))
```

```{r}
date <- as.Date("1970-01-02")
dttm_ct <- as.POSIXct("1970-01-01 01:00", tz = "UTC")
unclass(date)
unclass(dttm_ct)
```

```{r}
c(date, dttm_ct)
unclass(c(date, dttm_ct))
```

```{r}
c(dttm_ct, date)
unclass(c(dttm_ct, date))
```

## 3.6 Data frames and tibbles

```{r}
df1 <- data.frame(x = 1:3, y = letters[1:3])
typeof(df1)
attributes(df1)
```

```{r}
library(tibble)
df2 <- tibble(x = 1:3, y = letters[1:3])
typeof(df2)
attributes(df2)
```

```{r}
df <- data.frame(
  x = 1:3,
  y = c("a", "b", "c")
)
str(df)
```

```{r}
df2 <- tibble(
  x = 1:3,
  y = c("a", "b", "c")
)
str(df2)
```

```{r}
names(data.frame(`1` = 1))
names(tibble(`1` = 1))
```

```{r}
data.frame(x = 1:4, y = 1:2)
```

```{r}
try(data.frame(x = 1:4, y = 1:3))
```

```{r}
tibble(x = 1:4, y = 1)
```

```{r}
try(tibble(x = 1:4, y = 1:2))
```

```{r}
tibble(
  x = 1:3,
  y = x * 2
)
```

```{r}
df3 <- data.frame(
  age = c(35, 27, 18),
  hair = c("blond", "brown", "black"),
  row.names = c("Bob", "Susan", "Sam")
)
df3
```

```{r}
rownames(df3)
df3["Bob", ]
```

```{r}
as_tibble(df3, rownames = "name")
```

```{r}
dplyr::starwars
```

```{r}
df1 <- data.frame(xyz = "a")
str(df1$x)
```

```{r}
df2 <- tibble(xyz = "a")
str(df2$x)
```

```{r}
is.data.frame(df1)
is.data.frame(df2)
```

```{r}
is_tibble(df1)
is_tibble(df2)
```

```{r}
df <- data.frame(x = 1:3)
df$y <- list(1:2, 1:3, 1:4)
data.frame(
  x = 1:3,
  y = I(list(1:2, 1:3, 1:4))
)
```

```{r}
tibble(
  x = 1:3,
  y = list(1:2, 1:3, 1:4)
)
```

```{r}
dfm <- data.frame(
  x = 1:3 * 10
)
dfm$y <- matrix(1:9, nrow = 3)
dfm$z <- data.frame(a = 3:1, b = letters[1:3], stringsAsFactors = FALSE)

str(dfm)
```

```{r}
dfm[1, ]
```

```{r}
data.frame(a = integer(), b = logical())
```

```{r}
data.frame(row.names = 1:3)
```

```{r}
data.frame()
```

```{r}
mtcars[0, ]
mtcars[, 0]
mtcars[0, 0]
```

```{r}
try(data.frame(row.names = c("x", "y", "y")))
df <- data.frame(x = 1:3)
try(row.names(df) <- c("x", "y", "y"))
```

```{r}
row.names(df) <- c("x", "y", "z")
df[c(1, 1, 1), , drop = FALSE]
```

```{r}
df <- data.frame(x = 1:3, y = letters[1:3])
is.matrix(df)
is.matrix(t(df))
is.matrix(t(t(df)))
```

```{r}
t(t(df))
```

```{r}
dim(df)
dim(t(df))
dim(t(t(df)))
```

```{r}
df_coltypes <- data.frame(
  a = c("a", "b"),
  b = c(TRUE, FALSE),
  c = c(1L, 0L),
  d = c(1.5, 2),
  e = factor(c("f1", "f2"))
)
df_coltypes
```

```{r}
as.matrix(df_coltypes)
```

```{r}
data.matrix(df_coltypes)
```

## 3.7 NULL

```{r}
typeof(NULL)
```

```{r}
length(NULL)
```

```{r}
x <- NULL
try(attr(x, "y") <- 1)
```

```{r}
is.null(NULL)
```

## 3.8 Quiz answers
