---
title: "note02"
output: html_notebook
---

# 2 Names and values

```{r}
library(lobstr)
```

## 2.1 Introduction

```{r}
df <- data.frame(runif(3), runif(3))
names(df) <- c(1, 2)
df
```

```{r}
x <- runif(1e6)
y <- list(x, x, x)
obj_size(x)
obj_size(y)
obj_sizes(x, y)
```

```{r}
a <- c(1, 5, 3, 2)
b <- a
b[[1]] <- 10
a
b
```

## 2.2 Binding basics

```{r}
x <- c(1, 2, 3)
y <- x
obj_addr(x)
obj_addr(y)
```

```{r}
# _abc <- 1
# if <- 10  # 구문자체가 실행이 안됨
```

```{r}
`_abc` <- 1
`_abc`

`if` <- 10
`if`
```

```{r}
a <- 1:10
b <- a
c <- b
d <- 1:10
obj_addr(a)
obj_addr(b)
obj_addr(c)
obj_addr(d)
```

```{r}
mean_functions <- list(
  mean,
  base::mean,
  get("mean"),
  evalq(mean),
  match.fun("mean")
)
unique(obj_addrs(mean_functions))
```

```{r}
make.names("")
make.names(".1")
make.names("non-valid")
make.names("@")
make.names("  R")
make.names("if")
make.names(".123e1")
```

## 2.3 Copy-on-modify

```{r}
x <- c(1, 2, 3)
y <- x
y[[3]] <- 4
x
y
```

```{r}
x <- c(1, 2, 3)
cat(tracemem(x), "\n")
```

```{r}
y <- x
y[[3]] <- 4L
```

```{r}
y[[3]] <- 5L
untracemem(x)
```

```{r}
f <- function(a) {
  a
}
x <- c(1, 2, 3)
cat(tracemem(x), "\n")

z <- f(x)
untracemem(x)
```

```{r}
l1 <- list(1, 2, 3)
l2 <- l1
l2[[3]] <- 4

ref(l1, l2)
```

```{r}
d1 <- data.frame(x = c(1, 5, 6), y = c(2, 4, 3))
d2 <- d1
d2[, 2] <- d2[, 2] * 2
```

```{r}
d3 <- d1
d3[1, ] <- d3[1, ] * 3
ref(d1, d2, d3)
```

```{r}
x <- c("a", "a", "abc", "d")
ref(x, character = TRUE)
```

```{r}
obj_addr(1:10)
```

```{r}
x <- c(1L, 2L, 3L)
tracemem(x)
x[[3]] <- 4
untracemem(x)
```

```{r}
x <- c(1L, 2L, 3L)
tracemem(x)
x[[3]] <- 4L
untracemem(x)
```

```{r}
a <- 1:10
b <- list(a, a)
c <- list(b, a, 1:10)
ref(a, b, c)
```

```{r}
x <- list(1:10)
x[[2]] <- x
ref(x)
```

## 2.4 Object size

```{r}
obj_size(letters)
obj_size(ggplot2::diamonds)
```

```{r}
x <- runif(1e6)
obj_size(x)
y <- list(x, x, x)
obj_size(y)
```

```{r}
y <- rep(list(runif(1e4)), 100)
object.size(y)
obj_size(y)
```

```{r}
obj_size(list(NULL, NULL, NULL))
```

```{r}
banana <- "bananas bananas bananas"
obj_size(banana)
obj_size(rep(banana, 100))
```

```{r}
obj_size(x, y)
```

```{r}
obj_size(1:3)
obj_size(1:1e3)
obj_size(1:1e6)
obj_size(1:1e9)
```

```{r}
y <- rep(list(runif(1e4)), 100)

object.size(y)
obj_size(y)
```

```{r}
funs <- list(mean, sd, var)
obj_size(funs)
```

```{r}
base_pkgs <- c(
  "package:stats", "package:graphics", "package:grDevices",
  "package:utils", "package:datasets", "package:methods",
  "package:base"
)
base_objs <- base_pkgs |> 
  lapply(as.environment) |>
  lapply(function(x) mget(ls(x, all.names = TRUE), x)) |>
  setNames(base_pkgs)
sum(lengths(base_objs))
vapply(base_objs, obj_size, double(1)) / 1024^2
as.numeric(obj_size(!!!base_objs)) / 1024^2
```

```{r}
a <- runif(1e6)
obj_size(a)

b <- list(a, a)
obj_size(b)
obj_size(a, b)

b[[1]][[1]] <- 10
obj_size(b)
obj_size(a, b)

b[[2]][[1]] <- 10
obj_size(b)
obj_size(a, b)
```

## 2.5 Modify-in-place

```{r}
v <- c(1, 2, 3)
v[[3]] <- 4
```

```{r}
x <- data.frame(matrix(runif(5 * 1e4), ncol = 5))
medians <- vapply(x, median, numeric(1))


for (i in seq_along(medians)) {
  x[[i]] <- x[[i]] - medians[[i]]
}
```

```{r}
cat(tracemem(x), "\n")
for (i in 1:5) {
  x[[i]] <- x[[i]] - medians[[i]]
}
untracemem(x)
```

```{r}
y <- as.list(x)
cat(tracemem(y), "\n")

for (i in 1:5) {
  y[[i]] <- y[[i]] - medians[[i]]
}
untracemem(y)
```

```{r}
e1 <- rlang::env(a = 1, b = 2, c = 3)
e2 <- e1
e1$c <- 4
e2$c
```

```{r}
e <- rlang::env()
e$self <- e
ref(e)
```

```{r}
x <- list()
obj_addr(x)
tracemem(x)
x[[1]] <- x
obj_addr(x)
obj_addr(x[[1]])
untracemem(x)
```

```{r}
create_random_df <- function(nrow, ncol) {
  random_matrix <- matrix(runif(nrow * ncol), nrow = nrow)
  as.data.frame(random_matrix)
}
create_random_df(2, 2)
```

```{r}
substract_df <- function(x, medians) {
  for (i in seq_along(medians)) {
    x[[i]] <- x[[i]] - medians[[i]]
  }
  x
}

substract_list <- function(x, medians) {
  x <- as.list(x)
  x <- substract_df(x, medians)
  list2DF(x)
}
```

```{r}
benchmark_medians <- function(ncol) {
  df <- create_random_df(nrow = 1e4, ncol = ncol)
  medians <- vapply(df, median, numeric(1), USE.NAMES = FALSE)
  bench::mark(
    "data frame" = substract_df(df, medians),
    "list" = substract_list(df, medians),
    time_unit = "ms"
  )
}
benchmark_medians(1)
```

```{r}
results <- bench::press(
  ncol = c(1, 10, 50, 100, 250, 300, 400, 500, 750, 1000),
  benchmark_medians(ncol)
)
```

```{r}
library(ggplot2)
results |>
  ggplot(aes(ncol, median, col = attr(expression, "description"))) +
  geom_point(size = 2) +
  geom_smooth() +
  labs(
    x = "Number of Columns",
    y = "Execution Time (ms)",
    color = "Data Structure"
  ) +
  theme(legend.position = "top")
```

```{r}
x <- new.env()
try(tracemem(x))
```

## 2.6 Unbinding and the garbage collector

```{r}
gc()
```

```{r}
mem_used()
```

## 2.7 Quiz answers

```{r}
df <- data.frame(runif(3), runif(3))
names(df) <- c(1, 2)

df$`3` <- df$`1` + df$`2`
df
```
