---
title: "note24"
output: html_notebook
---

# 24 Improving performance

## 24.1 Introduction

```{r}
library(bench)
```

## 24.2 Code organisation

```{r}
mean1 <- function(x) mean(x)
mean2 <- function(x) sum(x) / length(x)
x <- runif(1e5)
```

```{r}
bench::mark(
  mean1(x),
  mean2(x)
)
```

## 24.3 Checking for existing solutions

```{r}
library(magrittr)
penguins <- palmerpenguins::penguins

bench::mark(
  "lm" = lm(
    body_mass_g ~ bill_length_mm + species,
    data = penguins
  ) %>% coef(),
  "biglm" = biglm::biglm(
    body_mass_g ~ bill_length_mm + species,
    data = penguins
  ) %>% coef(),
  "speedglm" = speedglm::speedlm(
    body_mass_g ~ bill_length_mm + species,
    data = penguins
  ) %>% coef(),
  "fastLm" = RcppEigen::fastLm(
    body_mass_g ~ bill_length_mm + species,
    data = penguins
  ) %>% coef()
)
```

```{r}
eps <- rnorm(100000)
x1 <- rnorm(100000, 5, 3)
x2 <- rep(c("a", "b"), 50000)
y <- 7 * x1 + (x2 == "a") + eps
td <- data.frame(y = y, x1 = x1, x2 = x2, eps = eps)

bench::mark(
  "lm" = lm(y ~ x1 + x2, data = td) %>% coef(),
  "biglm" = biglm::biglm(y ~ x1 + x2, data = td) %>% coef(),
  "speedglm" = speedglm::speedlm(y ~ x1 + x2, data = td) %>% coef(),
  "fastLm" = RcppEigen::fastLm(y ~ x1 + x2, data = td) %>% coef()
)
```

```{r}
table <- 1:100000
x <- sample(table, 10000, replace = TRUE)
bench::mark(
  match = match(x, table),
  fastmatch = fastmatch::fmatch(x, table)
)
```

```{r}
date_ct <- as.POSIXct("2020-01-01 12:30:25")
date_ct
```

```{r}
date_lt <- as.POSIXct("2020-01-01 12:30:25")
date_lt
```

```{r}
date_lt2 <- rep(date_lt, 10000)
date_ct2 <- rep(date_ct, 10000)

bench::mark(
  date_lt2 - date_lt2,
  date_ct2 - date_ct2,
  date_ct2 - date_lt2
)
```

```{r}
date_str <- strptime("2020-01-01 12:30:25",
  format = "%Y-%m-%d %H:%M:%S"
)
identical(date_lt, date_str)
```

```{r}
bench::mark(
  as.POSIXct = as.POSIXct("2020-01-01 12:30:25"),
  as.POSIXct_format = as.POSIXct("2020-01-01 12:30:25",
    format = "%Y-%m-%d %H:%M:%S"
  ),
  strptime_fomat = strptime("2020-01-01 12:30:25",
    format = "%Y-%m-%d %H:%M:%S"
  )
)[1:3]
```

```{r}
library(lubridate)
ymd_hms("2013-07-24 23:55:26")
```

```{r}
bench::mark(
  as.POSIXct = as.POSIXct("2013-07-24 23:55:26", tz = "UTC"),
  ymd_hms = ymd_hms("2013-07-24 23:55:26")
)[1:3]
```

```{r}
x <- 1:10
slider::slide_dbl(x, mean, .before = 1, .complete = TRUE)
```

```{r}
bench::mark(
  caTools = caTools::runmean(x, k = 2, endrule = "NA"),
  data.table = data.table::frollmean(x, 2),
  RcppRoll = RcppRoll::roll_mean(x,
    n = 2, fill = NA,
    align = "right"
  ),
  slider = slider::slide_dbl(x, mean, .before = 1, .complete = TRUE),
  TTR = TTR::SMA(x, 2),
  zoo_apply = zoo::rollapply(x, 2, mean, fill = NA, align = "right"),
  zoo_rollmean = zoo::rollmean(x, 2, fill = NA, align = "right")
)
```

```{r}
optim(0, function(x) x^2 - 100 * x + 50,
  method = "Brent",
  lower = -1e20, upper = 1e20
)
```

```{r}
optimize(function(x) x^2 - 100 * x + 50, c(-1e20, 1e20))
```

## 24.4 Doing as little as possible

```{r}
x <- runif(1e2)
bench::mark(
  mean(x),
  mean.default(x)
)[c("expression", "min", "median", "itr/sec", "n_gc")]
```

```{r}
x <- runif(1e2)
bench::mark(
  mean(x),
  mean.default(x),
  .Internal(mean(x))
)[c("expression", "min", "median", "itr/sec", "n_gc")]
```

```{r}
x <- runif(1e5)
bench::mark(
  mean(x),
  mean.default(x),
  .Internal(mean(x))
)[c("expression", "min", "median", "itr/sec", "n_gc")]
```

```{r}
quickdf <- function(l) {
  class(l) <- "data.frame"
  attr(l, "row.names") <- .set_row_names(length(l[[1]]))
  l
}

l <- lapply(1:26, function(i) runif(1e3))
names(l) <- letters

bench::mark(
  as.data.frame = as.data.frame(l),
  quick_df      = quickdf(l)
)[c("expression", "min", "median", "itr/sec", "n_gc")]
```

```{r}
quickdf(list(x = 1, y = 1:2))
```

```{r}
rowSums
```

```{r}
.rowSums
```

```{r}
m <- matrix(rnorm(1e6), nrow = 1000)

bench::mark(
  rowSums(m),
  .rowSums(m, 1000, 1000)
)
```

```{r}
chisq.test2 <- function(x, y) {
  m <- rbind(x, y)
  margin1 <- rowSums(m)
  margin2 <- colSums(m)
  n <- sum(m)
  me <- tcrossprod(margin1, margin2) / n

  x_stat <- sum((m - me)^2 / me)
  df <- (length(margin1) - 1) * (length(margin2) - 1)
  p.value <- pchisq(x_stat, df = df, lower.tail = FALSE)

  list(x_stat = x_stat, df = df, p.value = p.value)
}
```

```{r}
a <- 21:25
b <- seq(21, 29, 2)
m <- cbind(a, b)

chisq.test(m) %>% print(digits = 5)
```

```{r}
chisq.test2(a, b)
```

```{r}
bench::mark(
  chisq.test(m),
  chisq.test2(a, b),
  check = FALSE
)
```

```{r}
table2 <- function(a, b) {
  a_s <- sort(unique(a))
  b_s <- sort(unique(b))

  a_l <- length(a_s)
  b_l <- length(b_s)

  dims <- c(a_l, b_l)
  pr <- a_l * b_l
  dn <- list(a = a_s, b = b_s)

  bin <- fastmatch::fmatch(a, a_s) +
    a_l * fastmatch::fmatch(b, b_s) - a_l
  y <- tabulate(bin, pr)

  y <- array(y, dim = dims, dimnames = dn)
  class(y) <- "table"

  y
}

a <- sample(100, 10000, TRUE)
b <- sample(100, 10000, TRUE)

bench::mark(
  table(a, b),
  table2(a, b)
)
```

## 24.5 Vectorise

```{r}
lookup <- setNames(as.list(sample(100, 26)), letters)
str(lookup)
```

```{r}
x1 <- "j"
x10 <- sample(letters, 10)
x100 <- sample(letters, 100, replace = TRUE)
```

```{r}
bench::mark(
  lookup[x1],
  lookup[x10],
  lookup[x100],
  check = FALSE
)[c("expression", "min", "median", "itr/sec", "n_gc")]
```

```{r}
rowsums <- bench::press(
  p = seq(500, 5000, length.out = 10),
  {
    mat <- tcrossprod(rnorm(p), rnorm(p))
    bench::mark(
      rowSums = rowSums(mat),
      apply = apply(mat, 1, sum)
    )
  }
)
```

```{r}
library(ggplot2)
library(dplyr)
```

```{r}
rowsums %>%
  mutate(Approach = as.character(expression)) %>%
  ggplot(aes(p, as.numeric(median), color = Approach, group = Approach)) +
  geom_point() +
  geom_line() +
  labs(
    x = "Number of Rows and Columns",
    y = "Median (s)"
  ) +
  theme(legend.position = "top") +
  scale_y_continuous(trans = )
```

```{r}
x <- rnorm(10)
w <- rnorm(10)
all.equal(sum(x * w), crossprod(x, w)[[1]])
```

```{r}
weightedsum <- bench::press(
  n = 1:10,
  {
    x <- rnorm(n * 1e6)
    bench::mark(
      sum = sum(x * x),
      crossprod = crossprod(x, x)[[1]]
    )
  }
)
```

```{r}
weightedsum %>%
  mutate(Approach = as.character(expression)) %>%
  ggplot(aes(n, as.numeric(median), color = Approach, group = Approach)) +
  geom_point() +
  geom_line() +
  labs(
    x = "Vecotr Length (millions)",
    y = "Median (s)"
  ) +
  theme(legend.position = "top")
```

## 24.6 Avoiding copies

```{r}
random_string <- function() {
  paste(sample(letters, 50, replace = TRUE), collapse = "")
}
strings10 <- replicate(10, random_string())
strings100 <- replicate(100, random_string())
collapse <- function(xs) {
  out <- ""
  for (x in xs) {
    out <- paste0(out, x)
  }
  out
}
```

```{r}
bench::mark(
  loop10 = collapse(strings10),
  loop100 = collapse(strings100),
  vec10 = paste(strings10, collapse = ""),
  vec100 = paste(strings100, collapse = ""),
  check = FALSE
)
```

## 24.7 Case study: t-test

```{r}
m <- 1000
n <- 50
X <- matrix(rnorm(m * n, mean = 10, sd = 3), nrow = m)
str(X)
grp <- rep(1:2, each = n / 2)
grp
```

```{r}
system.time(
  for (i in 1:m) {
    t.test(X[i, ] ~ grp)$statistic
  }
)
```

```{r}
system.time(
  for (i in 1:m) {
    t.test(X[i, grp == 1], X[i, grp == 2])$statistic
  }
)
```

```{r}
compT <- function(i) {
  t.test(X[i, grp == 1], X[i, grp == 2])$statistic
}
system.time(t1 <- purrr::map_dbl(1:m, compT))
```

```{r}
my_t <- function(x, grp) {
  t_stat <- function(x) {
    m <- mean(x)
    n <- length(x)
    var <- sum((x - m)^2) / (n - 1)

    list(m = m, n = n, var = var)
  }

  g1 <- t_stat(x[grp == 1])
  g2 <- t_stat(x[grp == 2])

  se_total <- sqrt(g1$var / g1$n + g2$var / g2$n)
  (g1$m - g2$m) / se_total
}

system.time(t2 <- purrr::map_dbl(1:m, ~ my_t(X[., ], grp)))
```

```{r}
rowtstat <- function(X, grp) {
  t_stat <- function(X) {
    m <- rowMeans(X)
    n <- ncol(X)
    var <- rowSums((X - m)^2) / (n - 1)

    list(m = m, n = n, var = var)
  }

  g1 <- t_stat(X[, grp == 1])
  g2 <- t_stat(X[, grp == 2])

  se_total <- sqrt(g1$var / g1$n + g2$var / g2$n)
  (g1$m - g2$m) / se_total
}
system.time(t3 <- rowtstat(X, grp))
stopifnot(all.equal(t1, t3))
```

## 24.8 Other techniques
