---
title: "note15"
output: html_notebook
---

# 15 S4

## 15.1 Introduction

```{r}
library(methods)
```

## 15.2 Basics

```{r}
setClass(
  "Person",
  slots = c(
    name = "character",
    age = "numeric"
  )
)
john <- new("Person", name = "John Smith", age = NA_real_)
john
```

```{r}
is(john)
john@name
slot(john, "age")
```

```{r}
setGeneric("age", function(x) standardGeneric("age"))
setGeneric("age<-", function(x, value) standardGeneric("age<-"))
```

```{r}
setMethod("age", "Person", function(x) x@age)
setMethod("age<-", "Person", function(x, value) {
  x@age <- value
  x
})

age(john) <- 50
age(john)
```

```{r}
sloop::otype(john)
sloop::ftype(age)
```

```{r}
e12345 <- lubridate::period(
  c(1, 2, 3, 4, 5),
  c("second", "minute", "hour", "day", "week")
)
e12345
```

```{r}
str(e12345)
```

## 15.3 Classes

```{r}
setClass(
  "Person",
  slots = c(
    name = "character",
    age = "numeric"
  ),
  prototype = list(
    name = NA_character_,
    age = NA_real_
  )
)

me <- new("Person", name = "Hadley")
str(me)
```

```{r}
setClass(
  "Employee",
  contains = "Person",
  slots = c(
    boss = "Person"
  ),
  prototype = list(
    boss = new("Person")
  )
)

str(new("Employee"))
```

```{r}
is(new("Person"))
is(new("Employee"))
is(john, "Person")
```

```{r}
setClass("A", slots = c(x = "numeric"))
a <- new("A", x = 10)

try(setClass("A", slots = c(a_different_slot = "numeric")))
try(a)
```

```{r}
Person <- function(name, age = NA) {
  age <- as.double(age)

  new("Person", name = name, age = age)
}

Person("Hadley")
```

```{r}
try(Person(mtcars))
```

```{r}
Person("Hadley", age = c(30, 37))
```

```{r}
setValidity("Person", function(object) {
  if (length(object@name) != length(object@age)) {
    "@name and @age must be same length"
  } else {
    TRUE
  }
})
```

```{r}
Person(c("Hadley", "Lee"), age = c(30, 37))
```

```{r}
alex <- Person("alex", age = 30)
alex@age <- 1:10
alex
```

```{r}
try(validObject(alex))
```

```{r}
# Definition of the Person class
setClass("Person",
  slots = c(
    age = "numeric",
    given = "character",
    family = "character",
    role = "character",
    email = "character",
    comment = "character"
  ),
  prototype = list(
    age = NA_real_,
    given = NA_character_,
    family = NA_character_,
    role = NA_character_,
    email = NA_character_,
    comment = NA_character_
  )
)

# Helper to create instances of the Person class
Person <- function(given, family,
                   age = NA_real_,
                   role = NA_character_,
                   email = NA_character_,
                   comment = NA_character_) {
  age <- as.double(age)

  new("Person",
    age = age,
    given = given,
    family = family,
    role = role,
    email = email,
    comment = comment
  )
}

# Validator to ensure that each slot is of length one
setValidity("Person", function(object) {
  invalids <- c()
  if (length(object@age) != 1 ||
    length(object@given) != 1 ||
    length(object@family) != 1 ||
    length(object@email) != 1 ||
    length(object@comment) != 1) {
    invalids <- paste0(
      "@name, @age, @given, @family, @email, ",
      "@comment must be of length 1"
    )
  }

  known_roles <- c(
    NA_character_, "aut", "com", "cph", "cre", "ctb",
    "ctr", "dtc", "fnd", "rev", "ths", "trl"
  )

  if (!all(object@role %in% known_roles)) {
    paste(
      "@role(s) must be one of",
      paste(known_roles, collapse = ", ")
    )
  }

  if (length(invalids)) {
    return(invalids)
  }
  TRUE
})
```

```{r}
setClass("Human")
try(new("Human"))
setClass("Programmer", contains = "Human")
```

```{r}
setClass(
  "Factor",
  slots = c(
    data = "integer",
    levels = "character",
    ordered = "logical"
  ),
  prototype = list(
    data = integer(),
    levels = character(),
    ordered = FALSE
  )
)

new("Factor", data = c(1L, 2L), levels = letters[1:3])
```

```{r}
setClass(
  "Date2",
  slots = list(
    data = "integer"
  ),
  prototype = list(
    data = integer()
  )
)
new("Date2", data = 1L)
```

## 15.4 Generics and methods

```{r}
setGeneric("myGeneric", function(x) standardGeneric("myGeneric"))
```

```{r}
setGeneric(
  "myGeneric",
  function(x, ..., verbose = TRUE) standardGeneric("myGeneric"),
  signature = "x"
)
```

```{r}
# setMethod("myGeneric", "Person", function(x) {
# })
```

```{r}
args(getGeneric("show"))
```

```{r}
setMethod("show", "Person", function(object) {
  cat(is(object)[[1]], "\n",
    "  Name: ", object@name, "\n",
    "  Age: ", object@age, "\n",
    sep = ""
  )
})
john
```

```{r}
setGeneric("name", function(x) standardGeneric("name"))
setMethod("name", "Person", function(x) x@name)
name(john)
```

```{r}
setGeneric("name<-", function(x, value) standardGeneric("name<-"))
setMethod("name<-", "Person", function(x, value) {
  x@name <- value
  validObject(x)
  x
})

# name(john) <- "Jon Smythe"
# name(john)
```

## 15.5 Method dispatch

## 15.6 S4 and S3
