---
title: "note20"
output: html_notebook
---

# 20 Evaluation

## 20.1 Introduction

```{r}
library(rlang)
library(purrr)
```

## 20.2 Evaluation basics

```{r}
x <- 10
eval(expr(x))
```

```{r}
y <- 2
eval(expr(x + y))
x + y
```

```{r}
eval(expr(x + y), env(x = 1000))
```

```{r}
eval(print(x + 1), env(x = 1000))
```

```{r}
eval(expr(print(x + 1)), env(x = 1000))
```

```{r}
rm(x, y)
```

```{r}
foo <- local({
  x <- 10
  y <- 200
  x + y
})

foo
```

```{r}
local2 <- function(expr) {
  env <- env(caller_env())
  eval(enexpr(expr), env)
}
foo <- local2({
  x <- 10
  y <- 200
  x + y
})
foo
```

```{r}
source2 <- function(path, env = call_env()) {
  file <- paste(readLines(path, warn = FALSE), collapse = "\n")
  exprs <- parse_exprs(file)

  res <- NULL
  for (i in seq_along(exprs)) {
    res <- eval(exprs[[i]], env)
  }

  invisible(res)
}
```

```{r}
source3 <- function(file, env = parent.frame()) {
  lines <- parse(file)
  res <- eval(lines, envir = env)
  invisible(res)
}
```

```{r}
x <- 10
y <- 20
f <- eval(expr(function(x, y) !!x + !!y))
f
f()
```

```{r}
attr(f, "srcref") <- NULL
f
```

```{r}
tmp_file <- tempfile()
writeLines("print(x)", tmp_file)
```

```{r}
x <- "global environment"
env2 <- env(x = "specified environment")
locate_evaluation <- function(file, local) {
  x <- "local environment"
  source(file, local = local)
}
```

```{r}
locate_evaluation(tmp_file, local = FALSE)
locate_evaluation(tmp_file, local = env2)
locate_evaluation(tmp_file, local = TRUE)
```

```{r}
eval(expr(eval(expr(eval(expr(2 + 2)))))) # (1)
eval(eval(expr(eval(expr(eval(expr(2 + 2))))))) # (2)
expr(eval(expr(eval(expr(eval(expr(2 + 2))))))) # (3)
```

```{r}
get2 <- function(name, env = caller_env()) {
  name_sym <- sym(name)
  eval(name_sym, env)
}
x <- 1
get2("x")
```

```{r}
assign2 <- function(name, value, env = caller_env()) {
  name_sym <- sym(name)
  assign_expr <- expr(!!name_sym <- !!value)
  eval(assign_expr, env)
}
assign2("x", 4)
x
```

```{r}
source2 <- function(path, env = caller_env()) {
  file <- paste(readLines(path, warn = FALSE), collapse = "\n")
  exprs <- parse_exprs(file)

  res <- purrr::map(exprs, eval, env)
  invisible(res)
}
tmp_file <- tempfile()
writeLines(
  "x <- 1
  x
  y <- 2
  y # some comment",
  tmp_file
)

(source2(tmp_file))
```

```{r}
local3 <- function(expr, envir = new.env()) {
  call <- substitute(eval(quote(expr), envir))
  print(call)
  eval(call, envir = parent.frame())
}
local3({
  x <- 10
  x * 2
})
```

## 20.3 Quosures

```{r}
foo <- function(x) enquo(x)
foo(a + b)
```

```{r}
quo(x + y + z)
```

```{r}
new_quosure(expr(x + y), env(x = 1, y = 10))
```

```{r}
q1 <- new_quosure(expr(x + y), env(x = 1, y = 10))
eval_tidy(q1)
```

```{r}
f <- function(...) {
  x <- 1
  g(..., f = x)
}
g <- function(...) {
  enquos(...)
}
x <- 0
qs <- f(global = x)
qs
```

```{r}
map_dbl(qs, eval_tidy)
```

```{r}
f <- ~ runif(3)
str(f)
```

```{r}
q4 <- new_quosure(expr(x + y + z))
class(q4)
```

```{r}
is_call(q4)
```

```{r}
q4[[1]]
```

```{r}
q4[[2]]
```

```{r}
get_expr(q4)
get_env(q4)
```

```{r}
q2 <- new_quosure(expr(x), env(x = 1))
q3 <- new_quosure(expr(x), env(x = 10))
x <- expr(!!q2 + !!q3)
x
```

```{r}
eval_tidy(x)
```

```{r}
expr_print(x)
```

```{r}
q1 <- new_quosure(expr(x), env(x = 1))
q1
```

```{r}
q2 <- new_quosure(expr(x + !!q1), env(x = 10))
q2
```

```{r}
q3 <- new_quosure(expr(x + !!q2), env(x = 100))
q3
```

```{r}
eval_tidy(q1)
eval_tidy(q2)
eval_tidy(q3)
```

```{r}
enenv <- function(x) {
  get_env(enquo(x))
}

enenv(x)
```

```{r}
capture_env <- function(x) {
  enenv(x)
}
capture_env(x)
```

## 20.4 Data masks

```{r}
q1 <- new_quosure(expr(x * y), env(x = 100))
df <- data.frame(y = 1:10)
eval_tidy(q1, df)
```

```{r}
with2 <- function(data, expr) {
  expr <- enquo(expr)
  eval_tidy(expr, data)
}

x <- 100
with2(df, x * y)
```

```{r}
with3 <- function(data, expr) {
  expr <- substitute(expr)
  eval(expr, data, caller_env())
}
```

```{r}
x <- 1
df <- data.frame(x = 2)
with2(df, .data$x)
with2(df, .env$x)
```

```{r}
sample_df <- data.frame(a = 1:5, b = 5:1, c = c(5, 3, 1, 4, 1))
subset(sample_df, a >= 4)
```

```{r}
subset(sample_df, b == c)
```

```{r}
subset2 <- function(data, rows) {
  rows <- enquo(rows)
  rows_val <- eval_tidy(rows, data)
  stopifnot(is.logical(rows_val))

  data[rows_val, , drop = FALSE]
}
subset2(sample_df, b == c)
```

```{r}
df <- data.frame(x = c(2, 3, 1), y = runif(3))
transform(df, x = -x, y2 = 2 * y)
```

```{r}
transform2 <- function(.data, ...) {
  dots <- enquos(...)

  for (i in seq_along(dots)) {
    name <- names(dots)[[i]]
    dot <- dots[[i]]
    .data[[name]] <- eval_tidy(dot, .data)
  }
  .data
}
transform2(df, x2 = x * 2, y = -y)
```

```{r}
df <- data.frame(a = 1, b = 2, c = 3, d = 4, e = 5)
subset(df, select = b:d)
```

```{r}
vars <- as.list(set_names(seq_along(df), names(df)))
str(vars)
```

```{r}
select2 <- function(data, ...) {
  dots <- enquos(...)
  vars <- as.list(set_names(seq_along(data), names(data)))
  cols <- unlist(map(dots, eval_tidy, vars))

  data[, cols, drop = FALSE]
}
select2(df, b:d)
```

```{r}
subset3 <- function(data, rows) {
  rows <- enquo(rows)
  eval_tidy(expr(data[!!rows, , drop = FALSE]), data = data)
}

df <- data.frame(x = 1:3)
subset3(df, x == 1)
```

```{r}
arrange2 <- function(.df, ..., na.last = TRUE) {
  args <- enquos(...)
  order_call <- expr(order(!!!args, na.last = !!na.last))
  ord <- eval_tidy(order_call, .df)
  stopifnot(length(ord) == nrow(.df))

  .df[ord, , drop = FALSE]
}
```

## 20.5 Using tidy evaluation

```{r}
resample <- function(df, n) {
  idx <- sample(nrow(df), n, replace = TRUE)
  df[idx, , drop = FALSE]
}
```

```{r}
subsample <- function(df, cond, n = nrow(df)) {
  df <- subset2(df, cond)
  resample(df, n)
}

df <- data.frame(x = c(1, 1, 1, 2, 2), y = 1:5)
subsample(df, x == 1)
```

```{r}
subsample <- function(df, cond, n = nrow(df)) {
  cond <- enquo(cond)

  df <- subset2(df, !!cond)
  resample(df, n)
}

subsample(df, x == 1)
```

```{r}
threshold_x <- function(df, val) {
  subset2(df, x >= val)
}

x <- 10
no_x <- data.frame(y = 1:3)
threshold_x(no_x, 2)
```

```{r}
has_val <- data.frame(x = 1:3, val = 9:11)
threshold_x(has_val, 2)
```

```{r}
threshold_x <- function(df, val) {
  subset2(df, .data$x >= .env$val)
}

x <- 10
try(threshold_x(no_x, 2))
threshold_x(has_val, 2)
```

```{r}
threshold_var <- function(df, var, val) {
  var <- as_string(ensym(var))
  subset2(df, .data[[var]] >= !!val)
}

df <- data.frame(x = 1:10)
threshold_var(df, x, 8)
```

```{r}
threshold_expr <- function(df, expr, val) {
  expr <- enquo(expr)
  subset2(df, !!expr >= !!val)
}
```

## 20.6 Base evaluation

```{r}
subset_base <- function(data, rows) {
  rows <- substitute(rows)
  rows_val <- eval(rows, data, caller_env())
  stopifnot(is.logical(rows_val))

  data[rows_val, , drop = FALSE]
}

subset_tidy <- function(data, rows) {
  rows <- enquo(rows)
  rows_val <- eval_tidy(rows, data)
  stopifnot(is.logical(rows_val))

  data[rows_val, , drop = FALSE]
}
```

```{r}
f1 <- function(df, ...) {
  xval <- 3
  subset_base(df, ...)
}

my_df <- data.frame(x = 1:3, y = 3:1)
xval <- 1
f1(my_df, x == xval)
```

```{r}
try(local({
  zzz <- 2
  dfs <- list(data.frame(x = 1:3), data.frame(x = 4:6))
  lapply(dfs, subset_base, x == zzz)
}))
```

```{r}
f3 <- function(df) {
  call <- substitute(subset_base(df, z > 0))
  expr_print(call)
  eval(call, caller_env())
}

my_df <- data.frame(x = 1:3, y = 3:1)
z <- -1
f3(my_df)
```

```{r}
g <- function(x, y, z) {
  match.call()
}
g(1, 2, z = 3)
```

```{r}
write.csv <- function(...) {
  call <- match.call(write.table, expand.dots = TRUE)

  call[[1]] <- quote(write.table)
  call$sep <- ","
  call$dec <- "."
  eval(call, parent.frame())
}
```

```{r}
write.csv <- function(...) {
  write.table(..., sep = ",", dec = ".")
}
```

```{r}
lm2 <- function(formula, data) {
  lm(formula, data)
}
```

```{r}
lm2(mpg ~ disp, mtcars)
```

```{r}
lm3 <- function(formula, data, env = caller_env()) {
  formula <- enexpr(formula)
  data <- enexpr(data)

  lm_call <- expr(lm(!!formula, data = !!data))
  expr_print(lm_call)
  eval(lm_call, env)
}

lm3(mpg ~ disp, mtcars)
```

```{r}
resp <- expr(mpg)
disp1 <- expr(vs)
disp2 <- expr(wt)
lm3(!!resp ~ !!disp1 + !!disp2, mtcars)
```

```{r}
resample_lm0 <- function(formula, data, env = caller_env()) {
  formula <- enexpr(formula)
  resample_data <- resample(data, n = nrow(data))

  lm_call <- expr(lm(!!formula, data = !!resample_data))
  expr_print(lm_call)
  eval(lm_call, env)
}

df <- data.frame(x = 1:10, y = 5 + 3 * (1:10) + round(rnorm(10), 2))
resample_lm0(y ~ x, data = df)
```

```{r}
resample_lm2 <- function(formula, data, env = caller_env()) {
  formula <- enexpr(formula)
  resample_data <- resample(data, n = nrow(data))

  lm_env <- env(env, resample_data = resample_data)
  lm_call <- expr(lm(!!formula, data = resample_data))
  expr_print(lm_call)
  eval(lm_call, lm_env)
}
resample_lm2(y ~ x, data = df)
```

```{r}
lm3c <- function(formula, data) {
  formula <- enexpr(formula)
  data_quo <- enexpr(data)

  lm_call <- expr(lm(!!formula, data = !!data_quo))
  eval(lm_call, caller_env())
}
lm3c(mpg ~ disp, mtcars)$call
```

```{r}
lm_wrap <- function(pred, resp = mpg, data = mtcars,
                    env = caller_env()) {
  pred <- enexpr(pred)
  resp <- enexpr(resp)
  data <- enexpr(data)

  formula <- expr(!!resp ~ !!pred)
  lm_call <- expr(lm(!!formula, data = !!data))
  eval(lm_call, envir = env)
}

lm_wrap(I(1 / disp) + disp * cyl)
identical(
  lm_wrap(I(1 / disp) + disp * cyl),
  lm(mpg ~ I(1 / disp) + disp * cyl, data = mtcars)
)
```

```{r}
resample_lm <- function(formula, data,
                        resample_data = data[sample(nrow(data), replace = TRUE), ,
                          drop = FALSE
                        ],
                        env = current_env()) {
  formula <- enexpr(formula)

  lm_call <- expr(lm(!!formula, data = resample_data))
  expr_print(lm_call)
  eval(lm_call, env)
}

df <- data.frame(x = 1:10, y = 5 + 3 * (1:10) + round(rnorm(10), 2))
(lm_1 <- resample_lm(y ~ x, data = df))
```
