---
title: "note09"
output: html_notebook
---

```{r}
library(fpp2)
library(ggplot2)
theme_set(theme_gray(base_family = "NanumGothic"))
```

# 9 동적 회귀 모델

## 9.1 추정

## 9.2 R에서 ARIMA 오차를 고려하는 회귀

```{r}
uschange[, 1:2] |>
  autoplot(, facets = TRUE) +
  xlab("연도") +
  ylab("") +
  ggtitle("미국 소비와 개인소득의 분기별 변화")
```

```{r}
fit <- auto.arima(uschange[, "Consumption"], xreg = uschange[, "Income"])
fit
```

```{r}
cbind(
  "Regression Erros" = residuals(fit, type = "regression"),
  "ARIMA errors" = residuals(fit, type = "innovation")
) |>
  autoplot(facets = TRUE)
```

```{r}
checkresiduals(fit)
```

## 9.3 예측하기

```{r}
fcast <- forecast(fit, xreg = rep(mean(uschange[, 2]), 8))
autoplot(fcast) + xlab("연도")
```

```{r}
elecdaily[, c("Demand", "Temperature")] |>
  autoplot(facets = TRUE)
```

```{r}
xreg <-
  cbind(
    MaxTemp = elecdaily[, "Temperature"],
    MaxTempSq = elecdaily[, "Temperature"]^2,
    Workdoay = elecdaily[, "WorkDay"]
  )
fit <- auto.arima(elecdaily[, "Demand"], xreg = xreg)
checkresiduals(fit)
```

```{r}
fcast <- forecast(
  fit,
  xreg = cbind(
    MaxTemp = rep(26, 14),
    MaxTempSq = rep(26^2, 14),
    Workday = c(0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1)
  )
)
autoplot(fcast) +
  ylab("전력 수요(GW)")
```

## 9.4 확률적 추세와 확정적 추세

```{r}
autoplot(austa) +
  xlab("연도") +
  ylab("백만명") +
  ggtitle("호주에 입국하는 전체 연간 국제선 방문객")
```

```{r}
trend <- seq_along(austa)
fit1 <- auto.arima(austa, d = 0, xreg = trend)
fit1
```

```{r}
fit2 <- auto.arima(austa, d = 1)
fit2
```

```{r}
fc1 <- forecast(fit1, xreg = length(austa) + 1:10)
fc2 <- forecast(fit2, h = 10)
autoplot(austa) +
  autolayer(fc2, series = "확률적 추세") +
  autolayer(fc1, series = "확정적 추세") +
  ggtitle("확정적 추세 모델과 확률적 추세 모델에서 얻은 예측값") +
  xlab("연도") +
  ylab("호주 방문객 (백만)") +
  guides(color = guide_legend(title = "예측값"))
```

## 9.5 동적 조화 회귀

```{r, fig.asp=1}
cafe04 <- window(auscafe, start = 2004)
plots <- list()
for (i in seq(6)) {
  fit <- auto.arima(cafe04,
    xreg = fourier(cafe04, K = i),
    seasonal = FALSE, lambda = 0
  )
  plots[[i]] <- autoplot(
    forecast(
      fit,
      xreg = fourier(cafe04, K = i, h = 24)
    )
  ) +
    xlab(paste("K=", i, "   AICc=", round(fit[["aicc"]], 2))) +
    ylab("") + ylim(1.5, 4.7)
}

gridExtra::grid.arrange(
  plots[[1]], plots[[2]], plots[[3]], plots[[4]], plots[[5]], plots[[6]],
  nrow = 3
)
```

## 9.6 시차 예측변수

```{r}
insurance |>
  autoplot(facets = TRUE) +
  xlab("Year") +
  ylab("") +
  ggtitle("보험 광고와 견적")
```

```{r}
Advert <- cbind(
  AdLag0 = insurance[, "TV.advert"],
  AdLag1 = stats::lag(insurance[, "TV.advert"], -1),
  AdLag2 = stats::lag(insurance[, "TV.advert"], -2),
  AdLag3 = stats::lag(insurance[, "TV.advert"], -3)
) |>
  head(NROW(insurance))
Advert
```

```{r}
fit1 <- auto.arima(insurance[4:40, 1], xreg = Advert[4:40, 1], stationary = TRUE)
fit2 <- auto.arima(insurance[4:40, 1], xreg = Advert[4:40, 1:2], stationary = TRUE)
fit3 <- auto.arima(insurance[4:40, 1], xreg = Advert[4:40, 1:3], stationary = TRUE)
fit4 <- auto.arima(insurance[4:40, 1], xreg = Advert[4:40, 1:4], stationary = TRUE)
```

```{r}
c(fit1[["aicc"]], fit2[["aicc"]], fit3[["aicc"]], fit4[["aicc"]])
```

```{r}
fit <- auto.arima(insurance[, 1], xreg = Advert[, 1:2], stationary = TRUE)
fit
```

```{r}
xreg <- cbind(
  AdLag0 = rep(8, 20), AdLag1 = c(Advert[40, 1], rep(8, 19))
)
xreg
fc8 <- forecast(fit, h = 20, xreg = xreg)
fc8 |>
  autoplot() +
  ylab("견적") +
  ggtitle("미래 광고를 8로 두고 견적 예측")
```

## 9.7 연습문제
